### ISSUE TITLE
Data imported not found

### ISSUE THREAD

**Issue by petrizzo** [johannesjo/super-productivity#1010]
### Your Environment

* Version used: Super Productivity 6.5.2, snap 
* Operating System and version: Manjaro Linux
* Desktop Environment: gnome 
* Browser Name and version: 

### Expected Behavior

I'm importing data form json format doesn't show anything

### Current Behavior

I can import data, and super-productivity says that the process was successfull but nothing is displayed

### Steps to Reproduce (for bugs)

1. Open Settings, 
2. Select import data
3. Select json file
4. ok

### Console Output

running from terminal I have this output:

superproductivity 
{ enabled: null, showDevTools: false, mode: 'bottom' }
Gtk-Message: 20:49:10.768: Failed to load module "xapp-gtk3-module"
Saving backups to /home/petrizzo/snap/superproductivity/1060/.config/superProductivity/backups
No custom styles detected at /home/petrizzo/snap/superproductivity/1060/.config/superProductivity/styles.css
Gtk-Message: 20:49:28.837: GtkDialog mapped without a transient parent. This is discouraged.

### Error Log (Desktop only)

[2021-03-29 17:51:42.888] [error] Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886) Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886)
[2021-03-29 17:51:46.535] [error] Frontend Error Stack: Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:42:18)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
function (webpack:///node_modules/zone.js/dist/zone-evergreen.js:124:28)
[2021-03-29 17:52:50.439] [error] Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886) Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886)
[2021-03-29 17:52:52.771] [error] Frontend Error Stack: Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:42:18)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
function (webpack:///node_modules/zone.js/dist/zone-evergreen.js:124:28)
[2021-03-29 17:53:54.767] [error] Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886) Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798590)
    at Generator.next (<anonymous>)
    at file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at Z (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at eE (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
    at FileReader.n.onload (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798391)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:1903087)
    at l.invoke (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.runGuarded (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:2107)
    at FileReader.<anonymous> (file:///snap/superproductivity/1060/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1886)
[2021-03-29 17:53:56.959] [error] Frontend Error Stack: Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:42:18)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3798121)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///snap/superproductivity/1060/resources/app.asar/dist/main.d0fa4eecc2da3f177424.js:1:3797866)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone-evergreen.js:140:46)
function (webpack:///node_modules/zone.js/dist/zone-evergreen.js:124:28)

**Comment by johannesjo** [comment]
Thanks for opening this up. Looks like the data export you're trying to import is invalid. How did you generate the export and with which version of the app?
