### ISSUE TITLE
Error: Uncaught (in promise): Error: DataError: Failed to write blobs.Error: DataError: Failed to write blobs.  

### ISSUE THREAD

**Issue by kwongtn** [johannesjo/super-productivity#1220]
### Steps to Reproduce
1. Err... just using it at the background
2.
3.
4.

### Stacktrace
```
t.<anonymous> (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:2655980)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28522:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:1984561)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28522:32)
```
```
Error: DataError: Failed to write blobs. 
at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:2656776) 
at Generator.throw () 
at o (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:2655980) 
at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572) 
at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:384490) 
at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512) 
at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984) 
at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758 
at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190) 
at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.5.2.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.66b4ffc196396d37a038.js:1:384306)
```

### Meta Info
META: SP6.5.2 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1621507527187: [Task] Add time spent 
1621507527191: [Project] Update Work End 
1621507527193: [Tag] Update Work End for Tag 
1621507527204: [Persistence] Save to DB 
1621507527205: [Persistence] Save to DB 
1621507527206: [Persistence] Save to DB 
1621507528187: [Task] Add time spent 
1621507528189: [Project] Update Work End 
1621507528190: [Tag] Update Work End for Tag 
1621507528195: [Persistence] Save to DB 
1621507528196: [Persistence] Save to DB 
1621507528197: [Persistence] Save to DB 
1621507529187: [Task] Add time spent 
1621507529188: [Project] Update Work End 
1621507529189: [Tag] Update Work End for Tag 
1621507529193: [Persistence] Save to DB 
1621507529194: [Persistence] Save to DB 
1621507529194: [Persistence] Save to DB 
1621507530188: [Task] Add time spent 
1621507530189: [Project] Update Work End 
1621507530190: [Tag] Update Work End for Tag 
1621507530195: [Persistence] Save to DB 
1621507530196: [Persistence] Save to DB 
1621507530196: [Persistence] Save to DB 
1621507531187: [Task] Add time spent 
1621507531189: [Project] Update Work End 
1621507531191: [Tag] Update Work End for Tag 
1621507531201: [Persistence] Save to DB 
1621507531202: [Persistence] Save to DB 
1621507531203: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for opening this up. Hopefully this will be fixed with a future electron version. (Might also happen when disk space is low btw.). Not much we can do about it now unfortunately.
