### ISSUE TITLE
IndexSizeError: Index or size is negative or greater than the allowed amount

### ISSUE THREAD

**Issue by millerii** [johannesjo/super-productivity#1245]
### Steps to Reproduce
1st way:
1. Copy some word(s) to clipboard
2. Click one of task/sub-task that has already created to rename it 
3. Go to end of line and add one space after last word
5. Paste text to get error

2nd way:
1. Copy some words to clipboard that contains line-brake
2. Click one of already made task/sub-task to rename it
** Or make new empty sub-task
3. Paste text to get error

### Stacktrace
```
window.getSelection (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:152:10)
ev.clipboardData.getData (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:93:13)
listener.call (webpack:///node_modules/zone.js/dist/zone-evergreen.js:759:38)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:27)
```

### Meta Info
META: SP6.5.2 Browser – fi-FI – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0

### Actions Before Error
```
1622092933972: [Improvement] Load Improvement State 
1622092933981: [Note] Load Note State 
1622092933986: [Obstruction] Load Obstruction State 
1622092933987: [Project] Load Project related Data Success 
1622092933988: [Improvement] Clear Hidden Improvements 
1622092933989: [Improvement] Delete multiple Improvements 
1622092956783: [Task] Update Task 
1622092956785: [Persistence] Save to DB 
1622092962668: [Task] Add SubTask 
1622092962669: [Persistence] Save to DB 
1622092977972: [Task] Update Task 
1622092977977: [Persistence] Save to DB 
1622092981031: [Task] Move sub task 
1622092981034: [Persistence] Save to DB 
1622093011267: [Task] Update Task 
1622093011269: [Persistence] Save to DB 
1622093044029: [SP_ALL] Load(import) all data 
1622093044035: [SP_ALL] All Data was loaded 
1622093044043: [WorkContext] Set Active Work Context 
1622093044068: [Task] SetSelectedTask 
1622093044086: [Bookmark] Load Bookmark State 
1622093044087: [Metric] Load Metric State 
1622093044089: [Improvement] Load Improvement State 
1622093044094: [Note] Load Note State 
1622093044101: [Obstruction] Load Obstruction State 
1622093044102: [Project] Load Project related Data Success 
1622093044103: [Improvement] Clear Hidden Improvements 
1622093044103: [Improvement] Delete multiple Improvements 
1622093067754: [Task] Update Task 
1622093067758: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this!

**Comment by johannesjo** [comment]
I checked this and it only seems to occur in firefox. As the main focus of the app is the electron version (and chromium based browsers), I won't work on this myself but I gladly accept any PRs dealing with it.

**Comment by millerii** [comment]
Hi, if proceeded like 2nd way and paste text containing line brake on Edge-browser (v91) I get same kind of error:

IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 38 is larger than the node's length (33).

### Console Output
```
GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'setStart' on 'Range': The offset 15 is larger than the node's length (10).
    at t._insertAtCursor (https://app.super-productivity.com/main.5222887620543669fef3.js:1:3298239)
    at HTMLDivElement.t.onpaste [as __zone_symbol__ON_PROPERTYpaste] (https://app.super-productivity.com/main.5222887620543669fef3.js:1:3297468)
    at HTMLDivElement.D (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:11460)
    at l.invokeTask (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:7212)
    at Object.onInvokeTask (https://app.super-productivity.com/main.5222887620543669fef3.js:1:1641704)
    at l.invokeTask (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:7133)
    at i.runTask (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:2621)
    at u.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:8262)
    at _ (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:20185)
    at HTMLDivElement.k (https://app.super-productivity.com/polyfills.d9d3c25e259fe76fbf1e.js:1:20430)
handleError @ global-error-handler.class.ts:31
action-logger.ts:30 Last actions before error: Array(7)
zone-evergreen.js:182 Uncaught Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 15 is larger than the node's length (10).
    at t.handleError (global-error-handler.class.ts:63)
    at Object.next (core.js:29160)
    at u.__tryOrUnsub (Subscriber.js:183)
    at u.next (Subscriber.js:122)
    at l._next (Subscriber.js:72)
    at l.next (Subscriber.js:49)
    at Jc.next (Subject.js:39)
    at Jc.emit (core.js:25902)
    at core.js:28579
    at l.invoke (zone-evergreen.js:372)
```

### Stacktrace
```
window.getSelection (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:165:10)
ev.clipboardData.getData (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:106:13)
listener.call (webpack:///node_modules/zone.js/dist/zone-evergreen.js:763:38)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:178:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:487:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1600:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1626:16)
```

### Meta Info
META: SP7.0.1 Browser – fi – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41

### Actions Before Error
```
1623402449571: [SP_ALL] Load(import) all data 
1623402449573: [SP_ALL] All Data was loaded 
1623402456686: [Task] Update Task 
1623402456690: [Persistence] Save to DB 
1623402458907: [Task] Update Task 
1623402458910: [Persistence] Save to DB 
1623402469202: [Task] Update Task 
1623402469205: [Persistence] Save to DB 
1623402471209: [Task] Update Task 
1623402471212: [Persistence] Save to DB 
1623402493216: [Task] Update Task 
1623402493231: [Persistence] Save to DB 
1623402507929: [Task] Update Task 
1623402507931: [Persistence] Save to DB 
1623402513284: [Layout] Toggle SideBar 
1623402560707: [Task] Update Task 
1623402560722: [Persistence] Save to DB 
1623402567334: [Task] Update Task 
1623402567343: [Persistence] Save to DB 
1623402599131: [SP_ALL] Load(import) all data 
1623402599133: [SP_ALL] All Data was loaded 
1623402605792: [Task] Update Task 
1623402605797: [Persistence] Save to DB 
1623402608272: [Task] Update Task 
1623402608274: [Persistence] Save to DB 
1623402618819: [Task] Update Task 
1623402618825: [Persistence] Save to DB 
1623402658385: [SP_ALL] Load(import) all data 
1623402658386: [SP_ALL] All Data was loaded 
1623402664021: [Layout] Toggle SideBar
```

**Comment by johannesjo** [comment]
Same thing for edge :) It's not a priority, but PRs are welcome.

**Comment by johannesjo** [comment]
Thanks again @dsdomingues !
