### ISSUE TITLE
TypeError: Cannot read property 'subTaskIds' of undefined

### ISSUE THREAD

**Issue by tuxmachine** [johannesjo/super-productivity#1295]
### Steps to Reproduce

First time it happened, so haven't exactly reproduced, but last actions:
1. Finish a task
2. Click finish the day
3. Click round up to 15min

### Console Output

Nope, just the stacktrace and action log

### Stacktrace
```
subTaskIds (webpack:///src/app/features/tasks/store/task.reducer.ts:486:16)
filter (webpack:///src/app/features/tasks/store/task.reducer.ts:483:52)
createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:287:19)
combination (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:242:44)
actionLoggerReducer (webpack:///src/app/root-store/meta/action-logger.reducer.ts:7:11)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:122:11)
Array.isArray (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:275:19)
reduceState (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:430:20)
_tryNext (webpack:///node_modules/rxjs/_esm2015/internal/operators/scan.js:49:26)
```

### Meta Info
META: SP7.0.3 Browser – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

### Actions Before Error
```
1623436749598: [Persistence] Save to DB 
1623436750585: [Task] Add time spent 
1623436750586: [Project] Update Work End 
1623436750592: [Tag] Update Work End for Tag 
1623436750598: [Persistence] Save to DB 
1623436750599: [Persistence] Save to DB 
1623436750599: [Persistence] Save to DB 
1623436751585: [Task] Add time spent 
1623436751586: [Project] Update Work End 
1623436751593: [Tag] Update Work End for Tag 
1623436751599: [Persistence] Save to DB 
1623436751599: [Persistence] Save to DB 
1623436751599: [Persistence] Save to DB 
1623436752586: [Task] Add time spent 
1623436752587: [Project] Update Work End 
1623436752594: [Tag] Update Work End for Tag 
1623436752600: [Persistence] Save to DB 
1623436752600: [Persistence] Save to DB 
1623436752600: [Persistence] Save to DB 
1623436753585: [Task] Add time spent 
1623436753587: [Project] Update Work End 
1623436753593: [Tag] Update Work End for Tag 
1623436753599: [Persistence] Save to DB 
1623436753599: [Persistence] Save to DB 
1623436753599: [Persistence] Save to DB 
1623436754444: [Task] Update Task 
1623436754450: [Persistence] Save to DB 
1623436754450: [Task] UnsetCurrentTask 
1623436756826: [Task] SetSelectedTask 
1623436767672: [Task] RoundTimeSpentForDay
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export".

**Comment by johannesjo** [comment]
Hey there! I tried to reproduce the issue with your data, but was unable to do so. Could you maybe try exporting and then re-importing your data and then trying the steps you provided? That should work as a quick fix at least.

**Comment by tuxmachine** [comment]
Had it again last night, did a data export right after (whereas last time I manually edited the time to round the minutes). I'll send it via mail again.

I'll try the fix :) thanks for looking into it!

```
TypeError: Cannot read property 'subTaskIds' of undefined
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:110984
    at Array.filter (<anonymous>)
    at E (https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:110937)
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:1757705
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:1756915
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:4077799
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:4076456
    at https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:1757202
    at o.tt [as accumulator] (https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:1759343)
    at o._tryNext (https://app.super-productivity.com/main.2b3108c38bde681a9f80.js:1:500950)
```

**Comment by johannesjo** [comment]
Thanks again. I am still not able to reproduce this... :/  Not sure how to proceed tbh...

**Comment by tuxmachine** [comment]
I'd suggest parking it until another case comes along. It's not a critical bug; no data is lost and I can always manually round the numbers.
