### ISSUE TITLE
Internal error opening backing store for indexedDB.open.

### ISSUE THREAD

**Issue by Jogiio** [johannesjo/super-productivity#1298]
When I closed the app before its initial loading I received the following Error:

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open. Error: UnknownError: Internal error opening backing store for indexedDB.open. at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:2310608) at Generator.throw () at a (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:2308563) at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:317247) at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:317063)
! Please copy & report !

Error: Uncaught (in promise): Error: UnknownError: Internal error opening backing store for indexedDB.open. Error: UnknownError: Internal error opening backing store for indexedDB.open. at t. (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:2310608) at Generator.throw () at a (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:2308563) at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:317247) at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:317063)
terminated (webpack:///src/app/core/persistence/database.service.ts:113:12)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.0.3.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.339ce1cbc4ae1c91dd48.js:1:2308563)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28540:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1213:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1167:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1279:16)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28540:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone-evergreen.js:582:34)
task.zone.runTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:491:20)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1600:13)
META: SP7.0.3 Electron – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.3 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

**Comment by Jogiio** [comment]
![2021-06-16 17_03_23-](https://user-images.githubusercontent.com/84452087/122243945-cccf9480-cec4-11eb-8bf2-3389350ff2da.png)

**Comment by Jogiio** [comment]
Close Issue because its already reported with: #955
