### ISSUE TITLE
Error: Uncaught (in promise): Error: DataError: Failed to write blobs (IOError)Error: DataError: Failed to write blobs (IOError)    at t. (file:///snap/superproductivity/1269/resources/app.asar/dist/main.dc427a99a9bd15a0811f.js:1:2338095)    at Generator.throw ()    at a (file:///snap/superproductivity/1269/resources/app.asar/dist/main.dc427a99a9bd15a0811f.js:1:2337307)

### ISSUE THREAD

**Issue by TimoStolz** [johannesjo/super-productivity#1322]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
await (webpack:///src/app/core/persistence/database.service.ts:58:12)
Ur (file:///snap/superproductivity/1269/resources/app.asar/dist/main.dc427a99a9bd15a0811f.js:1:2337307)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1120:16)
Ur (file:///snap/superproductivity/1269/resources/app.asar/dist/main.dc427a99a9bd15a0811f.js:1:1499043)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
```

### Meta Info
META: SP7.1.0 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.1.0 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

### Actions Before Error
```
1624868887629: [Persistence] Save to DB 
1624868889912: [Task] Add time spent 
1624868889915: [Project] Update Work End 
1624868889924: [Tag] Update Work End for Tag 
1624868889932: [Persistence] Save to DB 
1624868889932: [Persistence] Save to DB 
1624868889933: [Persistence] Save to DB 
1624868890536: [Task] Add time spent 
1624868890538: [Project] Update Work End 
1624868890542: [Tag] Update Work End for Tag 
1624868890545: [Persistence] Save to DB 
1624868890545: [Persistence] Save to DB 
1624868890545: [Persistence] Save to DB 
1624868892464: [SP_ALL] Load(import) all data 
1624868892468: [SP_ALL] All Data was loaded 
1624868900809: [Task] SetSelectedTask 
1624868902558: [Task] Move to archive 
1624868902580: [Persistence] Save to DB 
1624868902581: [Persistence] Save to DB 
1624868902582: [Persistence] Save to DB 
1624868902583: [Task] UnsetCurrentTask 
1624868902584: [Pomodoro] Pause Pomodoro 
1624868902677: [Persistence] Save to DB 
1624868908324: [SP_ALL] Load(import) all data 
1624868908328: [SP_ALL] All Data was loaded 
1624868909285: [Task] SetSelectedTask 
1624868911011: [Task] Move to archive 
1624868911016: [Persistence] Save to DB 
1624868911018: [Task] UnsetCurrentTask 
1624868911020: [Pomodoro] Pause Pomodoro
```

**Comment by johannesjo** [comment]
Thanks for reporting this!
