### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by kesselb** [johannesjo/super-productivity#1426]
### Steps to Reproduce
1. Select a project
2. Show worklog
3. Try to export a month / a week

> Please provide an unambiguous set of steps to reproduce this bug! 

Sorry I don't know. I have a complex set of tasks / repeating tasks / repeating task with sub tasks. Not sure how to reproduce this state or which item is causing this.

Looks similar to: https://github.com/johannesjo/super-productivity/issues/874

### Stacktrace
```
TypeError: Cannot read property 'title' of undefined
    at CX (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:3187721)
    at file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:3196010
    at Array.forEach (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:3195977
    at file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:3196228
    at u._next (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:3196598)
    at u.__tryOrUnsub (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:1195492)
    at u.next (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:1194721)
    at c._next (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:1193900)
    at c.next (file:///opt/superProductivity/resources/app.asar/dist/main.10cd9b5fc9f506c72dc8.js:1:1193674)
```

### Meta Info
META: SP7.3.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.3.3 Chrome/91.0.4472.124 Electron/13.1.6 Safari/537.36

### Actions Before Error
```
1627999531240: [Task] SetSelectedTask 
1627999531467: [Note] Load Note State 
1627999531495: [Bookmark] Load Bookmark State 
1627999531495: [Project] Load Project related Data Success 
1627999531496: [Improvement] Clear Hidden Improvements 
1627999531496: [Improvement] Delete multiple Improvements 
1627999584783: [Layout] Hide SideBar 
1627999666475: [Task] Restore Task 
1627999666485: [Persistence] Save to DB 
1627999666485: [Persistence] Save to DB 
1627999666800: [Persistence] Save to DB 
1627999673422: [Task] Update Task 
1627999673423: [Persistence] Save to DB 
1627999674182: [Task] Update Task 
1627999674208: [Persistence] Save to DB 
1627999678738: [Task] SetSelectedTask 
1627999680356: [Task] Move to archive 
1627999680362: [Persistence] Save to DB 
1627999680362: [Persistence] Save to DB 
1627999680363: [Task] UnsetCurrentTask 
1627999680401: [Persistence] Save to DB 
1627999696069: [SP_ALL] Load(import) all data 
1627999696071: [SP_ALL] All Data was loaded 
1627999696086: [WorkContext] Set Active Work Context 
1627999696096: [Task] SetSelectedTask 
1627999696341: [Note] Load Note State 
1627999696380: [Bookmark] Load Bookmark State 
1627999696381: [Project] Load Project related Data Success 
1627999696381: [Improvement] Clear Hidden Improvements 
1627999696382: [Improvement] Delete multiple Improvements
```

**Comment by kesselb** [comment]
Hi, thanks for your fast reply. I'm sorry but sharing the data is not possible. 

```
{
    "id": "3HXSkCt8V",
    "projectId": "PQi8xylgS",
    "subTaskIds": [],
    "timeSpentOnDay": {
        "2021-07-12": 0
    },
    "timeSpent": 0,
    "isDone": true,
    "doneOn": null,
    "title": "☎️ Support Call",
    "notes": "",
    "tagIds": [],
    "parentId": "d7YL1xLgI_",
    "reminderId": null,
    "created": 1623674393120,
    "repeatCfgId": null,
    "plannedAt": null,
    "_showSubTasksMode": 2,
    "attachments": [],
    "issueId": null,
    "issuePoints": null,
    "issueType": null,
    "issueAttachmentNr": null,
    "issueLastUpdated": null,
    "issueWasUpdated": null,
    "dateStr": "2021-07-12"
}
```

https://github.com/johannesjo/super-productivity/blob/8b484481fed2f468cdf2391547ecb38e093df3da/src/app/features/worklog/worklog-export/worklog-export.util.ts#L186-L188

I did some debugging (using a git checkout). Above is the failing object. For some reason the parentId does not exist. I think Support Call was a "normal" item first but I made it a sub task of another item later.  `(data.tasks.find((ptIN) => ptIN.id === task.parentId)` is undefined for this `task.parentId`. 

![image](https://user-images.githubusercontent.com/3902676/128085226-8db2d13e-2bd0-4364-b1db-b27228ddfb4d.png)

Indeed this looks also a bit weird in the UI. I'm not able to restore the first Support Call item because the "parent" does not exist. I'm not sure how I broke that ;)
```

diff --git a/src/app/features/worklog/worklog-export/worklog-export.util.ts b/src/app/features/worklog/worklog-export/worklog-export.util.ts
index ac034a514..15be79ab6 100644
--- a/src/app/features/worklog/worklog-export/worklog-export.util.ts
+++ b/src/app/features/worklog/worklog-export/worklog-export.util.ts
@@ -182,9 +182,14 @@ const handleWorklogGroup = (data: WorklogExportData): ItemsByKey<RowItem> => {
  * Unfolds task into taskFields while mapping id's to titles, and minor formatting
  */
 const getTaskFields = (task: WorklogTask, data: WorklogExportData): TaskFields => {
+  let parentTask;
+  if (task.parentId) {
+    parentTask = data.tasks.find((ptIN) => ptIN.id == task.parentId);
+  }
+
   const titlesWithSub = [task.title];
-  const titles = task.parentId
-    ? [(data.tasks.find((ptIN) => ptIN.id === task.parentId) as WorklogTask).title]
+  const titles = parentTask
+    ? [parentTask.title]
     : [task.title];
 
   const notes = task.notes ? [task.notes.replace(/\n/g, ' - ')] : [];
@@ -197,8 +202,8 @@ const getTaskFields = (task: WorklogTask, data: WorklogExportData): TaskFields =
 
   // by design subtasks don't have tags, so we must set its parent's tags
   let tags =
-    task.parentId !== null
-      ? (data.tasks.find((t) => t.id === task.parentId) as WorklogTask).tagIds
+    parentTask
+      ? parentTask.tagIds
       : task.tagIds;
   tags = tags.map(
     (tagId) => (data.tags.find((tag) => tag.id === tagId) as TagCopy).title,
```

With the above changes exporting the tasklog view works again.

![image](https://user-images.githubusercontent.com/3902676/128085723-184a3368-729c-4968-a7b7-4d8fa55697ff.png)

**Comment by stkofler** [comment]
Hi and thanks for your efforts. We've faced similar problems and your solution definitely works. 
IMO, the problem is that the user would be left unaware that there is an underlying data inconsistency and might eventually and rightfully complain about wrong titles or no tags showing up where they actually should. (arguably, but most likely, still better than the breaking error you've been getting).

Maybe an idea for such cases could be to:
if parentTask is still not defined inside your provided if statement, add a snack popup warning that tells which task is failing and that the worklog might not be complete. This could then be used to manually fix the json-export of the app data and then be reimported.

Just a thought, not easy to deal with such cases...

**Comment by johannesjo** [comment]
@stkofler thank you for your input on this. :) I'd assume that the problem is caused by the data getting into an invalid state. Ideally this would never happen, but it can't be avoided with 100% certainty. This is why the data validity checks and the auto-repair scripts exist and I think those would be the best place to address the issue.

@kesselb there is a script to anonymize the data: `src/app/imex/file-imex/privacy-export.ts`. Unfortunately this is not yet implemented in a user friendly way, but if you're able to run the app for your self, you can do it by just commenting in line 64 in `src/app/imex/file-imex/file-imex.component.ts`

**Comment by stkofler** [comment]
After a quick look: _cleanupOrphanedSubTasks takes care of the opposite in data-repair.util.ts. 
It deletes wrong subtaskIds on the parent tasks.
Maybe this could be augmented to check if the task with parentId exists, too, and if not just delete the parentId on the subtask?

Not sure when I could get a deeper look of this, but it might be an easy fix...

**Comment by johannesjo** [comment]
> Maybe this could be augmented to check if the task with parentId exists, too, and if not just delete the parentId on the subtask?

That's a good idea! At least for archived tasks. For non archived tasks just deleting the sub task might be easier, as otherwise they might or might not need to be added to the project and tag task lists, too.

**Comment by kesselb** [comment]
Found some time today to do some debugging. I'm not able to trigger this kind of situation (subtask with an non-existing) parent task anymore. When the error happen I ran an outdated version of superproducitivty (6.x). So maybe some recent changes already fixed it and we only need a migration / repair routine for the old tasks.

**Comment by johannesjo** [comment]
> So maybe some recent changes already fixed it and we only need a migration / repair routine for the old tasks.

That might very well be.

**Comment by stkofler** [comment]
> Seems like this was already automatically fixed by the repair script, but not detected by the validation script. I updated the later.
> 
> Thank you very much you two!! :) (btw. @stkofler: How is it going? :))

Good to hear this was automatically fixed by the repair script :)
I'm doing quite well but as you can see also quite busy 😅
Hardly find the time to catch up on what is happening here...
Is there still something to do on this issue?

**Comment by johannesjo** [comment]
:)

> Is there still something to do on this issue?

No (:

**Comment by kesselb** [comment]
Hey :wave: 

I run into this issue again :disappointed: 

It seems related to tasks / sub tasks in different months this time. 

September:
![image](https://user-images.githubusercontent.com/3902676/139739399-34c255d9-d057-4b49-a4b8-727739efe022.png)

October:
![image](https://user-images.githubusercontent.com/3902676/139739465-cb41db61-107c-44b8-ba3f-5e9759069b5f.png)

The sub task in October is missing the parent and result in `TypeError: Cannot read property 'title' of undefined` again.

**Comment by johannesjo** [comment]
Hey @kesselb ! Could you maybe open up a new issue for this and also maybe send an export of your data to contact@super-productivity.com ?
