### ISSUE TITLE
Error: Textarea not visible

### ISSUE THREAD

**Issue by thangcqUET** [johannesjo/super-productivity#1440]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Textarea not visible
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2731453
    at s.<computed> (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:31944)
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7073)
    at t.runTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:8202)
    at invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:8104)
    at n.args.<computed> (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:31657)
```

### Meta Info
META: SP7.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1628479576474: [Persistence] Save to DB 
1628479576475: [Persistence] Save to DB 
1628479577448: [Task] Add time spent 
1628479577451: [Tag] Update Work End for Tag 
1628479577466: [Persistence] Save to DB 
1628479577467: [Persistence] Save to DB 
1628479578448: [Task] Add time spent 
1628479578450: [Tag] Update Work End for Tag 
1628479578462: [Persistence] Save to DB 
1628479578463: [Persistence] Save to DB 
1628479579448: [Task] Add time spent 
1628479579451: [Tag] Update Work End for Tag 
1628479579464: [Persistence] Save to DB 
1628479579465: [Persistence] Save to DB 
1628479580448: [Task] Add time spent 
1628479580450: [Tag] Update Work End for Tag 
1628479580461: [Persistence] Save to DB 
1628479580462: [Persistence] Save to DB 
1628479581448: [Task] Add time spent 
1628479581451: [Tag] Update Work End for Tag 
1628479581461: [Persistence] Save to DB 
1628479581461: [Persistence] Save to DB 
1628479582448: [Task] Add time spent 
1628479582451: [Tag] Update Work End for Tag 
1628479582461: [Persistence] Save to DB 
1628479582462: [Persistence] Save to DB 
1628479583448: [Task] Add time spent 
1628479583451: [Tag] Update Work End for Tag 
1628479583463: [Persistence] Save to DB 
1628479583463: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for reporting. Could you maybe provide a little bit more input on what happened before the error showed up?
