### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of nullTypeError: Cannot read property 'summary' of null  

### ISSUE THREAD

**Issue by thangcqUET** [johannesjo/super-productivity#1441]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): TypeError: Cannot read property 'summary' of null
TypeError: Cannot read property 'summary' of null
    at t.displayIssueWith [as displayWith] (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:3121268)
    at t._setTriggerValue (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2118384)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:2116317
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:140100)
    at l.invoke (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.run (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at Z (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:15947)
    at file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16798
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at Object.onInvokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/main.29fbb60c3500c86c2112.js:1:139916)
    at l.invokeTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7073)
    at t.runTask (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at m (file:///snap/superproductivity/1332/resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:9146)
```

### Meta Info
META: SP7.5.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1628485128407: [SP_ALL] All Data was loaded 
1628485128429: [WorkContext] Set Active Work Context 
1628485128505: [Task] SetSelectedTask 
1628485129227: [Note] Load Note State 
1628485129229: [Bookmark] Load Bookmark State 
1628485129230: [Project] Load Project related Data Success 
1628485129231: [Improvement] Clear Hidden Improvements 
1628485129231: [Improvement] Delete multiple Improvements 
1628485129243: [Persistence] Save to DB 
1628485129403: [Persistence] Save to DB 
1628485130429: [Persistence] Save to DB 
1628485130565: [Persistence] Save to DB 
1628485130676: [Persistence] Save to DB 
1628485130714: [Persistence] Save to DB 
1628485130715: [Persistence] Save to DB 
1628485130716: [Persistence] Save to DB 
1628485130717: [Persistence] Save to DB 
1628485130717: [Persistence] Save to DB 
1628485130718: [Persistence] Save to DB 
1628485130719: [Persistence] Save to DB 
1628485130721: [Persistence] Save to DB 
1628485130722: [Persistence] Save to DB 
1628485130724: [Persistence] Save to DB 
1628485130724: [Persistence] Save to DB 
1628485131784: [SP_ALL] Load(import) all data 
1628485131814: [Persistence] Remove from DB 
1628485138856: [SP_ALL] Load(import) all data 
1628485138858: [SP_ALL] All Data was loaded 
1628485138885: [WorkContext] Set Active Work Context 
1628485138908: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Thanks for reporting this!

**Comment by johannesjo** [comment]
Could you maybe provide a little bit more input on what happened before the error appeared?
