### ISSUE TITLE
Error: Editing sub task tags should not be possible.

### ISSUE THREAD

**Issue by cheynolds** [johannesjo/super-productivity#1452]
### Steps to Reproduce

1. create a task
2. create sub-task within the task
3. select sub-task
4. invoke keyboard shortcut  ('g') to edit tags on sub-task
5. select an existing tag or create new tag, press enter

### Stacktrace
```
Error: Editing sub task tags should not be possible.
    at t.updateTags (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:1960420)
    at t._updateTags (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3355632)
    at t.addTag (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3355396)
    at https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:3356313
    at mo (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:96387)
    at Object.n [as next] (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:96549)
    at u.__tryOrUnsub (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:1202479)
    at u.next (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:1201708)
    at l._next (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:1200887)
    at l.next (https://app.super-productivity.com/main-es2015.2107a37827bd4327090f.js:1:1200661)
```

### Meta Info
META: SP7.5.0 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

### Actions Before Error
```
1628909206819: [Persistence] Save to DB 
1628909206819: [Persistence] Save to DB 
1628909206820: [Persistence] Save to DB 
1628909207772: [Task] Add time spent 
1628909207773: [Project] Update Work End 
1628909207795: [Tag] Update Work End for Tag 
1628909207819: [Persistence] Save to DB 
1628909207820: [Persistence] Save to DB 
1628909207820: [Persistence] Save to DB 
1628909208772: [Task] Add time spent 
1628909208773: [Project] Update Work End 
1628909208796: [Tag] Update Work End for Tag 
1628909208820: [Persistence] Save to DB 
1628909208820: [Persistence] Save to DB 
1628909208820: [Persistence] Save to DB 
1628909209772: [Task] Add time spent 
1628909209773: [Project] Update Work End 
1628909209795: [Tag] Update Work End for Tag 
1628909209818: [Persistence] Save to DB 
1628909209819: [Persistence] Save to DB 
1628909209819: [Persistence] Save to DB 
1628909212081: [SP_ALL] Load(import) all data 
1628909212083: [SP_ALL] All Data was loaded 
1628909212099: [WorkContext] Set Active Work Context 
1628909212116: [Task] SetSelectedTask 
1628909212139: [Note] Load Note State 
1628909212147: [Bookmark] Load Bookmark State 
1628909212148: [Project] Load Project related Data Success 
1628909212149: [Improvement] Clear Hidden Improvements 
1628909212149: [Improvement] Delete multiple Improvements
```

**Comment by johannesjo** [comment]
Oh good catch! Thank you very much!

**Comment by johannesjo** [comment]
This will be fixed with the next release. Thank you very much again.
