### ISSUE TITLE
Error: Editing sub task tags should not be possible.

### ISSUE THREAD

**Issue by leonqli** [johannesjo/super-productivity#1462]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Editing sub task tags should not be possible.
    at t.updateTags (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1833321)
    at t._updateTags (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:3227674)
    at t.addTag (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:3227438)
    at file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:3228355
    at ko (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:94028)
    at Object.n [as next] (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:94190)
    at u.__tryOrUnsub (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1077400)
    at u.next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1076629)
    at c._next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1075808)
    at c.next (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:1075582)
```

### Meta Info
META: SP7.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.1 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1629292658719: [Project] Load Project related Data Success 
1629292658720: [Improvement] Clear Hidden Improvements 
1629292658720: [Improvement] Delete multiple Improvements 
1629292663102: [Bookmark] Toggle Bookmarks 
1629292663103: [Persistence] Save to DB 
1629292664977: [WorkContext] Set Active Work Context 
1629292665021: [Task] SetSelectedTask 
1629292665940: [WorkContext] Set Active Work Context 
1629292665967: [Task] SetSelectedTask 
1629292666158: [Bookmark] Load Bookmark State 
1629292666174: [Note] Load Note State 
1629292666175: [Project] Load Project related Data Success 
1629292666175: [Improvement] Clear Hidden Improvements 
1629292666176: [Improvement] Delete multiple Improvements 
1629292684327: [Bookmark] Delete Bookmark 
1629292684328: [Persistence] Save to DB 
1629292691478: [WorkContext] Set Active Work Context 
1629292691518: [Task] SetSelectedTask 
1629292695005: [WorkContext] Set Active Work Context 
1629292695027: [Task] SetSelectedTask 
1629292695247: [Bookmark] Load Bookmark State 
1629292695255: [Note] Load Note State 
1629292695256: [Project] Load Project related Data Success 
1629292695257: [Improvement] Clear Hidden Improvements 
1629292695257: [Improvement] Delete multiple Improvements 
1629292702909: [Bookmark] Toggle Bookmarks 
1629292702909: [Persistence] Save to DB 
1629292714152: [Task] Update Task Tags 
1629292714169: [Persistence] Save to DB 
1629292714169: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this. I provide a fix for this with the next release.
