### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefinedTypeError: Cannot read property 'config' of undefined    at t. (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2995687)

### ISSUE THREAD

**Issue by yunonima** [johannesjo/super-productivity#1463]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2995687)
    at Generator.next (<anonymous>)
    at https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2995223
    at new P (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:17784)
    at nJ (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2994971)
    at FileReader.n.onload (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2995490)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6540)
    at Object.onInvoke (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:142498)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6480)
    at t.runGuarded (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:2062)
    at b (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:15919)
    at new P (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:17812)
    at nJ (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2994971)
    at FileReader.n.onload (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:2995490)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6540)
    at Object.onInvoke (https://app.super-productivity.com/main-es2015.1f4a1875293d2b9f7cb0.js:1:142498)
    at l.invoke (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:6480)
    at t.runGuarded (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:2062)
    at FileReader.<anonymous> (https://app.super-productivity.com/polyfills-es2015.df6fcf2a87a01af28504.js:1:1841)
```

### Meta Info
META: SP7.5.1 Browser – es-CO – Win32 – Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

### Actions Before Error
```
1629327017580: [WorkContext] Set Active Work Context 
1629327017603: [Task] SetSelectedTask 
1629327037225: [Layout] Show SearchBar 
1629327038891: [Layout] Hide SearchBar 
1629328307444: [SP_ALL] Load(import) all data 
1629328307455: [SP_ALL] All Data was loaded 
1629328342575: [SP_ALL] Load(import) all data 
1629328342581: [SP_ALL] All Data was loaded 
1629328348881: [SP_ALL] Load(import) all data 
1629328348895: [SP_ALL] All Data was loaded 
1629328381514: [Global Config] Update Global Config Section 
1629328381523: [Persistence] Save to DB 
1629328399328: [Global Config] Update Global Config Section 
1629328399361: [Persistence] Save to DB 
1629328418400: [Global Config] Update Global Config Section 
1629328418429: [Persistence] Save to DB 
1629328424741: [Global Config] Update Global Config Section 
1629328424754: [Persistence] Save to DB 
1629328431976: [Global Config] Update Global Config Section 
1629328431996: [Persistence] Save to DB 
1629328448589: [SP_ALL] Load(import) all data 
1629328448599: [SP_ALL] All Data was loaded 
1629328463322: [Global Config] Update Global Config Section 
1629328463342: [Persistence] Save to DB 
1629328465879: [Global Config] Update Global Config Section 
1629328465888: [Persistence] Save to DB 
1629328484175: [Global Config] Update Global Config Section 
1629328484204: [Persistence] Save to DB 
1629328486663: [Global Config] Update Global Config Section 
1629328486677: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for reporting! Could you maybe provide a little bit more context on what happened right before this appeared?
