### ISSUE TITLE
Error: Uncaught (in promise): Error: Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by jfeid** [johannesjo/super-productivity#1477]
### Steps to Reproduce
1. Nothing special, just popped this error unexpectedly 
2.
3.
4.

### Console Output
```
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
zone.js:2561 12:37:27.464 › Error while backing up
zone.js:2561 12:37:27.466 › Error: EACCES: permission denied, open '/home/john/snap/superproductivity/1342/.config/superProductivity/backups/2021-08-30.json'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.writeFileSync (fs.js:1467:35)
    at IpcMainImpl.backupData (/snap/superproductivity/1342/resources/app.asar/electron/backup.js:52:14)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)
s.<computed> @ zone.js:2561
sync.effects.ts:123 sync(effect)..... I_FOCUS_THROTTLED
database.service.ts:45 DB Load Error: Last Params, Object
(anonymous) @ database.service.ts:45
zone.js:2561 12:37:27.525 › getSettingsCb no callbacks left
s.<computed> @ zone.js:2561
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
database.service.ts:45 DB Load Error: Last Params, Object
(anonymous) @ database.service.ts:45
database.service.ts:57 DB Save Error: Last Params, Object
(anonymous) @ database.service.ts:57
global-error-handler.class.ts:36 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at sm.<anonymous> (database.service.ts:58)
    at Generator.throw (<anonymous>)
    at a (main.1e19198e6fde17fa3e56.js:1)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
    at Z (zone.js:1213)
    at zone.js:1120
    at a (main.1e19198e6fde17fa3e56.js:1)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28660)
```

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:63:12)
toString (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:3402212)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
toString (file:///snap/superproductivity/1342/resources/app.asar/dist/main.1e19198e6fde17fa3e56.js:1:3402230)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28660:32)
```

### Meta Info
META: SP7.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.1 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1630315924307: [Tag] Update Work End for Tag 
1630315924310: [Persistence] Save to DB 
1630315924310: [Persistence] Save to DB 
1630315924311: [Persistence] Save to DB 
1630315925297: [Task] Add time spent 
1630315925299: [Project] Update Work End 
1630315925307: [Tag] Update Work End for Tag 
1630315925310: [Persistence] Save to DB 
1630315925310: [Persistence] Save to DB 
1630315925311: [Persistence] Save to DB 
1630315926297: [Task] Add time spent 
1630315926299: [Project] Update Work End 
1630315926306: [Tag] Update Work End for Tag 
1630315926312: [Persistence] Save to DB 
1630315926313: [Persistence] Save to DB 
1630315926313: [Persistence] Save to DB 
1630315927297: [Task] Add time spent 
1630315927299: [Project] Update Work End 
1630315927308: [Tag] Update Work End for Tag 
1630315927311: [Persistence] Save to DB 
1630315927311: [Persistence] Save to DB 
1630315927312: [Persistence] Save to DB 
1630316247438: [Task] Add time spent 
1630316247440: [Project] Update Work End 
1630316247447: [Tag] Update Work End for Tag 
1630316247450: [Persistence] Save to DB 
1630316247451: [Persistence] Save to DB 
1630316247451: [Persistence] Save to DB 
1630316247466: [Task] Remove time spent 
1630316247467: [Task] UnsetCurrentTask
```

**Comment by johannesjo** [comment]
Thanks for reporting. Looks like a duplicate of #398
