### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefinedTypeError

### ISSUE THREAD

**Issue by DingDean** [johannesjo/super-productivity#1484]
# What happened
Failed to sync from Google Drive.

I have two computers (A and B) with super-productivity installed. I setup A with syncing Google Drive the other day, and now I tried to sync with Google Drive on B, and then things got wired:

1. The first time I opened superproductivity on B, it stucks on loading screen and at the bottom there is a fast-refreshing error message something like "failed to load config, fall back to local copy" (It's not the exact word appeared).
2. I reopened the app, then it asked me if I still want to sync with remote config since there was an error. I clicked "Cancel" and want to import the config file manually.
3. I download the config file from Google Drive manually and then loaded it, and bam, the following error msg appeared.

### Steps to Reproduce

1. Take two computers
2. Sync one computer's superproductivity with Google Drive
3. Open superproductivity on another computer
4. Load config file from Google Drive mannualy.

### Console Output
**Following is just part of the console output**, it seems it's related to reading local config file.
I opened the config file and it's definitely **not valid JSON** as it contains garbled character.

global-error-handler.class.ts:36 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file-imex.component.ts:42)
    at Generator.next (<anonymous>)
    at main.fadf279e9635436f8e1b.js:1
    at new C (zone.js:1387)
    at SK (main.fadf279e9635436f8e1b.js:1)
    at FileReader.n.onload (file-imex.component.ts:31)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.runGuarded (zone.js:144)
    at Z (zone.js:1213)
    at new C (zone.js:1390)
    at SK (main.fadf279e9635436f8e1b.js:1)
    at FileReader.n.onload (file-imex.component.ts:31)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.runGuarded (zone.js:144)
    at FileReader.<anonymous> (zone.js:128)
(anonymous) @ global-error-handler.class.ts:36
action-logger.ts:30 Last actions before error: Array(30)
global-error-handler.class.ts:80 t
global-error-handler.util.ts:115 Object
zone.js:1063 Unhandled Promise rejection: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984491)
    at Generator.next (<anonymous>)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984027
    at new C (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:17806)
    at SK (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2983775)
    at FileReader.n.onload (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984294)
    at l.invoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:140100)
    at l.invoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.runGuarded (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2056) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file-imex.component.ts:42)
    at Generator.next (<anonymous>)
    at main.fadf279e9635436f8e1b.js:1
    at new C (zone.js:1387)
    at SK (main.fadf279e9635436f8e1b.js:1)
    at FileReader.n.onload (file-imex.component.ts:31)
    at l.invoke (zone.js:372)
    at Object.onInvoke (core.js:28673)
    at l.invoke (zone.js:371)
    at t.runGuarded (zone.js:144)
    at t.<anonymous> (global-error-handler.class.ts:63)
    at Generator.next (<anonymous>)
    at o (main.fadf279e9635436f8e1b.js:1)
    at l.invoke (zone.js:372)
    at t.run (zone.js:134)
    at zone.js:1276
    at l.invokeTask (zone.js:406)
    at t.runTask (zone.js:178)
    at m (zone.js:582) Error: Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined
TypeError: Cannot read property 'config' of undefined
    at t.<anonymous> (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984491)
    at Generator.next (<anonymous>)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984027
    at new C (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:17806)
    at SK (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2983775)
    at FileReader.n.onload (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984294)
    at l.invoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at Object.onInvoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:140100)
    at l.invoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6474)
    at t.runGuarded (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2056)
    at t.<anonymous> (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:3401936)
    at Generator.next (<anonymous>)
    at o (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:3399290)
    at l.invoke (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:6534)
    at t.run (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:1933)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:16742
    at l.invokeTask (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:7152)
    at t.runTask (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:2548)
    at m (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/polyfills.3f21005097f2d4ba8d4e.js:1:9146)
n.onUnhandledError @ zone.js:1063

### Stacktrace
```
Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:42:18)
toString (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2984027)
constructor (webpack:///node_modules/zone.js/fesm2015/zone.js:1387:28)
toString (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2983775)
constructor (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:31)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
runGuarded (webpack:///node_modules/zone.js/fesm2015/zone.js:144:46)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
executor(makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1390:16)
toString (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fadf279e9635436f8e1b.js:1:2983775)
constructor (webpack:///src/app/imex/file-imex/file-imex.component.ts:31:31)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28673:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
runGuarded (webpack:///node_modules/zone.js/fesm2015/zone.js:144:46)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:128:28)
```

### Meta Info
META: SP7.5.2 Electron – zh-CN – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.2 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1630549123750: [Persistence] Save to DB 
1630549123751: [Persistence] Save to DB 
1630549123879: [Persistence] Save to DB 
1630549123880: [Persistence] Save to DB 
1630549123881: [Persistence] Save to DB 
1630549123882: [Persistence] Save to DB 
1630549123882: [Persistence] Save to DB 
1630549123883: [Persistence] Save to DB 
1630549123883: [Persistence] Save to DB 
1630549123884: [Persistence] Save to DB 
1630549123884: [Persistence] Save to DB 
1630549123884: [Persistence] Save to DB 
1630549123885: [Persistence] Save to DB 
1630549124014: [Persistence] Save to DB 
1630549124015: [Persistence] Save to DB 
1630549124016: [Persistence] Save to DB 
1630549124016: [Persistence] Save to DB 
1630549124017: [Persistence] Save to DB 
1630549124017: [Persistence] Save to DB 
1630549124018: [Persistence] Save to DB 
1630549124018: [Persistence] Save to DB 
1630549124019: [Persistence] Save to DB 
1630549124020: [Persistence] Save to DB 
1630549124020: [Persistence] Save to DB 
1630549130736: [Persistence] Remove from DB 
1630549130805: [SP_ALL] Load(import) all data 
1630549130807: [SP_ALL] All Data was loaded 
1630549137028: [Layout] Toggle SideBar 
1630549166518: [Global Config] Update Global Config Section 
1630549166523: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for taking your time to open this up. Maybe one of those is helpful to you: #1023 #1390

**Comment by DingDean** [comment]
oops, my bad, I forgot to search for similar existing issues before posting. 
The "Copy & Report" button was too tempting :)

I set up my second computer with Google Drive properly. Thanks!

**Comment by johannesjo** [comment]
Glad that it works now ! :) Thanks for letting me know.
