### ISSUE TITLE
Error: Project dHB7xzomZ not found

### ISSUE THREAD

**Issue by DBecker7** [johannesjo/super-productivity#1530]
Every time I start the app I get a "Project not FOund" error. There appears to be a ghost task with an old/renamed project. 

### Steps to Reproduce
1. Add recurring task to project
2. Delete or rename project? (I'm not fully sure, and it's hard for me to just delete all my data to see if I can reproduce an error.)

### Console Output
- projectId dHB7xzomZ from task not existing

### Stacktrace
```
Error: Project dHB7xzomZ not found
    at file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1510204
    at file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:177333
    at memoized (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:176907)
    at mt (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:177725)
    at file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:177385
    at memoized (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:176907)
    at o.project (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:176302)
    at o._next (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1087618)
    at o.next (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1075767)
    at t._subscribe (file:///tmp/.mount_superPep8myi/resources/app.asar/dist/main.2169d5d12358f46feff8.js:1:1068444)
```

### Meta Info
META: SP7.5.2 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.5.2 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1632170745855: [Persistence] Save to DB 
1632170745856: [TaskRepeatCfg] Update TaskRepeatCfg 
1632170745856: [Persistence] Save to DB 
1632170745856: [Task][Issue] Add Task 
1632170745861: [Persistence] Save to DB 
1632170745861: [Persistence] Save to DB 
1632170745862: [Persistence] Save to DB 
1632170745862: [TaskRepeatCfg] Update TaskRepeatCfg 
1632170745862: [Persistence] Save to DB 
1632170745975: [Task] Update Task 
1632170745977: [Persistence] Save to DB 
1632170745977: [Task] Update Task Tags 
1632170745986: [Project] Auto Move Task from backlog to today 
1632170745987: [Persistence] Save to DB 
1632170745987: [Persistence] Save to DB 
1632170745987: [Persistence] Save to DB 
1632170745987: [Task] Update Task 
1632170745988: [Persistence] Save to DB 
1632170745988: [Task] Update Task Tags 
1632170745993: [Project] Auto Move Task from backlog to today 
1632170745994: [Persistence] Save to DB 
1632170745994: [Persistence] Save to DB 
1632170745994: [Persistence] Save to DB 
1632170745995: [Task] Update Task 
1632170745996: [Persistence] Save to DB 
1632170745996: [Task] Update Task Tags 
1632170746000: [Project] Auto Move Task from backlog to today 
1632170746001: [Persistence] Save to DB 
1632170746001: [Persistence] Save to DB 
1632170746001: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look!

**Comment by johannesjo** [comment]
With the next release this should be fixed from occurring again. I also added extended the data repair script to fix this for cases when this already happened. Please, let me know if it works for you!
