### ISSUE TITLE
Error: Error retrieving icon :jira! Http failure response for assets/icons/jira.svg: 0 Unknown Error

### ISSUE THREAD

**Issue by Zab-an** [johannesjo/super-productivity#1562]
### Steps to Reproduce

1. Disconnect from internet (Android) 
2. Go to manage projects tab
3. Try to edit a project
4.

### Stacktrace
```
Error: Error retrieving icon :jira! Http failure response for assets/icons/jira.svg: 0 Unknown Error
    at u._error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1781602)
    at u.__tryOrUnsub (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1081727)
    at u.error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1081195)
    at c._error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1080170)
    at c.error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1079967)
    at l._error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1080170)
    at l.error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1079967)
    at o._error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1080170)
    at o.error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1079967)
    at o._error (https://app.super-productivity.com/main.eb1cb7759871775ef85b.js:1:1080170)
```

### Meta Info
META: SP7.6.0 Browser – fr-FR – Linux armv8l – Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Actions Before Error
```
1633298575075: [Layout] Hide AddTaskBar 
1633298575567: [Task] SetSelectedTask 
1633298577547: [Task] Add SubTask 
1633298577556: [Persistence] Save to DB 
1633298578235: [Task] SetSelectedTask 
1633298584008: [Task] Update Task 
1633298584013: [Persistence] Save to DB 
1633298585651: [Task] SetSelectedTask (2) 
1633298587620: [Task] Add SubTask 
1633298587623: [Persistence] Save to DB 
1633298588945: [Task] SetSelectedTask 
1633298600567: [Task] Update Task 
1633298600570: [Persistence] Save to DB 
1633298601931: [Task] SetSelectedTask (2) 
1633298603686: [Task] Add SubTask 
1633298603690: [Persistence] Save to DB 
1633298606384: [Task] SetSelectedTask (3) 
1633298608233: [Task] Add SubTask 
1633298608240: [Persistence] Save to DB 
1633298608930: [Task] SetSelectedTask 
1633298612207: [Task] Update Task 
1633298612214: [Persistence] Save to DB 
1633298613357: [Task] SetSelectedTask (2) 
1633298616235: [Task] Update Task 
1633298616240: [Persistence] Save to DB 
1633298616258: [Task] SetSelectedTask 
1633298618136: [Layout] Toggle SideBar 
1633298619781: [Layout] Hide SideBar (2) 
1633298629654: [SP_ALL] Load(import) all data 
1633298629659: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look.

**Comment by johannesjo** [comment]
I think that this should be fixed now. Can you confirm @Zab-an ?

**Comment by Zab-an** [comment]
Yes, I can't reproduce it anymore. 

Tested on 7.10.1

**Comment by johannesjo** [comment]
Thank you very much for checking  @Zab-an
