### ISSUE TITLE
Jira request error

### ISSUE THREAD

**Issue by rikobrandes** [johannesjo/super-productivity#161]
### Your Environment

* Version used: 2.5.8
* Operating System and version: Ubuntu 16.04.6 LTS
* Desktop Environment: Unity
* Browser Name and version: 

### Expected Behavior
Set up Jira credentials (version 1.10.56 works still with Jira)
Get "Updated project settings for Jira" checked in green. 
Saved settings.
 

### Current Behavior
When adding a task, I get "Jira request error"

### Error Log (Desktop only)
<!--- For the desktop versions there is also an error log file. 
Usually you can find it here:
on Linux: ~/.config/superProductivity/log.log
[2019-04-04 15:05:25.750] [error] Frontend Error: { handledError: 'RequestError' } Error
    at e.handleError (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:2883130)
    at Object.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:229226)
    at t.object.r [as _next] (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:188023)
    at t.__tryOrUnsub (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:373421)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:372566)
    at t._next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371618)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371289)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:405160)
    at t.emit (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:187804)
    at file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:222854
[2019-04-04 15:07:05.463] [error] Frontend Error: { handledError: 'RequestError' } Error
    at e.handleError (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:2883130)
    at Object.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:229226)
    at t.object.r [as _next] (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:188023)
    at t.__tryOrUnsub (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:373421)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:372566)
    at t._next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371618)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371289)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:405160)
    at t.emit (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:187804)
    at file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:222854
[2019-04-04 15:15:01.807] [error] Frontend Error: { handledError: 'RequestError' } Error
    at e.handleError (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:2883130)
    at Object.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:229226)
    at t.object.r [as _next] (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:188023)
    at t.__tryOrUnsub (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:373421)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:372566)
    at t._next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371618)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:371289)
    at t.next (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:405160)
    at t.emit (file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:187804)
    at file:///opt/superProductivity/resources/app.asar/dist/main.ffbc3c56f98159248a91.js:1:222854

**Comment by johannesjo** [comment]
There is no console output neither in the app console (Ctrl+Shift+i) nor the the command line? 

My first guess would be that there is something wrong with the config, likely the host.

**Comment by johannesjo** [comment]
Closing due to inactivity.
