### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by minus20** [johannesjo/super-productivity#1652]
1. Press "Finish day"
2. Add some tags to "What hindered your productivity"
3. Delete this tags

### Error Log (Desktop only)
I can't get logs. They are not in `%USERPROFILE%/AppData/Roaming/superProductivity/logs/` folder

### Console Output
[console-output.txt](https://github.com/johannesjo/super-productivity/files/7468706/console-output.txt)

### Stacktrace
```
TypeError: Cannot read property 'id' of undefined
    at Va.trackById [as _trackByFn] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:2836614)
    at Va.check (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:109246)
    at Va.diff (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:109075)
    at t.ngDoCheck (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:1297080)
    at Se (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:47731)
    at Ae (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:47532)
    at Oe (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:47252)
    at Mr (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:71794)
    at Object.xr (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:71637)
    at template (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.6.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.4297b2fe74deb2892f3c.js:1:2839155)
```

### Meta Info
META: SP7.6.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.6.0 Chrome/91.0.4472.124 Electron/13.1.7 Safari/537.36

### Actions Before Error
```
1635952508573: [Persistence] Save to DB 
1635952513481: [Metric] Upsert Metric 
1635952513485: [Obstruction] Delete multiple Obstructions 
1635952513485: [Persistence] Save to DB 
1635952515485: [Metric] Upsert Metric 
1635952515487: [Obstruction] Delete multiple Obstructions 
1635952515493: [Persistence] Save to DB 
1635952521569: [Obstruction] Add Obstruction 
1635952521569: [Persistence] Save to DB 
1635952521569: [Metric] Upsert Metric 
1635952521579: [Obstruction] Delete multiple Obstructions 
1635952521579: [Persistence] Save to DB 
1635952541871: [SP_ALL] Load(import) all data 
1635952541881: [SP_ALL] All Data was loaded 
1635952541993: [Task] SetSelectedTask 
1635952545892: [Task] Toggle start 
1635952545895: [Persistence] Save to DB 
1635952545895: [Task] UnsetCurrentTask 
1635952561257: [SP_ALL] Load(import) all data 
1635952561260: [SP_ALL] All Data was loaded 
1635952561321: [Task] SetSelectedTask 
1635952603762: [SP_ALL] Load(import) all data 
1635952603766: [SP_ALL] All Data was loaded 
1635952608252: [Task] SetSelectedTask 
1635952665444: [Layout] Toggle SideBar (2) 
1635952665448: [Layout] Hide SideBar 
1635952667253: [Task] SetSelectedTask 
1635952688544: [SP_ALL] Load(import) all data 
1635952688547: [SP_ALL] All Data was loaded 
1635952691543: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Thanks for reporting! I'll have a look!

**Comment by johannesjo** [comment]
Unfortunately I am unable to reproduce this. Did the error directly appear after deleting the last value from the input or only after clicking "Save and go home" ?

**Comment by minus20** [comment]
> Unfortunately I am unable to reproduce this. Did the error directly appear after deleting the last value from the input or only after clicking "Save and go home" ?

I deleted it and selected again a few times.

**Comment by johannesjo** [comment]
Thanks. Still unable to reproduce this unfortunately. If this happens again, could you maybe wait a second and then copy the traces from the console opening up (if it doesn't you can open it via Ctrl+Shift+i)?

**Comment by minus20** [comment]
Sure. It appears even after restart. I'll try again tomorrow and let you
know

**Comment by johannesjo** [comment]
Oh, it does? In that case: Would you be willing to share an export of your data to contact@super-productivity.com? That would be very helpful!

**Comment by minus20** [comment]
Today I can't reproduce the error, so I close the issue. Thank you for attention.
