### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by w-user** [johannesjo/super-productivity#1658]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:2543077
    at g.project (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:2543099)
    at g._next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1116314)
    at g.next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1104439)
    at g._next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1104665)
    at g.next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1104439)
    at g._next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1116412)
    at g.next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1104439)
    at g._next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1115823)
    at g.next (file:///snap/superproductivity/1477/resources/app.asar/dist/main.f45ed7b1b71b1d431a26.js:1:1104439)
```

### Meta Info
META: SP7.7.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.7.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1636095980094: [Task] Add time spent 
1636095980099: [Project] Update Work End 
1636095980113: [Persistence] Save to DB (2) 
1636095982796: [Task] Add time spent 
1636095982801: [Project] Update Work End 
1636095982813: [Persistence] Save to DB (2) 
1636095983029: [Task] Add time spent 
1636095983033: [Project] Update Work End 
1636095983043: [Persistence] Save to DB (2) 
1636095984030: [Task] Add time spent 
1636095984038: [Project] Update Work End 
1636095984064: [Persistence] Save to DB (2) 
1636095985030: [Task] Add time spent 
1636095985038: [Project] Update Work End 
1636095985071: [Persistence] Save to DB (2) 
1636095986060: [SP_ALL] Load(import) all data 
1636095986069: [SP_ALL] All Data was loaded 
1636095986102: [WorkContext] Set Active Work Context 
1636095986124: [Task] SetSelectedTask 
1636095989978: [Note] Load Note State 
1636095990618: [Bookmark] Load Bookmark State 
1636095990622: [Project] Load Project related Data Success 
1636095990626: [Improvement] Clear Hidden Improvements 
1636095990629: [Improvement] Delete multiple Improvements 
1636095993746: [Task] SetCurrentTask 
1636095993754: [Pomodoro] Start Pomodoro 
1636095993870: [Task] Add time spent 
1636095993877: [Project] Update Work End 
1636095993893: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
Thanks for opening this up! Could you provide a little bit more context maybe?
