### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by key-ur** [johannesjo/super-productivity#1683]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:2107790)
    at b.__tryOrUnsub (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:956876)
    at b.next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:956105)
    at T._next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:955288)
    at T.next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:955062)
    at v._next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:975388)
    at v.next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:955062)
    at O.next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:952809)
    at b._next (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:1716081)
    at b.__tryOrUnsub (file:///snap/superproductivity/1491/resources/app.asar/dist/main.9f84df739578c2cd.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1637565310080: [Tag] Update Work End for Tag 
1637565310089: [Persistence] Save to DB (3) 
1637565370067: [Task] Add time spent 
1637565370071: [Project] Update Work End 
1637565370079: [Tag] Update Work End for Tag 
1637565370086: [Persistence] Save to DB (3) 
1637565430071: [Task] Add time spent 
1637565430077: [Project] Update Work End 
1637565430093: [Tag] Update Work End for Tag 
1637565430108: [Persistence] Save to DB (3) 
1637565490067: [Task] Add time spent 
1637565490072: [Project] Update Work End 
1637565490081: [Tag] Update Work End for Tag 
1637565490094: [Persistence] Save to DB (3) 
1637565550068: [Task] Add time spent 
1637565550074: [Project] Update Work End 
1637565550088: [Tag] Update Work End for Tag 
1637565550104: [Persistence] Save to DB (3) 
1637565610067: [Task] Add time spent 
1637565610072: [Project] Update Work End 
1637565610084: [Tag] Update Work End for Tag 
1637565610099: [Persistence] Save to DB (3) 
1637565665950: [Idle] Trigger Idle 
1637565665953: [Task] Remove time spent 
1637565665958: [Task] UnsetCurrentTask 
1637565665964: [Pomodoro] Pause Pomodoro 
1637565669970: [Idle] Set idle time (5) 
1637565670938: [Idle] Trigger Idle 
1637565680972: [Idle] Set idle time (11)
```

**Comment by johannesjo** [comment]
Thanks for reporting! I am closing this in favor of #1684
