### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by timdhoffmann** [johannesjo/super-productivity#1684]
### Steps to Reproduce
I only noticed the error when returning to the app, so I'm not sure about the steps to reproduce. I _believe_ that I had a timer running on an issue and clicked on "back to work", "skip break", or similar, to discard a Pomodoro timer notification.

### Error Log (Desktop only)
No error log found at `%USERPROFILE%/AppData/Roaming/superProductivity/logs/main.log`

### Console Output
No console entries found with log levels "warning" or "error" (after restarting the app).

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1637568116332: [Idle] Set idle time (5) 
1637568117230: [Idle] Trigger Idle 
1637568121337: [Idle] Set idle time (5) 
1637568122231: [Idle] Trigger Idle 
1637568126343: [Idle] Set idle time (5) 
1637568127232: [Idle] Trigger Idle 
1637568131346: [Idle] Set idle time (5) 
1637568132232: [Idle] Trigger Idle 
1637568136352: [Idle] Set idle time (5) 
1637568137232: [Idle] Trigger Idle 
1637568141355: [Idle] Set idle time (5) 
1637568142232: [Idle] Trigger Idle 
1637568146360: [Idle] Set idle time (5) 
1637568147232: [Idle] Trigger Idle 
1637568151365: [Idle] Set idle time (5) 
1637568152234: [Idle] Trigger Idle 
1637568156371: [Idle] Set idle time (5) 
1637568157234: [Idle] Trigger Idle 
1637568161375: [Idle] Set idle time (5) 
1637568162233: [Idle] Trigger Idle 
1637568166379: [Idle] Set idle time (5) 
1637568167234: [Idle] Trigger Idle 
1637568171381: [Idle] Set idle time (5) 
1637568172234: [Idle] Trigger Idle 
1637568174383: [Idle] Set idle time (3) 
1637568174885: [Pomodoro] Finish Pomodoro Session 
1637568174886: [Task] Toggle start 
1637568174887: [Persistence] Save to DB 
1637568174887: [Task] SetCurrentTask 
1637568174888: [Pomodoro] Start Pomodoro
```

**Comment by johannesjo** [comment]
@Fleker can you have a look at this? I think this might be related to the changes in #1587

**Comment by Fleker** [comment]
I can take a look.

**Comment by johannesjo** [comment]
Thank you!

**Comment by johannesjo** [comment]
@Fleker seems like this is something else. I'll work on it.

**Comment by johannesjo** [comment]
Unfortunately I am unable to reproduce this. I also don't have an idea what might be causing this, since – as long as the dialog component works fine (and there is no reason for it working differently on different systems) – the error should not be possible. Any help in debugging this would be welcome!

**Comment by nomare** [comment]
I have this issue at least once per day (

**Comment by johannesjo** [comment]
@nomare could you maybe help debugging this?

**Comment by morningglory17** [comment]
I had this happen again but this time it did give an error in the console:
`zone.js:1063 Unhandled Promise rejection: TypeError: Cannot destructure property 'task' of 'c' as it is undefined. ; Zone: <root> ; Task: Promise.then ; Value: Error: TypeError: Cannot destructure property 'task' of 'c' as it is undefined.
    at n.<anonymous> (global-error-handler.class.ts:60)
    at Generator.next (<anonymous>)
    at p (global-error-handler.util.ts:214)
    at T.invoke (zone.js:372)
    at I.run (zone.js:134)
    at zone.js:1276
    at T.invokeTask (zone.js:406)
    at I.runTask (zone.js:178)
    at L (zone.js:582)
    at m.invokeTask [as invoke] (zone.js:491) Error: TypeError: Cannot destructure property 'task' of 'c' as it is undefined.
    at n.<anonymous> (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:3324614)
    at Generator.next (<anonymous>)
    at p (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:3321956)
    at T.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:6511)
    at I.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:1907)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:16704
    at T.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:7129)
    at I.runTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:2524)
    at L (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:9127)
    at m.invokeTask [as invoke] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.44e5798ddb58b585.js:1:8210)
i.onUnhandledError @ zone.js:1063
`

**Comment by johannesjo** [comment]
Hi there! Would be super great, if someone could check, if this still occurs with the new version. 

I would also be interested to know what the console output looks like with the new changes in place (Ctrl+Shift+i).
