### ISSUE TITLE
When I didnot used my latop for a while, it run out of battery. Then when I recharged, I faced this error " TypeError: Cannot destructure property 'task' of 'c' as it is undefined."

### ISSUE THREAD

**Issue by hieutv85** [johannesjo/super-productivity#1689]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is undefined.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1637845047524: [Idle] Trigger Idle (12) 
1637845051263: [Idle] Set idle time 
1637845107628: [Idle] Trigger Idle (12) 
1637845111250: [Idle] Set idle time 
1637845167754: [Idle] Trigger Idle (12) 
1637845171242: [Idle] Set idle time 
1637845227837: [Idle] Trigger Idle (12) 
1637845231248: [Idle] Set idle time 
1637845287974: [Idle] Trigger Idle (12) 
1637845291251: [Idle] Set idle time 
1637845348077: [Idle] Trigger Idle (12) 
1637845351273: [Idle] Set idle time 
1637845408187: [Idle] Trigger Idle (12) 
1637845411254: [Idle] Set idle time 
1637845468317: [Idle] Trigger Idle (12) 
1637845471261: [Idle] Set idle time 
1637845528433: [Idle] Trigger Idle (12) 
1637845531265: [Idle] Set idle time 
1637845588520: [Idle] Trigger Idle (12) 
1637845591283: [Idle] Set idle time 
1637845598536: [Idle] Trigger Idle (2) 
1637845891282: [Idle] Set idle time (5) 
1637845949100: [Idle] Trigger Idle (10) 
1637845951241: [Idle] Set idle time 
1637846009175: [Idle] Trigger Idle (12) 
1637846011246: [Idle] Set idle time 
1637846044238: [Idle] Trigger Idle (7) 
1637847366226: [Idle] Set idle time 
1637847371846: [Idle] Trigger Idle (3)
```

**Comment by johannesjo** [comment]
Thanks for opening this up. Is this maybe the same as #1684 ?

**Comment by hieutv85** [comment]
Hi @johannesjo , 

I already see #1684. But did you have a solution for this bug ? 
Just copy here your last comment from #1684. Thank you very much for support. 

<img width="661" alt="image" src="https://user-images.githubusercontent.com/34276013/144732561-54c2278f-8f4f-49c0-a8b8-5434e77de4bd.png">

**Comment by johannesjo** [comment]
@hieutv85 no there still is no solution. Would you be willing to help? 

The problem is, that I am unable to reproduce this and code wise the error shouldn't be possible, so help would be very welcome.

My first question would be if this might be accidentally fixed with the most recent changes made.

To build the app you need to:

Follow the steps "Clone repo" and "Install dependencies" here
execute npm run dist:win which will build the exe files. There is also npm run dist:win:appx, but if I remember correctly, this cannot be run without pushing it to the store.
If the issue still persists, I would be interested in the error logs thrown there. If those don't help to track the issue down, I would then try to provide a build with much more logging info.
