### ISSUE TITLE
Error: Task not found: fskSxBU5L

### ISSUE THREAD

**Issue by EngelPika32** [johannesjo/super-productivity#1692]
### Steps to Reproduce

1. I've clicked on "Finish Day" while on the "Today" screen
2. I've selected "round up all tasks to 5 minutes"
3. Crash… 
4.

Tbh. I have no idea what and why just happened :/ 
And I'm stuck on the "celebrate" screen now…
edit.: Okay, after editing every single timestamp (time worked on a task) manually for today, I was able to finish it. – Now I'm very thankful for this automatic rounding feature which takes just a few clicks (if it works) xD

### Error Log (Desktop only)

```
[2021-11-25 TIME] [error] Frontend Error: Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187 Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187
[2021-11-25 TIME] [error] Frontend Error Stack: Es (webpack:///src/app/features/tasks/store/task.reducer.util.ts:11:10)
getTaskById (webpack:///src/app/features/tasks/store/task.reducer.ts:439:25)
filter (webpack:///src/app/features/tasks/store/task.reducer.ts:438:50)
function (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:1341:25)
createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:293:19)
combination (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:248:44)
return (webpack:///src/app/root-store/meta/action-logger.reducer.ts:14:11)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:128:11)
Array.isArray (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:281:19)
[2021-11-25 TIME] [error] Frontend Error: Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187 Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187
[2021-11-25 TIME] [error] Frontend Error Stack: Es (webpack:///src/app/features/tasks/store/task.reducer.util.ts:11:10)
getTaskById (webpack:///src/app/features/tasks/store/task.reducer.ts:439:25)
filter (webpack:///src/app/features/tasks/store/task.reducer.ts:438:50)
function (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:1341:25)
createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:293:19)
combination (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:248:44)
return (webpack:///src/app/root-store/meta/action-logger.reducer.ts:14:11)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:128:11)
Array.isArray (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:281:19)
[2021-11-25 TIME] [error] Frontend Error: Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187 Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187
[2021-11-25 TIME] [error] Frontend Error Stack: Es (webpack:///src/app/features/tasks/store/task.reducer.util.ts:11:10)
getTaskById (webpack:///src/app/features/tasks/store/task.reducer.ts:439:25)
filter (webpack:///src/app/features/tasks/store/task.reducer.ts:438:50)
function (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:1341:25)
createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:293:19)
combination (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:248:44)
return (webpack:///src/app/root-store/meta/action-logger.reducer.ts:14:11)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:128:11)
Array.isArray (webpack:///node_modules/@ngrx/store/fesm2020/ngrx-store.mjs:281:19)
```
(I've tried it three times with different tasks/projects…)

### Stacktrace
```
Error: Task not found: fskSxBU5L
    at Es (file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1331197)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352217
    at Array.filter (<anonymous>)
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:1352196
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3689960
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678784
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3677857
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3524787
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3523321
    at file:///opt/superProductivity/resources/app.asar/dist/main.e545a9b2bb2fd396.js:1:3678187
```

### Meta Info
META: SP7.8.0 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1637874194242: [Task] SetSelectedTask 
1637874194283: [Bookmark] Load Bookmark State 
1637874194283: [Project] Load Project related Data Success 
1637874194284: [Improvement] Clear Hidden Improvements 
1637874194284: [Improvement] Delete multiple Improvements 
1637874194965: [WorkContext] Set Active Work Context 
1637874194970: [Task] SetSelectedTask 
1637874195059: [Bookmark] Load Bookmark State 
1637874195059: [Project] Load Project related Data Success 
1637874195059: [Improvement] Clear Hidden Improvements 
1637874195059: [Improvement] Delete multiple Improvements 
1637874197983: [WorkContext] Set Active Work Context 
1637874198004: [Task] SetSelectedTask 
1637874212570: [WorkContext] Set Active Work Context 
1637874212576: [Task] SetSelectedTask 
1637875345570: [WorkContext] Set Active Work Context 
1637875345606: [Task] SetSelectedTask 
1637875347834: [WorkContext] Set Active Work Context 
1637875347839: [Task] SetSelectedTask 
1637875364463: [Task] Update Task Tags 
1637875364468: [Persistence] Save to DB (2) 
1637875374473: [WorkContext] Set Active Work Context 
1637875374502: [Task] SetSelectedTask 
1637875378328: [Improvement] Add checked day 
1637875378328: [Persistence] Save to DB 
1637875378329: [Improvement] Hide Improvement 
1637875378329: [Persistence] Save to DB 
1637875379767: [WorkContext] Set Active Work Context 
1637875384073: [Task] SetSelectedTask (2) 
1637875389207: [Task] RoundTimeSpentForDay
```

**Comment by johannesjo** [comment]
Hi there! Thanks for reporting!

> Okay, after editing every single timestamp (time worked on a task) manually for today, I was able to finish it.

What and how did you edit them? 

Do you by any chance have backup from before you were able to fix it? This would be super helpful to me in finding out what might have went wrong.

**Comment by EngelPika32** [comment]
> What and how did you edit them?

You can click into the field "spent today" and change the value manually (though, it only accepts valid entries like `25m`). The other two fields can't be edited on that screen.

![image](https://user-images.githubusercontent.com/41995155/143595545-206fe36c-b4dc-4700-84a2-f30b429700e2.png) *("Task" is empty, cuz it's out-of-screen/I didn't include it in the screenshot)*

Looking at the history, it worked. I'm using that sometimes to split up the time worked over multiple (sub-)tasks when I forgot to switch the tracking. But doing that for all tasks of a day is a bit of a hassle.

> Do you by any chance have a backup from before you were able to fix it? This would be super helpful to me in finding out what might have gone wrong.

I have the `super-productivity-crash-user-data-export.json` and the auto-backups

- - - - -
I just took a look at the exported data. The ID `fskSxBU5L` is listed under the following:
```
  "taskArchive": {
  	"ids": [
  		"a bunch of IDs",
  		"including",
  		"fskSxBU5L"
  	],
  	"entities": {
  		"many entries": {
  			"stuff":"stuff"
  		},
  		"fskSxBU5L": {
		    "id": "fskSxBU5L",
		    "projectId": "**P_ID**",
		    "subTaskIds": [],
		    "timeSpentOnDay": {
		      "2021-11-25": **int**
		    },
		    "timeSpent": **int**,
		    "timeEstimate": 0,
		    "isDone": true,
		    "doneOn": **timestamp**,
		    "title": "**MY_TITLE**",
		    "notes": "",
		    "tagIds": [
		      "**T_ID**",
		      "TODAY"
		    ],
		    "parentId": null,
		    "reminderId": null,
		    "created": **timestamp**,
		    "repeatCfgId": null,
		    "plannedAt": null,
		    "_showSubTasksMode": 2, // what does this do?… ; task is without sub-tasks
		    "attachments": [],
		    "issueId": null,
		    "issuePoints": null,
		    "issueType": null,
		    "issueAttachmentNr": null,
		    "issueLastUpdated": null,
		    "issueWasUpdated": null
		  },
  		
  	},
  	"__modelVersion": 3.3337
  }
``` 
From: `super-productivity-crash-user-data-export.json`; with the same entries for this task in the auto-backups `2021-11-25.json` and `2021-11-26.json` (as they appear right now). – I have absolutely no clue what is wrong with that task. It seems fine to me.

**Comment by johannesjo** [comment]
Looks fine to me too. Could you by any chance send a copy of these files to contact@super-productivity.com so I can try to reproduce the error with the data?

**Comment by EngelPika32** [comment]
Don't think so, sorry. 
Can't reproduce by simply importing the files (just tried). I can only guess, that the app has some issues if it runs for too long(?). 
Yesterday, I should have tried to exit the app and then import one of the backups, as it seems to be an issue with the internal state. But I dunno.
Not related, but while trying to reproduce it, I found out that the app freezes when a due task appears while you're selecting a file to import.

**Comment by johannesjo** [comment]
Hm. That's unfortunate. Thanks for checking anyway. Not sure how to proceed tbh. :)

> Not related, but while trying to reproduce it, I found out that the app freezes when a due task appears while you're selecting a file to import.

I try to have look. Could you maybe open up a separate issue for this?
