### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null after hibernation 

### ISSUE THREAD

**Issue by jpalczewski** [johannesjo/super-productivity#1700]
### Steps to Reproduce

1. Start tracing time with   a task 
2. Hibernate PC
3.  Soon after resuming  error appears 

Seems to be rather reproducible - seen I has seen it two times yet.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – pl – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638119757085: [Tag] Update Work End for Tag (3) 
1638119757092: [Persistence] Save to DB (5) 
1638119817070: [Task] Add time spent 
1638119817072: [Project] Update Work End 
1638119817127: [Tag] Update Work End for Tag (3) 
1638119817141: [Persistence] Save to DB (5) 
1638119877124: [Task] Add time spent 
1638119877129: [Project] Update Work End 
1638119877162: [Tag] Update Work End for Tag (3) 
1638119877169: [Persistence] Save to DB (5) 
1638119937060: [Task] Add time spent 
1638119937061: [Project] Update Work End 
1638119937078: [Tag] Update Work End for Tag (3) 
1638119937086: [Persistence] Save to DB (5) 
1638119997072: [Task] Add time spent 
1638119997073: [Project] Update Work End 
1638119997096: [Tag] Update Work End for Tag (3) 
1638119997113: [Persistence] Save to DB (5) 
1638120894657: [Pomodoro] Finish Pomodoro Session 
1638120894887: [Task] UnsetCurrentTask 
1638120895457: [Idle] Trigger Idle 
1638120895496: [Idle] Set idle time 
1638120895607: [Idle] Trigger Idle 
1638120897556: [Idle] Set idle time (2) 
1638120898445: [Pomodoro] Skip Break 
1638120898450: [Task] Toggle start 
1638120898452: [Persistence] Save to DB 
1638120898452: [Task] SetCurrentTask 
1638120898454: [Pomodoro] Start Pomodoro 
1638120898667: [Idle] Set idle time
```

**Comment by johannesjo** [comment]
Thank you very much for opening this up. This issue might be related #1684

**Comment by johannesjo** [comment]
Unfortunately I am unable to reproduce this. I also don't have an idea what might be causing this, since – as long as the dialog component works fine (and there is no reason for it working differently on different systems) – the error should not be possible. Any help in debugging this would be welcome!

**Comment by jpalczewski** [comment]
Things that might be important:

- I'm using a Windows store release. I have recently worked with one project that use UWP version of Godot and things can get weird - maybe electron builder issues?
- I have syncing through gdrive enabled -  errors mentioned in issue happened in home, after resuming from hibernation. Maybe there is some code  not aware of lack of internet connectivity? F.e. a case where there goes a sync request while Wi-Fi isn't connected yet? 

How can I help with debugging? Is there any verbose version that I can build on my own?

**Comment by johannesjo** [comment]
Thank you! That's great to hear. Quite some people seem to have problems with this, but as I said, I am puzzled on how and why this happened. My first question would be if this works with the most recent changes made. To build the app you need to
1. Follow the steps "Clone repo" and "Install dependencies" [here](https://github.com/johannesjo/super-productivity#running-the-development-server)
2. execute `npm run dist:win` which will build the exe files. There is also `npm run dist:win:appx`, but if I remember correctly, this cannot be run without pushing it to the store.

If the issue still persists, I would be interested in the error logs thrown there. If those don't help to track the issue down, I would then try to provide a build with much more logging info.

**Comment by jpalczewski** [comment]
I haven't yet built a master release(but I will do it now), so this issue also appeared on another pc, and no hibernation were involved. This time error happened after ending a pomodoro break:

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
    at b.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956105)
    at T._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955288)
    at T.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at v._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:975388)
    at v.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:955062)
    at O.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:952809)
    at b._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.8.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.1e9942faffaf603d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – pl – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638723772676: [Task] Add time spent 
1638723772677: [Project] Update Work End 
1638723772680: [Tag] Update Work End for Tag 
1638723772684: [Persistence] Save to DB (3) 
1638723773677: [Task] Add time spent 
1638723773678: [Project] Update Work End 
1638723773682: [Tag] Update Work End for Tag 
1638723773684: [Persistence] Save to DB (3) 
1638723774676: [Task] Add time spent 
1638723774677: [Project] Update Work End 
1638723774681: [Tag] Update Work End for Tag 
1638723774685: [Persistence] Save to DB (3) 
1638723775676: [Task] Add time spent 
1638723775679: [Project] Update Work End 
1638723775684: [Tag] Update Work End for Tag 
1638723775688: [Persistence] Save to DB (3) 
1638723776675: [Pomodoro] Finish Pomodoro Session 
1638723776695: [Task] UnsetCurrentTask 
1638724086449: [Idle] Trigger Idle 
1638724086456: [Idle] Set idle time 
1638724086472: [Pomodoro] Finish Pomodoro Session 
1638724086474: [Task] Toggle start 
1638724086476: [Persistence] Save to DB 
1638724086477: [Task] SetCurrentTask 
1638724086478: [Pomodoro] Start Pomodoro 
1638724086529: [Task] Add time spent 
1638724086532: [Project] Update Work End 
1638724086545: [Tag] Update Work End for Tag 
1638724086555: [Persistence] Save to DB (3)
```

_but if I remember correctly, this cannot be run without pushing it to the store._
You can install it locally, but you neeed to sign it with a locally trusted key.  Well designed by MS, but greatly annoying for developers.

**Comment by johannesjo** [comment]
Hi there! Could you maybe check again if it works with the new release and if it works but possibly throws an error in the console?

**Comment by jpalczewski** [comment]
I have been testing since your comment, recorded about 6 pomodoros and had the app opened in the background a lot longer - I haven't spotted this nor #1745  error anymore(ocasionally I was looking in the console few times, but haven't seen anything). Works much better now, thanks!

**Comment by johannesjo** [comment]
Thank you very much for checking. I wouldn't have been able to fix this without your help.

I still don't fully understand what caused this in the first place, but I'm glad that it works now. :)
