### ISSUE TITLE
Inconsistent task projectId

### ISSUE THREAD

**Issue by 1103st-labs** [johannesjo/super-productivity#1701]
### Your Environment

- Version used: 7.8.0 (2021-11-19) AppImage
- Operating System and version: Fedora 34.20210913.1 (Silverblue) x86_64
- Desktop Environment: GNOME 40.4

I am also experiencing a slowdown in the android app, but I do not have a
means to see if it is the same console error.

### Expected Behavior

Lower CPU usage and presumably fewer errors from the console. 
Maybe related to #1678.

### Current Behavior

Shortly after startup the app consumes around 20-25% cpu and the console spams the errs detailed below.

### Steps to Reproduce (for bugs)

1. Run app with ./superProductivity
2. Check console and task manager

### Console Output

Below is my console with the two errors that are spammed.

![Screenshot from 2021-11-28 16-48-38](https://user-images.githubusercontent.com/79700949/143791509-b1842c2c-8003-4ad3-bce2-03cc10c411b4.png)

### Error Log (Desktop only)

The only anomalous data in my log is below.

```
[2021-11-27 23:46:25.290] [error] Frontend Error: Error: Cannot load model. Version to load is newer than local
    at _n (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1333263)
    at zd (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1510343)
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1512207
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:184167
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:173718
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:172885
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:3627402
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:3625782
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:173172
    at o.X [as accumulator] (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:175383) Error: Cannot load model. Version to load is newer than local
    at _n (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1333263)
    at zd (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1510343)
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:1512207
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:184167
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:173718
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:172885
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:3627402
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:3625782
    at file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:173172
    at o.X [as accumulator] (file:///tmp/.mount_ahsY1mtvG/resources/app.asar/dist/main.0726891bcbe9eeb4eb61.js:1:175383)
[2021-11-27 23:46:31.679] [error] Frontend Error Stack: Math.floor (webpack:///src/app/util/model-version.ts:20:12)
isMigrateModel (webpack:///src/app/features/project/migrate-projects-state.util.ts:19:7)
migrateProjectState (webpack:///src/app/features/project/store/project.reducer.ts:82:8)
function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:1358:25)
createFeatureReducerFactory (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:290:19)
combination (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:245:44)
return (webpack:///src/app/root-store/meta/action-logger.reducer.ts:14:11)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:128:11)
Array.isArray (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:278:19)
reduceState (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.js:435:20)
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this. Does this happen on every startup?

It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.
