### ISSUE TITLE
TypeError: Cannot destructure property 'task' of 'c' as it is null.

### ISSUE THREAD

**Issue by DavidSSL** [johannesjo/super-productivity#1703]
- Start the application.
- Start the timer.
- Go into the break.
- Wait for break to finish
- Click on "Get back to work"

At this point the application crashes.

### Stacktrace
```
TypeError: Cannot destructure property 'task' of 'c' as it is null.
    at b._next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:2107790)
    at b.__tryOrUnsub (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956876)
    at b.next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956105)
    at T._next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955288)
    at T.next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955062)
    at v._next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:975388)
    at v.next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:955062)
    at O.next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:952809)
    at b._next (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:1716081)
    at b.__tryOrUnsub (file:///C:/Users/320136294/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.23adabd5347fc20d.js:1:956876)
```

### Meta Info
META: SP7.8.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1638255990593: [Idle] Set idle time (5) 
1638255991470: [Idle] Trigger Idle 
1638255995598: [Idle] Set idle time (5) 
1638255996470: [Idle] Trigger Idle 
1638256000602: [Idle] Set idle time (5) 
1638256001471: [Idle] Trigger Idle 
1638256005606: [Idle] Set idle time (5) 
1638256006472: [Idle] Trigger Idle 
1638256010609: [Idle] Set idle time (5) 
1638256011472: [Idle] Trigger Idle 
1638256015616: [Idle] Set idle time (5) 
1638256016473: [Idle] Trigger Idle 
1638256020621: [Idle] Set idle time (5) 
1638256021473: [Idle] Trigger Idle 
1638256025625: [Idle] Set idle time (5) 
1638256026473: [Idle] Trigger Idle 
1638256030628: [Idle] Set idle time (5) 
1638256031472: [Idle] Trigger Idle 
1638256035636: [Idle] Set idle time (5) 
1638256036474: [Idle] Trigger Idle 
1638256040642: [Idle] Set idle time (5) 
1638256041473: [Idle] Trigger Idle 
1638256045649: [Idle] Set idle time (5) 
1638256046474: [Idle] Trigger Idle 
1638256051653: [Idle] Set idle time (6) 
1638256052261: [Pomodoro] Finish Pomodoro Session 
1638256052261: [Task] Toggle start 
1638256052262: [Persistence] Save to DB 
1638256052262: [Task] SetCurrentTask 
1638256052263: [Pomodoro] Start Pomodoro
```

**Comment by DavidSSL** [comment]
Others have reported this already.
