### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'task') while starting work after a pomodoro break

### ISSUE THREAD

**Issue by jpalczewski** [johannesjo/super-productivity#1745]
### Steps to Reproduce

1.Configure  SP to follow a pomodoro style as in following example:
![obraz](https://user-images.githubusercontent.com/4793526/145106073-5bbbdb64-87b1-426d-96e0-4c0e738cdd99.png)
2. Wait until time runs out
3. Do yourself a tea due a break time(It's worth to mention that it included a lemon balm 👀)
4. Return and try to continue working

### Error Log (Desktop only)

```
[2021-12-05 19:04:01.455] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-05 19:04:01.936] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-05 19:04:05.352] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-05 19:56:29.731] [info]  close, isQuiting: undefined
[2021-12-05 19:56:29.733] [info]  Actions to wait for  [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT', 'SYNC_BEFORE_CLOSE_ID' ]
[2021-12-05 19:56:37.813] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2021-12-05 19:56:42.345] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT []
[2021-12-05 19:56:42.346] [info]  close, isQuiting: undefined
[2021-12-05 19:56:42.378] [info]  close, isQuiting: true
[2021-12-05 19:56:42.410] [info]  Quit after all windows being closed
[2021-12-05 19:57:52.937] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-05 19:57:53.127] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-05 19:57:56.037] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-05 19:58:12.594] [info]  close, isQuiting: undefined
[2021-12-05 19:58:12.597] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2021-12-05 19:58:12.601] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2021-12-05 19:58:13.019] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2021-12-05 19:58:13.020] [info]  close, isQuiting: undefined
[2021-12-05 19:58:13.022] [info]  close, isQuiting: true
[2021-12-05 19:58:13.048] [info]  Quit after all windows being closed
[2021-12-06 01:32:11.916] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-06 01:32:12.119] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-06 01:32:15.061] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-06 01:34:19.440] [info]  close, isQuiting: undefined
[2021-12-06 01:34:19.442] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2021-12-06 01:34:19.446] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2021-12-06 01:34:22.530] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2021-12-06 01:34:22.531] [info]  close, isQuiting: undefined
[2021-12-06 01:34:22.532] [info]  close, isQuiting: true
[2021-12-06 01:34:22.556] [info]  Quit after all windows being closed
[2021-12-06 13:16:39.369] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-06 13:16:39.629] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-06 13:16:42.751] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-06 13:16:49.669] [info]  close, isQuiting: undefined
[2021-12-06 13:16:49.670] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2021-12-06 13:16:49.675] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2021-12-06 13:16:50.093] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2021-12-06 13:16:50.099] [info]  close, isQuiting: undefined
[2021-12-06 13:16:50.101] [info]  close, isQuiting: true
[2021-12-06 13:16:50.137] [info]  Quit after all windows being closed
[2021-12-06 18:43:49.015] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-06 18:43:49.213] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-06 18:43:52.128] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-06 19:53:43.746] [warn]  getSettingsCb no callbacks left
[2021-12-06 20:01:30.445] [info]  close, isQuiting: undefined
[2021-12-06 20:01:30.448] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2021-12-06 20:01:30.451] [info]  BEFORE_CLOSE_DONE FINISH_DAY_BEFORE_CLOSE_EFFECT [ 'SYNC_BEFORE_CLOSE_ID' ]
[2021-12-06 20:01:30.853] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID []
[2021-12-06 20:01:30.854] [info]  close, isQuiting: undefined
[2021-12-06 20:01:30.855] [info]  close, isQuiting: true
[2021-12-06 20:01:30.897] [info]  Quit after all windows being closed
[2021-12-07 20:02:26.722] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2021-12-07 20:02:26.953] [info]  Saving backups to C:\Users\erxyi\AppData\Roaming\superProductivity/backups
[2021-12-07 20:02:29.937] [info]  No custom styles detected at C:\Users\erxyi\AppData\Roaming\superProductivity/styles.css
[2021-12-07 21:51:44.287] [warn]  getSettingsCb no callbacks left
[2021-12-07 21:52:44.385] [error] Frontend Error: TypeError: Cannot read properties of null (reading 'task')
    at y.project (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3666147)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1094835)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at b._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1103285)
    at b.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at $k.notifyNext (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1487532)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1087734)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at M.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1080714)
    at m._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1844452) TypeError: Cannot read properties of null (reading 'task')
    at y.project (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3666147)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1094835)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at b._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1103285)
    at b.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at $k.notifyNext (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1487532)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1087734)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at M.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1080714)
    at m._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1844452)
[2021-12-07 21:52:44.463] [error] Frontend Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'task')
Error: TypeError: Cannot read properties of null (reading 'task')
    at n.<anonymous> (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3447613)
    at Generator.next (<anonymous>)
    at p (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3444685)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6511)
    at Object.onInvoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769407)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6451)
    at I.run (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:1907)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:16704
    at T.invokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:7129)
    at Object.onInvokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769222)
    at G (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:15894)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:14978
    at p (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3444703)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6511)
    at Object.onInvoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769407)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6451)
    at I.run (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:1907)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:16704
    at T.invokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:7129)
    at Object.onInvokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769222) Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'task')
Error: TypeError: Cannot read properties of null (reading 'task')
    at n.<anonymous> (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3447613)
    at Generator.next (<anonymous>)
    at p (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3444685)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6511)
    at Object.onInvoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769407)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6451)
    at I.run (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:1907)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:16704
    at T.invokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:7129)
    at Object.onInvokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769222)
    at G (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:15894)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:14978
    at p (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3444703)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6511)
    at Object.onInvoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769407)
    at T.invoke (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:6451)
    at I.run (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:1907)
    at file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:16704
    at T.invokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.c47476fe287673d2.js:1:7129)
    at Object.onInvokeTask (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3769222)
[2021-12-07 21:52:47.189] [error] Frontend Error Stack: task (webpack:///src/app/features/idle/store/idle.effects.ts:164:12)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/withLatestFrom.js:57:33)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
notifyNext (webpack:///node_modules/rxjs/_esm2015/internal/operators/exhaustMap.js:61:25)
_next (webpack:///node_modules/rxjs/_esm2015/internal/innerSubscribe.js:10:20)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
observers.slice (webpack:///node_modules/rxjs/_esm2015/internal/Subject.js:39:24)
next (webpack:///node_modules/@angular/material/fesm2020/dialog.mjs:423:30)
[2021-12-07 21:52:47.197] [error] Frontend Error Stack: isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:60:12)
p (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25877:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25864:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
p (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25877:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2020/core.mjs:25864:32)
```
### Console Output

Despite a lot of set idle time messages:
![obraz](https://user-images.githubusercontent.com/4793526/145105502-38beea53-7ef7-46b2-aef2-b006e1e61f2b.png)

Rather nothing useful.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'task')
    at y.project (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:3666147)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1094835)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at b._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1103285)
    at b.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at $k.notifyNext (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1487532)
    at y._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1087734)
    at y.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1082967)
    at M.next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1080714)
    at m._next (file:///C:/Users/erxyi/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.f14ef281b68ad5f3.js:1:1844452)
```

### Meta Info
META: SP7.8.0 Electron – pl – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

Self built exe from master commit f9b15bef529bbffafd773fbef04351e4396e9ec8

### Actions Before Error
```
1638909824249: [Tag] Update Work End for Tag (3) 
1638909824257: [Persistence] Save to DB (5) 
1638909884232: [Task] Add time spent 
1638909884233: [Project] Update Work End 
1638909884251: [Tag] Update Work End for Tag (3) 
1638909884256: [Persistence] Save to DB (5) 
1638909944233: [Pomodoro] Finish Pomodoro Session 
1638909944245: [Task] UnsetCurrentTask 
1638910252085: [Idle] Trigger Idle 
1638910252089: [Idle] Set idle time 
1638910252090: [Idle] Open dialog 
1638910258226: [Idle] Set idle time (4) 
1638910304234: [Pomodoro] Finish Pomodoro Session 
1638910304236: [Task] Toggle start 
1638910304237: [Persistence] Save to DB 
1638910304237: [Task] SetCurrentTask 
1638910304239: [Pomodoro] Start Pomodoro 
1638910304254: [Task] Add time spent 
1638910304256: [Project] Update Work End 
1638910304275: [Tag] Update Work End for Tag (3) 
1638910304281: [Persistence] Save to DB (5) 
1638910304284: [Idle] Set idle time 
1638910361613: [Task] Toggle start 
1638910361613: [Persistence] Save to DB 
1638910361613: [Task] UnsetCurrentTask 
1638910361614: [Pomodoro] Pause Pomodoro 
1638910362259: [Task] Toggle start 
1638910362260: [Persistence] Save to DB 
1638910362260: [Task] SetCurrentTask 
1638910362260: [Pomodoro] Start Pomodoro
```
I have sent an email with crash user data, you should be able to find it by #1745 in title.

**Comment by johannesjo** [comment]
Thank you very much for opening this up! I'll have a look.

**Comment by johannesjo** [comment]
I am still not able to reproduce this. The only idea I have, is that angular material messes up the dialog references on windows (and mac?), which possibly also explains #1684
