### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by gacuxz** [johannesjo/super-productivity#1779]
### Steps to Reproduce

1. Break Reminder was disabled.
2. Pomodoro timer with 15 min sessions, 5 min short breaks and 15 min long breaks (every 4-th session) was enabled
3. Finished 12-th session of the project. Pomodoro long break countdown was in process.
4. I pressed the "Close" button and this error appeared.

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Nd._tapNext (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:3703516)
    at Nd._next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1321919)
    at Nd.next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1082266)
    at v._next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1102584)
    at v.next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1082266)
    at m._next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1093643)
    at m.next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1082266)
    at se.next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1080013)
    at _._next (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:3855133)
    at __tryOrUnsub (file:///C:/Users/Admin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.dd51a7b019cad54c.js:1:1084080)
```

### Meta Info
META: SP7.9.1 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.9.1 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1640823485867: [Project] Update Work End 
1640823485910: [Tag] Update Work End for Tag 
1640823485926: [Persistence] Save to DB (3) 
1640823545146: [Task] Add time spent 
1640823545147: [Project] Update Work End 
1640823545153: [Tag] Update Work End for Tag 
1640823545159: [Persistence] Save to DB (3) 
1640823605155: [Task] Add time spent 
1640823605156: [Project] Update Work End 
1640823605163: [Tag] Update Work End for Tag 
1640823605170: [Persistence] Save to DB (3) 
1640823665139: [Task] Add time spent 
1640823665140: [Project] Update Work End 
1640823665145: [Tag] Update Work End for Tag 
1640823665151: [Persistence] Save to DB (3) 
1640823725141: [Task] Add time spent 
1640823725142: [Project] Update Work End 
1640823725149: [Tag] Update Work End for Tag 
1640823725153: [Persistence] Save to DB (3) 
1640823785139: [Task] Add time spent 
1640823785140: [Project] Update Work End 
1640823785145: [Tag] Update Work End for Tag 
1640823785151: [Persistence] Save to DB (3) 
1640823785153: [Pomodoro] Finish Pomodoro Session 
1640823785167: [Task] UnsetCurrentTask 
1640824097053: [Idle] Trigger Idle 
1640824097057: [Idle] Set idle time 
1640824097057: [Idle] Open dialog 
1640824620136: [Idle] Set idle time (251) 
1640824621047: [Idle] Dialog result
```

**Comment by johannesjo** [comment]
Thanks for opening this up! I'll have a look.

**Comment by johannesjo** [comment]
It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog.

**Comment by gacuxz** [comment]
Just sent you an e-mail.

**Comment by johannesjo** [comment]
Thank you very much for sending the data. Still I am unable to reproduce this, I am sorry :( 

Are there any additional logs? Can you reproduce this reliably or is it a one time thing? If this happens again and wait a little longer the logs might be more useful (takes some time till the source maps are loaded).

**Comment by gacuxz** [comment]
Using it on two different machines in sync. No more errors except those till now. Will do as you described if any occurs again. Thank you!

**Comment by johannesjo** [comment]
@gacuxz thank you! That would be great!

I at least have found the part where error is thrown and was able  to prevent it from happening in the future, while the actual cause of the error is still unclear to me and might be related to the angular material dialogs not working correctly.
