### ISSUE TITLE
Error: Cannot load model. Version to load is newer than local

### ISSUE THREAD

**Issue by AlcideBava** [johannesjo/super-productivity#1825]
### Steps to Reproduce
1. I want to use superproductivity on both Linux and Windows
2. So I installed the latest version of the app on windows and tried to use the same json file to sync data (I'm using google drive to sync), however the linux version of the app is way older (6.5.2 I think), so it didn't work
3. Now I can't access my data neither on Windows nor on Linux and the app is blocked on this error message, is there any way to access some local backups or retrieve my data ? 

### Error Log (Desktop only)
```
[2022-01-10 12:27:41.159] [error] Frontend Error Stack: Math.floor (webpack:///src/app/util/model-version.ts:14:12)
isMigrateModel (webpack:///src/app/features/project/migrate-projects-state.util.ts:16:22)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
[2022-01-10 12:27:41.160] [error] Frontend Error Stack: Math.floor (webpack:///src/app/util/model-version.ts:14:12)
isMigrateModel (webpack:///src/app/features/project/migrate-projects-state.util.ts:16:22)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
```

### Stacktrace
```
Math.floor (webpack:///src/app/util/model-version.ts:14:12)
isMigrateModel (webpack:///src/app/features/project/migrate-projects-state.util.ts:16:22)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28535:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28522:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
```

### Meta Info
META: SP6.5.2 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.5.2 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1641741155157: [Pomodoro] Pause Pomodoro 
1641810784950: [SP_ALL] Load(import) all data 
1641810784952: [SP_ALL] All Data was loaded 
1641810784964: [WorkContext] Set Active Work Context 
1641810784981: [Task] SetSelectedTask 
1641810787293: [Persistence] Save to DB 
1641810788377: [Persistence] Save to DB 
1641810788745: [Persistence] Save to DB 
1641810788745: [Persistence] Save to DB 
1641810788746: [Persistence] Save to DB 
1641810788747: [Persistence] Save to DB 
1641810788747: [Persistence] Save to DB 
1641810788747: [Persistence] Save to DB 
1641810788748: [Persistence] Save to DB 
1641810788748: [Persistence] Save to DB 
1641810788748: [Persistence] Save to DB 
1641810788749: [Persistence] Save to DB 
1641810788749: [Persistence] Save to DB 
1641810788749: [Persistence] Save to DB 
1641810788750: [Persistence] Save to DB 
1641810788750: [Persistence] Save to DB 
1641810788750: [Persistence] Save to DB 
1641810788750: [Persistence] Save to DB 
1641810788751: [Persistence] Save to DB 
1641810788751: [Persistence] Save to DB 
1641810788751: [Persistence] Save to DB 
1641810788751: [Persistence] Save to DB 
1641810788752: [Persistence] Save to DB 
1641810788752: [Persistence] Save to DB 
1641810791740: [SP_ALL] Load(import) all data
```

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up. I recommend updating both versions on both systems to the very latest (7.9.2) and then to try again.

**Comment by AlcideBava** [comment]
Hi ! Thanks for your quick answer, I tried doing what you recommended but I got another error :
```
Error: Uncaught (in promise): TypeError: Cannot convert undefined or null to objectTypeError: Cannot convert undefined or null to object    at Function.keys ()    at Qte (file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:960727)    at file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:960970    at Array.forEach ()    at file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:960953    at file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:960985    at n.repairData (file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:967485)    at n. (file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:1206175)    at Generator.next ()    at h (file:///opt/superProductivity/resources/app.asar/dist/main.efc0e93266c38443.js:1:1203607)
```

### Steps to Reproduce
1. I updated both versions to the latest then tried to import my old data (automatic backups from ~/.config/superProductivity/backups)
2. Got the message : ```Legacy data detected while importing, do you want to try to migrate it ?``` Chose "Yes"
3. Then got the message : ```Your data seems to be damaged ("Inconsistent entity state for note"). Do you want to try to automatically fix it? This might result in partial data loss.``` Chose "Yes" again

### Error Log (Desktop only)


### Console Output


### Stacktrace
```
_resetEntityIdsFromObjects (webpack:///src/app/core/data-repair/data-repair.util.ts:229:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:44:16)
_fixEntityStates (webpack:///src/app/core/data-repair/data-repair.util.ts:43:20)
isDataRepairPossible (webpack:///src/app/core/data-repair/data-repair.util.ts:21:29)
constructor (webpack:///src/app/core/data-repair/data-repair.service.ts:16:22)
this._dataRepairService.isRepairPossibleAndConfirmed (webpack:///src/app/imex/sync/data-import.service.ts:117:48)
h (webpack:///src/app/features/reminder/reminder.service.ts:23:)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
recurse (webpack:///src/app/imex/file-imex/privacy-export.ts:56:24)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25450:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25437:32)
```

### Meta Info
META: SP7.9.2 Electron – fr – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.9.2 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1641988514648: [SP_ALL] Load(import) all data (2) 
1641988514650: [SP_ALL] All Data was loaded 
1641988544102: [Layout] Toggle SideBar 
1641988545903: [WorkContext] Set Active Work Context 
1641988545913: [Task] SetSelectedTask 
1641988552938: [Layout] Toggle SideBar 
1641988552944: [Layout] Hide SideBar 
1641988554042: [Layout] Toggle SideBar 
1641988558081: [WorkContext] Set Active Work Context 
1641988558098: [Task] SetSelectedTask 
1641988558163: [Bookmark] Load Bookmark State 
1641988558163: [Project] Load Project related Data Success 
1641988558164: [Improvement] Clear Hidden Improvements 
1641988558165: [Improvement] Delete multiple Improvements 
1641988561134: [WorkContext] Set Active Work Context 
1641988561150: [Task] SetSelectedTask 
1641988577340: [Task] UnsetCurrentTask 
1641988577341: [SimpleCounter] Turn off all simple counters 
1641988580537: [SP_ALL] Load(import) all data 
1641988580539: [SP_ALL] All Data was loaded 
1641988584325: [Layout] ToggleShow Notes 
1641988584326: [Task] SetSelectedTask 
1641988584924: [Layout] ToggleShow Notes 
1641988585872: [Layout] Toggle SideBar 
1641988635942: [WorkContext] Set Active Work Context 
1641988635950: [Task] SetSelectedTask 
1641988667642: [Persistence] Save to DB (14) 
1641988668118: [SP_ALL] Load(import) all data 
1641988668124: [Persistence] Remove from DB 
1641988682476: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

Meanwhile you could also try to import one of the files in the backup folder.
