### ISSUE TITLE
Error: Invalid project data

### ISSUE THREAD

**Issue by Rapha149** [johannesjo/super-productivity#1849]
### Steps to Reproduce

I created a task, then opened SuperProductivity a few days later and tried to delete the task, but the error came up.
![grafik](https://user-images.githubusercontent.com/49787110/150016132-bac6cfdf-46e9-4369-939b-27ec9f17618d.png)

### Stacktrace
```
Error: Invalid project data
    at XAe (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2427076)
    at file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:2425426
    at file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3735155
    at m.Qn [as accumulator] (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3737549)
    at m._tryNext (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3437232)
    at m._next (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3437133)
    at m.next (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3421355)
    at y._next (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3441656)
    at y.next (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3421355)
    at y.observe (file:///snap/superproductivity/1545/resources/app.asar/dist/main.bb3078299280df47.js:1:3414396)
```

### Meta Info
META: SP7.9.2 Electron – de – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.9.2 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1642159920636: [Layout] Hide AddTaskBar 
1642159925022: [Layout] Show AddTaskBar 
1642159929191: [Task][Issue] Add Task 
1642159929220: [Persistence] Save to DB (2) 
1642159929221: [Task] Update Task 
1642159929223: [Task] Move tasks to other project 
1642159929234: [Persistence] Save to DB (2) 
1642159929594: [Layout] Hide AddTaskBar (2) 
1642159930610: [Task] UnsetCurrentTask 
1642159930615: [SimpleCounter] Turn off all simple counters 
1642352192348: [SP_ALL] Load(import) all data 
1642352192353: [SP_ALL] All Data was loaded 
1642352210603: [Task] UnsetCurrentTask 
1642352210606: [SimpleCounter] Turn off all simple counters 
1642358274153: [SP_ALL] Load(import) all data 
1642358274158: [SP_ALL] All Data was loaded 
1642358341860: [Task] SetSelectedTask 
1642358341863: [Layout] Hide Notes 
1642360415314: [Task] UnsetCurrentTask 
1642360415316: [SimpleCounter] Turn off all simple counters 
1642360422219: [SP_ALL] Load(import) all data 
1642360422225: [SP_ALL] All Data was loaded 
1642360441176: [Task] SetSelectedTask 
1642360441178: [Layout] Hide Notes 
1642360443034: [Task] SetSelectedTask 
1642360444262: [Layout] Toggle SideBar 
1642360451578: [Task] UnsetCurrentTask 
1642360451584: [SimpleCounter] Turn off all simple counters 
1642538692594: [SP_ALL] Load(import) all data 
1642538692598: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hi there! Thanks for opening this up! Did you by any chance delete the project of the task?

In any case: It would be great if you could send an export of your data to contact@super-productivity.com so I can check for myself.

**Comment by Rapha149** [comment]
No it still exists. I will send the export later today, right now I can't.

**Comment by Rapha149** [comment]
I just sent the email, just wanted to add something to the issue.
When the error occurs the inspector opens and selects a specific line, maybe that will help to identify the problem. Here's a screenshot:
![grafik](https://user-images.githubusercontent.com/49787110/150206476-dde85288-6656-42d7-bbd6-4cf67955ef39.png)

**Comment by johannesjo** [comment]
I now was able to reproduce and fix this. Thank you very much again for your help!
