### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by srinivasknarayan** [johannesjo/super-productivity#1866]
### Steps to Reproduce

1. Create a repeating task
2. Select start time and reminder window. Specifying a clock string as 9.30 instead of 9:30 seems to trigger this.
3. Select custom schedule with all weekdays selected and save

The error puts the task in an irrecoverable state. Only way out seems to be to delete the task and start over.
Seems like input validation of the fields before allowing submission would fix the problem.

### Stacktrace
```
Error: Invalid clock string
    at lh (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:1421193)
    at W5 (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:1650210)
    at m.project (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:1724560)
    at m._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3461792)
    at m.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3449933)
    at m._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3460816)
    at m.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3449933)
    at m._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3461890)
    at m.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3449933)
    at re._subscribe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3442692)
```

### Meta Info
META: SP7.10.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.10.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1643008103382: [Task] SetSelectedTask 
1643008103386: [Layout] Hide Notes 
1643008133258: [SP_ALL] Load(import) all data 
1643008133259: [SP_ALL] All Data was loaded 
1643008133273: [WorkContext] Set Active Work Context 
1643008133283: [Task] SetSelectedTask 
1643008133430: [Bookmark] Load Bookmark State 
1643008133431: [Project] Load Project related Data Success 
1643008133431: [Improvement] Clear Hidden Improvements 
1643008133432: [Improvement] Delete multiple Improvements 
1643008142250: [Task] SetSelectedTask 
1643008142251: [Layout] Hide Notes 
1643008151286: [Task] SetSelectedTask 
1643008151288: [Layout] Hide Notes 
1643008191528: [SP_ALL] Load(import) all data 
1643008191530: [SP_ALL] All Data was loaded 
1643008195179: [Layout] Toggle SideBar 
1643008196817: [WorkContext] Set Active Work Context 
1643008196831: [Task] SetSelectedTask 
1643008196903: [Bookmark] Load Bookmark State 
1643008196903: [Project] Load Project related Data Success 
1643008196904: [Improvement] Clear Hidden Improvements 
1643008196904: [Improvement] Delete multiple Improvements 
1643008209319: [Task] Update Task Tags 
1643008209326: [Project] Auto Move Task from backlog to today 
1643008209327: [Persistence] Save to DB (3) 
1643008211803: [Task] Update Task Tags 
1643008211808: [Persistence] Save to DB (2) 
1643008216719: [Task] SetSelectedTask 
1643008216720: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Thanks for reporting this. Probably also related to #1867
