### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by srinivasknarayan** [johannesjo/super-productivity#1867]
### Steps to Reproduce

1. Start up the app with no projects or tasks
2. Click Timeline

### Stacktrace
```
Error: Invalid clock string
    at lh (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:1421193)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:2155332
    at Array.forEach (<anonymous>)
    at R0e (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:2155232)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:2174814
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:2174885
    at m.project (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:2176024)
    at m._next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3461792)
    at m.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3449933)
    at v.debouncedNext (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.fbeb548743487b8b.js:1:3460009)
```

### Meta Info
META: SP7.10.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.10.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1643009945749: [SP_ALL] Load(import) all data 
1643009945751: [SP_ALL] All Data was loaded 
1643009958135: [SP_ALL] Load(import) all data 
1643009958136: [SP_ALL] All Data was loaded 
1643009975518: [Project] Delete Project 
1643009975525: [Persistence] Save to DB 
1643009975526: [Persistence] Remove from DB 
1643009975566: [Task] Delete Tasks 
1643009975620: [Persistence] Save to DB (3) 
1643009978221: [Project] Delete Project 
1643009978226: [Persistence] Save to DB 
1643009978226: [Persistence] Remove from DB 
1643009978263: [Task] Delete Tasks 
1643009978323: [Persistence] Save to DB (3) 
1643009980389: [Project] Delete Project 
1643009980394: [Persistence] Save to DB 
1643009980394: [Persistence] Remove from DB 
1643009980432: [Task] Delete Tasks 
1643009980493: [Persistence] Save to DB (3) 
1643009982957: [Project] Delete Project 
1643009982961: [Persistence] Save to DB 
1643009982961: [Persistence] Remove from DB 
1643009982997: [Task] Delete Tasks 
1643009983002: [Persistence] Save to DB (2) 
1643009983002: [TaskRepeatCfg] Update multiple TaskRepeatCfgs 
1643009983077: [Persistence] Save to DB (2) 
1643011889556: [SP_ALL] Load(import) all data 
1643011889557: [SP_ALL] All Data was loaded 
1643011895388: [WorkContext] Set Active Work Context 
1643011895395: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Thanks for opening this up! Unfortunately I am unable to reproduce this. Is this a completely fresh install with no previous instance ever having been installed? If not, it would be great if you could share a copy of your data to contact@super-productivity.com, so I can try to debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).
