### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by bcrpntr** [johannesjo/super-productivity#1875]
### Steps to Reproduce

1. enter invalid time on Repeat task (I accidentally entered 011:00)
2. Task will immediately crash with the error below
3. Reopen and navigate to any page with the task and it will crash

### Stacktrace
```
Error: Invalid clock string
    at lh (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:1421193)
    at W5 (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:1650210)
    at m.project (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:1724560)
    at m._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3461786)
    at m.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3449927)
    at m._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3460810)
    at m.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3449927)
    at m._next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3461884)
    at m.next (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3449927)
    at re._subscribe (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.10.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.5ca48fa3cda9fba9.js:1:3442686)
```

### Meta Info
META: SP7.10.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.10.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1643220291064: [Project] Update Work End 
1643220291068: [Tag] Update Work End for Tag 
1643220291072: [Persistence] Save to DB (3) 
1643220292062: [Task] Add time spent 
1643220292063: [Project] Update Work End 
1643220292066: [Tag] Update Work End for Tag 
1643220292070: [Persistence] Save to DB (3) 
1643220292730: [SP_ALL] Load(import) all data 
1643220292732: [SP_ALL] All Data was loaded 
1643220304433: [Task] SetSelectedTask 
1643220304433: [Layout] Hide Notes 
1643220305263: [Layout] Hide SideBar 
1643220320701: [SP_ALL] Load(import) all data 
1643220320703: [SP_ALL] All Data was loaded 
1643220334066: [Task] SetSelectedTask 
1643220334067: [Layout] Hide Notes 
1643220334909: [Layout] Hide SideBar 
1643220338577: [SP_ALL] Load(import) all data 
1643220338579: [SP_ALL] All Data was loaded 
1643220346272: [Layout] Toggle SideBar 
1643220441087: [Task] Update Task 
1643220441104: [Persistence] Save to DB 
1643220441104: [Task] UnSchedule 
1643220441106: [Persistence] Save to DB (2) 
1643220441106: [Task] Update Task 
1643220441107: [Persistence] Save to DB 
1643220442867: [Task] Update Task 
1643220442868: [Persistence] Save to DB 
1643220446465: [Task] SetSelectedTask 
1643220446466: [Layout] Hide Notes
```

**Comment by bcrpntr** [comment]
I am back up and running, corrected by exporting and editing repeatCfgId to null for the task.
Input validation appears to be needed.

**Comment by johannesjo** [comment]
Thank you very much for reporting! Probably related to #1867 I look into it!

**Comment by bcrpntr** [comment]
Thank you!

**Comment by ximemira** [comment]
I corrected by exporting and editing repeatCfgId to null for the task. And in my case, I also had to change the "startTime" for the task to a valid start-time on the json file.
