### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting '_lastParams')TypeError: Cannot set properties of undefined (setting '_lastParams')    at https://app.super-productivity.com/main.fc2884a953019906.js:1:294052    at Generator.next ()    at https://app.super-productivity.com/main.fc2884a953019906.js:1:293517    at new t (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:17832)    at Wd (https://app.super-productivity.com/main.fc2884a953019906.js:1:293254)    at save (https://app.super-productivity.com/main.fc2884a953019906.js:1:294002)    at n. (https://app.super-productivity.com/main.fc2884a953019906.js:1:295182)    at Generator.next ()    at h (https://app.super-productivity.com/main.fc2884a953019906.js:1:293310)    at T.invoke (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:6575)

### ISSUE THREAD

**Issue by romanborokhqa** [johannesjo/super-productivity#1882]
### Steps to Reproduce

1. timer was enabled for sub task
2.
3.
4.

![image](https://user-images.githubusercontent.com/52780913/151391131-f45349e7-f83a-4119-b1d9-6a1092dd2280.png)
![image](https://user-images.githubusercontent.com/52780913/151391580-df4cdecb-331e-4161-aa3f-fab72c738ff3.png)

### Stacktrace
```
Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting '_lastParams')
TypeError: Cannot set properties of undefined (setting '_lastParams')
    at https://app.super-productivity.com/main.fc2884a953019906.js:1:294052
    at Generator.next (<anonymous>)
    at https://app.super-productivity.com/main.fc2884a953019906.js:1:293517
    at new t (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:17832)
    at Wd (https://app.super-productivity.com/main.fc2884a953019906.js:1:293254)
    at save (https://app.super-productivity.com/main.fc2884a953019906.js:1:294002)
    at n.<anonymous> (https://app.super-productivity.com/main.fc2884a953019906.js:1:295182)
    at Generator.next (<anonymous>)
    at h (https://app.super-productivity.com/main.fc2884a953019906.js:1:293310)
    at T.invoke (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:6575)
    at G (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:15958)
    at https://app.super-productivity.com/polyfills.94238d1595150347.js:1:15042
    at C (https://app.super-productivity.com/main.fc2884a953019906.js:1:565608)
    at T.invoke (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:6575)
    at Object.onInvoke (https://app.super-productivity.com/main.fc2884a953019906.js:1:3718125)
    at T.invoke (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:6515)
    at I.run (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:1971)
    at https://app.super-productivity.com/polyfills.94238d1595150347.js:1:16768
    at T.invokeTask (https://app.super-productivity.com/polyfills.94238d1595150347.js:1:7193)
    at Object.onInvokeTask (https://app.super-productivity.com/main.fc2884a953019906.js:1:3717940)
```

### Meta Info
META: SP7.10.0 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### Actions Before Error
```
1643296850813: [Tag] Update Work End for Tag 
1643296851014: [Persistence] Save to DB (2) 
1643296910789: [Task] Add time spent 
1643296910800: [Tag] Update Work End for Tag 
1643296911186: [Persistence] Save to DB (2) 
1643296970465: [Task] Add time spent 
1643296970470: [Tag] Update Work End for Tag 
1643296970682: [Persistence] Save to DB (2) 
1643297030492: [Task] Add time spent 
1643297030493: [Tag] Update Work End for Tag 
1643297030662: [Persistence] Save to DB (2) 
1643297090433: [Task] Add time spent 
1643297090439: [Tag] Update Work End for Tag 
1643297090633: [Persistence] Save to DB (2) 
1643297150544: [Task] Add time spent 
1643297150548: [Tag] Update Work End for Tag 
1643297150809: [Persistence] Save to DB (2) 
1643297210559: [Task] Add time spent 
1643297210561: [Tag] Update Work End for Tag 
1643297210661: [Persistence] Save to DB (2) 
1643297270992: [Task] Add time spent 
1643297270995: [Tag] Update Work End for Tag 
1643297271225: [Persistence] Save to DB (2) 
1643297330632: [Task] Add time spent 
1643297330635: [Tag] Update Work End for Tag 
1643297330725: [Persistence] Save to DB (2) 
1643297391038: [Task] Add time spent 
1643297391094: [Tag] Update Work End for Tag 
1643297391826: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
Thank you very much for reporting! Can you reproduce this reliably?
