### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by penn5** [johannesjo/super-productivity#1906]
### Steps to Reproduce
1. Create task with daily repeat at "9:0"
2. Save repeat and reload application (reload might not be needed)
3. Edit repeat setting by selecting the "9:0" and hitting backspace until the field is empty
4. This error occurs

### Error Log (Desktop only)
Console output is adequate

### Console Output
Nothing beyond the stacktrace

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Are.toggleFormControl (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1087269)
    at file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1085895
    at Array.forEach (<anonymous>)
    at Are.checkField (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1085879)
    at file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1084044
    at Xj (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1060184)
    at Object.r.options._checkField (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1084018)
    at n.checkExpressionChange (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1070519)
    at ngDoCheck (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:1068783)
    at vh (file:///C:/Users/penn/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.5a4c2b15580c32ae.js:1:3638814)
```

### Meta Info
META: SP7.10.0 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.10.0 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1644176397684: [Task] Update Task 
1644176397686: [Persistence] Save to DB 
1644176397686: [Task] Update Task 
1644176397688: [Persistence] Save to DB 
1644176397689: [Task] Update Task 
1644176397815: [Persistence] Save to DB (2) 
1644176411742: [SP_ALL] Load(import) all data 
1644176411746: [SP_ALL] All Data was loaded 
1644176411767: [WorkContext] Set Active Work Context 
1644176411782: [Task] SetSelectedTask 
1644176411787: [Bookmark] Load Bookmark State 
1644176411788: [Project] Load Project related Data Success 
1644176411789: [Improvement] Clear Hidden Improvements 
1644176411791: [Improvement] Delete multiple Improvements 
1644176416046: [Task] SetSelectedTask 
1644176416047: [Layout] Hide Notes 
1644176461253: [TaskRepeatCfg] Update TaskRepeatCfg 
1644176461262: [Persistence] Save to DB 
1644176464105: [Task] Schedule 
1644176464109: [Persistence] Save to DB (2) 
1644176464110: [Task] Update Task 
1644176464111: [Persistence] Save to DB 
1644176464112: [Task] Update Task Tags 
1644176464113: [Project] Auto Move Task from backlog to today 
1644176464116: [Persistence] Save to DB (3) 
1644176464118: [Task] Update Task 
1644176464121: [Persistence] Save to DB 
1644176464122: [Task] Update Task 
1644176464189: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
This is fixed with 7.10.1.
