### ISSUE TITLE
Error: A reminder for this TASK already exists

### ISSUE THREAD

**Issue by JoseOlin** [johannesjo/super-productivity#1914]
It's happened a couple of times in the last few days. Only happens with some tasks. When I open the app and edit a remainder.

### Steps to Reproduce

1. Open app
2. List of due tasks pop up
3.  Edit remainder of several tasks
4. With one of them this error shows
**Error: A reminder for this TASK already exists**

### Stacktrace
```
Error: A reminder for this TASK already exists
    at n.addReminder (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:2434043)
    at b.project (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:3538076)
    at b._tryNext (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1095092)
    at b._next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1095010)
    at b.next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1082266)
    at Bd._next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1322004)
    at Bd.next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1082266)
    at m._next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1093643)
    at m.next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1082266)
    at se.next (file:///opt/superProductivity/resources/app.asar/dist/main.ae2ed0852742346a.js:1:1080013)
```

### Meta Info
META: SP7.8.1 Electron – es-419 – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.8.1 Chrome/93.0.4577.82 Electron/14.1.1 Safari/537.36

### Actions Before Error
```
1644511860399: [SP_ALL] All Data was loaded 
1644511863600: [Task][Issue] Add Task 
1644511863636: [Persistence] Save to DB (3) 
1644511863637: [TaskRepeatCfg] Update TaskRepeatCfg 
1644511863638: [Persistence] Save to DB 
1644511863640: [Task] Update Task 
1644511863814: [Persistence] Save to DB 
1644511863816: [Task][Issue] Add Task 
1644511863841: [Persistence] Save to DB (2) 
1644511863842: [TaskRepeatCfg] Update TaskRepeatCfg 
1644511863844: [Persistence] Save to DB 
1644511863845: [Task][Issue] Add Task 
1644511863864: [Persistence] Save to DB (3) 
1644511863865: [TaskRepeatCfg] Update TaskRepeatCfg 
1644511863867: [Persistence] Save to DB 
1644511863868: [Task][Issue] Add Task 
1644511863882: [Persistence] Save to DB (3) 
1644511863883: [TaskRepeatCfg] Update TaskRepeatCfg 
1644511863884: [Persistence] Save to DB 
1644511922403: [Task] ReSchedule 
1644511929477: [Persistence] Save to DB (3) 
1644511947590: [Task] ReSchedule 
1644511947600: [Persistence] Save to DB (2) 
1644511959776: [Task] Schedule 
1644511959787: [Persistence] Save to DB 
1644511962047: [Layout] Hide SideBar 
1644512044301: [SP_ALL] Load(import) all data 
1644512044312: [Idle] Reset 
1644512044314: [SP_ALL] All Data was loaded 
1644512091409: [Task] Schedule
```

**Comment by johannesjo** [comment]
Hey there! Thanks for opening this up! Could you maybe provide me with a data export for this error case (to contact@super-productivity.com)?

**Comment by johannesjo** [comment]
Thanks for your help! Not sure what caused this in the first place (possibly just some rare hickup), but I think it makes sense to handle the error more gracefully, which effectively should solve the issue.
