### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by nickcomua** [johannesjo/super-productivity#2131]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:1014179
    at _.project (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:1014201)
    at _next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3478914)
    at _.next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3467043)
    at _next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3467269)
    at _.next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3467043)
    at _next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3479012)
    at _.next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3467043)
    at _next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3478425)
    at _.next (file:///opt/superProductivity/resources/app.asar/dist/main.d08971c1cba715a8.js:1:3467043)
```

### Meta Info
META: SP7.11.5 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.11.5 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36

### Actions Before Error
```
1656435732002: [WorkContext] Set Active Work Context 
1656435732026: [Task] SetSelectedTask 
1656435732191: [Bookmark] Load Bookmark State 
1656435732192: [Project] Load Project related Data Success 
1656435732193: [Improvement] Clear Hidden Improvements 
1656435732194: [Improvement] Delete multiple Improvements 
1656435735077: [Task] Update Task 
1656435735079: [Persistence] Save to DB 
1656435736833: [Task] Update Task 
1656435736835: [Persistence] Save to DB 
1656435742415: [WorkContext] Set Active Work Context 
1656435742432: [Task] SetSelectedTask 
1656435742521: [Bookmark] Load Bookmark State 
1656435742522: [Project] Load Project related Data Success 
1656435742522: [Improvement] Clear Hidden Improvements 
1656435742522: [Improvement] Delete multiple Improvements 
1656435743592: [WorkContext] Set Active Work Context 
1656435743609: [Task] SetSelectedTask 
1656435743628: [Bookmark] Load Bookmark State 
1656435743628: [Project] Load Project related Data Success 
1656435743628: [Improvement] Clear Hidden Improvements 
1656435743628: [Improvement] Delete multiple Improvements 
1656435966202: [Project] Add Project 
1656435966204: [Persistence] Save to DB 
1656435969139: [WorkContext] Set Active Work Context 
1656435969151: [Task] SetSelectedTask 
1656435969184: [Bookmark] Load Bookmark State 
1656435969185: [Project] Load Project related Data Success 
1656435969185: [Improvement] Clear Hidden Improvements 
1656435969185: [Improvement] Delete multiple Improvements
```

**Comment by codingantoine** [comment]
It happened to me with GitHub integration because the token did not have the right access "repo".
