### ISSUE TITLE
Error: Project not found

### ISSUE THREAD

**Issue by CapedBaldy0** [johannesjo/super-productivity#2163]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Uncaught (in promise): Error: Project BfwnjvYxtAFqtMEMpGIlb not foundError: Project BfwnjvYxtAFqtMEMpGIlb not found    at https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:255651    at https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3780869    at hi (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3780305)    at yt (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3781302)    at https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3780926    at hi (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3780305)    at _.project (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3779732)    at _._next (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3476383)    at _.next (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3464512)    at ie._subscribe (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3457267)


Error (webpack:///src/app/features/project/store/project.selectors.ts:39:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:697:29)
memoized (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:578:38)
defaultStateFn (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:604:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:700:35)
memoized (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:578:38)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:478:51)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
value.hasOwnProperty (webpack:///node_modules/zone.js/fesm2015/zone.js:1167:16)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1279:16)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25574:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
drainMicroTaskQueue (webpack:///node_modules/zone.js/fesm2015/zone.js:582:34)
task.zone.runTask (webpack:///node_modules/zone.js/fesm2015/zone.js:491:20)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1600:13)
```

### Meta Info
META: SP7.11.5 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Actions Before Error
```
1658415968710: [Persistence] Save to DB (2) 
1658416028708: [Task] Add time spent 
1658416028708: [Tag] Update Work End for Tag 
1658416028709: [Persistence] Save to DB (2) 
1658416088713: [Task] Add time spent 
1658416088714: [Tag] Update Work End for Tag 
1658416088715: [Persistence] Save to DB (2) 
1658416148709: [Task] Add time spent 
1658416148710: [Tag] Update Work End for Tag 
1658416148711: [Persistence] Save to DB (2) 
1658416208710: [Task] Add time spent 
1658416208711: [Tag] Update Work End for Tag 
1658416208712: [Persistence] Save to DB (2) 
1658416268709: [Task] Add time spent 
1658416268710: [Tag] Update Work End for Tag 
1658416268711: [Persistence] Save to DB (2) 
1658416328709: [Task] Add time spent 
1658416328710: [Tag] Update Work End for Tag 
1658416328710: [Persistence] Save to DB (2) 
1658416388708: [Task] Add time spent 
1658416388708: [Tag] Update Work End for Tag 
1658416388709: [Persistence] Save to DB (2) 
1658416448709: [Task] Add time spent 
1658416448711: [Tag] Update Work End for Tag 
1658416448712: [Persistence] Save to DB (2) 
1658416508708: [Task] Add time spent 
1658416508708: [Tag] Update Work End for Tag 
1658416508709: [Persistence] Save to DB (2) 
1658416594735: [SP_ALL] Load(import) all data 
1658416594736: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by CapedBaldy0** [comment]
[ANONYMIZED-super-productivity-crash-user-data-export.txt](https://github.com/johannesjo/super-productivity/files/9300638/ANONYMIZED-super-productivity-crash-user-data-export.txt)

**Comment by johannesjo** [comment]
Thanks for the data export! Unfortunately I am unable to reproduce this. What did you do before the error occurred?
