### ISSUE TITLE
Error: Uncaught (in promise): Error: TypeError: Cannot set properties of undefined (setting '_lastParams')Error: TypeError: Cannot set properties of undefined (setting '_lastParams')    at n. (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:2260570)    at Generator.next ()    at h (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:2257611)    at T.invoke (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:6575)    at Object.onInvoke (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3733601)    at T.invoke (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:6515)    at I.run (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:1971)    at https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:16770    at T.invokeTask (https://app.super-productivity.com/polyfills.863cca7d8b9d1abd.js:1:7193)    at Object.onInvokeTask (https://app.super-productivity.com/main.d4cb8d7da2417afc.js:1:3733416)

### ISSUE THREAD

**Issue by akang22** [johannesjo/super-productivity#2169]
### Steps to Reproduce
1. Navigate to task page
2. Track time for a task
3. I believe I let the task run for at least 24 hours. I may have been low on RAM at some point so there could also be issues there.

Sorry I can't be more detailed on this. I was not making use of any special functions. 
When reloading, it shows 
'There is only very little disk space available (-17592185975169mb). This might affect how the app is running.'
It is otherwise normal when booting up.

### Error Log (Desktop only)
could not find, sorry. checked both library/logs and .config (I'm on mac) and wasn't in either. I also tried to find using fzf and didn't find any main.log. There were some LOG, LOG.old files in some obscure chrome profile directory that weren't useful.

Here's anonymized json export:
`{"bookmark":{},"globalConfig":{"lang":{"lng":null},"misc":{"isDarkMode":true,"isConfirmBeforeExit":false,"isConfirmBeforeExitWithoutFinishDay":true,"isNotifyWhenTimeEstimateExceeded":true,"isAutMarkParentAsDone":false,"isAutoStartNextTask":true,"isTurnOffMarkdown":false,"isAutoAddWorkedOnToToday":true,"isMinimizeToTray":false,"isTrayShowCurrentTask":true,"defaultProjectId":null,"firstDayOfWeek":1,"isDisableAnimations":false,"taskNotesTpl":"**How can I best achieve it now?**\n\n**What do I want?**\n\n**Why do I want it?**\n"},"evaluation":{"isHideEvaluationSheet":false},"idle":{"isOnlyOpenIdleWhenCurrentTask":false,"isEnableIdleTimeTracking":true,"minIdleTime":300000,"isUnTrackedIdleResetsBreakTimer":true},"takeABreak":{"isTakeABreakEnabled":true,"isLockScreen":false,"isFocusWindow":false,"takeABreakMessage":"You have been working for ${duration} without one. Go away from the computer! Take a short walk! Makes you more productive in the long run!","takeABreakMinWorkingTime":3600000,"takeABreakSnoozeTime":900000,"motivationalImg":null},"pomodoro":{"isEnabled":false,"duration":1500000,"breakDuration":300000,"longerBreakDuration":900000,"cyclesBeforeLongerBreak":4,"isStopTrackingOnBreak":true,"isStopTrackingOnLongBreak":true,"isManualContinue":false,"isPlaySound":true,"isPlaySoundAfterBreak":false,"isPlayTick":false},"keyboard":{"globalShowHide":"Ctrl+Shift+X","globalToggleTaskStart":null,"globalAddNote":null,"globalAddTask":null,"addNewTask":"Shift+A","addNewNote":"n","openProjectNotes":"Shift+N","toggleSideNav":"Shift+D","showHelp":"?","showSearchBar":"Shift+F","toggleBookmarks":"Shift+V","toggleBacklog":"b","goToWorkView":"w","goToScheduledView":"Shift+S","goToTimeline":"Shift+T","goToSettings":null,"zoomIn":"Ctrl++","zoomOut":"Ctrl+-","zoomDefault":"Ctrl+0","taskEditTitle":null,"taskToggleAdditionalInfoOpen":"i","taskOpenEstimationDialog":"t","taskSchedule":"s","taskToggleDone":"d","taskAddSubTask":"a","taskDelete":"Backspace","taskMoveToProject":"e","taskOpenContextMenu":"q","selectPreviousTask":"k","selectNextTask":"j","moveTaskUp":"Ctrl+Shift+ArrowUp","moveTaskDown":"Ctrl+Shift+ArrowDown","moveToBacklog":"Shift+B","moveToTodaysTasks":"Shift+T","expandSubTasks":null,"collapseSubTasks":null,"togglePlay":"y","taskEditTags":"g"},"localBackup":{"isEnabled":true},"sound":{"volume":75,"isPlayDoneSound":true,"isIncreaseDoneSoundPitch":true,"doneSound":"done2.mp3"},"trackingReminder":{"isEnabled":true,"isShowOnMobile":false,"minTime":120000},"timeline":{"isWorkStartEndEnabled":true,"workStart":"9:00","workEnd":"17:00","calendarProviders":[]},"sync":{"isEnabled":true,"isCompressionEnabled":false,"syncProvider":"GoogleDrive","syncInterval":60000,"dropboxSync":{"accessToken":null,"refreshToken":null},"googleDriveSync":{"isCompressData":true,"syncFileName":"SUPER_PRODUCTIVITY_SYNC.json","_syncFileNameForBackupDocId":null,"_backupDocId":null},"webDav":{"baseUrl":null,"userName":null,"password":null,"syncFilePath":null},"localFileSync":{"syncFilePath":null}},"__modelVersion":2.2009},"reminders":[],"project":{"ids":["DEFAULT"],"entities":{"DEFAULT":{"id":"DEFAULT","title":"title__125","isHiddenFromMenu":false,"isArchived":false,"issueIntegrationCfgs":{"JIRA":{"isEnabled":false,"_isBlockAccess":false,"host":null,"userName":null,"password":null,"isWonkyCookieMode":false,"usePAT":false,"isAutoPollTickets":true,"searchJqlQuery":"","isAutoAddToBacklog":true,"autoAddBacklogJqlQuery":"assignee = currentUser() AND sprint in openSprints() AND resolution = Unresolved","isWorklogEnabled":true,"isAddWorklogOnSubTaskDone":true,"worklogDialogDefaultTime":"AllTime","isAllowSelfSignedCertificate":false,"isUpdateIssueFromLocal":false,"isShowComponents":true,"isCheckToReAssignTicketOnTaskStart":false,"storyPointFieldId":null,"isTransitionIssuesEnabled":true,"availableTransitions":[],"transitionConfig":{"OPEN":"DO_NOT","IN_PROGRESS":"ALWAYS_ASK","DONE":"ALWAYS_ASK"},"userToAssignOnDone":null},"GITHUB":{"isEnabled":false,"repo":null,"token":null,"isSearchIssuesFromGithub":false,"isAutoPoll":false,"isAutoAddToBacklog":false,"filterUsername":null},"GITLAB":{"isEnabled":false,"project":null,"gitlabBaseUrl":null,"token":null,"isSearchIssuesFromGitlab":false,"isAutoPoll":false,"isAutoAddToBacklog":false,"filterUsername":null,"scope":"created-by-me","source":"project"},"CALDAV":{"isEnabled":false,"caldavUrl":null,"resourceName":null,"username":null,"password":null,"isAutoAddToBacklog":false,"isAutoPoll":false,"isSearchIssuesFromCaldav":false,"isTransitionIssuesEnabled":false,"categoryFilter":null},"OPEN_PROJECT":{"isEnabled":false,"host":null,"projectId":null,"token":null,"isSearchIssuesFromOpenProject":false,"isAutoPoll":false,"isAutoAddToBacklog":false,"isShowTimeTrackingDialog":false,"isShowTimeTrackingDialogForEachSubTask":false,"timeTrackingDialogDefaultTime":"AllTime","filterUsername":null,"scope":"created-by-me"}},"taskIds":[],"backlogTaskIds":[],"noteIds":[],"advancedCfg":{"worklogExportSettings":{"cols":["DATE","START","END","TIME_CLOCK","TITLES_INCLUDING_SUB"],"roundWorkTimeTo":null,"roundStartTimeTo":null,"roundEndTimeTo":null,"separateTasksBy":" | ","groupBy":"DATE"}},"theme":{"isAutoContrast":true,"isDisableBackgroundGradient":false,"primary":"#29a1aa","huePrimary":"500","accent":"#ff4081","hueAccent":"500","warn":"#e11826","hueWarn":"500","backgroundImageDark":null,"backgroundImageLight":null},"workStart":{},"workEnd":{},"breakTime":{},"breakNr":{}}},"__modelVersion":6.02},"tag":{"ids":["TODAY"],"entities":{"TODAY":{"id":"TODAY","icon":"wb_sunny","title":"title__232","color":null,"created":1656470976571,"taskIds":["EjMDRwnYVgf3aizjbI3hi","L08I2BmalBibujDCtteaF","e8VN2DOEQgFY_6hqM2QR4","ZdgPRH3oUeJNpc4iPUllU","pbbTu51ouqC4EBr8w1Lvb","UIKxSUywE50pzW2Ct_lMY","VInClNMS7g7hLPzJRoQB1","hTQ5Y9Y08NbVo55XrOmyK","AbZGHuh4LSXXhP6IBU_zF"],"advancedCfg":{"worklogExportSettings":{"cols":["DATE","START","END","TIME_CLOCK","TITLES_INCLUDING_SUB"],"roundWorkTimeTo":null,"roundStartTimeTo":null,"roundEndTimeTo":null,"separateTasksBy":" | ","groupBy":"DATE"}},"theme":{"isAutoContrast":true,"isDisableBackgroundGradient":false,"primary":"#6495ED","huePrimary":"500","accent":"#ff4081","hueAccent":"500","warn":"#e11826","hueWarn":"500","backgroundImageDark":"assets/bg/NIGHT_manuel-will.jpg","backgroundImageLight":null},"workStart":{"2022-06-28":1656470987679,"2022-07-23":1658593651988,"2022-07-24":1658646094401},"workEnd":{"2022-06-28":1656471862705,"2022-07-23":1658637608698,"2022-07-24":1658714231120},"breakTime":{"2022-07-23":600000},"breakNr":{"2022-07-23":2}}},"__modelVersion":1},"simpleCounter":{"ids":["STANDING_DESK_ID","COFFEE COUNTER"],"entities":{"STANDING_DESK_ID":{"id":"STANDING_DESK_ID","title":"title__273","isEnabled":false,"icon":"airline_seat_recline_normal","iconOn":"directions_walk","type":"StopWatch","triggerOnActions":[],"triggerOffActions":[],"countOnDay":{},"isOn":false},"COFFEE COUNTER":{"id":"COFFEE COUNTER","title":"title__284","isEnabled":false,"icon":"free_breakfast","type":"ClickCounter","triggerOnActions":[],"triggerOffActions":[],"countOnDay":{},"isOn":false}},"__modelVersion":2},"note":{"ids":[],"entities":{},"todayOrder":[],"__modelVersion":1},"metric":{"ids":[],"entities":{},"__modelVersion":1},"improvement":{"ids":[],"entities":{},"hideDay":null,"hiddenImprovementBannerItems":[]},"obstruction":{"ids":[],"entities":{}},"task":{"ids":["AbZGHuh4LSXXhP6IBU_zF","hTQ5Y9Y08NbVo55XrOmyK","VInClNMS7g7hLPzJRoQB1","UIKxSUywE50pzW2Ct_lMY","pbbTu51ouqC4EBr8w1Lvb","ZdgPRH3oUeJNpc4iPUllU","e8VN2DOEQgFY_6hqM2QR4","L08I2BmalBibujDCtteaF","EjMDRwnYVgf3aizjbI3hi"],"entities":{"AbZGHuh4LSXXhP6IBU_zF":{"id":"AbZGHuh4LSXXhP6IBU_zF","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-06-28":876029},"timeSpent":876029,"timeEstimate":0,"isDone":true,"doneOn":1658550266532,"title":"title__323","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1656470979623,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"hTQ5Y9Y08NbVo55XrOmyK":{"id":"hTQ5Y9Y08NbVo55XrOmyK","projectId":null,"subTaskIds":[],"timeSpentOnDay":{},"timeSpent":0,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__348","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550260809,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"VInClNMS7g7hLPzJRoQB1":{"id":"VInClNMS7g7hLPzJRoQB1","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-24":6506126},"timeSpent":6506126,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__374","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550270845,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"UIKxSUywE50pzW2Ct_lMY":{"id":"UIKxSUywE50pzW2Ct_lMY","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-23":4200000,"2022-07-24":3002},"timeSpent":4203002,"timeEstimate":0,"isDone":true,"doneOn":1658707725629,"title":"title__401","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550277198,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"pbbTu51ouqC4EBr8w1Lvb":{"id":"pbbTu51ouqC4EBr8w1Lvb","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-24":6001},"timeSpent":6001,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__427","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550325048,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"ZdgPRH3oUeJNpc4iPUllU":{"id":"ZdgPRH3oUeJNpc4iPUllU","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-24":999},"timeSpent":999,"timeEstimate":0,"isDone":true,"doneOn":1658707716306,"title":"title__453","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550341465,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"e8VN2DOEQgFY_6hqM2QR4":{"id":"e8VN2DOEQgFY_6hqM2QR4","projectId":null,"subTaskIds":[],"timeSpentOnDay":{},"timeSpent":0,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__478","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658550344235,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"L08I2BmalBibujDCtteaF":{"id":"L08I2BmalBibujDCtteaF","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-23":6911876},"timeSpent":6911876,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__504","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658593649325,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null},"EjMDRwnYVgf3aizjbI3hi":{"id":"EjMDRwnYVgf3aizjbI3hi","projectId":null,"subTaskIds":[],"timeSpentOnDay":{"2022-07-23":18245467,"2022-07-24":70106309},"timeSpent":88351776,"timeEstimate":0,"isDone":false,"doneOn":null,"title":"title__531","notes":"","tagIds":["TODAY"],"parentId":null,"reminderId":null,"created":1658600826158,"repeatCfgId":null,"plannedAt":null,"_showSubTasksMode":2,"attachments":[],"issueId":null,"issuePoints":null,"issueType":null,"issueAttachmentNr":null,"issueLastUpdated":null,"issueWasUpdated":null}},"currentTaskId":null,"selectedTaskId":null,"taskAdditionalInfoTargetPanel":"Default","lastCurrentTaskId":"EjMDRwnYVgf3aizjbI3hi","isDataLoaded":true,"__modelVersion":3.3337},"taskArchive":{"ids":[],"entities":{},"__modelVersion":3.3337},"taskRepeatCfg":{"ids":[],"entities":{},"__modelVersion":1.43},"lastLocalSyncModelChange":1658714231165}`

### Console Output
...
[Persistence] Save to DB 
Uncaught (in promise) DOMException: Unexpected internal error.
[Task] Add time spent
...
I think the console logs after the uncaught exception are after I opened console, not sure (because the objects are expanded without needing to click on them).

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:60:12)
h (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25587:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25574:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1213:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1120:16)
h (webpack:///src/app/core/error-handler/global-error-handler.util.ts:227:37)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25587:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1276:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:25574:32)
```

### Meta Info
META: SP7.11.5 Browser – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

### Actions Before Error
```
1658714221328: [Tag] Update Work End for Tag 
1658714221329: [Persistence] Save to DB (2) 
1658714223373: [Task] Add time spent 
1658714223375: [Tag] Update Work End for Tag 
1658714223376: [Persistence] Save to DB (2) 
1658714225405: [Task] Add time spent 
1658714225406: [Tag] Update Work End for Tag 
1658714225407: [Persistence] Save to DB (2) 
1658714227427: [Task] Add time spent 
1658714227428: [Tag] Update Work End for Tag 
1658714227429: [Persistence] Save to DB (2) 
1658714228174: [Task] Add time spent 
1658714228175: [Tag] Update Work End for Tag 
1658714228176: [Persistence] Save to DB (2) 
1658714229302: [Task] Add time spent 
1658714229303: [Tag] Update Work End for Tag 
1658714229305: [Persistence] Save to DB (2) 
1658714230201: [Task] Add time spent 
1658714230202: [Tag] Update Work End for Tag 
1658714230203: [Persistence] Save to DB (2) 
1658714231119: [Task] Add time spent 
1658714231121: [Tag] Update Work End for Tag 
1658714231122: [Persistence] Save to DB (2) 
1658714293945: [Task] Add time spent 
1658714293946: [Tag] Update Work End for Tag 
1658714293946: [Persistence] Save to DB (2) 
1658714351214: [Task] Add time spent 
1658714351219: [Tag] Update Work End for Tag 
1658714351221: [Persistence] Save to DB (2)
```

**Comment by akang22** [comment]
Possible duplicate of #2164
