### ISSUE TITLE
Error: Project SvlPWnhIPhB4dT_gbl00M not found

### ISSUE THREAD

**Issue by KVZoltan** [johannesjo/super-productivity#2416]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: Project SvlPWnhIPhB4dT_gbl00M not found
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:313585
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020769
    at Function.Ur [as projector] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020289)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:315675
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020769
    at Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020289)
    at _n (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4021137)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020826
    at Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4020289)
    at m.project (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_7.12.0.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.afd0cc8c5ae84e6b.js:1:4019632)
```

### Meta Info
META: SP7.12.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.12.0 Chrome/100.0.4896.160 Electron/18.3.9 Safari/537.36

### Actions Before Error
```
1673735106896: [Persistence] Save to DB 
1673735106902: [Task] Update Task 
1673735106904: [Persistence] Save to DB 
1673735115791: [Task] Schedule 
1673735115795: [Persistence] Save to DB (2) 
1673735115795: [Task] Update Task 
1673735115797: [Persistence] Save to DB 
1673735133257: [TaskRepeatCfg][Task] Add TaskRepeatCfg to Task 
1673735133259: [Persistence] Save to DB (2) 
1673735145359: [Task] SetSelectedTask 
1673735145361: [Layout] Hide Notes 
1673735668176: [Idle] Trigger Idle 
1673735668178: [Idle] Set idle time 
1673735668179: [Idle] Open dialog 
1673773918004: [Idle] Set idle time (29432) 
1673773918201: [Global Config] Update Global Config Section 
1673773918210: [Persistence] Save to DB 
1673773926085: [Idle] Set idle time (8) 
1673773926174: [Idle] Dialog result 
1673773926174: [Idle] Reset 
1673773954297: [Persistence] Save to DB 
1673774084251: [Idle] Trigger Idle 
1673774084253: [Idle] Set idle time 
1673774084253: [Idle] Open dialog 
1673794679083: [Idle] Set idle time (409) 
1673794680021: [Global Config] Update Global Config Section 
1673794680035: [Persistence] Save to DB 
1673794737710: [Idle] Set idle time (49) 
1673794737717: [Persistence] Save to DB (13) 
1673794737763: [SP_ALL] Load(import) all data
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by KVZoltan** [comment]
Hey Johannes!

 

There is no ’Setting’ anywhere in the menu.

 

Med vänliga hälsningar,

 

Zoltan
