### ISSUE TITLE
IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64).

### ISSUE THREAD

**Issue by OckhamOdyssey** [johannesjo/super-productivity#2422]
### Steps to Reproduce

1. Open Super Productivity TODAY section.
2. Mark a task as done without time registered today.
3. Right click to another task. I only did this today. It exploded immediately.

### Console Output

```
GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64).
    at n._insertAtCursorChromium (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1857853)
    at n._insertAtCursor (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1857057)
    at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1856409)
    at HTMLDivElement.We (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:11535)
    at v.invokeTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:7195)
    at Object.onInvokeTask (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:3964349)
    at v.invokeTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:7116)
    at M.runTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:2590)
    at m.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:8246)
    at Z (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:20861)
```
```
zone.js:1061 Unhandled Promise rejection: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64). ; Zone: <root> ; Task: Promise.then ; Value: Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64).
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at h (global-error-handler.util.ts:227:38)
    at v.invoke (zone.js:372:26)
    at M.run (zone.js:134:43)
    at zone.js:1275:36
    at v.invokeTask (zone.js:406:31)
    at M.runTask (zone.js:178:47)
    at _ (zone.js:585:35)
    at m.invokeTask [as invoke] (zone.js:491:21) Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64).
    at n.<anonymous> (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:2455461)
    at Generator.next (<anonymous>)
    at h (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:2452502)
    at v.invoke (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:6577)
    at M.run (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:1973)
    at https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:16811
    at v.invokeTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:7195)
    at M.runTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:2590)
    at _ (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:9210)
    at m.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:8276)
```
### Stacktrace
```
Error: Failed to execute 'setStart' on 'Range': The offset 118 is larger than the node's length (64).
    at n._insertAtCursorChromium (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1857853)
    at n._insertAtCursor (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1857057)
    at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:1856409)
    at HTMLDivElement.We (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:11535)
    at v.invokeTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:7195)
    at Object.onInvokeTask (https://app.super-productivity.com/main.05ec82a44189ec80.js:1:3964349)
    at v.invokeTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:7116)
    at M.runTask (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:2590)
    at m.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:8246)
    at Z (https://app.super-productivity.com/polyfills.71887e22dbf899f2.js:1:20861)
```

### Meta Info
META: SP7.12.1 Browser – es-ES – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

### Actions Before Error
```
1674219402011: [Persistence] Save to DB (4) 
1674219462012: [Task] Add time spent 
1674219462013: [Project] Update Work End 
1674219462015: [Tag] Update Work End for Tag (2) 
1674219462016: [Persistence] Save to DB (4) 
1674219498204: [Task] Add time spent 
1674219498205: [Project] Update Work End 
1674219498205: [Tag] Update Work End for Tag (2) 
1674219498206: [Persistence] Save to DB (4) 
1674219498950: [Task] Add time spent 
1674219498950: [Project] Update Work End 
1674219498951: [Tag] Update Work End for Tag (2) 
1674219498951: [Persistence] Save to DB (4) 
1674219499950: [Task] Add time spent 
1674219499951: [Project] Update Work End 
1674219499952: [Tag] Update Work End for Tag (2) 
1674219499952: [Persistence] Save to DB (4) 
1674219500534: [Task] UnsetCurrentTask 
1674219502323: [Task] Update Task 
1674219502325: [Persistence] Save to DB 
1674219752136: [SP_ALL] Load(import) all data 
1674219752138: [Idle] Reset 
1674219752139: [SP_ALL] All Data was loaded 
1674301125639: [SP_ALL] Load(import) all data 
1674301125642: [Idle] Reset 
1674301125642: [SP_ALL] All Data was loaded 
1674301126713: [Global Config] Update Global Config Section 
1674301126714: [Persistence] Save to DB 
1674301194158: [Task] Update Task 
1674301194161: [Persistence] Save to DB
```

**Comment by OckhamOdyssey** [comment]
I must say the task name I right-clicked originally was `AF_EJER_15 - Recolección Ram Linux (fallo con la compilación de LiME)`. After created this issue, it changes.
![image](https://user-images.githubusercontent.com/60941836/213865510-5c220f80-089a-418b-abb7-0e7350af428b.png)
