### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by noname77** [johannesjo/super-productivity#2464]
### Steps to Reproduce
1.  create a sub task
2. drag it outside of a task (as if one wanted to convert it to a parent task)
3. error popped out

### Error Log (Desktop only)
```
this._dragulaService.dropModel(this.listId).subscribe( (webpack:///src/app/features/tasks/task-list/task-list.component.ts:120:68)this._dragulaService.dropModel(this.listId).subscribe( (webpack:///src/app/features/tasks/task-list/task-list.component.ts:120:43)__tryOrUnsub (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:183:15)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:122:21)_next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:72:25)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)this.project.call (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:35:25)next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)this.destination.error (webpack:///node_modules/rxjs/_esm2015/internal/operators/filter.js:33:29)
```

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:1608384
    at Array.map (<anonymous>)
    at p._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:1608375)
    at p.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3696495)
    at p.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3695724)
    at M._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3694907)
    at M.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3694681)
    at m._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3706650)
    at m.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3694681)
    at m._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.0bd934a91d830ad2.js:1:3706063)
```

### Meta Info
META: SP7.12.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.12.0 Chrome/100.0.4896.160 Electron/18.3.9 Safari/537.36

### Actions Before Error
```
1676381304945: [Persistence] Save to DB 
1676381309363: [WorkContextMeta] Move Task in Today 
1676381309364: [Persistence] Save to DB 
1676381317586: [WorkContextMeta] Move Task in Today 
1676381317587: [Persistence] Save to DB 
1676381333797: [Task] Update Task 
1676381333798: [Persistence] Save to DB 
1676381333798: [Task] Update Task 
1676381333798: [Task] Update Task Tags 
1676381333799: [Persistence] Save to DB (3) 
1676381341996: [Task] Add SubTask 
1676381341998: [Persistence] Save to DB 
1676381344392: [Task] Move sub task 
1676381344393: [Persistence] Save to DB 
1676381350334: [Task] Delete Task 
1676381350335: [Persistence] Save to DB (2) 
1676381350336: [Task] UnsetCurrentTask 
1676381350336: [Pomodoro] Pause Pomodoro 
1676381355531: [Task] Move sub task 
1676381355532: [Persistence] Save to DB 
1676381360638: [Task] Delete Task 
1676381360640: [Persistence] Save to DB (3) 
1676381360640: [Task] UnsetCurrentTask 
1676381360641: [Pomodoro] Pause Pomodoro 
1676381371008: [Task] Update Task 
1676381371008: [Persistence] Save to DB 
1676381371009: [Task] Update Task 
1676381371009: [Task] Update Task Tags 
1676381371010: [Persistence] Save to DB (3)
```

**Comment by johannesjo** [comment]
Thanks for reporting. I am unable to reproduce this. Can you reproduce this reliably?

**Comment by noname77** [comment]
nope, just happened once. got a pop up to report, so reported :)

thanks for the great work!
