### ISSUE TITLE
[Android] Java exception was raised during method invocation

### ISSUE THREAD

**Issue by fraschm1998** [johannesjo/super-productivity#2481]
### Your Environment

- Version used: latest installed using ng
- Operating System and version:
- Desktop Environment: Gentoo Linux
- Browser Name and version: Brave and Latest

### Expected Behavior

For it to sync as it does with the Desktop Client

### Current Behavior

Gives me an Unknown Sync Error

### Steps to Reproduce (for bugs)

1. Enable WebDev on Android App and try to connect

### Console Output

```
web-dav-sync.service.ts:54 Error: Java exception was raised during method invocation
    at androidInterface.makeHttpRequestWrapped (android-interface.ts:223:24)
    at WebDavApiService.<anonymous> (web-dav-api.service.ts:108:29)
    at Generator.next (<anonymous>)
    at fulfilled (sync.module.ts:32:24)
    at _ZoneDelegate.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at _ZoneDelegate.invoke (zone.js:371:52)
    at Zone.run (zone.js:134:43)
    at zone.js:1275:36
    at _ZoneDelegate.invokeTask (zone.js:406:31)
```

**Comment by fraschm1998** [comment]
```
  | (anonymous) | @ | web-dav-sync.service.ts:54
-- | -- | -- | --
  | rejected | @ | web-dav-api.service.ts:32
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:68
  | fulfilled | @ | database.service.ts:14
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:68
  | fulfilled | @ | database.service.ts:14
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:68
  | fulfilled | @ | database.service.ts:14
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:68
  | fulfilled | @ | database.service.ts:14
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:68
  | fulfilled | @ | database.service.ts:14
  | IndexedDB (async) |   |  
  | (anonymous) | @ | indexed-db-adapter.service.ts:33
  | (anonymous) | @ | database.service.ts:14
  | __awaiter | @ | database.service.ts:14
  | init | @ | indexed-db-adapter.service.ts:31
  | (anonymous) | @ | database.service.ts:73
  | (anonymous) | @ | cross-model-migrations.ts:196
  | __awaiter | @ | cross-model-migrations.ts:196
  | _init | @ | database.service.ts:71
  | DatabaseService | @ | database.service.ts:28
  | DatabaseService_Factory | @ | ɵfac.js? [sm]:1
  | PersistenceService_Factory | @ | ɵfac.js? [sm]:1
  | GlobalConfigEffects_Factory | @ | ɵfac.js? [sm]:1
  | Promise.then (async) |   |  
  | 22964 | @ | issue.service.ts:40
  | 92201 | @ | caldav-client.service.ts:28
  | 14509 | @ | issue.module.ts:32
  | 47020 | @ | dialog-jira-initial-…tup.component.ts:12
  | 39471 | @ | jira-cfg.component.ts:48
  | 42976 | @ | config-page.component.ts:34
  | 18950 | @ | metric-page.module.ts:11
  | 36747 | @ | app.guard.ts:60
  | 14431 | @ | hammer-config.class.ts:12
  | (anonymous) | @ | main.js:1


```

**Comment by jgavilanescolastico-ai** [comment]
Nooooo

**Comment by johannesjo** [comment]
@jgavilanescolastico-ai  is this still a problem?
