### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by VAISHAKH-GK** [johannesjo/super-productivity#2519]
### Steps to Reproduce

1.  Integrate Github repository which has no issues
2. After trying to load all issues error messages pop ups

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:1421064
    at m.project (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:1421086)
    at m._next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3706546)
    at m.next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3694675)
    at m._next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3694901)
    at m.next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3694675)
    at m._next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3706644)
    at m.next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3694675)
    at m._next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3706057)
    at m.next (file:///tmp/.mount_superP0kTufO/resources/app.asar/dist/main.17a5c3c10efdd0c8.js:1:3694675)
```

### Meta Info
META: SP7.12.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.12.0 Chrome/100.0.4896.160 Electron/18.3.9 Safari/537.36

### Actions Before Error
```
1678952447177: [SP_ALL] Load(import) all data 
1678952447181: [SP_ALL] All Data was loaded 
1678952452817: [Layout] Hide SideBar 
1678952585175: [Project] Add Project 
1678952585179: [Persistence] Save to DB 
1678952594990: [WorkContext] Set Active Work Context 
1678952595021: [Task] SetSelectedTask 
1678952595137: [Bookmark] Load Bookmark State 
1678952595139: [Project] Load Project related Data Success 
1678952595140: [Improvement] Clear Hidden Improvements 
1678952595141: [Improvement] Delete multiple Improvements 
1678952628008: [SP_ALL] Load(import) all data 
1678952628011: [SP_ALL] All Data was loaded 
1678952628039: [WorkContext] Set Active Work Context 
1678952628055: [Task] SetSelectedTask 
1678952628346: [Bookmark] Load Bookmark State 
1678952628347: [Project] Load Project related Data Success 
1678952628348: [Improvement] Clear Hidden Improvements 
1678952628349: [Improvement] Delete multiple Improvements
```

**Comment by johannesjo** [comment]
I just tried with a fresh empty repository, but I am unable to reproduce this.

**Comment by VAISHAKH-GK** [comment]
I installed new 7.13.1 as appimage and tried but i still has the same issue.

**Comment by VAISHAKH-GK** [comment]
I added integration for another github repository, it worked fine.
I think in the set up process i give wrong access token not sure about that.
Thanks for the effort, am closing this issue.

**Comment by johannesjo** [comment]
Glad that it works now!
