### ISSUE TITLE
Jira integration is not working on mac

### ISSUE THREAD

**Issue by nathenapse** [johannesjo/super-productivity#252]
### Your Environment

* Version used: 2.13.6
* Operating System and version: macOS Catalina

 Expected Behavior
So I wanted to integrate Jira so I added https://atlassian.net as URL email and password then when I test the connection I see this error 
<img width="786" alt="Screen Shot 2019-10-31 at 11 20 21 PM" src="https://user-images.githubusercontent.com/6860642/67983352-908aea00-fc35-11e9-8254-33c8441c3db7.png">

### Error Log (Desktop only)
[2019-10-31 21:27:34.132] [error] Frontend Error: { handledError: { handledError: undefined } } undefined
[2019-10-31 22:58:07.839] [error] Frontend Error: TypeError {} TypeError: Cannot read property '48x48' of undefined
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2062492)
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:367116)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358934)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at Jb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365417)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358832)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at qb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365152)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358954)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
[2019-10-31 22:58:34.721] [error] Frontend Error: TypeError {} TypeError: Cannot read property '48x48' of undefined
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2062492)
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:367116)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358934)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at Jb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365417)
    at Object.Bb [as checkAndUpdateView] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358832)
    at e.detectChanges (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:272880)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2060723)
    at t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:441480)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:440625)
[2019-10-31 22:59:09.359] [error] Frontend Error: TypeError {
  handledError: TypeError { handledError: 'StatusCodeError' }
} undefined
[2019-10-31 22:59:38.979] [error] Frontend Error: TypeError {} TypeError: Cannot read property '48x48' of undefined
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2062492)
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:367116)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358934)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at Jb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365417)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358832)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at qb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365152)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358954)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
[2019-10-31 23:00:37.391] [error] Frontend Error: TypeError {} TypeError: Cannot read property '48x48' of undefined
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2062492)
    at Object.updateRenderer (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:367116)
    at Bb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358934)
    at Zb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365754)
    at Jb (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:365417)
    at Object.Bb [as checkAndUpdateView] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:358832)
    at e.detectChanges (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:272880)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:2060723)
    at t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:441480)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.f30ce200c50cc007bdb0.js:1:440625)
[2019-10-31 23:05:37.698] [error] Frontend Error: TypeError {
  handledError: TypeError { handledError: 'StatusCodeError' }

**Comment by johannesjo** [comment]
Thanks for reporting. There seems to be some sort of inconsistency in Jira's api responses. This should be fixed with the next release.
