### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by cheseremtitus24** [johannesjo/super-productivity#2582]
### Steps to Reproduce

1. setup a github project and provide access token then save
2. click on the created project
3. Click on start Working.
4. Met with the below thread error.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:1410740
    at m.project (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:1410762)
    at m._next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3748176)
    at m.next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736531)
    at m.next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3748274)
    at m.next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3747687)
    at m.next (file:///snap/superproductivity/1736/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
```

### Meta Info
META: SP7.13.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.13.2 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

### Actions Before Error
```
1681629876824: [Project] Add Project 
1681629876830: [Persistence] Save to DB 
1681629886700: [Project] Toggle hide from menu (2) 
1681629887988: [WorkContext] Set Active Work Context 
1681629888097: [Task] SetSelectedTask 
1681629888478: [Bookmark] Load Bookmark State 
1681629888480: [Project] Load Project related Data Success 
1681629888486: [Improvement] Clear Hidden Improvements 
1681629888489: [Improvement] Delete multiple Improvements 
1681629928772: [SP_ALL] Load(import) all data 
1681629928785: [SP_ALL] All Data was loaded 
1681629928899: [WorkContext] Set Active Work Context 
1681629928962: [Task] SetSelectedTask 
1681629929693: [Bookmark] Load Bookmark State 
1681629929699: [Project] Load Project related Data Success 
1681629929703: [Improvement] Clear Hidden Improvements 
1681629929707: [Improvement] Delete multiple Improvements 
1681629961566: [Layout] Toggle SideBar 
1681629981631: [WorkContext] Set Active Work Context 
1681629981718: [Task] SetSelectedTask 
1681630008651: [Global Config] Update Global Config Section 
1681630008701: [Persistence] Save to DB 
1681630337076: [WorkContext] Set Active Work Context 
1681630337262: [Task] SetSelectedTask 
1681630337710: [Bookmark] Load Bookmark State 
1681630337712: [Project] Load Project related Data Success 
1681630337714: [Improvement] Clear Hidden Improvements 
1681630337717: [Improvement] Delete multiple Improvements 
1681630338714: [Bookmark] Toggle Bookmarks 
1681630338717: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for reporting! This can happen when your repository name is not correct. I improved the error handling.
