### ISSUE TITLE
TypeError: Cannot read property 'timeEstimate' of undefined

### ISSUE THREAD

**Issue by microreset** [johannesjo/super-productivity#260]
### Your Environment

* Version used: 
* Operating System and version: Ubuntu 19.10
* Desktop Environment: Gnome Shell
* Browser Name and version: I use the snap version
(superproductivity     2.13.9                      471       stable    johannesjo    -)

### Expected Behavior
I want to add a task from Jira, typing the name of the issue and when I press enter it should add the highlighted task into the list of current tasks

### Current Behavior
After pressing enter to select the task the error appears. Then I can't get rid of it, even if I restart the application of press "Reload app". I have to erase all user data and sync again from google drive.

The error:
```
Snap! A critical error occurred...
! Please Report !
TypeError: Cannot read property 'timeEstimate' of undefined
TypeError: Cannot read property 'timeEstimate' of undefined at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2843866 at Array.reduce () at Object.kT [as transform] (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2843833) at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:361829 at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:362175 at Ub (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:362229) at mO (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:370231) at Object.updateRenderer (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2885361) at Object.updateRenderer (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:367116) at Bb (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:358934)
```

### Steps to Reproduce (for bugs)
1. Press the "+" icon to search for a Jira issue
2. when found, press enter to add it to the work in progress

The issue was already in status "resolved"

### Error Log (Desktop only)
Found in _~/snap/superproductivity/current/.config/superProductivity/log.log_ (because it's a snap)

```
[2019-11-26 14:58:40.555] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'timeEstimate' of undefined
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2843866
    at Array.reduce (<anonymous>)
    at Object.kT [as transform] (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2843833)
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:361829
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:362175
    at Ub (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:362229)
    at mO (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:370231)
    at Object.updateRenderer (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:2885361)
    at Object.updateRenderer (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:367116)
    at Bb (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:358934)
[2019-11-26 14:58:40.635] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'isDone' of undefined
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:19161
    at Array.filter (<anonymous>)
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:19132
    at Array.filter (<anonymous>)
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:19031
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:1441409
    at memoized (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:1440629)
    at oe (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:1441794)
    at file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:1441463
    at memoized (file:///snap/superproductivity/471/resources/app.asar/dist/main.e0c8502e0c032e042ef3.js:1:1440629)

```

**Comment by johannesjo** [comment]
Thanks for reporting. Did you by any chance add the task before and delete it somehow? What would also be very helpful, is if you could open up the console to post the error text there, which normally should be mapped to the sources (main.e0c8502e0c032e042ef3.js is a bundled and minified file).

**Comment by microreset** [comment]
Hi,
Thanks for your answer.

It's a task I already worked on before and checked as "done" (and updated the status to resolved in Jira at the same time). I don't remember deleting it but maybe when I closed the day it got flushed automatically?

Here's the log, I hope this is what you were looking for.
[console.log](https://github.com/johannesjo/super-productivity/files/3898292/console.log)

**Comment by johannesjo** [comment]
Ah exactly! Thank you very much!

**Comment by johannesjo** [comment]
Thank you very much for your help! The issue is resolved and I will provide a new release shortly

**Comment by microreset** [comment]
Amazing, thank you!

**Comment by johannesjo** [comment]
New release is out. Please me know if the issue is resolved now.

**Comment by microreset** [comment]
Hi @johannesjo,

Good news, it seems to work.

Thank you very much!
