### ISSUE TITLE
Error opening app after adding markdown comment to task

### ISSUE THREAD

**Issue by khartahk** [johannesjo/super-productivity#261]
### Your Environment
* Version used: snap superproductivity  2.13.12
* Operating System and version: Arch Linux, kernel  5.3.10-arch1-1
* Desktop Environment: gnome shell

### Expected Behavior
- app should open without an error

### Current Behavior
- opening the app causes an error

### Steps to Reproduce (for bugs)
1. add markdown comment on task
2. app crashes
3. opening the app crashes it everytime

### Console Output
```
TypeError: Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485) at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888) at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061) at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578 at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085 at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408) at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410) at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059) at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220) at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
```

### Error Log (Desktop only)
```
2019-12-02 10:15:17.398] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:17.501] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:20.775] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:20.837] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:24.422] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:24.442] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:37.563] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:37.588] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:42.471] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:15:42.545] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:20:41.488] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
[2019-12-02 10:20:41.528] [error] Frontend Error: TypeError {} TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:381485)
    at e.set [as task] (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2846888)
    at mm (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:282061)
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:360578
    at file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:361085
    at Uy (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:362408)
    at mO (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:370410)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:2878059)
    at Object.updateDirectives (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:367220)
    at By (file:///snap/superproductivity/487/resources/app.asar/dist/main.8923018c99e34b6ab950.js:1:358989)
```

**Comment by johannesjo** [comment]
Thank you very much for reporting! I look into it!

**Comment by khartahk** [comment]
Unfortunately I've already restored a previous version of the data that I have backed up using G Drive and the error is gone for now. I'll try adding markdown again and try to recreate the issue. If I get the error I'll try to get the console opened.

**Comment by johannesjo** [comment]
That would be great!

**Comment by nigelsim** [comment]
This is the stacktrace from the console that I get.:
```
global-error-handler.class.ts:82 GLOBAL_ERROR_HANDLER TypeError: Cannot read property 'replace' of null
    at r.Cm2g.r.to_markdown (index.js:21)
    at e.set [as task] (jira-issue-content.component.ts:35)
    at mm (core.js.pre-build-optimizer.js:21299)
    at core.js.pre-build-optimizer.js:21054
    at core.js.pre-build-optimizer.js:29495
    at Uy (core.js.pre-build-optimizer.js:29457)
    at mO (core.js.pre-build-optimizer.js:29998)
    at Object.updateDirectives (issue-content.component.html:2)
    at Object.updateDirectives (core.js.pre-build-optimizer.js:29786)
    at By (core.js.pre-build-optimizer.js:29439)
```

The ticket that is causing the issue is one that I created in a Kanban board with just a title. A sanatised version of the task object is as follows:
```
{
  "id": "xx",
  "projectId": "xx",
  "subTaskIds": [],
  "attachmentIds": [],
  "timeSpentOnDay": {},
  "timeSpent": 0,
  "timeEstimate": 0,
  "isDone": false,
  "title": "IT-30 Migrate app to static hosting",
  "notes": "",
  "parentId": null,
  "issueId": "14918",
  "issueType": "JIRA",
  "reminderId": null,
  "created": 1575239158788,
  "repeatCfgId": null,
  "_isAdditionalInfoOpen": true,
  "_showSubTasksMode": 2,
  "_currentTab": 0,
  "issueData": {
    "key": "IT-30",
    "id": "14918",
    "components": [],
    "timeestimate": null,
    "timespent": null,
    "description": null,
    "summary": "Migrate app to static hosting",
    "updated": "2019-12-02T08:25:29.758+1000",
    "lastUpdateFromRemote": 1575366579547,
    "status": {
      "description": "",
      "iconUrl": "https://xx.atlassian.net/",
      "id": "10341",
      "name": "In Progress",
      "self": "https://xx.atlassian.net/rest/api/2/status/xx",
      "statusCategory": {
        "colorName": "yellow",
        "id": 4,
        "key": "indeterminate",
        "name": "In Progress",
        "self": "https://xx.atlassian.net/rest/api/2/statuscategory/4"
      }
    },
    "storyPoints": null,
    "attachments": [],
    "comments": [],
    "changelog": [],
    "assignee": {
      "accountId": "xx",
      "accountType": "atlassian",
      "active": true,
      "displayName": "xx",
      "emailAddress": "xx",
      "key": "xx",
      "name": "xx",
      "timeZone": "Australia/Brisbane",
      "avatarUrl": "xx"
    },
    "url": "https://xx.atlassian.net//browse/IT-30"
  }
}
```

**Comment by johannesjo** [comment]
Much better! Thank you very much! I look into it!

**Comment by khartahk** [comment]
This just happened to me again after I edited a tasks title. I've attached the log file from the console.
[superproductivity.log](https://github.com/johannesjo/super-productivity/files/3917019/superproductivity.log)

**Comment by johannesjo** [comment]
Thanks to your help, I was able to locate the issue and to fix it. It will be out with the next release!
