### ISSUE TITLE
bookmark command not working

### ISSUE THREAD

**Issue by hakimovic** [johannesjo/super-productivity#262]
### Your Environment
* Version used: deb/2.13.15
* Operating System and version: Ubuntu 18.04
* Desktop Environment: Gnome

### Expected Behavior
I add a bookmark select *Command (custom shell command)* type `code` in the *command* input click save, click the new bookmark and a new window of *visual studio code* is launched

### Current Behavior
When I click the bookmark, a snackbar comes up saying *launching "code"* and then nothing happens.
There is an error about ngx-translate in the console here are the screenshots: 

### Steps to Reproduce (for bugs)

1. add bookmark to launch a programm
2. click the bookmark
3. nothing happens

### Console Output
ngx-translate-core.js.pre-build-optimizer.js:1033 Uncaught Error: Parameter "key" required
    at e.instant (ngx-translate-core.js.pre-build-optimizer.js:1033)
    at e._openSnack (snack.service.ts:59)
    at e.open (snack.service.ts:35)
    at EventEmitter.<anonymous> (app.component.ts:177)
    at EventEmitter.emit (events.js:200)
    at Object.onMessage (/snap/superproductivity/492/resources/electron.asar/renderer/init.js:42)
![app.component.ts](https://user-images.githubusercontent.com/16239103/70341079-67700180-1852-11ea-90f3-b8fca1d7800c.png)
  
![snack service see instant call crashing](https://user-images.githubusercontent.com/16239103/70342200-d6e6f080-1854-11ea-8e3d-72f51af54797.png)

  
![screenshot_Selection_20191206	(008)](https://user-images.githubusercontent.com/16239103/70342448-4fe64800-1855-11ea-993f-2638bdefd7f3.png)

**Comment by johannesjo** [comment]
Thanks for reporting. The error is due to the command you're trying to execute does throw an empty error (or the error is not handled correctly inside the app). May I ask what the command is you're trying to execute?

**Comment by hakimovic** [comment]
it's `code`, am I doing something wrong?  

thank you for replying! and great projet by the way !!!  

![screenshot_Selection_20191206	(007)](https://user-images.githubusercontent.com/16239103/70343585-eddb1200-1857-11ea-99de-5ddea155a03b.png)

**Comment by johannesjo** [comment]
Not sure :)
I just tried with `notify-send "Hooooraaaayyy."` and it worked just fine. Is `code` an alias for something? Aliases won't work (I suppose) because `.bashrc` etc. won't be loaded when executing scripts outside a terminal.

**Comment by hakimovic** [comment]
hmmm I don't uderstand, when I launch a terminal I type `/bin/sh` then `notify-send "hello"` it works, but when I launch superproductivity from terminal I add a bookmark with the same command, it doesn't work and I have this error message:  
  ```
 ~/Documents/projets/dashboard testing ✗                                                           3d ⚑  
🚀 $ superproductivity 
Saving backups to /home/hakim/snap/superproductivity/492/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
[25225:1209/113521.812885:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
running command notify-send "hello"
ERR Error: Command failed: notify-send "hello"
/bin/sh: 1: notify-send: not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'notify-send "hello"'
}
Error: Error: Command failed: notify-send "hello"
/bin/sh: 1: notify-send: not found

    at Object.exports.errorHandler (/snap/superproductivity/492/resources/app.asar/electron/error-handler.js:10:18)
    at /snap/superproductivity/492/resources/app.asar/electron/main.js:294:29
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
11:35:35.602 › Error: Command failed: notify-send "hello"
/bin/sh: 1: notify-send: not found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12) Error: Error: Command failed: notify-send "hello"
/bin/sh: 1: notify-send: not found

    at Object.exports.errorHandler (/snap/superproductivity/492/resources/app.asar/electron/error-handler.js:10:18)
    at /snap/superproductivity/492/resources/app.asar/electron/main.js:294:29
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12)
```  
I also tryed `bash -c 'notify-send "hello" '` and got the same result.  
Any Idea? Thank you

**Comment by johannesjo** [comment]
That's puzzling indeed. Always confuses me what context bash scripts have which are run from other non terminal programs.

What you might try is this in a terminal:
```
which notify-send 
/usr/bin/notify-send
```





And use that path instead. The program might simply not be in the path. On my system I am doing something like this in the `~/.profile`
```
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```
This might be, why I have no problems with running `notify-send`.

**Comment by johannesjo** [comment]
Closed due to inactivity.
