### ISSUE TITLE
Error: Project dr9sdsF7guv5c_Wz7lkSn not found

### ISSUE THREAD

**Issue by manavbharambe** [johannesjo/super-productivity#2705]
### Steps to Reproduce

1. I was already using SuperProductivity. I deleted my projects.
2. Then go to tags section and click on deleted tags.
3. It started crashing.
4. Uninstalled the superProductivity app. And downloaded the latest version, which is still crashing.

### Stacktrace
```
Error: Project dr9sdsF7guv5c_Wz7lkSn not found
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:255651
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3783328
    at hi (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3782764)
    at yt (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3783761)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3783385
    at hi (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3782764)
    at _.project (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3782191)
    at _next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3478842)
    at _.next (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3466971)
    at ie._subscribe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/main.dc34c042c8dc7881.js:1:3459726)
```

### Meta Info
META: SP7.11.5 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.11.5 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36

### Actions Before Error
```
1690522586586: [Task] Delete Tasks 
1690522586602: [Persistence] Save to DB (3) 
1690522592839: [WorkContext] Set Active Work Context 
1690522592858: [Task] SetSelectedTask 
1690522594755: [Layout] Hide SideBar 
1690522601143: [SP_ALL] Load(import) all data 
1690522601150: [SP_ALL] All Data was loaded 
1690522601210: [WorkContext] Set Active Work Context 
1690522601228: [Task] SetSelectedTask 
1690522622191: [SP_ALL] Load(import) all data 
1690522622197: [SP_ALL] All Data was loaded 
1690522622225: [WorkContext] Set Active Work Context 
1690522622233: [Task] SetSelectedTask 
1690522623999: [WorkContext] Set Active Work Context 
1690522624001: [Task] SetSelectedTask 
1690522624835: [Layout] Hide SideBar 
1690522656862: [WorkContext] Set Active Work Context 
1690522656915: [Task] SetSelectedTask 
1690522657002: [Bookmark] Load Bookmark State 
1690522657002: [Project] Load Project related Data Success 
1690522657002: [Improvement] Clear Hidden Improvements 
1690522657003: [Improvement] Delete multiple Improvements 
1690522678994: [SP_ALL] Load(import) all data 
1690522679002: [SP_ALL] All Data was loaded 
1690522683343: [Layout] Hide SideBar 
1690522691566: [SP_ALL] Load(import) all data 
1690522691570: [SP_ALL] All Data was loaded 
1690522693460: [Layout] Hide SideBar 
1690524252123: [SP_ALL] Load(import) all data 
1690524252132: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It looks like your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by dali-does** [comment]
I had a similar `Project Not Found` problem for a while, but only after switching from the AUR package to the snap installation, and thus moving from 6.5.2 to the latest version, I was able to reproduce the same error whenever I opened the Sceduled tab.

I had a recurring task every Wednesday that was not attached to any existing project. I suspect that it was connected to one previously, but that it was left behind somehow when I deleted the project. I had the stack trace below triggered whenever I opened Scheduled. After removing the task completely (luckily it loaded in Today since it's Wednesday!), the error went away. So perhaps scheduled tasks without projects, or with deleted projects, might be a place to start?

```
10:50:24.849 › Frontend Error: Error: Project FXq6Ar6G1 not found
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:313788
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062351
    at Br (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061871)
    at fn (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062784)
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062408
    at Br (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061871)
    at m.project (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061214)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748158)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at Ye._subscribe (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3729042) Error: Project FXq6Ar6G1 not found
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:313788
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062351
    at Br (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061871)
    at fn (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062784)
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4062408
    at Br (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061871)
    at m.project (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4061214)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748158)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at Ye._subscribe (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3729042)
10:50:25.481 › Frontend Error Stack: Error (webpack:///src/app/features/project/store/project.selectors.ts:43:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:757:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:645:39)
defaultStateFn (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:664:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:760:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:645:39)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/fesm2015/ngrx-store.mjs:542:51)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
```
