### ISSUE TITLE
Widget Android is Broken

### ISSUE THREAD

**Issue by Carlos12001** [johannesjo/super-productivity#2727]
### Discussed in https://github.com/johannesjo/super-productivity/discussions/2726

<div type='discussions-op-text'>

<sup>Originally posted by **Carlos12001** August 17, 2023</sup>
When you add a widget the app explode and stop working.</div>

**Comment by howarddo2208** [comment]
I witnessed this too, here's the log

```
kotlin.UninitializedPropertyAccessException: lateinit property tasks has not been initialized
	at com.superproductivity.superproductivity.TaskListWidgetViewsFactory.getCount(TaskListWidgetViewsFactory.kt:32)
	at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.getCount(RemoteViewsService.java:154)
	at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:173)
	at android.os.Binder.execTransactInternal(Binder.java:1290)
	at android.os.Binder.execTransact(Binder.java:1249)

```

**Comment by Ryonez** [comment]
Can confirm I'm having the issue as well.

**Comment by Jagdfalke** [comment]
I can confirm this issue with version 8.0.1 on Android 13.

**Comment by johannesjo** [comment]
Widget will be removed with the next android release. It's not working well atm. Possibly will be reintroduced with a later version.
