### ISSUE TITLE
IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 49 is larger than the node's length (16).

### ISSUE THREAD

**Issue by AugustasV** [johannesjo/super-productivity#2738]
### Steps to Reproduce

1. Open a PDF document.
2. Copy any text from the PDF.
3. Go to the subtask field in the task.
4. Paste the copied text into the subtask field.
5. An error message or unexpected behavior may occur.

### Console Output

```
global-error-handler.class.ts:33  GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'setStart' on 'Range': The offset 235 is larger than the node's length (101).
    at n._insertAtCursorChromium (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:1888448)
    at n._insertAtCursor (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:1887652)
    at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:1887004)
    at HTMLDivElement.ht (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:11663)
    at W.invokeTask (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:7289)
    at Object.onInvokeTask (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:4002221)
    at W.invokeTask (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:7210)
    at lt.runTask (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:2646)
    at k.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:8348)
    at tt (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:21099)
(anonymous) @ global-error-handler.class.ts:33
```

```
Unhandled Promise rejection: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 235 is larger than the node's length (101). ; Zone: <root> ; Task: Promise.then ; Value: Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 235 is larger than the node's length (101).
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at d (global-error-handler.util.ts:227:38)
    at W.invoke (zone.js:372:26)
    at lt.run (zone.js:134:43)
    at zone.js:1275:36
    at W.invokeTask (zone.js:406:31)
    at lt.runTask (zone.js:178:47)
    at G (zone.js:585:35)
    at k.invokeTask [as invoke] (zone.js:491:21) Error: IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 235 is larger than the node's length (101).
    at n.<anonymous> (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:2488560)
    at Generator.next (<anonymous>)
    at d (https://app.super-productivity.com/main.f41ec36bbe587d0c.js:1:2485601)
    at W.invoke (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:6670)
    at lt.run (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:2010)
    at https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:16973
    at W.invokeTask (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:7289)
    at lt.runTask (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:2646)
    at G (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:9346)
    at k.invokeTask [as invoke] (https://app.super-productivity.com/polyfills.73ebf1f8f690ae69.js:1:8378)
```
### Stacktrace
```
setStart (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:232:10)
window.getSelection (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:159:11)
ev.clipboardData.getData (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:108:13)
listener.call (webpack:///node_modules/zone.js/fesm2015/zone.js:766:38)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26343:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59)
task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:487:33)
callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1661:17)
```

### Meta Info
META: SP7.13.2 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54

### Actions Before Error
```
1692710613873: [Task] Add time spent 
1692710613874: [Tag] Update Work End for Tag 
1692710613875: [Persistence] Save to DB (2) 
1692710614877: [Task] Add time spent 
1692710614878: [Tag] Update Work End for Tag 
1692710614880: [Persistence] Save to DB (2) 
1692710615873: [Task] Add time spent 
1692710615874: [Tag] Update Work End for Tag 
1692710615875: [Persistence] Save to DB (2) 
1692710616181: [Task] Update Task 
1692710616184: [Persistence] Save to DB 
1692710616887: [Task] Add time spent 
1692710616888: [Tag] Update Work End for Tag 
1692710616889: [Persistence] Save to DB (2) 
1692710617885: [Task] Add time spent 
1692710617886: [Tag] Update Work End for Tag 
1692710617886: [Persistence] Save to DB (2) 
1692710618879: [Task] Add time spent 
1692710618880: [Tag] Update Work End for Tag 
1692710618881: [Persistence] Save to DB (2) 
1692710619883: [Task] Add time spent 
1692710619885: [Tag] Update Work End for Tag 
1692710619886: [Persistence] Save to DB (2) 
1692710620877: [Task] Add time spent 
1692710620879: [Tag] Update Work End for Tag 
1692710620880: [Persistence] Save to DB (2) 
1692710621887: [Task] Add time spent 
1692710621889: [Tag] Update Work End for Tag 
1692710621890: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
Thanks for reporting! This seems to happen for any multiline text
