### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by fraxnet** [johannesjo/super-productivity#2793]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:1410740
    at m.project (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:1410762)
    at m._next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3748176)
    at m.next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736531)
    at m.next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3748274)
    at m.next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
    at m._next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3747687)
    at m.next (file:///opt/superProductivity/resources/app.asar/dist/main.4815a64c1258ec76.js:1:3736305)
```

### Meta Info
META: SP7.13.2 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.13.2 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

### Actions Before Error
```
1695360639672: [Task] Add time spent 
1695360639675: [Project] Update Work End 
1695360639678: [Tag] Update Work End for Tag (3) 
1695360639682: [Persistence] Save to DB (5) 
1695360640178: [Task] SetCurrentTask 
1695360640673: [Task] Add time spent 
1695360640676: [Project] Update Work Start 
1695360640677: [Project] Update Work End 
1695360640679: [Persistence] Save to DB 
1695360640679: [Task] Update Task Tags 
1695360640684: [Persistence] Save to DB (2) 
1695360640684: [Project] Auto Move Task from backlog to today 
1695360640686: [Persistence] Save to DB (3) 
1695360641672: [Task] Add time spent 
1695360641674: [Project] Update Work End 
1695360641676: [Tag] Update Work End for Tag 
1695360641679: [Persistence] Save to DB (3) 
1695360642672: [Task] Add time spent 
1695360642673: [Project] Update Work End 
1695360642673: [Tag] Update Work End for Tag 
1695360642675: [Persistence] Save to DB (3) 
1695360643672: [Task] Add time spent 
1695360643675: [Project] Update Work End 
1695360643676: [Tag] Update Work End for Tag 
1695360643678: [Persistence] Save to DB (3) 
1695360644673: [Task] Add time spent 
1695360644675: [Project] Update Work End 
1695360644677: [Tag] Update Work End for Tag 
1695360644678: [Persistence] Save to DB (3)
```

**Comment by johannesjo** [comment]
Could you maybe provide a bit more input? Were you trying to use one of the issue providers like jira?
