### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by mrfrobinson** [johannesjo/super-productivity#2796]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'digest')
    at http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134595
    at http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134616
    at Generator.next (<anonymous>)
    at http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134453
    at new i (http://192.168.3.42:8011/polyfills.73ebf1f8f690ae69.js:1:18636)
    at _4 (http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134188)
    at sle (http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134477)
    at http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1137700
    at Generator.next (<anonymous>)
    at http://192.168.3.42:8011/main.fc6d6f4cfe3ecd43.js:1:1134453
```

### Meta Info
META: SP7.14.3 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

### Actions Before Error
```
1695742210907: [Global Config] Update Global Config Section 
1695742210913: [Persistence] Save to DB 
1695742225733: [Global Config] Update Global Config Section 
1695742225739: [Persistence] Save to DB 
1695742730015: [Task] Update Task 
1695742730162: [Persistence] Save to DB 
1695742730162: [Task] UnSchedule 
1695742730164: [Persistence] Save to DB (2) 
1695742730164: [Task] Update Task 
1695742730165: [Persistence] Save to DB 
1695742736874: [Task][Issue] Add Task 
1695742736877: [Persistence] Save to DB (2) 
1695742742457: [Task][Issue] Add Task 
1695742742459: [Persistence] Save to DB (2) 
1695742744879: [Task][Issue] Add Task 
1695742744881: [Persistence] Save to DB (2) 
1695742745840: [Task][Issue] Add Task 
1695742745841: [Persistence] Save to DB (2) 
1695742748087: [Task][Issue] Add Task 
1695742748089: [Persistence] Save to DB (2) 
1695742751243: [WorkContext] Set Active Work Context 
1695742751246: [Task] SetSelectedTask 
1695743213514: [Global Config] Update Global Config Section 
1695743213518: [Persistence] Save to DB 
1695743213518: [Dropbox] Trigger Auth Dialog 
1695743221417: [SP_ALL] Load(import) all data 
1695743221418: [SP_ALL] All Data was loaded 
1695743226016: [Global Config] Update Global Config Section 
1695743226017: [Persistence] Save to DB 
1695743226017: [Dropbox] Trigger Auth Dialog
```

**Comment by mrfrobinson** [comment]
Figured it out. I was accessing via http not https. I pointed a reverse proxy with an ssl cert and problem was solved.
