### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by MartinWegmann** [johannesjo/super-productivity#2812]
Hello Johannes,
during my work with Super Productivity `7.14.3` I got an error popup and the following report. 
`main.log` attached.

Thank you for looking into this.
Martin

### Steps to Reproduce

1. Drag and drop sub tasks from a task in my `Privat` project into another task located in the project backlog.
2. I'll let you know once I know precisely how to reproduce the issue.

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:1669119
    at Array.map (<anonymous>)
    at p._next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:1669110)
    at p.__tryOrUnsub (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3757100)
    at p.next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3756329)
    at S._next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3755512)
    at S.next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3755286)
    at v._next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3767255)
    at v.next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3755286)
    at v._next (file:///C:/Users/marti/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.07fa65affdad3bc5.js:1:3766668)
```

### Meta Info
META: SP7.14.3 Electron – en-GB – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.14.3 Chrome/110.0.5481.208 Electron/23.3.13 Safari/537.36

### Actions Before Error
```
1696489160492: [Task] Update Task 
1696489160493: [Persistence] Save to DB 
1696489171325: [Task] Move sub task 
1696489171326: [Persistence] Save to DB 
1696489174579: [Task] Move sub task 
1696489174580: [Persistence] Save to DB 
1696489178792: [Task] Move sub task 
1696489178794: [Persistence] Save to DB 
1696489193203: [Task] Add SubTask 
1696489193204: [Persistence] Save to DB 
1696489204715: [Task] Update Task 
1696489204716: [Persistence] Save to DB 
1696489209835: [Task] Move sub task 
1696489209837: [Persistence] Save to DB 
1696489216762: [Task] Update Task 
1696489216763: [Persistence] Save to DB 
1696489242575: [Task] Move sub task 
1696489242577: [Persistence] Save to DB 
1696489250226: [Task] Add SubTask 
1696489250227: [Persistence] Save to DB 
1696489252368: [Task] Update Task 
1696489252369: [Persistence] Save to DB 
1696489258698: [Task] Move sub task 
1696489258700: [Persistence] Save to DB 
1696489266552: [Task] Move sub task 
1696489266553: [Persistence] Save to DB 
1696489271832: [Task] Move sub task 
1696489271833: [Persistence] Save to DB 
[main.log](https://github.com/johannesjo/super-productivity/files/12813492/main.log)

1696489274091: [Task] Move sub task 
1696489274092: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for reporting! Unfortunately I am unable to reproduce this!
