### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by Kom46** [johannesjo/super-productivity#2823]
### Steps to Reproduce

1.enable github sync
2.try to sync

 Log (Desktop only)

### Console Output

​ @ngrx/store/init Object
​ @ngrx/store/update-reducers Object
​ @ngrx/effects/init Object
​ LOAD COMPLETE true
​ @ngrx/store/update-reducers Object
​ Persistence already allowed
app.component.ts:315 2 out of 604722 MiB used (0%)
reminder.service.ts:89 loaded reminders from database Array(0)
cross-model-migrations.ts:14 [M] Starting cross model migrations...
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data Object
action-logger.reducer.ts:11 [Idle] Reset Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded Object
sync.effects.ts:137 sync(effect)..... INITIAL_SYNC_TRIGGER
sync-provider.service.ts:186 Object
sync-provider.service.ts:546 LocalFile PRE1: ↔ Same Rev 1697482696653
persistence.service.ts:338 LOAD COMPLETE false
sync-provider.service.ts:546 LocalFile PRE1: No local changes to sync
sync-trigger.service.ts:198 immediate sync trigger I_FOCUS_THROTTLED
sync.effects.ts:137 sync(effect)..... I_FOCUS_THROTTLED
sync-provider.service.ts:186 Object
sync-provider.service.ts:546 LocalFile PRE1: ↔ Same Rev 1697482696653
persistence.service.ts:338 LOAD COMPLETE false
sync-provider.service.ts:546 LocalFile PRE1: No local changes to sync
action-logger.reducer.ts:11 [Task][Issue] Add Task Object
task-related-model.effects.ts:179 shortSyntax undefined
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [TaskRepeatCfg] Update TaskRepeatCfg Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task] Schedule Object
reminder.service.ts:231 saveReminders Array(1)
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task] Update Task Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task][Issue] Add Task Object
task-related-model.effects.ts:179 shortSyntax undefined
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [TaskRepeatCfg] Update TaskRepeatCfg Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task] Schedule Object
reminder.service.ts:231 saveReminders Array(2)
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task] Update Task Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ tag
sync-trigger.service.ts:210 __trigger_sync__ task
sync-trigger.service.ts:210 __trigger_sync__ taskRepeatCfg
sync-trigger.service.ts:210 __trigger_sync__ task
sync-trigger.service.ts:210 __trigger_sync__ reminders
sync-trigger.service.ts:210 __trigger_sync__ task
sync-trigger.service.ts:210 __trigger_sync__ tag
sync-trigger.service.ts:210 __trigger_sync__ task
sync-trigger.service.ts:210 __trigger_sync__ taskRepeatCfg
sync-trigger.service.ts:210 __trigger_sync__ task
sync-trigger.service.ts:210 __trigger_sync__ reminders
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Layout] Toggle SideBar Object
5persistence.service.ts:338 LOAD COMPLETE false
action-logger.reducer.ts:11 [WorkContext] Set Active Work Context Object
action-logger.reducer.ts:11 [Task] SetSelectedTask Object
action-logger.reducer.ts:11 [Bookmark] Load Bookmark State Object
action-logger.reducer.ts:11 [Project] Load Project related Data Success Object
action-logger.reducer.ts:11 [Improvement] Clear Hidden Improvements Object
action-logger.reducer.ts:11 [Improvement] Delete multiple Improvements Object
action-logger.reducer.ts:11 [Task] Update Task Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Update Task Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Add SubTask Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Update Task Object
task-related-model.effects.ts:179 shortSyntax undefined
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Add SubTask Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Update Task Object
task-related-model.effects.ts:179 shortSyntax undefined
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ task
persistence.service.ts:338 LOAD COMPLETE false
action-logger.reducer.ts:11 [Project] Update Project Issue Provider Cfg Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:210 __trigger_sync__ project
poll-to-backlog.effects.ts:48 POLL GITHUB
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of null (reading 'issues')
    at github-issue-map.util.ts:42:30
    at m.project (github-api.service.ts:152:25)
    at m._next (map.js:29:35)
    at m.next (Subscriber.js:49:18)
    at m._next (Subscriber.js:72:26)
    at m.next (Subscriber.js:49:18)
    at m._next (map.js:35:26)
    at m.next (Subscriber.js:49:18)
    at m._next (filter.js:33:30)
    at m.next (Subscriber.js:49:18)
(anonymous) @ global-error-handler.class.ts:33
action-logger.ts:39 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
global-error-handler.util.ts:115 Object
global-error-handler.class.ts:33 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'issues')
Error: TypeError: Cannot read properties of null (reading 'issues')
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at d (global-error-handler.util.ts:227:38)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at xt (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at d (global-error-handler.util.ts:227:38)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
(anonymous) @ global-error-handler.class.ts:33
action-logger.ts:39 Last actions before error: Array(30)
persistence.service.ts:338 LOAD COMPLETE false
zone.js:1061 Unhandled Promise rejection: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'issues')
Error: TypeError: Cannot read properties of null (reading 'issues')
    at n.<anonymous> (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2500062)
    at Generator.next (<anonymous>)
    at d (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2497103)
    at U.invoke (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4014327)
    at U.invoke (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
    at Object.onInvokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4014140) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'issues')
Error: TypeError: Cannot read properties of null (reading 'issues')
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at d (global-error-handler.util.ts:227:38)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at n.<anonymous> (global-error-handler.class.ts:60:13)
    at Generator.next (<anonymous>)
    at d (global-error-handler.util.ts:227:38)
    at U.invoke (zone.js:372:26)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at it.runTask (zone.js:178:47)
    at w (zone.js:585:35)
    at B.invokeTask [as invoke] (zone.js:491:21) Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of null (reading 'issues')
Error: TypeError: Cannot read properties of null (reading 'issues')
    at n.<anonymous> (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2500062)
    at Generator.next (<anonymous>)
    at d (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2497103)
    at U.invoke (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4014327)
    at U.invoke (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
    at Object.onInvokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4014140)
    at n.<anonymous> (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2500062)
    at Generator.next (<anonymous>)
    at d (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:2497103)
    at U.invoke (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at it.run (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
    at it.runTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2646)
    at w (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:9348)
    at B.invokeTask [as invoke] (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:8379)
E.onUnhandledError @ zone.js:1061
Show 1 more frame
persistence.service.ts:338 LOAD COMPLETE false
### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:1410740
    at m.project (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:1410762)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748158)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736513)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748256)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3747669)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
```

### Meta Info
META: SP7.13.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.13.2 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

### Actions Before Error
```
1697519228080: [Persistence] Save to DB 
1697519228081: [Task][Issue] Add Task 
1697519228082: [Persistence] Save to DB (2) 
1697519228083: [TaskRepeatCfg] Update TaskRepeatCfg 
1697519228083: [Persistence] Save to DB 
1697519228083: [Task] Schedule 
1697519228084: [Persistence] Save to DB (2) 
1697519228084: [Task] Update Task 
1697519228085: [Persistence] Save to DB 
1697519246967: [Layout] Toggle SideBar 
1697519910731: [WorkContext] Set Active Work Context 
1697519910763: [Task] SetSelectedTask 
1697519910944: [Bookmark] Load Bookmark State 
1697519910944: [Project] Load Project related Data Success 
1697519910944: [Improvement] Clear Hidden Improvements 
1697519910944: [Improvement] Delete multiple Improvements 
1697519915884: [Task] Update Task 
1697519915990: [Persistence] Save to DB 
1697519919549: [Task] Update Task 
1697519919551: [Persistence] Save to DB 
1697519921025: [Task] Add SubTask 
1697519921026: [Persistence] Save to DB 
1697519929549: [Task] Update Task 
1697519929550: [Persistence] Save to DB 
1697519937624: [Task] Add SubTask 
1697519937625: [Persistence] Save to DB 
1697519939467: [Task] Update Task 
1697519939468: [Persistence] Save to DB 
1697519953063: [Project] Update Project Issue Provider Cfg 
1697519953068: [Persistence] Save to DB
```

**Comment by codeling** [comment]
Duplicate of https://github.com/johannesjo/super-productivity/issues/2793 .
