### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'issues')

### ISSUE THREAD

**Issue by AmarUstavdic** [johannesjo/super-productivity#2838]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'issues')
    at file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:1410740
    at m.project (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:1410762)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748158)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736513)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3748256)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
    at m._next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3747669)
    at m.next (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3736287)
```

### Meta Info
META: SP7.13.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.13.2 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

### Actions Before Error
```
1698707084963: [Task] SetSelectedTask 
1698707085051: [Bookmark] Load Bookmark State 
1698707085052: [Project] Load Project related Data Success 
1698707085053: [Improvement] Clear Hidden Improvements 
1698707085054: [Improvement] Delete multiple Improvements 
1698707144352: [Project] Update Project Issue Provider Cfg 
1698707144357: [Persistence] Save to DB 
1698707148058: [Layout] Toggle SideBar 
1698707148061: [Layout] Hide SideBar 
1698707233527: [Project] Update Project 
1698707233545: [Persistence] Save to DB 
1698707301390: [Task][Issue] Add Task 
1698707301392: [Persistence] Save to DB (2) 
1698707351644: [Task] SetSelectedTask 
1698707351645: [Layout] Hide Notes 
1698707358421: [Layout] ToggleShow Notes 
1698707358422: [Task] SetSelectedTask 
1698707359305: [Layout] ToggleShow Notes 
1698707440927: [Project] Update Project Issue Provider Cfg 
1698707440931: [Persistence] Save to DB 
1698707464919: [SP_ALL] Load(import) all data 
1698707464925: [SP_ALL] All Data was loaded 
1698707464960: [WorkContext] Set Active Work Context 
1698707464985: [Task] SetSelectedTask 
1698707465057: [Bookmark] Load Bookmark State 
1698707465059: [Project] Load Project related Data Success 
1698707465060: [Improvement] Clear Hidden Improvements 
1698707465061: [Improvement] Delete multiple Improvements 
1698707510998: [Project] Update Project Issue Provider Cfg 
1698707511001: [Persistence] Save to DB
```

**Comment by codeling** [comment]
Duplicate of https://github.com/johannesjo/super-productivity/issues/2793 .
