### ISSUE TITLE
DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

### ISSUE THREAD

**Issue by astoeriko** [johannesjo/super-productivity#287]
### Your Environment
* Version used: 3.1.3 snap
* Operating System and version: Ubuntu 18.04.4 LTS
* Desktop Environment: Gnome 3.28.2

### Current Behavior
When starting the app, it does not show the normal user interface but instead a console and other inspection tools. The console shows errors. When I click 'Toogle device toolbar' (or press Ctrl + Shift + M) – so only at 766 x 926 px – I see the normal user interface background with the project title. But instead of tasks I see a red box titled *Snap! A critical error occured...*, showing the error message and asking me to report it.

### Console Output
```
GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e._triggerWebAnimation (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889969)
    at e._buildPlayer (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889623)
    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890192)
    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:876834)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872607
    at Array.forEach (<anonymous>)
    at e._flushAnimations (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872481)
    at e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:867431)
    at t.e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:880111)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:1449902
e.handleError @ main.4c881b437b84d380133c.js:1
main.4c881b437b84d380133c.js:1 META: Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/3.1.3 Chrome/78.0.3904.130 Electron/7.1.4 Safari/537.36
main.4c881b437b84d380133c.js:1 GLOBAL_ERROR_HANDLER Error: NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e.handleError (main.4c881b437b84d380133c.js:1)
    at main.4c881b437b84d380133c.js:1
    at t.invoke (polyfills.ba9ede11574490fb99be.js:1)
    at e.run (polyfills.ba9ede11574490fb99be.js:1)
    at e.runOutsideAngular (main.4c881b437b84d380133c.js:1)
    at e.tick (main.4c881b437b84d380133c.js:1)
    at main.4c881b437b84d380133c.js:1
    at t.invoke (polyfills.ba9ede11574490fb99be.js:1)
    at Object.onInvoke (main.4c881b437b84d380133c.js:1)
    at t.invoke (polyfills.ba9ede11574490fb99be.js:1)
e.handleError @ main.4c881b437b84d380133c.js:1
main.4c881b437b84d380133c.js:1 META: Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/3.1.3 Chrome/78.0.3904.130 Electron/7.1.4 Safari/537.36
polyfills.ba9ede11574490fb99be.js:1 Uncaught Error: Error: NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e.handleError (main.4c881b437b84d380133c.js:1)
    at Object.next (main.4c881b437b84d380133c.js:1)
    at t.o [as _next] (main.4c881b437b84d380133c.js:1)
    at t.__tryOrUnsub (main.4c881b437b84d380133c.js:1)
    at t.next (main.4c881b437b84d380133c.js:1)
    at t._next (main.4c881b437b84d380133c.js:1)
    at t.next (main.4c881b437b84d380133c.js:1)
    at t.next (main.4c881b437b84d380133c.js:1)
    at t.emit (main.4c881b437b84d380133c.js:1)
    at main.4c881b437b84d380133c.js:1
main.4c881b437b84d380133c.js:1 Invalid keyframe value for property height: nanpx
e._triggerWebAnimation @ main.4c881b437b84d380133c.js:1
polyfills.ba9ede11574490fb99be.js:1 Uncaught DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e._triggerWebAnimation (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889969)
    at e._buildPlayer (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889623)
    at e.init (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889442)
    at e.finish (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890489)
    at e.finish (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:877019)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:876216
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889381
    at Array.forEach (<anonymous>)
    at e._onFinish (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889353)
    at e.finish (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890551)
```

### Error Log (Desktop only)
```
[2020-02-10 12:23:21.179] [error] Frontend Error: DOMException {
  stack: "Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.\n" +
    '    at e._triggerWebAnimation (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889969)\n' +
    '    at e._buildPlayer (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889623)\n' +
    '    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890192)\n' +
    '    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:876834)\n' +
    '    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872607\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at e._flushAnimations (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872481)\n' +
    '    at e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:867431)\n' +
    '    at t.e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:880111)\n' +
    '    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:1449902',
  INDEX_SIZE_ERR: 1,
  DOMSTRING_SIZE_ERR: 2,
  HIERARCHY_REQUEST_ERR: 3,
  WRONG_DOCUMENT_ERR: 4,
  INVALID_CHARACTER_ERR: 5,
  NO_DATA_ALLOWED_ERR: 6,
  NO_MODIFICATION_ALLOWED_ERR: 7,
  NOT_FOUND_ERR: 8,
  NOT_SUPPORTED_ERR: 9,
  INUSE_ATTRIBUTE_ERR: 10,
  INVALID_STATE_ERR: 11,
  SYNTAX_ERR: 12,
  INVALID_MODIFICATION_ERR: 13,
  NAMESPACE_ERR: 14,
  INVALID_ACCESS_ERR: 15,
  VALIDATION_ERR: 16,
  TYPE_MISMATCH_ERR: 17,
  SECURITY_ERR: 18,
  NETWORK_ERR: 19,
  ABORT_ERR: 20,
  URL_MISMATCH_ERR: 21,
  QUOTA_EXCEEDED_ERR: 22,
  TIMEOUT_ERR: 23,
  INVALID_NODE_TYPE_ERR: 24,
  DATA_CLONE_ERR: 25,
  code: 9,
  name: 'NotSupportedError',
  message: "Failed to execute 'animate' on 'Element': Partial keyframes are not supported."
} Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e._triggerWebAnimation (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889969)
    at e._buildPlayer (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889623)
    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890192)
    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:876834)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872607
    at Array.forEach (<anonymous>)
    at e._flushAnimations (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872481)
    at e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:867431)
    at t.e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:880111)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:1449902
[2020-02-10 12:23:21.296] [error] Frontend Error: Error {} Error: NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
    at e.handleError (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:3738629)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:344238
    at t.invoke (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:9367)
    at e.run (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:4570)
    at e.runOutsideAngular (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:333862)
    at e.tick (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:344181)
    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:342074
    at t.invoke (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:9367)
    at Object.onInvoke (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:332831)
    at t.invoke (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:9307)
[2020-02-10 12:23:26.970] [error] Frontend Error Stack: DOMException {
  stack: "Error: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.\n" +
    '    at e._triggerWebAnimation (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889969)\n' +
    '    at e._buildPlayer (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:889623)\n' +
    '    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:890192)\n' +
    '    at e.play (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:876834)\n' +
    '    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872607\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at e._flushAnimations (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:872481)\n' +
    '    at e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:867431)\n' +
    '    at t.e.flush (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:880111)\n' +
    '    at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:1449902',
  INDEX_SIZE_ERR: 1,
  DOMSTRING_SIZE_ERR: 2,
  HIERARCHY_REQUEST_ERR: 3,
  WRONG_DOCUMENT_ERR: 4,
  INVALID_CHARACTER_ERR: 5,
  NO_DATA_ALLOWED_ERR: 6,
  NO_MODIFICATION_ALLOWED_ERR: 7,
  NOT_FOUND_ERR: 8,
  NOT_SUPPORTED_ERR: 9,
  INUSE_ATTRIBUTE_ERR: 10,
  INVALID_STATE_ERR: 11,
  SYNTAX_ERR: 12,
  INVALID_MODIFICATION_ERR: 13,
  NAMESPACE_ERR: 14,
  INVALID_ACCESS_ERR: 15,
  VALIDATION_ERR: 16,
  TYPE_MISMATCH_ERR: 17,
  SECURITY_ERR: 18,
  NETWORK_ERR: 19,
  ABORT_ERR: 20,
  URL_MISMATCH_ERR: 21,
  QUOTA_EXCEEDED_ERR: 22,
  TIMEOUT_ERR: 23,
  INVALID_NODE_TYPE_ERR: 24,
  DATA_CLONE_ERR: 25,
  code: 9,
  name: 'NotSupportedError',
  message: "Failed to execute 'animate' on 'Element': Partial keyframes are not supported."
} _triggerWebAnimation (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:4481:32)
_buildPlayer (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:4464:17)
play (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:4487:13)
play (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:3617:90)
player.onDone(function (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:3397:19)
rootPlayers.forEach(function (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:3390:20)
addClass (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:3039:31)
flush (webpack:///node_modules/@angular/animations/fesm5/browser.js.pre-build-optimizer.js:3896:31)
this._zone.runOutsideAngular(function (webpack:///node_modules/@angular/platform-browser/fesm5/animations.js.pre-build-optimizer.js:182:29)
[2020-02-10 12:23:26.971] [error] Frontend Error Stack: Error {} isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:127:12)
this._zone.runOutsideAngular(function (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:27137:86)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:391:25)
run (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:150:42)
runOutsideAngular (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:26215:27)
this._zone.runOutsideAngular(function (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:27137:23)
next (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:26998:104)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:391:25)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:26256:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:390:51)
```

**Comment by johannesjo** [comment]
Interesting... Thanks for reporting. I look into it!

**Comment by johannesjo** [comment]
I am unable to reproduce the issue.  Does it occur on every single application start?

**Comment by astoeriko** [comment]
Yes, this happens on every start of the application for me. It also seems that I cannot properly close the app by clicking on the close button (instead I need to kill the process) but I don't know if that is related.

**Comment by johannesjo** [comment]
I recently made a release with some fundamental changes:
https://github.com/johannesjo/super-productivity/releases/tag/v3.2.4

The error might stem from an underlying library. As those are all updated  it might be gone with that release.

Could you please check if that is the case?

**Comment by astoeriko** [comment]
I was not able to install version 3.2.4 via snap, only the 3.2.3 version (from the edge channel). This, however, does not resolve the issue.
