### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'tagName')

### ISSUE THREAD

**Issue by mostafa20220** [johannesjo/super-productivity#2881]
### Steps to Reproduce

1. Just opening the app

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'tagName')
    at U (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3175725)
    at HTMLHtmlElement.Ft (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:3178021)
    at U.invokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
    at Object.onInvokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/main.c31d1657a38b74f0.js:1:4014140)
    at U.invokeTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7211)
    at it.runTask (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2646)
    at B.invokeTask [as invoke] (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:8349)
    at tt (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21088)
    at rt (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21387)
    at HTMLHtmlElement.gt (file:///snap/superproductivity/1737/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21656)
```

### Meta Info
META: SP7.13.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.13.2 Chrome/110.0.5481.177 Electron/23.1.2 Safari/537.36

### Actions Before Error
```
1701087047356: [Task] Add time spent 
1701087047363: [Project] Update Work End 
1701087047365: [Tag] Update Work End for Tag 
1701087047371: [Persistence] Save to DB (3) 
1701087048356: [Task] Add time spent 
1701087048363: [Project] Update Work End 
1701087048365: [Tag] Update Work End for Tag 
1701087048371: [Persistence] Save to DB (3) 
1701087049356: [Task] Add time spent 
1701087049362: [Project] Update Work End 
1701087049366: [Tag] Update Work End for Tag 
1701087049371: [Persistence] Save to DB (3) 
1701087050356: [Task] Add time spent 
1701087050363: [Project] Update Work End 
1701087050366: [Tag] Update Work End for Tag 
1701087050373: [Persistence] Save to DB (3) 
1701087051356: [Task] Add time spent 
1701087051363: [Project] Update Work End 
1701087051365: [Tag] Update Work End for Tag 
1701087051371: [Persistence] Save to DB (3) 
1701087052356: [Task] Add time spent 
1701087052359: [Project] Update Work End 
1701087052361: [Tag] Update Work End for Tag 
1701087052364: [Persistence] Save to DB (3) 
1701087053356: [Task] Add time spent 
1701087053362: [Project] Update Work End 
1701087053364: [Tag] Update Work End for Tag 
1701087053368: [Persistence] Save to DB (3) 
1701087192422: [SP_ALL] Load(import) all data 
1701087192428: [SP_ALL] All Data was loaded
```

**Comment by Jagdfalke** [comment]
Can you provide more details around what happened and how to reproduce this issue?
