### ISSUE TITLE
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'

### ISSUE THREAD

**Issue by mzch** [johannesjo/super-productivity#2901]
### Steps to Reproduce

1. Launch super-productivity on M1 Mac Studio.

### Error Log (Desktop only)

[2023-12-06 19:58:49.326] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2023-12-06 19:58:49.472] [info]  Saving backups to /
[2023-12-06 19:58:50.314] [info]  No custom styles detected at /Users/mzch/Library/Application Support/superProductivity/styles.css
[2023-12-06 19:58:50.469] [error] Frontend Error: Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
[2023-12-06 19:58:51.093] [error] Frontend Error Stack: statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
[2023-12-06 20:00:50.316] [info]  Error while backing up
[2023-12-06 20:00:50.317] [error] Error: EROFS: read-only file system, open '//2023-12-06.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at writeFileSync (node:fs:2249:35)
    at IpcMainImpl.backupData (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:55:32)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88713)
    at WebContents.emit (node:events:513:28)

### Console Output

<img width="1651" alt="ScreenShot" src="https://github.com/johannesjo/super-productivity/assets/621178/b781c427-2b96-4881-b9c7-7116eaf06878">

### Stacktrace
```
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
```

### Meta Info
META: SP7.16.0 Electron – ja – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1701860330274: [FocusMode] Set focus session elapsed time 
1701860330342: [SP_ALL] Load(import) all data 
1701860330343: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
I definitely need help with this one since I currently don't have a mac available and can't check the issue  :(

One possible cause might be the electron version or the electron builder version used. Another problem could be the `icon.icns` file inside the `build` folder.

**Comment by johannesjo** [comment]
> As a work around you can sudo touch /.VolumeIcons.icns


https://github.com/johannesjo/super-productivity/issues/2921#issuecomment-1859018015

**Comment by aadrian** [comment]
> As a work around you can sudo touch /.VolumeIcons.icns

@johannesjo  in which directory? :)

**Comment by sahansk2** [comment]
@aadrian According to this identical issue in Cypress ([link](https://github.com/cypress-io/cypress/issues/8759#issuecomment-728009798)), the solution is to touch the file in the following system directory.

```
cd /
sudo touch System/Volumes/Data/.VolumeIcon.icns
ln -s .VolumeIcon.icns System/Volumes/Data/.VolumeIcon.icns
```

Interesting to note, I didn't have to run the last command (the soft link), it just seemed to appear there. But I am also a stranger to MacOS.

**Comment by johannesjo** [comment]
Thank you @sahansk2  ! 

I tried researching electron and electron-builder for some clue why this error might occur. Didn't find anything so far :(

Any help with fixing this would be welcome!
