### ISSUE TITLE
sync doesn't work accross multiple devices

### ISSUE THREAD

**Issue by soheilred** [johannesjo/super-productivity#291]
* Version used: snap 3.1.3
* Operating System and version: Manjaro 
* Desktop Environment: Cinnamon

### Steps to Reproduce (for bugs)
1. Sync using google in one device 
2. Open the app in another device and sync

### Error
Google Drive - Error: [object Object]

I tried to re-install the app, and clean the local directory and re-log-in, but it didn't work.

**Comment by johannesjo** [comment]
Thanks for reporting. So far I am unable to reproduce the issue. Is there any more information printed in the console?

**Comment by soheilred** [comment]
> Thanks for reporting. So far I am unable to reproduce the issue. Is there any more information printed in the console?

No, it doesn't print any useful error in console when I run it from the terminal. It only prints this, which I think is irrelevant to the issue:
```
{ enabled: null, showDevTools: false, mode: 'bottom' }
[8204:0224/234014.399381:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
refreshToken 103
```
Is there any other log file that I can share with you?

**Comment by johannesjo** [comment]
Could you maybe try to open the console before the error appears (Ctrl+Shift+I)? The output should be more helpful then.

**Comment by soheilred** [comment]
> Could you maybe try to open the console before the error appears (Ctrl+Shift+I)? The output should be more helpful then.

Here is what I can see in the console:
![photo_2020-02-25_08-57-41](https://user-images.githubusercontent.com/13761049/75253652-f3882a00-57ac-11ea-8bc3-6baf06b9b388.jpg)

**Comment by johannesjo** [comment]
Thank you! Did you allow super productivity to access to your google drive data?

In case you didn't you can find more information on how to change that here: https://support.google.com/accounts/answer/3466521

**Comment by soheilred** [comment]
> Thank you! Did you allow super productivity to access to your google drive data?
> 
> In case you didn't you can find more information on how to change that here: https://support.google.com/accounts/answer/3466521

Thank you for your response.

Yes, I did give the right access to the app. When I started working with superproductivity I granted the permission to the app. And, I didn't change anything ever since. In fact, I just checked my google account, and the app was under listed under "Third-party apps with account access".

**Comment by soheilred** [comment]
The strange thing is that if I only work on one computer, it works fine. That tells me that the app has the right access to google.
But, for instance, when I finish my job on my computer and go to my laptop, it throws the error I just sent for you. Then, if I fix everything in my laptop, by removing the previous json file, and importing a backup file manually, it starts working fine on my laptop. But, again, the problem would be when I am done with my laptop and I want to start working on my pc.

**Comment by johannesjo** [comment]
Could you try one more thing please:
1. Sync one device and close the app
2. Open the app on the other device
3. Use the chrome devtools to clear cookies & cache (but NOT the indexeddb!).
4. Reload the app via Ctrl+R
5. And then try syncing again afterwards

Running two instances of the app simultaneously  won't work well at the moment unfortunately.

**Comment by soheilred** [comment]
>     3\. he chrome devtools to clear cookies & cache (but NOT the indexeddb!).

I just did that. Didn't fix it. I also went a bit further, and uninstall the app, and install it again. That also didn't fix it.

**Comment by johannesjo** [comment]
So this all worked before?

**Comment by soheilred** [comment]
> So this all worked before?
Yes! It stopped working around 4-5 days ago.

**Comment by soheilred** [comment]
I found another way of replicating the issue.
1. sync using the app and close it
2. open the web interface
3. go to settings->sync via google drive
4. login and give the permission to app
5. hit load from gdrive button

**Comment by johannesjo** [comment]
I am not able to replicate the exact error you got, but when testing inside the browser I am also encountering some issues. Might very well be that google changed something on their side. I am investigating.

**Comment by soheilred** [comment]
I want to add one more thing which I think is related to the issue. When I completely wipe out the local storage (including the indexddb file) and try to import the json file that is in my google drive, I get this:
```
Snap! A critical error occurred...
! Please Report !

Error: Uncaught (in promise): TypeError: Cannot read property 'config' of undefined TypeError: Cannot read property 'config' of undefined at e. (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2047155) at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2046504 at Object.next (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2046609) at file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2045544 at new e (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:16759) at qs (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2045318) at FileReader.Js.onload (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:2046909) at t.invoke (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:9367) at Object.onInvoke (file:///snap/superproductivity/529/resources/app.asar/dist/main.4c881b437b84d380133c.js:1:332831) at t.invoke (file:///snap/superproductivity/529/resources/app.asar/dist/polyfills.ba9ede11574490fb99be.js:1:9307)
Array.isArray (webpack:///src/app/imex/file-imex/file-imex.component.ts:39:18)
_.ops.pop (webpack:///src/app/imex/file-imex/file-imex.component.ts.pre-build-optimizer.js:31:22)
verb (webpack:///src/app/imex/file-imex/file-imex.component.ts.pre-build-optimizer.js:12:57)
step (webpack:///src/app/imex/file-imex/file-imex.component.ts.pre-build-optimizer.js:6:70)
ZoneAwarePromise (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:931:28)
new (webpack:///src/app/imex/file-imex/file-imex.component.ts.pre-build-optimizer.js:2:11)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:28:20)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:391:25)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:26256:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:390:51)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:852:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:934:16)
new (webpack:///src/app/imex/file-imex/file-imex.component.ts.pre-build-optimizer.js:2:11)
handleFileInput (webpack:///src/app/imex/file-imex/file-imex.component.ts:28:20)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:391:25)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js.pre-build-optimizer.js:26256:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:390:51)
runGuarded (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:161:46)
function (webpack:///node_modules/zone.js/dist/zone.js.pre-build-optimizer.js:144:28)
META: Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/3.1.3 Chrome/78.0.3904.130 Electron/7.1.4 Safari/537.36
Reload App
```

**Comment by johannesjo** [comment]
I spent hours trying to fix this with no success, so far :( 

To me it seems like that google changed something with their api (or possibly it's related to how chrome handles cors in recent version).

I opened up an issue. 
https://github.com/google/google-api-javascript-client/issues/600

**Comment by soheilred** [comment]
> I spent hours trying to fix this with no success, so far :(
> 
> To me it seems like that google changed something with their api (or possibly it's related to how chrome handles cors in recent version).
> 
> I opened up an issue.
> [google/google-api-javascript-client#600](https://github.com/google/google-api-javascript-client/issues/600)

Thanks for taking time and looking into the issue.

**Comment by soheilred** [comment]
Can you even open your account using the web interface from different devices? Or this is just my problem?

**Comment by johannesjo** [comment]
What do you mean by opening my account? :)

**Comment by TGMcLean** [comment]
I've had the exact same issue as @soheilred – about 4-5 days now. See it in both desktop and web. And, yeah, likely a Google issue.

**Comment by soheilred** [comment]
> What do you mean by opening my account? :)

Sorry for not being clear. I meant logging into your google using the web interface in different devices.

**Comment by johannesjo** [comment]
@soheilred I am able to log into my account just fine.

**Comment by soheilred** [comment]
> @soheilred I am able to log into my account just fine.

And using different devices? Did you try it on the same operating systems every time or you have different os's?
Isn't there any way around the synchronization, using another syncing tool, for instance onedrive or dropbox?

**Comment by johannesjo** [comment]
Works on my mobile device and on my laptop (Ubuntu). The only thing not working for me is to load files. Everything else, even saving stuff works fine.

**Comment by rajshrestha86** [comment]
Same issue: Google Drive - Error: [object Object]. Please fix it, all of my today's task are gone.

**Comment by johannesjo** [comment]
@rajshrestha86: for starters you could try raising awareness on googles end:
https://github.com/google/google-api-javascript-client/issues/600
Can't do anything about it, if they don't fix this on their side :(

**Comment by rajshrestha86** [comment]
@johannesjo Is it possible to decrypt the JSON file stored on google drive and upload it manually on the app?

**Comment by johannesjo** [comment]
@rajshrestha86 there is, but it would require a bit of fiddling around. There are also automatic backups, in case you didn't know. You can get on overview by having a look at the sync.service.ts and the persistence.service.ts. The data is not encrypted, just compressed via [lz-string](https://www.npmjs.com/package/lz-string)

**Comment by rajshrestha86** [comment]
Thank you. Got my lists back.

**Comment by johannesjo** [comment]
@rajshrestha86 That's great to hear. I am really sorry about this and I have to say that I am pretty annoyed myself. When I am done with the new upcoming cross project task list stuff, I will start looking for alternative solutions for syncing...
