### ISSUE TITLE
Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'    at statSync (node:fs:1615:3)    at t.statSync (node:electron/js2c/asar_bundle:2:4557)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40    at Array.map ()    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71    at new Promise ()

### ISSUE THREAD

**Issue by wmealing** [johannesjo/super-productivity#2922]
### Steps to Reproduce

1.  brew install --cask superproductivity
2. find superproductivty in finder
3. right click open

Presented with an error emssage

### Error Log (Desktop only)

 ✗ cat ~/Library/Logs/superProductivity/main.log
[2023-12-17 12:22:26.979] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2023-12-17 12:22:27.092] [info]  Saving backups to /
[2023-12-17 12:22:27.893] [info]  No custom styles detected at /Users/wmealing/Library/Application Support/superProductivity/styles.css
[2023-12-17 12:22:28.051] [error] Frontend Error: Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) Error: Uncaught (in promise): Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
Error: ENOENT: no such file or directory, stat '/.VolumeIcon.icns'
    at statSync (node:fs:1615:3)
    at t.statSync (node:electron/js2c/asar_bundle:2:4557)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
    at Array.map (<anonymous>)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
    at step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
    at Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
    at new Promise (<anonymous>)
    at xt (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16156)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15214
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:15322
    at m (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:2579177)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6670)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4080172)
    at U.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:6609)
    at it.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2010)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:16980
    at U.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
[2023-12-17 12:22:29.071] [error] Frontend Error Stack: statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)

### Stacktrace
```
statSync (node:fs:1615:3)
t.statSync (node:electron/js2c/asar_bundle:2:4557)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:34:40
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/backup.js:30:35
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:64:42
step (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:33:23)
Object.next (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:14:53)
/Applications/superProductivity.app/Contents/Resources/app.asar/electron/better-ipc.js:8:71
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)
function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)
constructor (webpack:///src/app/imex/local-backup/local-backup.effects.ts:38:39)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
```

### Meta Info
META: SP7.16.0 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1702779747857: [FocusMode] Set focus session elapsed time 
1702779747930: [SP_ALL] Load(import) all data 
1702779747931: [SP_ALL] All Data was loaded
```

Running:

sudo touch /.VolumeIcon.icns

Seems to work around this, The file did not exist before I touched/created it.

**Comment by wmealing** [comment]
Dupe of https://github.com/johannesjo/super-productivity/issues/2921
#2921
