### ISSUE TITLE
Error: NG0701

### ISSUE THREAD

**Issue by yus6rn6m** [johannesjo/super-productivity#2944]
### Steps to Reproduce

1.
2.
3.
4.

### Stacktrace
```
Error: NG0701
    at Fv (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4060173)
    at et (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:8049)
    at new n (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:1030598)
    at n.ɵfac [as factory] (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:1037008)
    at Kc (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4000330)
    at gI (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4032281)
    at eg (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4032361)
    at Object.Qo (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4048392)
    at uoe (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:945446)
    at k_ (file:///opt/superProductivity/resources/app.asar/dist/main.c0c9ee4d32dd70c3.js:1:4031879)
```

### Meta Info
META: SP7.16.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.16.0 Chrome/114.0.5735.289 Electron/25.9.0 Safari/537.36

### Actions Before Error
```
1703729805825: [Layout] Show AddTaskBar 
1703729818475: [Task][Issue] Add Task 
1703729818485: [Persistence] Save to DB (2) 
1703729819401: [Layout] Hide AddTaskBar (2) 
1703729928689: [Layout] ToggleShow Notes 
1703729928690: [Task] SetSelectedTask 
1703729930628: [Task] Update Task 
1703729930737: [Persistence] Save to DB 
1703729932257: [Task] Update Task 
1703729932259: [Persistence] Save to DB 
1703729933364: [Task] SetSelectedTask 
1703729933365: [Layout] Hide Notes 
1703730155648: [Global Config] Update Global Config Section 
1703730155657: [Persistence] Save to DB 
1703730162694: [Layout] Hide SideBar 
1703730180899: [FocusMode] Set focus session elapsed time 
1703730181081: [SP_ALL] Load(import) all data 
1703730181090: [SP_ALL] All Data was loaded 
1703730192417: [Task] SetSelectedTask 
1703730192422: [Layout] Hide Notes 
1703730200660: [Layout] Hide SideBar 
1703730232044: [FocusMode] Set focus session elapsed time 
1703730232434: [SP_ALL] Load(import) all data 
1703730232449: [SP_ALL] All Data was loaded 
1703730242532: [Global Config] Update Global Config Section 
1703730242558: [Persistence] Save to DB 
1703730246674: [Task] SetSelectedTask 
1703730246678: [Layout] Hide Notes 
1703730258636: [Global Config] Update Global Config Section 
1703730258656: [Persistence] Save to DB
```

**Comment by Jagdfalke** [comment]
Can you provide some more context on how to reproduce this issue?
