### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'taskIds')

### ISSUE THREAD

**Issue by Spargwy** [johannesjo/super-productivity#2962]
### Steps to Reproduce
1. Just create task after some break(about two months mb)
2. Task created but error happens

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'taskIds')
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:319644
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:4147255
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:4135967
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:4135037
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:2773055
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:2771608
    at file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:4135367
    at v.hi [as accumulator] (file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:4137771)
    at v._tryNext (file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:3828656)
    at v._next (file:///snap/superproductivity/1830/resources/app.asar/dist/main.3e399feb98f3f00c.js:1:3828557)
```

### Meta Info
META: SP7.17.2 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.17.2 Chrome/120.0.6099.109 Electron/28.1.0 Safari/537.36

### Actions Before Error
```
1704142456522: [Persistence] Save to DB (3) 
1704142457521: [Task] Add time spent 
1704142457521: [Project] Update Work End 
1704142457521: [Tag] Update Work End for Tag 
1704142457521: [Persistence] Save to DB (3) 
1704142458521: [Task] Add time spent 
1704142458523: [Project] Update Work End 
1704142458523: [Tag] Update Work End for Tag 
1704142458524: [Persistence] Save to DB (3) 
1704142459521: [Task] Add time spent 
1704142459523: [Project] Update Work End 
1704142459524: [Tag] Update Work End for Tag 
1704142459525: [Persistence] Save to DB (3) 
1704142460521: [Task] Add time spent 
1704142460522: [Project] Update Work End 
1704142460523: [Tag] Update Work End for Tag 
1704142460524: [Persistence] Save to DB (3) 
1704142461305: [Task] UnsetCurrentTask 
1704142852910: [Idle] Trigger Idle 
1704142852910: [Idle] Set idle time 
1704142852910: [Idle] Open dialog 
1704148340353: [Idle] Set idle time (5486) 
1704148340372: [Idle] Dialog result 
1704148340373: [Idle] Reset 
1704148346516: [Layout] Show AddTaskBar 
1704148352636: [Layout] Hide AddTaskBar 
1704148377765: [Layout] Show AddTaskBar 
1704148382139: [Task][Issue] Add Task 
1704148382141: [Persistence] Save to DB (2) 
1704148382141: [Task] Move tasks to other project
```

**Comment by Jagdfalke** [comment]
Can you provide more details around what happened and how to reproduce this issue?
