### ISSUE TITLE
Infinite loading at start 

### ISSUE THREAD

**Issue by MSBarbieri** [johannesjo/super-productivity#2986]
### Your Environment
```bash
nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.72, NixOS, 24.05 (Uakari), 24.05.20240115.c3e128f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

- Version used: 7.14.3  (AppImage from nixpkgs)

### Expected Behavior
after some time the application go to tasks menu.
this worked in my machine for quite some time, after some updates, stopped.

### Current Behavior
i never leave this screen (the one with productivity-tip)
![2024-01-17_12-44](https://github.com/johannesjo/super-productivity/assets/57580599/4aabb0fd-8706-4334-acf6-f99884f8b31f)

### Steps to Reproduce (for bugs)
start at nixos

### Can you reproduce this reliably?
every time i start

### Console Output
```
Service Worker Registration Error
TypeError: Cannot read properties of undefined (reading 'require')
    at /nix/store/awjv472f74l6f5cxrfa0drcif72lv32k-super-productivity-7.13.2/share/super-productivity/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:369:62
    at IpcMainImpl.<anonymous> (/nix/store/awjv472f74l6f5cxrfa0drcif72lv32k-super-productivity-7.13.2/share/super-productivity/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:323:27)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:87478)
    at WebContents.emit (node:events:517:28)
```

### Error Log (Desktop only)
```
[2024-01-17 12:53:20.398] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-01-17 12:53:20.503] [info]  Saving backups to /home/hefestus/.config/superProductivity/backups
[2024-01-17 12:53:20.941] [info]  No custom styles detected at /home/hefestus/.config/superProductivity/styles.css
```

**Comment by johannesjo** [comment]
Most recent version is 7.17.2. Also nixpkgs is not maintained by me.
