### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'cancel')

### ISSUE THREAD

**Issue by thrabash** [johannesjo/super-productivity#2992]
### Steps to Reproduce

1. Open superprod app on Android (device: Redmi Note 11s 5G, android 13, miui 14)
2. Start tracking any task
3. Wait some seconds
4. Voilà

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'cancel')
    at J$ (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:2187365)
    at qp._tapNext (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:2792237)
    at qp._next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:190001)
    at qp.next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3800866)
    at b._next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3821181)
    at b.next (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3800866)
    at C.NI [as work] (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:265519)
    at C._execute (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3822723)
    at C.execute (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3822568)
    at _.flush (https://app.super-productivity.com/main.63765dab1008d0bc.js:1:3823627)
```

### Meta Info
META: SP7.17.2 Browser – es-ES – Linux aarch64 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Actions Before Error
```
1705905709740: [Tag] Update Work End for Tag (2) 
1705905709752: [Persistence] Save to DB (4) 
1705905710697: [Task] Add time spent 
1705905710720: [Project] Update Work End 
1705905710753: [Tag] Update Work End for Tag (2) 
1705905710778: [Persistence] Save to DB (4) 
1705905711698: [Task] Add time spent 
1705905711732: [Project] Update Work End 
1705905711781: [Tag] Update Work End for Tag (2) 
1705905711801: [Persistence] Save to DB (4) 
1705905712697: [Task] Add time spent 
1705905712728: [Project] Update Work End 
1705905712764: [Tag] Update Work End for Tag (2) 
1705905712781: [Persistence] Save to DB (4) 
1705905713697: [Task] Add time spent 
1705905713727: [Project] Update Work End 
1705905713756: [Tag] Update Work End for Tag (2) 
1705905713779: [Persistence] Save to DB (4) 
1705905714317: [Task] Delete Task 
1705905714328: [Persistence] Save to DB (3) 
1705905714329: [Task] SetCurrentTask 
1705905714695: [Task] Add time spent 
1705905714708: [Project] Update Work End 
1705905714718: [Tag] Update Work End for Tag (2) 
1705905714728: [Persistence] Save to DB (4) 
1705905715697: [Task] Add time spent 
1705905715729: [Project] Update Work End 
1705905715763: [Tag] Update Work End for Tag (2) 
1705905715785: [Persistence] Save to DB (4)
```

**Comment by thrabash** [comment]
I really apreciate it, thank you very much. I absolutely love this app. Cheers!
