### ISSUE TITLE
Snap leads to `Error: Cannot find module '../dialog'`

### ISSUE THREAD

**Issue by johannesjo** [johannesjo/super-productivity#30]
@HarmtH 

## Your Environment

* Version used: 1.4.2 (snap)
* Operating System and version: Ubuntu 17.10
* Desktop Environment: Gnome

## Expected Behavior
Should not throw an error.

## Current Behavior
I don't know if this is the same issue, but if I try to start the application, while it is still running (window is closed, but icon still in the notification area), it won't show the main window. This is with the Ubuntu snap package under Ubuntu 17.10.
```
blackbox ~% superproductivity 
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/snap/superproductivity/5/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/snap/superproductivity/5/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/snap/superproductivity/5/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by johannesjo** [comment]
This is likely related to #27.

**Comment by johannesjo** [comment]
Does installing some dependencies help: `apt-get install libatk-adaptor libgail-common`? I just tried it with a fresh ubuntu install and only the canberra-gtk-module is missing there (which doesn't seem to be required anyway).

**Comment by johannesjo** [comment]
Also I am curios if maybe the deb package is working for you. Could you check if installing the dependencies doesn't help?

**Comment by Shdulin** [comment]
I faced the same issue on Fedora 27
```
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/snap/superproductivity/5/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/snap/superproductivity/5/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/snap/superproductivity/5/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)
```

**Comment by johannesjo** [comment]
Could you try installing the newest version? The issue should be fixed there.

**Comment by v6ak** [comment]
I've tried the latest version on Debian 9, but it fails the same way:

    ~% superproductivity 
    module.js:487
        throw err;
        ^
    
    Error: Cannot find module '../dialog'
        at Module._resolveFilename (module.js:485:15)
        at Function.Module._resolveFilename (/snap/superproductivity/5/resources/electron.asar/common/reset-    search-paths.js:35:12)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.get [as dialog] (/snap/superproductivity/5/resources/electron.asar/browser/api/exports    /electron.js:11:16)
    at process.<anonymous> (/snap/superproductivity/5/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)

**Comment by johannesjo** [comment]
Thanks for reporting! I'll try to look into this weekend.

**Comment by v6ak** [comment]
However, deleting ~/snap has fixed the issue. I hope it will not occur again.

**Comment by johannesjo** [comment]
That's... Interesting! Deleting snap in your home folder fixed the issue??

**Comment by v6ak** [comment]
Exactly. I have no idea what has caused the nondeterminism. But I can experiment. The Debian is a freshly created template-based VM in QubesOS, so I can easily create a new VM based on the same template.

**Comment by v6ak** [comment]
Hmm, so I have tried to create 10 disposable VMs and install and run SP using the following command:

    qvm-run '$dispvm' 'sudo snap install superproductivity && while true; do /snap/bin/superproductivity; done'

I've also tried to close all the instances of SP (so they were restarted due to the while cycle), still cannot reproduce.

But I can reproduce it simply by trying to run two instances. Well, if I had read the original post better… Also, removing the ~/snap “helps”, because it allows to run a second instance, probably due to removing some pidfile/lockfile…

**Comment by johannesjo** [comment]
Weird definitely! Thanks for digging into this. I'm pretty new to snap and I don't really use it myself, so I'm unfortunately not able to do much with that info atm, but I'm sure it will be very useful if someone else encounters that error. Until then I hope that this more of a rare edge case ;)
