### ISSUE TITLE
Error: task data not ready

### ISSUE THREAD

**Issue by tempookian** [johannesjo/super-productivity#3004]
### Steps to Reproduce

1. Setup google calendar sync
2. Hover over an event
3. Click on add event as task 
4. Hover over the created task
5. Click on Show/Hide additional info

### Meta Info
META: SP8.0.0-rc.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.0-rc.0 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
Error: task data not ready
    at SwitchMapSubscriber.project (http://localhost:4200/main.js:41070:27)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.js:103908:21)
    at SwitchMapSubscriber.next (http://localhost:4200/vendor.js:99597:12)
    at MergeMapSubscriber.notifyNext (http://localhost:4200/vendor.js:103132:22)
    at SimpleInnerSubscriber._next (http://localhost:4200/vendor.js:100055:17)
    at SimpleInnerSubscriber.next (http://localhost:4200/vendor.js:99597:12)
    at ReplaySubject.next (http://localhost:4200/vendor.js:99337:17)
    at ReplaySubject.nextInfiniteTimeWindow (http://localhost:4200/vendor.js:99147:11)
    at set task [as task] (http://localhost:4200/main.js:41153:34)
    at setInputsForProperty (http://localhost:4200/vendor.js:205902:29)
```

### Actions Before Error
```
1706777181683: [SimpleCounter] Set SimpleCounter Counter On 
1706777181683: [Persistence] Save to DB 
1706777181908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777181910: [Persistence] Save to DB 
1706777182908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777182911: [Persistence] Save to DB 
1706777183915: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777183916: [Persistence] Save to DB 
1706777184908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777184912: [Persistence] Save to DB 
1706777185909: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777185912: [Persistence] Save to DB 
1706777186908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777186912: [Persistence] Save to DB 
1706777187588: [Task][Issue] Add Task 
1706777187593: [Persistence] Save to DB (2) 
1706777187595: [Task] Schedule 
1706777187597: [Persistence] Save to
[Uploading ANONYMIZED-super-productivity-crash-user-data-export (1).json…]()
 DB (2) 
1706777187597: [Task] Update Task 
1706777187598: [Persistence] Save to DB 
1706777187909: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777187910: [Persistence] Save to DB 
1706777188908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777188911: [Persistence] Save to DB 
1706777189908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777189910: [Persistence] Save to DB 
1706777190908: [SimpleCounter] Increase SimpleCounter Counter Today 
1706777190911: [Persistence] Save to DB 
1706777191224: [Task] SetSelectedTask 
1706777191226: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Thank you very much! This will be fixed with the next release.
