### ISSUE TITLE
DB Init Error

### ISSUE THREAD

**Issue by halloichbingunnar** [johannesjo/super-productivity#3006]
### Your Environment

- Version used: 8.0 rc, x64 Setup
- Operating System and version: Win11

### Current Behavior

Instead of starting the app, I get an DB INIT Error. Then, after a while, the interface is loaded, but the app is not able to load a sync. 

### Can you reproduce this reliably?

I have tried reinstalling and using the non-x64 version, but same error. 
It's also not possible to go back to 7.17 ("update the app before sync")

### Console Output
``` 
VM6:92 preload script loading complete
is-mouse-primary.ts:17 Object
action-logger.reducer.ts:11 @ngrx/store/init Object
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
action-logger.reducer.ts:11 @ngrx/effects/init Object
persistence.service.ts:336 LOAD COMPLETE true
action-logger.reducer.ts:11 [FocusMode] Set focus session elapsed time Object
calendar-integration.effects.ts:90 this._currentlyShownBanners$ Array(0)
calendar-integration.effects.ts:157 SHOW BANNER
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
database.service.ts:73 Database initialization failed
(anonymous) @ database.service.ts:73
database.service.ts:74 _lastParams Object
(anonymous) @ database.service.ts:74
database.service.ts:75 Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at n.<anonymous> (indexed-db-adapter.service.ts:55:13)
    at Generator.throw (<anonymous>)
    at f (index.js:85:78)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
(anonymous) @ database.service.ts:75
global-error-handler.class.ts:24 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: Error: UnknownError: Internal error opening backing store for indexedDB.open.
Error: Error: UnknownError: Internal error opening backing store for indexedDB.open.
    at n.<anonymous> (database.service.ts:78:13)
    at Generator.throw (<anonymous>)
    at f (ngx-translate-core.mjs:967:7)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at xt (zone.js:1211:31)
    at xt (zone.js:1165:17)
    at zone.js:1278:17
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at U.invokeTask (zone.js:405:60)
    at it.runTask (zone.js:178:47)
    at w (zone.js:585:35)
    at B.invokeTask [as invoke] (zone.js:491:21)
    at tt (zone.js:1661:18)
(anonymous) @ global-error-handler.class.ts:24
action-logger.ts:39 Last actions before error: Array(15)0: "1706789947969: [FocusMode] Set focus session elapsed time"1: "1706790043503: [Global Config] Update Global Config Section"2: "1706790043510: [Persistence] Save to DB"3: "1706790043511: [Dropbox] Trigger Auth Dialog"4: "1706790097877: [Global Config] Update Global Config Section"5: "1706790097883: [Persistence] Save to DB"6: "1706790108271: [Global Config] Update Global Config Section"7: "1706790108276: [Persistence] Save to DB"8: "1706790203529: [FocusMode] Set focus session elapsed time"9: "1706790268959: [Global Config] Update Global Config Section"10: "1706790268969: [Persistence] Save to DB"11: "1706790268969: [Dropbox] Trigger Auth Dialog"12: "1706790283004: [Global Config] Update Global Config Section"13: "1706790283009: [Persistence] Save to DB"14: "1706791472412: [FocusMode] Set focus session elapsed time (7)"length: 15[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
persistence.service.ts:336 LOAD COMPLETE false
app.component.ts:332 0 out of 253977 MiB used (0%)
app.component.ts:303 Persistence already allowed
persistence.service.ts:336 LOAD COMPLETE false
action-logger.reducer.ts:11 [Layout] Hide SideBar Object
persistence.service.ts:336 LOAD COMPLETE false
```

### Error Log (Desktop only)

```
[2023-11-20 08:50:11.274] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2023-11-20 08:50:11.624] [info]  Saving backups to C:\Users\Gunnar\AppData\Roaming\superProductivity/backups
[2023-11-20 08:50:12.812] [info]  No custom styles detected at C:\Users\Gunnar\AppData\Roaming\superProductivity/styles.css
[2023-11-20 08:50:31.741] [info]  close, isQuiting: true
```

**Comment by johannesjo** [comment]
Do you have any backups available? Best course of action might be a fresh import of data. Not really sure what could have caused this, apart from maybe two versions of the app trying to access the data at the same time?

**Comment by halloichbingunnar** [comment]
I have tried importing a backup file, but it does not load. The app takes a long while without reacting after selecting the import file, and now is stuck with the loading screen

**Comment by halloichbingunnar** [comment]
I reinstalled super productivity and ran the setup as administrator. Now it works again!

**Comment by johannesjo** [comment]
That is great to hear! I am sorry for the issue you encountered. Not really sure why it  might have happened or how to prevent it... :(

**Comment by AyoItsYas** [comment]
Having the same issue importing a backup does not work, I am using appimage launcher to integrate and run the appimage, running as administrator (sudo) works I think the issue is with files that are not cleared when a backup is restored as the config paths and the caching paths change. Clearing these files manually and restoring a backup works.
