### ISSUE TITLE
Error when changing project

### ISSUE THREAD

**Issue by matthewdunngeon** [johannesjo/super-productivity#302]
### Your Environment

* Version used: 
* Operating System and version:
* Desktop Environment: 
* Browser Name and version: 

### Steps to Reproduce (for bugs)

I created one project at the beginning.
Then add some tasks.
Then started first task.
At that moment decided to add another project.
Created new project.
When clicked the new project from the list, this error occurred. 
Regards

### Console Output

Error: Project was changing while attempting to do something
t.call [as _tapNext] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/features/tasks/store/task-db.effects.ts:55:17)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:66:34)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
t.call [as _next] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:407:28)
t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16)

### Error Log (Desktop only)

[2020-03-20 07:49:39.511] [error] Frontend Error: Error: Project was changing while attempting to do something
    at t.call [as _tapNext] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/features/tasks/store/task-db.effects.ts:55:17)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:66:34)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
    at t.call [as _next] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:407:28)
    at t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16) Error: Project was changing while attempting to do something
    at t.call [as _tapNext] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/features/tasks/store/task-db.effects.ts:55:17)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:66:34)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
    at t.call [as _next] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:407:28)
    at t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16)
[2020-03-20 07:49:39.623] [error] Frontend Error Stack: Error: Project was changing while attempting to do something
    at t.call [as _tapNext] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/features/tasks/store/task-db.effects.ts:55:17)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:66:34)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
    at t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
    at t.call [as _next] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:407:28)
    at t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16) t.call [as _tapNext] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/features/tasks/store/task-db.effects.ts:55:17)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:45:27)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:66:34)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/filter.js:38:30)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:53:18)
t.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subject.js:47:25)
t.call [as _next] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/store/__ivy_ngcc__/fesm5/store.js:407:28)
t.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:192:16)
[2020-03-20 07:49:39.644] [error] Frontend Error: Error: Error: Project was changing while attempting to do something
    at e.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:127:13)
    at t.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/effects/__ivy_ngcc__/fesm5/effects.js:158:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/catchError.js:34:31)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:48:30) Error: Error: Project was changing while attempting to do something
    at e.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:127:13)
    at t.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/effects/__ivy_ngcc__/fesm5/effects.js:158:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/catchError.js:34:31)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:48:30)
[2020-03-20 07:49:39.790] [error] Frontend Error Stack: Error: Error: Project was changing while attempting to do something
    at e.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:127:13)
    at t.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/effects/__ivy_ngcc__/fesm5/effects.js:158:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/catchError.js:34:31)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:26)
    at t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
    at t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:48:30) e.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:127:13)
t.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/@ngrx/effects/__ivy_ngcc__/fesm5/effects.js:158:26)
t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/catchError.js:34:31)
t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:61:26)
t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
t._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:79:26)
t.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/Subscriber.js:59:18)
t._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/webpack:/node_modules/rxjs/_esm5/internal/operators/tap.js:48:30)

**Comment by johannesjo** [comment]
Thank you very much for reporting. I'll check this as soon as I can.

**Comment by johannesjo** [comment]
I found the problem and will provide a fix shortly.
