### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by AlissonSantos95** [johannesjo/super-productivity#3039]
### Your Environment
Docker Portrainer 

- Version used: Docker
- Operating System and version: Ubuntu server

- Browser Name and version: Chrome lateste

### Expected Behavior
Dropbox sync configuration 

### Current Behavior
Opens an white screen with red borders with an error

### Steps to Reproduce (for bugs)

It happens everytime
1.Select Settings
2.Sync
3.Active sync and select Dropbox fron the list and put 30m to sync
4.Bug

### Can you reproduce this reliably?
Yes

### Console Output
`TypeError: Cannot read properties of undefined (reading 'digest')
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:45:12)FormlyMaterialModule (webpack:///node_modules/@ngx-formly/material/fesm2015/ngx-formly-material.js:16:6)invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26343:32)scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1211:30)makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:16)function (webpack:///node_modules/zone.js/fesm2015/zone.js:1134:32)FormlyMaterialModule (webpack:///node_modules/@ngx-formly/material/fesm2015/ngx-formly-material.js:16:6)invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:25)onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26356:32)invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:371:51)run (webpack:///node_modules/zone.js/fesm2015/zone.js:134:42)zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1275:35)invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30)
META: SP8.0.0 Browser – pt-BR – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

Yes
`GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of undefined (reading 'digest')
    at generate-pkce-codes.ts:17:31
    at generate-pkce-codes.ts:34:24
    at Generator.next (<anonymous>)
    at dialog-get-and-enter-auth-code.component.ts:11:1
    at new i (zone.js:1429:21)
    at WG (dialog-get-and-enter-auth-code.component.ts:11:1)
    at zde (generate-pkce-codes.ts:33:72)
    at generate-pkce-codes.ts:42:31
    at Generator.next (<anonymous>)
    at dialog-get-and-enter-auth-code.component.ts:11:1`

`GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: TypeError: Cannot read properties of undefined (reading 'digest')
Error: TypeError: Cannot read properties of undefined (reading 'digest')
    at n.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at u (ngx-formly-material.js:16:7)
    at W.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at W.invoke (zone.js:371:52)
    at lt.run (zone.js:134:43)
    at zone.js:1275:36
    at W.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at bt (zone.js:1211:31)
    at zone.js:1118:17
    at zone.js:1134:33
    at u (ngx-formly-material.js:16:7)
    at W.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at W.invoke (zone.js:371:52)
    at lt.run (zone.js:134:43)
    at zone.js:1275:36
    at W.invokeTask (zone.js:406:31)`

`Unhandled Promise rejection: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of undefined (reading 'digest')
Error: TypeError: Cannot read properties of undefined (reading 'digest')
    at n.<anonymous> (http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:2643492)
    at Generator.next (<anonymous>)
    at u (http://IP:PORT/main.bdf656bd9c1d525b.js:1:2640753)
    at W.invoke (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:6670)
    at Object.onInvoke (http://IP:PORT/main.bdf656bd9c1d525b.js:1:4172716)
    at W.invoke (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:6609)
    at lt.run (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:2010)
    at http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:16973
    at W.invokeTask (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:7289)
    at Object.onInvokeTask (http://IP:PORT/main.bdf656bd9c1d525b.js:1:4172529) ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of undefined (reading 'digest')
Error: TypeError: Cannot read properties of undefined (reading 'digest')
    at n.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at u (ngx-formly-material.js:16:7)
    at W.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at W.invoke (zone.js:371:52)
    at lt.run (zone.js:134:43)
    at zone.js:1275:36
    at W.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
    at n.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at u (ngx-formly-material.js:16:7)
    at W.invoke (zone.js:372:26)
    at lt.run (zone.js:134:43)
    at zone.js:1275:36
    at W.invokeTask (zone.js:406:31)
    at lt.runTask (zone.js:178:47)
    at G (zone.js:585:35)
    at k.invokeTask [as invoke] (zone.js:491:21) Error: Error: Uncaught (in promise): Error: TypeError: Cannot read properties of undefined (reading 'digest')
Error: TypeError: Cannot read properties of undefined (reading 'digest')
    at n.<anonymous> (http://IP:PORT/main.bdf656bd9c1d525b.js:1:2643492)
    at Generator.next (<anonymous>)
    at u (http://IP:PORT/main.bdf656bd9c1d525b.js:1:2640753)
    at W.invoke (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:6670)
    at Object.onInvoke (http://IP:PORT/main.bdf656bd9c1d525b.js:1:4172716)
    at W.invoke (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:6609)
    at lt.run (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:2010)
    at http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:16973
    at W.invokeTask (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:7289)
    at Object.onInvokeTask (http://IP:PORT/main.bdf656bd9c1d525b.js:1:4172529)
    at n.<anonymous> (http://IP:PORT/main.bdf656bd9c1d525b.js:1:2643492)
    at Generator.next (<anonymous>)
    at u (http://IP:PORT/main.bdf656bd9c1d525b.js:1:2640753)
    at W.invoke (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:6670)
    at lt.run (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:2010)
    at http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:16973
    at W.invokeTask (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:7289)
    at lt.runTask (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:2646)
    at G (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:9346)
    at k.invokeTask [as invoke] (http://IP:PORT/polyfills.73ebf1f8f690ae69.js:1:8378)`

### Meta Info
META: SP8.0.0 Browser – pt-BR – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'digest')
    at http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1146994
    at http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1147015
    at Generator.next (<anonymous>)
    at http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1146852
    at new i (http://172.16.20.249:8092/polyfills.73ebf1f8f690ae69.js:1:18636)
    at WG (http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1146587)
    at zde (http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1146876)
    at http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1150099
    at Generator.next (<anonymous>)
    at http://172.16.20.249:8092/main.bdf656bd9c1d525b.js:1:1146852
```

### Actions Before Error
```
1708104594734: [Improvement] Clear Hidden Improvements 
1708104594734: [Improvement] Delete multiple Improvements 
1708104616285: [Task] SetSelectedTask 
1708104616285: [Layout] Hide Notes 
1708104629207: [Task] Delete Task 
1708104629209: [Persistence] Save to DB (2) 
1708104629209: [Task] UnsetCurrentTask 
1708104629210: [Persistence] Save to DB 
1708104686295: [Global Config] Update Global Config Section 
1708104686297: [Persistence] Save to DB 
1708104686297: [Dropbox] Trigger Auth Dialog 
1708104779297: [FocusMode] Set focus session elapsed time 
1708104779341: [SP_ALL] Load(import) all data 
1708104779345: [SP_ALL] All Data was loaded 
1708104789553: [Global Config] Update Global Config Section 
1708104789555: [Persistence] Save to DB 
1708104789556: [Dropbox] Trigger Auth Dialog 
1708105213096: [Layout] Hide SideBar (2) 
1708105601959: [FocusMode] Set focus session elapsed time 
1708105602007: [SP_ALL] Load(import) all data 
1708105602009: [SP_ALL] All Data was loaded 
1708105605699: [Global Config] Update Global Config Section 
1708105605702: [Persistence] Save to DB 
1708105605702: [Dropbox] Trigger Auth Dialog 
1708105609410: [FocusMode] Set focus session elapsed time 
1708105609448: [SP_ALL] Load(import) all data 
1708105609450: [SP_ALL] All Data was loaded 
1708105626837: [Global Config] Update Global Config Section 
1708105626839: [Persistence] Save to DB 
1708105626839: [Dropbox] Trigger Auth Dialog
```

**Comment by johannesjo** [comment]
This is likely because you're starting the app in an insecure context. https is required to authenticate dropbox.
