### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by key-ur** [johannesjo/super-productivity#3051]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP8.0.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.0 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'length')
    at n.isCollapsedIssueSummary (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:2165811)
    at mDe (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:2164016)
    at zS (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4137602)
    at Ag (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4136244)
    at Dg (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4136675)
    at Ag (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4136700)
    at Dg (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4136675)
    at Ag (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4136700)
    at q_ (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4143387)
    at Bx (file:///snap/superproductivity/1865/resources/app.asar/dist/main.072f23bff10f4821.js:1:4137120)
```

### Actions Before Error
```
1707971477779: [Idle] Reset (9) 
1707971496359: [Task] Toggle start 
1707971496362: [Persistence] Save to DB 
1707971496363: [Task] SetCurrentTask 
1707971496368: [Pomodoro] Start Pomodoro 
1707971496779: [Task] Add time spent 
1707971496787: [Project] Update Work Start 
1707971496796: [Project] Update Work End 
1707971496798: [Tag] Update Work Start for Tag 
1707971496814: [Tag] Update Work End for Tag 
1707971496818: [Persistence] Save to DB (5) 
1707971497746: [Task] Add time spent 
1707971497754: [Project] Update Work End 
1707971497758: [Tag] Update Work End for Tag 
1707971497775: [Persistence] Save to DB (3) 
1707971498603: [Task] Toggle start 
1707971498605: [Persistence] Save to DB 
1707971498606: [Task] UnsetCurrentTask 
1707971498608: [Pomodoro] Pause Pomodoro 
1707971530721: [Task] SetSelectedTask 
1707971530723: [Layout] Hide Notes 
1707977083686: [Idle] Reset (679) 
1707977207927: [Task] UnsetCurrentTask 
1707977207929: [Pomodoro] Pause Pomodoro 
1707977207931: [SimpleCounter] Turn off all simple counters 
1708820014800: [FocusMode] Set focus session elapsed time 
1708820015334: [SP_ALL] Load(import) all data 
1708820015343: [SP_ALL] All Data was loaded 
1708820037065: [Task] SetSelectedTask 
1708820037084: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Can  you maybe provide a little more info on what happened?

**Comment by johannesjo** [comment]
Can  you maybe provide a little more info on what happened?

**Comment by Jagdfalke** [comment]
Probably related to #3052.
