### ISSUE TITLE
Calendar Provider Error: TypeError: Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by d4ms3c** [johannesjo/super-productivity#3055]
Error loading Outlook Calendar (also in Timeline). I also tried to re-create link but nothing change.

### Console Output
TypeError: Cannot read properties of null (reading 'parent')
    at C.addSubcomponent (ical.js:2628:21)
    at Object.updateTimezones (ical.js:101:14)
    at get-relevant-events-from-ical.ts:106:19
    at get-relevant-events-from-ical.ts:14:35
    at g.project (calendar-integration.service.ts:34:9)
    at g._next (map.js:29:35)
    at g.next (Subscriber.js:49:18)
    at g._next (map.js:35:26)
    at g.next (Subscriber.js:49:18)
    at g._next (filter.js:33:30)
(anonymous) @ calendar-integration.service.ts:42

### Meta Info
META: SP8.0.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.0 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

**Comment by Jamesau0** [comment]
Im getting this error, I think it is similar. 

![Image](https://github.com/user-attachments/assets/894a3555-e2d3-4e4d-a40c-3b24667c2c36)
