### ISSUE TITLE
Your data seems to be damaged ("Inconsistent Task State: Lonely Sub Task)

### ISSUE THREAD

**Issue by sripwoud** [johannesjo/super-productivity#3059]
### Your Environment

- Version used: [superproductivity-bin  8.0.0-1  AUR](https://aur.archlinux.org/packages/superproductivity-bin) (same happened to me with official AppImage)
- Operating System and version: Manjaro Linux 22.1.2 (Linux 6.6.16-2-MANJARO)
- Desktop Environment: sway
- ~~Browser Name and version:~~ 

### Expected Behavior

superproductivity should start and show my tasks.

### Current Behavior
superproductivity doesn't start.
A pop shows very briefly the following message and closes itself. I don't have time to click 'OK"
![image](https://github.com/johannesjo/super-productivity/assets/38692952/3b7fc0e8-f6e8-44ff-8c88-a7daa9adada2)

### Steps to Reproduce (for bugs)

1. `rm -rf ~/.local/superProductivity`
2. settings > Sync & Export > Import/Export > Import from file
3. import [`super-productivity-backup-anon.json`](https://gist.githubusercontent.com/sripwoud/14f6f110fad72ba790040feb3340aa63/raw/105b9831a12d3fd42c754b0ba63e8996ef5b574e/super-productivity-backup-anon.json)
4. Finish Day > save and go home > aye aye! shutdown
5. Try to start superProductivity again
6. Message pop up is shown

If instead of step 4 I just quit the app (tray icon > quit), I can start superProductivity without problems again.

### Can you reproduce this reliably?

Yes

### Console Output

Can't access it as the app doesn't start

### Error Log (Desktop only)
<details>
  <summary>`main.log`</summary>

```
[2024-02-27 10:03:47.241] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-02-27 10:03:47.359] [info]  Saving backups to /home/sripwoud/.config/superProductivity/backups
[2024-02-27 10:03:47.989] [info]  No custom styles detected at /home/sripwoud/.config/superProductivity/styles.css
[2024-02-27 10:03:48.042] [info]  Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:03:48.043] [error] Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:03:48.043] [info]  Additional Error info:  Ctrl+Shift+X
[2024-02-27 10:04:04.693] [info]  Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:04:04.693] [error] Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:04:04.693] [info]  Additional Error info:  Ctrl+Shift+X
[2024-02-27 10:04:18.666] [info]  close, isQuiting: true
[2024-02-27 10:04:27.313] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-02-27 10:04:27.439] [info]  Saving backups to /home/sripwoud/.config/superProductivity/backups
[2024-02-27 10:04:28.052] [info]  No custom styles detected at /home/sripwoud/.config/superProductivity/styles.css
[2024-02-27 10:04:28.074] [info]  Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:04:28.074] [error] Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/opt/superProductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /opt/superProductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/opt/superProductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:517:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77364)
    at WebContents.emit (node:events:517:28)
[2024-02-27 10:04:28.075] [info]  Additional Error info:  Ctrl+Shift+X
[2024-02-27 10:05:23.855] [info]  close, isQuiting: true
```
</details>

**Comment by sripwoud** [comment]
Thanks for the reactivity!
Is there a way I can help test the fix?
I am not sure how I should build the app from source in this case?
with https://github.com/johannesjo/super-productivity/blob/69c5a70ef0efb6f12e71547a43244edfda14534f/package.json#L81 ?

**Comment by johannesjo** [comment]
There is an edge channel for the snap releases. Apart from that building from the sources is the only way. There is a short guide in the readme how to do it.

**Comment by sripwoud** [comment]
I confirm I haven't experienced this issue anymore since I have been using [8.0.1](https://github.com/johannesjo/super-productivity/blob/master/CHANGELOG.md#801-2024-03-04). :ok_hand:
