### ISSUE TITLE
Error: No tag undefined

### ISSUE THREAD

**Issue by mitgitumgekippt** [johannesjo/super-productivity#3060]
### Steps to Reproduce

0. Application is running in the background. Only the "Today" Tab is opened. I create new tasks and mark others as done. I flip between desktops inbetween. 
1. I tried to unlist a task from "Today". But the icon for it was not there in the "Today"-Tab
2. I removed the tag, by right-clicking and remove it from the tag list
3. Error comes up

### Console Output

[Task] Add time spent Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:208 __trigger_sync__ task
sync.effects.ts:137 sync(effect)..... Object
sync-provider.service.ts:186 Object
sync-provider.service.ts:546 WebDAV PRE1: ↔ Same Rev "9298eefa104f0164b386abc3349cce04"
persistence.service.ts:336 LOAD COMPLETE false
dev-error.ts:7 Task without project or tag
$o @ dev-error.ts:7
Tl @ is-valid-app-data.util.ts:51
(anonymous) @ is-valid-app-data.util.ts:122
Z9 @ is-valid-app-data.util.ts:119
yA @ is-valid-app-data.util.ts:42
(anonymous) @ persistence.service.ts:156
u @ persistence.const.ts:199
invoke @ zone.js:372
onInvoke @ core.mjs:26356
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26343
invokeTask @ zone.js:405
runTask @ zone.js:178
w @ zone.js:585
invokeTask @ zone.js:491
tt @ zone.js:1661
rt @ zone.js:1692
gt @ zone.js:1725
Show 14 more frames
Show less
dev-error.ts:7 Invalid data => RETRY getValidCompleteData
$o @ dev-error.ts:7
(anonymous) @ persistence.service.ts:161
u @ persistence.const.ts:199
invoke @ zone.js:372
onInvoke @ core.mjs:26356
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26343
invokeTask @ zone.js:405
runTask @ zone.js:178
w @ zone.js:585
invokeTask @ zone.js:491
tt @ zone.js:1661
rt @ zone.js:1692
gt @ zone.js:1725
Show 14 more frames
Show less
sync-provider.service.ts:130 __error during sync__
sync-provider.service.ts:131 Error: Unable to get valid app data
    at n.<anonymous> (persistence.service.ts:164:15)
    at Generator.next (<anonymous>)
    at u (persistence.const.ts:199:6)
    at U.invoke (zone.js:372:26)
    at Object.onInvoke (core.mjs:26356:33)
    at U.invoke (zone.js:371:52)
    at it.run (zone.js:134:43)
    at zone.js:1275:36
    at U.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26343:33)
(anonymous) @ sync-provider.service.ts:131
f @ local-file-sync-electron.service.ts:12
invoke @ zone.js:372
onInvoke @ core.mjs:26356
invoke @ zone.js:371
run @ zone.js:134
(anonymous) @ zone.js:1275
invokeTask @ zone.js:406
onInvokeTask @ core.mjs:26343
invokeTask @ zone.js:405
runTask @ zone.js:178
w @ zone.js:585
invokeTask @ zone.js:491
tt @ zone.js:1661
rt @ zone.js:1692
gt @ zone.js:1725
Show 14 more frames
Show less
action-logger.reducer.ts:11 [Task] Add time spent Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
sync-trigger.service.ts:208 __trigger_sync__ task
action-logger.reducer.ts:11 [Task] Add time spent Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object

### Meta Info
META: SP8.0.0 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.0 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
Error: No tag undefined
    at file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:280763
    at file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4233947
    at Xr (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4233467)
    at vn (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4234380)
    at file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4234004
    at Xr (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4233467)
    at g.project (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4232810)
    at g._next (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:3918066)
    at g.next (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:3906187)
    at Ne._subscribe (file:///opt/superProductivity/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:3898942)
```

### Actions Before Error
```
1709055634684: [Task] Add time spent 
1709055634691: [Tag] Update Work End for Tag 
1709055634694: [Persistence] Save to DB (2) 
1709055635045: [Task] SetSelectedTask 
1709055635049: [Layout] Hide Notes 
1709055635681: [Task] Add time spent 
1709055635689: [Tag] Update Work End for Tag 
1709055635692: [Persistence] Save to DB (2) 
1709055636684: [Task] Add time spent 
1709055636691: [Tag] Update Work End for Tag 
1709055636694: [Persistence] Save to DB (2) 
1709055636723: [Task] SetSelectedTask 
1709055637681: [Task] Add time spent 
1709055637685: [Tag] Update Work End for Tag 
1709055637688: [Persistence] Save to DB (2) 
1709055638703: [Task] Add time spent 
1709055638709: [Tag] Update Work End for Tag 
1709055638711: [Persistence] Save to DB (2) 
1709055639710: [Task] Add time spent 
1709055639715: [Tag] Update Work End for Tag 
1709055639716: [Persistence] Save to DB (2) 
1709055640689: [Task] Add time spent 
1709055640693: [Tag] Update Work End for Tag 
1709055640695: [Persistence] Save to DB (2) 
1709055641681: [Task] Add time spent 
1709055641683: [Tag] Update Work End for Tag 
1709055641684: [Persistence] Save to DB (2) 
1709055642539: [Task] Update Task Tags 
1709055642543: [Persistence] Save to DB (2)
```

**Comment by mitgitumgekippt** [comment]
I only created the issue, because the application asked to do so. If you think that the error is irrelevant, feel free to close it.
