### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'subTasks')

### ISSUE THREAD

**Issue by galois-grothen** [johannesjo/super-productivity#3062]
[ANONYMIZED-super-productivity-crash-user-data-export.json](https://github.com/johannesjo/super-productivity/files/14432787/ANONYMIZED-super-productivity-crash-user-data-export.json)
### Steps to Reproduce

1. Clicked on a tag to get a list of items. 

### Console Output

See attached. 

### Meta Info
META: SP8.0.0 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.0 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'subTasks')
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:299146
    at Array.forEach (<anonymous>)
    at Pp (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:299122)
    at g.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:578043)
    at g._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:3918000)
    at g.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:3906121)
    at S.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:3903871)
    at S.nextInfiniteTimeWindow (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:3902444)
    at Object.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:187078)
    at p.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.059230447973e241.js:1:3907935)
```

### Actions Before Error
```
1709117014307: [Persistence] Save to DB 
1709117026119: [Task] Update Task 
1709117026123: [Persistence] Save to DB 
1709117048625: [Task] SetSelectedTask 
1709117048628: [Layout] Hide Notes 
1709117057898: [Task] Update Task 
1709117057903: [Persistence] Save to DB 
1709117067997: [Task] SetSelectedTask (2) 
1709117067998: [Layout] Hide Notes 
1709117072435: [Task] Update Task 
1709117072438: [Persistence] Save to DB 
1709117074943: [Task] Update Task 
1709117074956: [Persistence] Save to DB 
1709117082900: [Task] Update Task 
1709117082903: [Persistence] Save to DB 
1709117143215: [Task] Update Task 
1709117143219: [Persistence] Save to DB 
1709117168335: [Task] Update Task 
1709117168343: [Persistence] Save to DB 
1709117174203: [Task] SetSelectedTask 
1709117174239: [Layout] Hide Notes 
1709117215319: [Task] Move to archive 
1709117215326: [Persistence] Save to DB (3) 
1709117215326: [Task] UnsetCurrentTask 
1709117215356: [Persistence] Save to DB 
1709117243698: [WorkContext] Set Active Work Context 
1709117243735: [Task] SetSelectedTask 
1709117245166: [WorkContext] Set Active Work Context 
1709117245168: [Task] SetSelectedTask 
1709117246273: [WorkContext] Set Active Work Context
```

**Comment by galois-grothen** [comment]
My main intention is to simply log this error. Feel free to comment if this issue makes sense to you? Had anyone else experienced this 'issue' as well?

**Comment by johannesjo** [comment]
Thank you very much for reporting this. 

I think you accidentally(?) posted  your real data which contained your dropbox token which gives access to the super productivity data in your dropbox. You might want to invalidate this token (https://stackoverflow.com/questions/43705630/how-do-i-revoke-generated-access-tokens-for-dropbox-applications).

After importing your data – which had some inconsistency in them – I was prompted if i would like to fix it. 

Probably hard to reconstruct what caused this in the first place. Or do you have any pointers by any chance?
