### ISSUE TITLE
IndexSizeError: Failed to execute 'setStart' on 'Range': The offset 36 is larger than the node's length (35).

### ISSUE THREAD

**Issue by rrfranks** [johannesjo/super-productivity#3080]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP8.0.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.1 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
Error: Failed to execute 'setStart' on 'Range': The offset 36 is larger than the node's length (35).
    at n._insertAtCursorChromium (file:///snap/superproductivity/1878/resources/app.asar/dist/main.2271e764c39109d8.js:1:1873387)
    at n._insertAtCursor (file:///snap/superproductivity/1878/resources/app.asar/dist/main.2271e764c39109d8.js:1:1872555)
    at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (file:///snap/superproductivity/1878/resources/app.asar/dist/main.2271e764c39109d8.js:1:1871907)
    at HTMLDivElement.pt (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:11666)
    at U.invokeTask (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290)
    at Object.onInvokeTask (file:///snap/superproductivity/1878/resources/app.asar/dist/main.2271e764c39109d8.js:1:4187193)
    at U.invokeTask (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7211)
    at it.runTask (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2646)
    at B.invokeTask [as invoke] (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:8349)
    at tt (file:///snap/superproductivity/1878/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21088)
```

### Actions Before Error
```
1710342745860: [Task] SetSelectedTask 
1710342746028: [Bookmark] Load Bookmark State 
1710342746029: [Project] Load Project related Data Success 
1710342746030: [Improvement] Clear Hidden Improvements 
1710342746033: [Improvement] Delete multiple Improvements 
1710342748789: [Layout] Show AddTaskBar 
1710342764241: [Task][Issue] Add Task 
1710342764247: [Persistence] Save to DB (2) 
1710342767569: [Layout] Hide AddTaskBar 
1710342771227: [Task] SetSelectedTask 
1710342771228: [Layout] Hide Notes 
1710342799936: [Task] Schedule 
1710342799942: [Persistence] Save to DB (2) 
1710342799943: [Task] Update Task 
1710342799946: [Project] Auto Move Task from today to backlog 
1710342799949: [Persistence] Save to DB (2) 
1710342835657: [TaskRepeatCfg][Task] Add TaskRepeatCfg to Task 
1710342835661: [Persistence] Save to DB (2) 
1710342852519: [Task] Update Task 
1710342852521: [Persistence] Save to DB 
1710342860795: [Task] Update Task 
1710342860797: [Persistence] Save to DB 
1710342870023: [Task] Update Task Tags 
1710342870029: [Persistence] Save to DB (2) 
1710342871697: [WorkContext] Set Active Work Context 
1710342871873: [Task] SetSelectedTask 
1710342875404: [WorkContext] Set Active Work Context 
1710342875407: [Task] SetSelectedTask 
1710342959083: [Task] Update Task 
1710342959086: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Can you possibly provide a bit more detail on what happened before the error?

**Comment by Jagdfalke** [comment]
Probably related to #3104.
