### ISSUE TITLE
Superproductivity won't launch correctly

### ISSUE THREAD

**Issue by Cyber-Syntax** [johannesjo/super-productivity#3114]
### Your Environment

- Version used: appimage 8.0.0 - 8.0.1, aur version
- Operating System and version: arch 6.8.2 
- Desktop Environment: qtile

### Current Behavior

I could able to use superproductivity on my desktop with last linux kernel. I can't able to see superproductivity screen on my thinkpad E16 g1. I was copy all my home directory from desktop to my laptop and I get dunst notification about my tasks on my first launch superproductivity but unable to see screen. Also, I was try to delete config and start from scratch with downgraded appimage and even aur package. No one worked.

I have been able to use super productivity on desktop with recent linux kernel. I can't see the super productivity screen on Thinkpad E16 g1. I was copy my entire home directory from desktop to laptop and when I first boot up super productivity I can see my tasks notification from dunst but no screen. I also tried to clean config with appimage and aur package but didn't work.

### Steps to Reproduce (for bugs)

1. Try to open app
2. App goes systray but won't show screen even when click show app from systray.
3. Try for 8.0.0 version and aur versions.
4. Experience same behavior.

### Can you reproduce this reliably?

Yes

### Console Output
```
./super-productivity.AppImage                                                                                                     ─╯
Start app...
18:26:49.668 › { enabled: null, showDevTools: false, mode: 'bottom' }
Gtk-Message: 18:26:49.721: Failed to load module "pk-gtk-module"
Saving backups to /home/cyber-syntax/.config/superProductivity/backups
18:26:50.097 › Saving backups to /home/cyber-syntax/.config/superProductivity/backups
18:26:50.952 › No custom styles detected at /home/cyber-syntax/.config/superProductivity/styles.css
18:26:50.974 › Avilable Backup Files:  [
  '/home/cyber-syntax/.config/superProductivity/backups/2024-03-31.json'
]
```

### Error Log (Desktop only)

sudo and --no-sandbox started console log:
```
sudo superproductivity --no-sandbox ─╯
Start app…
18:16:37.240 › { enabled: null, showDevTools: false, mode: ‘bottom’ }
[18741:0331/181637.272680:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
[18741:0331/181637.272748:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
[18741:0331/181637.272760:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
[18741:0331/181637.272772:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[18793:0331/181637.306071:ERROR:egl_util.cc(44)] Failed to load GLES library: /opt/superProductivity/libGLESv2.so: /opt/superProductivity/libGLESv2.so: cannot open shared object file: Permission denied
[18793:0331/181637.308674:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[18741:0331/181637.344653:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
Saving backups to /root/.config/superProductivity/backups
18:16:37.344 › Saving backups to /root/.config/superProductivity/backups
[18741:0331/181637.345642:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are “tcp” and on UNIX “unix”)
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[18815:0331/181637.354478:ERROR:egl_util.cc(44)] Failed to load GLES library: /opt/superProductivity/libGLESv2.so: /opt/superProductivity/libGLESv2.so: cannot open shared object file: Permission denied
[18815:0331/181637.355303:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
[18741:0331/181637.355581:ERROR:object_proxy.cc(577)] Failed to call method: org.freedesktop.DBus.NameHasOwner: object_path= /org/freedesktop/DBus: unknown error type:
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[18824:0331/181637.369108:ERROR:egl_util.cc(44)] Failed to load GLES library: /opt/superProductivity/libGLESv2.so: /opt/superProductivity/libGLESv2.so: cannot open shared object file: Permission denied
[18824:0331/181637.370678:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[18839:0331/181637.376884:ERROR:egl_util.cc(44)] Failed to load GLES library: /opt/superProductivity/libGLESv2.so: /opt/superProductivity/libGLESv2.so: cannot open shared object file: Permission denied
[18839:0331/181637.378194:ERROR:viz_main_impl.cc(196)] Exiting GPU process due to errors during initialization
Authorization required, but no authorization protocol specified

Authorization required, but no authorization protocol specified

[18846:0331/181637.389220:ERROR:x11_software_bitmap_presenter.cc(141)] XGetWindowAttributes failed for window 29360131
18:16:37.784 › No custom styles detected at /root/.config/superProductivity/styles.css
```

This error does not reoccur anymore but I got this error once.

```
[2024-02-28 18:43:12.794] [error] Frontend Error: Error: Failed to execute 'setStart' on 'Range': The offset 57 is larger than the node's length (56). at n._insertAtCursorChromium (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1872003) at n._insertAtCursor (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1871171) at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1870523) at HTMLDivElement.pt (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:11666) at U.invokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) at Object.onInvokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4185709) at U.invokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7211) at it.runTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2646) at B.invokeTask [as invoke] (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:8349) at tt (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21088) Error: Failed to execute 'setStart' on 'Range': The offset 57 is larger than the node's length (56). at n._insertAtCursorChromium (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1872003) at n._insertAtCursor (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1871171) at e.onpaste [as __zone_symbol__ON_PROPERTYpaste] (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:1870523) at HTMLDivElement.pt (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:11666) at U.invokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7290) at Object.onInvokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/main.cfea6b39dd7d63d8.js:1:4185709) at U.invokeTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:7211) at it.runTask (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:2646) at B.invokeTask [as invoke] (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:8349) at tt (file:///tmp/.mount_super-mxfTBQ/resources/app.asar/dist/polyfills.8db5726c6ae16cfe.js:1:21088) [2024-02-28 18:43:13.777] [error] Frontend Error Stack: setStart (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:235:10) window.getSelection (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:160:11) ev.clipboardData.getData (webpack:///src/app/ui/edit-on-click/content-editable-on-click.directive.ts:109:13) listener.call (webpack:///node_modules/zone.js/fesm2015/zone.js:766:38) invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:30) onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.mjs:26343:32) invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:405:59) task._transitionTo (webpack:///node_modules/zone.js/fesm2015/zone.js:178:46) invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:487:33) callback (webpack:///node_modules/zone.js/fesm2015/zone.js:1661:17) [2024-02-28 18:46:02.865] [info] close, isQuiting: undefined [2024-02-28 18:46:02.868] [info] Actions to wait for [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT', 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
```

systemd-coredump:

```
systemd-coredump[3508]: [🡕] Process 2796 (superproductivi) of user 1000 dumped core.
                                                    
                                                    Stack trace of thread 2801:
                                                    #0  0x000064d90fb964e0 n/a (/superproductivity + 0x61e64e0)
                                                    #1  0x000064d90fb2b9de n/a (/superproductivity + 0x617b9de)
                                                    #2  0x000064d90fbfe4b5 n/a (/superproductivity + 0x624e4b5)
                                                    #3  0x000064d910ed73f3 n/a (/superproductivity + 0x75273f3)
                                                    #4  0x000064d910e14b4a n/a (/superproductivity + 0x7464b4a)
                                                    #5  0x000064d910e14c0e n/a (/superproductivity + 0x7464c0e)
                                                    #6  0x000064d910e0d40f n/a (/superproductivity + 0x745d40f)
                                                    #7  0x000064d910e140ea n/a (/superproductivity + 0x74640ea)
                                                    #8  0x000064d90fa23121 n/a (/superproductivity + 0x6073121)
                                                    #9  0x000064d90fa2acd5 n/a (/superproductivity + 0x607acd5)
                                                    #10 0x000064d90fa32e82 n/a (/superproductivity + 0x6082e82)
                                                    #11 0x000064d90fa2000b n/a (/superproductivity + 0x607000b)
                                                    #12 0x000064d90beb928f n/a (/superproductivity + 0x250928f)
                                                    #13 0x000064d90fa458af n/a (/superproductivity + 0x60958af)
                                                    #14 0x000064d90c1b2290 n/a (/superproductivity + 0x2802290)
                                                    #15 0x000064d90c277c66 n/a (/superproductivity + 0x28c7c66)
                                                    #16 0x000064d90c26e4e9 n/a (/superproductivity + 0x28be4e9)
                                                    #17 0x000064d90c2732cb n/a (/superproductivity + 0x28c32cb)
                                                    #18 0x000064d90c25d4da n/a (/superproductivity + 0x28ad4da)
                                                    #19 0x000064d90c260d27 n/a (/superproductivity + 0x28b0d27)
                                                    #20 0x000064d90c24da91 n/a (/superproductivity + 0x289da91)
                                                    #21 0x000064d90c1b665f n/a (/superproductivity + 0x280665f)
                                                    #22 0x000064d90c1cb98f n/a (/superproductivity + 0x281b98f)
                                                    #23 0x000064d90f75e657 n/a (/superproductivity + 0x5dae657)
                                                    #24 0x000064d90f878ec4 n/a (/superproductivity + 0x5ec8ec4)
                                                    #25 0x000064d90f75eae3 n/a (/superproductivity + 0x5daeae3)
                                                    #26 0x000064d90f709115 n/a (/superproductivity + 0x5d59115)
                                                    #27 0x000064d90f6ce63a n/a (/superproductivity + 0x5d1e63a)
                                                    #28 0x000064d90f72aad8 n/a (/superproductivity + 0x5d7aad8)
                                                    #29 0x000064d91116481f n/a (/superproductivity + 0x77b481f)
                                                    #30 0x000064d90f72ac51 n/a (/superproductivity + 0x5d7ac51)
                                                    #31 0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #32 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #33 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2800:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfda65 pthread_cond_timedwait (libc.so.6 + 0x8aa65)
                                                    #2  0x000064d90f73dfb8 n/a (/superproductivity + 0x5d8dfb8)
                                                    #3  0x000064d90f763bd2 n/a (/superproductivity + 0x5db3bd2)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f7231d1 n/a (/superproductivity + 0x5d731d1)
                                                    #6  0x000064d90f723dd2 n/a (/superproductivity + 0x5d73dd2)
                                                    #7  0x000064d90f723a1d n/a (/superproductivity + 0x5d73a1d)
                                                    #8  0x000064d90f723930 n/a (/superproductivity + 0x5d73930)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2807:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfd750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x000064d90f73dea5 n/a (/superproductivity + 0x5d8dea5)
                                                    #3  0x000064d90f763ba4 n/a (/superproductivity + 0x5db3ba4)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f723224 n/a (/superproductivity + 0x5d73224)
                                                    #6  0x000064d90f723dd2 n/a (/superproductivity + 0x5d73dd2)
                                                    #7  0x000064d90f723a1d n/a (/superproductivity + 0x5d73a1d)
                                                    #8  0x000064d90f723930 n/a (/superproductivity + 0x5d73930)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2808:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfd750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x000064d90f73dea5 n/a (/superproductivity + 0x5d8dea5)
                                                    #3  0x000064d90f763ba4 n/a (/superproductivity + 0x5db3ba4)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f723224 n/a (/superproductivity + 0x5d73224)
                                                    #6  0x000064d90f723dd2 n/a (/superproductivity + 0x5d73dd2)
                                                    #7  0x000064d90f723a1d n/a (/superproductivity + 0x5d73a1d)
                                                    #8  0x000064d90f723930 n/a (/superproductivity + 0x5d73930)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2831:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfd750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x000064d90f73dea5 n/a (/superproductivity + 0x5d8dea5)
                                                    #3  0x000064d90f763ba4 n/a (/superproductivity + 0x5db3ba4)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f723224 n/a (/superproductivity + 0x5d73224)
                                                    #6  0x000064d90f723ba7 n/a (/superproductivity + 0x5d73ba7)
                                                    #7  0x000064d90f723a1d n/a (/superproductivity + 0x5d73a1d)
                                                    #8  0x000064d90f723930 n/a (/superproductivity + 0x5d73930)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2802:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfd750 pthread_cond_wait (libc.so.6 + 0x8a750)
                                                    #2  0x000064d90f73dea5 n/a (/superproductivity + 0x5d8dea5)
                                                    #3  0x000064d90f763ba4 n/a (/superproductivity + 0x5db3ba4)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f723224 n/a (/superproductivity + 0x5d73224)
                                                    #6  0x000064d90f723dd2 n/a (/superproductivity + 0x5d73dd2)
                                                    #7  0x000064d90f723a1d n/a (/superproductivity + 0x5d73a1d)
                                                    #8  0x000064d90f723930 n/a (/superproductivity + 0x5d73930)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2796:
                                                    #0  0x00007435c7dfaebe n/a (libc.so.6 + 0x87ebe)
                                                    #1  0x00007435c7dfda65 pthread_cond_timedwait (libc.so.6 + 0x8aa65)
                                                    #2  0x000064d90f73dfb8 n/a (/superproductivity + 0x5d8dfb8)
                                                    #3  0x000064d90f763bd2 n/a (/superproductivity + 0x5db3bd2)
                                                    #4  0x000064d90f6e9803 n/a (/superproductivity + 0x5d39803)
                                                    #5  0x000064d90f6a7835 n/a (/superproductivity + 0x5cf7835)
                                                    #6  0x000064d90f709115 n/a (/superproductivity + 0x5d59115)
                                                    #7  0x000064d90f6ce63a n/a (/superproductivity + 0x5d1e63a)
                                                    #8  0x000064d90f02a71a n/a (/superproductivity + 0x567a71a)
                                                    #9  0x000064d90c193de2 n/a (/superproductivity + 0x27e3de2)
                                                    #10 0x000064d90c1951a4 n/a (/superproductivity + 0x27e51a4)
                                                    #11 0x000064d90c1929bd n/a (/superproductivity + 0x27e29bd)
                                                    #12 0x000064d90c192ac6 n/a (/superproductivity + 0x27e2ac6)
                                                    #13 0x000064d90be7d469 n/a (/superproductivity + 0x24cd469)
                                                    #14 0x00007435c7d98cd0 n/a (libc.so.6 + 0x25cd0)
                                                    #15 0x00007435c7d98d8a __libc_start_main (libc.so.6 + 0x25d8a)
                                                    #16 0x000064d90ba8702a _start (/superproductivity + 0x20d702a)
                                                    
                                                    Stack trace of thread 2806:
                                                    #0  0x00007435c7e6e0bf __poll (libc.so.6 + 0xfb0bf)
                                                    #1  0x000064d90f741907 n/a (/superproductivity + 0x5d91907)
                                                    #2  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #3  0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #4  0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    
                                                    Stack trace of thread 2799:
                                                    #0  0x00007435c7e7be66 epoll_wait (libc.so.6 + 0x108e66)
                                                    #1  0x000064d90f87b2d0 n/a (/superproductivity + 0x5ecb2d0)
                                                    #2  0x000064d90f8790b6 n/a (/superproductivity + 0x5ec90b6)
                                                    #3  0x000064d90f75e99c n/a (/superproductivity + 0x5dae99c)
                                                    #4  0x000064d90f709115 n/a (/superproductivity + 0x5d59115)
                                                    #5  0x000064d90f6ce63a n/a (/superproductivity + 0x5d1e63a)
                                                    #6  0x000064d90f72aad8 n/a (/superproductivity + 0x5d7aad8)
                                                    #7  0x000064d90f71541d n/a (/superproductivity + 0x5d6541d)
                                                    #8  0x000064d90f72ac51 n/a (/superproductivity + 0x5d7ac51)
                                                    #9  0x000064d90f73e709 n/a (/superproductivity + 0x5d8e709)
                                                    #10 0x00007435c7dfe55a n/a (libc.so.6 + 0x8b55a)
                                                    #11 0x00007435c7e7ba3c n/a (libc.so.6 + 0x108a3c)
                                                    ELF object binary architecture: AMD x86-64
░░ Subject: Process 2796 (superproductivi) dumped core
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)
░░ 
░░ Process 2796 (superproductivi) crashed and dumped core.
```

**Comment by Cyber-Syntax** [comment]
I wasn't able to saw error window when I use max workspace on Qtile. I was able to saw error when I use monadtall - it was config errors, they just corrupted when I use rsync - and fixed it.
