### ISSUE TITLE
Status bar in the dock icon is flickering while in Focus Mode

### ISSUE THREAD

**Issue by vsaravind01** [johannesjo/super-productivity#3131]
### Your Environment

- Version used: 8.0.1
- Operating System and version: MacOS 14.4
- Desktop Environment: 
- Browser Name and version: NA (Desktop version)

### Expected Behavior

The icon in the dock should display the progress properly while in Focus mode.

### Current Behavior

The status bar in the dock icon is flickering while in Focus mode.

### Steps to Reproduce (for bugs)

Create a task and start focus mode on the Desktop app.

### Can you reproduce this reliably?

Yes, this is occurring every time when I switch to Focus mode.

### Error Log (Desktop only)

```
[2024-04-06 19:48:17.400] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-04-06 19:48:17.539] [info]  Saving backups to /Users/vsaravind/Library/Application Support/superProductivity/backups
[2024-04-06 19:48:18.145] [info]  No custom styles detected at /Users/vsaravind/Library/Application Support/superProductivity/styles.css
[2024-04-06 19:53:34.545] [info]  ERR: Sync error while getting meta for super-productivity-sync.json
[2024-04-06 19:53:34.546] [error] Error: ENOENT: no such file or directory, open 'super-productivity-sync.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2238)
    at readFileSync (node:fs:471:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9777)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/local-file-sync.js:24:35
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77758)
    at WebContents.emit (node:events:517:28)
[2024-04-06 19:53:41.092] [info]  ERR: Sync error while writing to super-productivity-sync.json
[2024-04-06 19:53:41.092] [error] Error: EROFS: read-only file system, open 'super-productivity-sync.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2238)
    at writeFileSync (node:fs:2324:35)
    at /Applications/superProductivity.app/Contents/Resources/app.asar/electron/local-file-sync.js:12:36
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:77758)
    at WebContents.emit (node:events:517:28)
[2024-04-06 22:21:46.708] [info]  close, isQuiting: true
[2024-04-06 22:21:48.838] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-04-06 22:21:48.995] [info]  Saving backups to /Users/vsaravind/Library/Application Support/superProductivity/backups
[2024-04-06 22:21:49.568] [info]  No custom styles detected at /Users/vsaravind/Library/Application Support/superProductivity/styles.css
[2024-04-06 22:22:16.413] [warn]  getSettingsCb no callbacks left
```

**Comment by vsaravind01** [comment]
https://github.com/johannesjo/super-productivity/assets/63002244/4739430a-30a1-4b87-8010-0d2c38f09cf5

**Comment by Jagdfalke** [comment]
Thank you for the detailed report. This seems to be a Mac-specific issue as I cannot reproduce it on either Linux or Windows.
