### ISSUE TITLE
Error: NG0701

### ISSUE THREAD

**Issue by lowprize** [johannesjo/super-productivity#3152]
Second time throw error, while I want plan a task

### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP8.0.5 Browser – cs-CZ – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36

### Stacktrace
```
Error: NG0701
    at QC (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4158459)
    at je (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:8784)
    at new n (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:1027534)
    at n.ɵfac [as factory] (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:1033944)
    at vl (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4098613)
    at Zx (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4130567)
    at _C (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4130647)
    at Object.os (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4146678)
    at cle (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:942377)
    at VE (https://app.super-productivity.com/main.e358da4cf5dc9d12.js:1:4130165)
```

### Actions Before Error
```
1713343861836: [Layout] Hide Notes 
1713343862581: [Task] Add time spent 
1713343862582: [Tag] Update Work End for Tag (2) 
1713343862583: [Persistence] Save to DB (3) 
1713343863581: [Task] Add time spent 
1713343863582: [Tag] Update Work End for Tag (2) 
1713343863582: [Persistence] Save to DB (3) 
1713343864581: [Task] Add time spent 
1713343864584: [Tag] Update Work End for Tag (2) 
1713343864585: [Persistence] Save to DB (3) 
1713343865581: [Task] Add time spent 
1713343865583: [Tag] Update Work End for Tag (2) 
1713343865584: [Persistence] Save to DB (3) 
1713343866581: [Task] Add time spent 
1713343866583: [Tag] Update Work End for Tag (2) 
1713343866584: [Persistence] Save to DB (3) 
1713343867581: [Task] Add time spent 
1713343867582: [Tag] Update Work End for Tag (2) 
1713343867583: [Persistence] Save to DB (3) 
1713343868581: [Task] Add time spent 
1713343868582: [Tag] Update Work End for Tag (2) 
1713343868582: [Persistence] Save to DB (3) 
1713343869581: [Task] Add time spent 
1713343869584: [Tag] Update Work End for Tag (2) 
1713343869585: [Persistence] Save to DB (3) 
1713343870581: [Task] Add time spent 
1713343870583: [Tag] Update Work End for Tag (2) 
1713343870584: [Persistence] Save to DB (3) 
1713343870682: [Task] SetSelectedTask 
1713343870683: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Could you provide a little bit more info on what happened before the error was shown?
