### ISSUE TITLE
Error: Error retrieving icon :drag_handle! Http failure response for https://task.derong.synology.me/assets/icons/drag-handle.svg: 404 OK

### ISSUE THREAD

**Issue by samderong** [johannesjo/super-productivity#3206]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP8.0.5 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

### Stacktrace
```
Error: Error retrieving icon :drag_handle! Http failure response for https://task.derong.synology.me/assets/icons/drag-handle.svg: 404 OK
    at p._error (https://task.derong.synology.me/main.8517425cb519773e.js:1:522530)
    at p.__tryOrUnsub (https://task.derong.synology.me/main.8517425cb519773e.js:1:3901968)
    at p.error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3901436)
    at E._error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900415)
    at E.error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900212)
    at v._error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900415)
    at v.error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900212)
    at y._error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900415)
    at y.error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900212)
    at y._error (https://task.derong.synology.me/main.8517425cb519773e.js:1:3900415)
```

### Actions Before Error
```
1713183778386: [FocusMode] Set focus session elapsed time 
1713183778574: [SP_ALL] Load(import) all data 
1713183778575: [SP_ALL] All Data was loaded 
1713183784606: [FocusMode] Set focus session elapsed time 
1713183784766: [SP_ALL] Load(import) all data 
1713183784767: [SP_ALL] All Data was loaded 
1713933870967: [FocusMode] Set focus session elapsed time 
1713933871170: [SP_ALL] Load(import) all data 
1713933871172: [SP_ALL] All Data was loaded 
1713934727176: [FocusMode] Set focus session elapsed time 
1713934727344: [SP_ALL] Load(import) all data 
1713934727345: [SP_ALL] All Data was loaded 
1713935025543: [FocusMode] Set focus session elapsed time 
1713935025825: [SP_ALL] Load(import) all data 
1713935025827: [SP_ALL] All Data was loaded 
1715769281654: [FocusMode] Set focus session elapsed time 
1715769281866: [SP_ALL] Load(import) all data 
1715769281867: [SP_ALL] All Data was loaded 
1717028779688: [FocusMode] Set focus session elapsed time 
1717028779798: [SP_ALL] Load(import) all data 
1717028779800: [SP_ALL] All Data was loaded 
1717030049748: [FocusMode] Set focus session elapsed time 
1717030049992: [SP_ALL] Load(import) all data 
1717030049993: [SP_ALL] All Data was loaded 
1717289798514: [FocusMode] Set focus session elapsed time 
1717289798726: [SP_ALL] Load(import) all data 
1717289798729: [SP_ALL] All Data was loaded 
1717296688329: [FocusMode] Set focus session elapsed time 
1717296688559: [SP_ALL] Load(import) all data 
1717296688561: [SP_ALL] All Data was loaded
```

**Comment by Jagdfalke** [comment]
Can you provide more details what you did before this error occured or even how to reproduce it?
