### ISSUE TITLE
Error: NG0701

### ISSUE THREAD

**Issue by betelne** [johannesjo/super-productivity#3262]
### Steps to Reproduce
1. Set language to Czech (no problem in English)
2. Go to Inbox
3. Show additional info for specific task
4. Click on Schedule task

### Error Log (Desktop only)
```
[2024-07-17 20:22:52.756] [error] Frontend Error: Error: NG0701
    at xM (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4068484)
    at Ye (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:8187)
    at new n (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1039341)
    at n.ɵfac [as factory] (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1045751)
    at Sl (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4008863)
    at UP (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040741)
    at qC (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040819)
    at Object.cs (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4056771)
    at Mce (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:954184)
    at Ok (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040343) Error: NG0701
    at xM (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4068484)
    at Ye (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:8187)
    at new n (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1039341)
    at n.ɵfac [as factory] (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1045751)
    at Sl (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4008863)
    at UP (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040741)
    at qC (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040819)
    at Object.cs (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4056771)
    at Mce (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:954184)
    at Ok (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040343)
[2024-07-17 20:22:53.749] [error] Frontend Error Stack: getLocaleData (webpack:///node_modules/@angular/core/fesm2015/core.mjs:19329:10)
getLocaleFirstDayOfWeek (webpack:///node_modules/@angular/common/fesm2015/common.mjs:1123:33)
getLocaleFirstDayOfWeek (webpack:///node_modules/ngx-date-time-picker-schedule/fesm2015/ngx-date-time-picker-schedule.js:4263:31)
fac (webpack:///node_modules/ngx-date-time-picker-schedule/fesm2015/ngx-date-time-picker-schedule.js:4621:80)
isFactory (webpack:///node_modules/@angular/core/fesm2015/core.mjs:3513:43)
isComponentDef (webpack:///node_modules/@angular/core/fesm2015/core.mjs:12717:26)
createDirectivesInstances (webpack:///node_modules/@angular/core/fesm2015/core.mjs:12141:29)
isDirectiveHost (webpack:///node_modules/@angular/core/fesm2015/core.mjs:15373:8)
OwlCalendarComponent_owl_date_time_month_view_18_Template (webpack:///node_modules/ngx-date-time-picker-schedule/fesm2015/ngx-date-time-picker-schedule.js:26:4)
setSelectedIndex (webpack:///node_modules/@angular/core/fesm2015/core.mjs:12112:8)
```

### Console Output
1. global-error-handler.class.ts:24 GLOBAL_ERROR_HANDLER Error: NG0701
2. indexed-db-adapter.service.ts:68 Unhandled Promise rejection: Error: NG0701 ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: NG0701
3. global-error-handler.class.ts:34 Frontend Error: Error: NG0701
4. global-error-handler.class.ts:38 Frontend Error Stack: getLocaleData

### Meta Info
META: SP8.0.10 Electron – cs – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.10 Chrome/122.0.6261.156 Electron/29.4.2 Safari/537.36

### Stacktrace
```
Error: NG0701
    at xM (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4068484)
    at Ye (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:8187)
    at new n (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1039341)
    at n.ɵfac [as factory] (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:1045751)
    at Sl (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4008863)
    at UP (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040741)
    at qC (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040819)
    at Object.cs (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4056771)
    at Mce (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:954184)
    at Ok (file:///opt/superProductivity/resources/app.asar/dist/main.3db797d21aeafa5b.js:1:4040343)
```

### Actions Before Error
```
1721213346409: [Project] Update Work End 
1721213346410: [Tag] Update Work End for Tag 
1721213346411: [Persistence] Save to DB (3) 
1721213347409: [Task] Add time spent 
1721213347411: [Project] Update Work End 
1721213347412: [Tag] Update Work End for Tag 
1721213347413: [Persistence] Save to DB (3) 
1721213348408: [Task] Add time spent 
1721213348411: [Project] Update Work End 
1721213348411: [Tag] Update Work End for Tag 
1721213348412: [Persistence] Save to DB (3) 
1721213348905: [Task] Update Task 
1721213348969: [Persistence] Save to DB 
1721213348970: [Task] UnsetCurrentTask 
1721213596568: [Tag] Update Break Time for Tag 
1721213596569: [Persistence] Save to DB 
1721239942644: [WorkContext] Set Active Work Context 
1721239942667: [Task] SetSelectedTask 
1721239942761: [Bookmark] Load Bookmark State 
1721239942762: [Project] Load Project related Data Success 
1721239942762: [Improvement] Clear Hidden Improvements 
1721239942763: [Improvement] Delete multiple Improvements 
1721239949148: [Layout] Show SearchBar 
1721239969111: [Layout] Hide SearchBar 
1721239969923: [Layout] Show AddTaskBar 
1721239972009: [Task][Issue] Add Task 
1721239972011: [Persistence] Save to DB (2) 
1721239972738: [Layout] Hide AddTaskBar 
1721239984707: [Task] SetSelectedTask 
1721239984708: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Thank you! Will be fixed with the next release!
