### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'subTasks')

### ISSUE THREAD

**Issue by milakendell** [johannesjo/super-productivity#3272]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP8.0.1 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/8.0.1 Chrome/120.0.6099.227 Electron/28.2.0 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'subTasks')
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:299348
    at Array.forEach (<anonymous>)
    at Pp (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:299324)
    at g.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:578245)
    at g._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:3919550)
    at g.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:3907671)
    at S.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:3905421)
    at S.nextInfiniteTimeWindow (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:3903994)
    at Object.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:187280)
    at p.__tryOrUnsub (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2271e764c39109d8.js:1:3909485)
```

### Actions Before Error
```
1721394388332: [Task][Issue] Add Task 
1721394388341: [Persistence] Save to DB (2) 
1721394390216: [Layout] Hide AddTaskBar 
1721394509399: [Layout] Toggle AddTaskBar 
1721394512516: [Task][Issue] Add Task 
1721394512518: [Persistence] Save to DB (2) 
1721394540829: [Task][Issue] Add Task 
1721394540831: [Persistence] Save to DB (2) 
1721394542254: [Layout] Hide AddTaskBar 
1721395338586: [Task] Update Task Tags 
1721395338602: [Persistence] Save to DB (2) 
1721395339404: [Task] Update Task Tags 
1721395339408: [Persistence] Save to DB (2) 
1721395340381: [Task] Update Task Tags 
1721395340384: [Persistence] Save to DB (2) 
1721395342606: [Task] Update Task Tags 
1721395342608: [Persistence] Save to DB (2) 
1721395343429: [Task] Update Task Tags 
1721395343433: [Persistence] Save to DB (2) 
1721395344779: [Task] Update Task Tags 
1721395344781: [Persistence] Save to DB (2) 
1721395347357: [Task] Update Task Tags 
1721395347359: [Persistence] Save to DB (2) 
1721395389399: [WorkContext] Set Active Work Context 
1721395389482: [Task] SetSelectedTask 
1721395389630: [Bookmark] Load Bookmark State 
1721395389630: [Project] Load Project related Data Success 
1721395389631: [Improvement] Clear Hidden Improvements 
1721395389631: [Improvement] Delete multiple Improvements 
1721395393095: [WorkContext] Set Active Work Context
```

**Comment by johannesjo** [comment]
Can you reproduce this with the newest version 9.0.5?
