### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by lsewcx** [johannesjo/super-productivity#3276]
### Steps to Reproduce
I found the bug
![image](https://github.com/user-attachments/assets/051e818f-bd29-4d3c-93f2-1085906dc645)

### Meta Info
META: SP9.0.3 Browser – zh-CN – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'type')
    at fEt (https://app.super-productivity.com/main-XULEE4CZ.js:384:5010)
    at ike (https://app.super-productivity.com/main-XULEE4CZ.js:384:4042)
    at P4.project (https://app.super-productivity.com/main-XULEE4CZ.js:386:5959)
    at P4._next (https://app.super-productivity.com/main-XULEE4CZ.js:79:20305)
    at P4.next (https://app.super-productivity.com/main-XULEE4CZ.js:79:2372)
    at e$.debouncedNext (https://app.super-productivity.com/main-XULEE4CZ.js:79:34222)
    at f0.lAe (https://app.super-productivity.com/main-XULEE4CZ.js:79:34375)
    at f0._execute (https://app.super-productivity.com/main-XULEE4CZ.js:79:13221)
    at f0.execute (https://app.super-productivity.com/main-XULEE4CZ.js:79:13066)
    at i.flush (https://app.super-productivity.com/main-XULEE4CZ.js:79:14456)
```

### Actions Before Error
```
1721442490839: [Global Config] Update Global Config Section 
1721442490856: [Persistence] Save to DB 
1721442490857: [Dropbox] Trigger Auth Dialog 
1721442517412: [Persistence] Save to DB (14) 
1721442517426: [SP_ALL] Load(import) all data 
1721442517428: [Persistence] Remove from DB 
1721442521000: [WorkContext] Set Active Work Context 
1721442521001: [Task] SetSelectedTask 
1721442531419: [WorkContext] Set Active Work Context 
1721442531451: [Task] SetSelectedTask 
1721442531552: [Bookmark] Load Bookmark State 
1721442531553: [Project] Load Project related Data Success 
1721442531554: [Improvement] Clear Hidden Improvements 
1721442531555: [Improvement] Delete multiple Improvements 
1721442534268: [FocusMode] Set focus session elapsed time 
1721442537561: [SP_ALL] Load(import) all data 
1721442537564: [SP_ALL] All Data was loaded 
1721442537732: [WorkContext] Set Active Work Context 
1721442537830: [Task] SetSelectedTask 
1721442538264: [Bookmark] Load Bookmark State 
1721442538265: [Project] Load Project related Data Success 
1721442538266: [Improvement] Clear Hidden Improvements 
1721442538267: [Improvement] Delete multiple Improvements 
1721442672473: [WorkContext] Set Active Work Context 
1721442672523: [Task] SetSelectedTask 
1721442674813: [FocusMode] Set focus session elapsed time 
1721442677010: [SP_ALL] Load(import) all data 
1721442677012: [SP_ALL] All Data was loaded 
1721442677077: [WorkContext] Set Active Work Context 
1721442677078: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Thank you very much for digging into this!

**Comment by johannesjo** [comment]
Was able to fix this. Logic is still not waterproof, but there is a big update coming anyway to the timeline which will make this obsolete. 

Thank you for your help!

**Comment by lsewcx** [comment]
> Was able to fix this. Logic is still not waterproof, but there is a big update coming anyway to the timeline which will make this obsolete.
> 
> Thank you for your help!

I'm very glad you were able to fix this bug with my findings😄
