### ISSUE TITLE
While trying to set the volume to 0 --> TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by ArtisVansovics** [johannesjo/super-productivity#3313]
### Steps to Reproduce

1. Using the slider to set the app volume to 0
2.
3.
4.

### Console Output
isHandledError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/src/app/core/error-handler/global-error-handler.class.ts:45:12)AA (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:1:1522)invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:157)onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15681:24)invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:45)run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:111:36)zone.scheduleMicroTask(source, (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:2366:29)invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)shouldBeIgnoredByZone (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:15670:24)

### Meta Info
META: SP9.0.7 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.7 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:380:14323)
    at e._onValueChange (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:380:12754)
    at i._onInput (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:409:4951)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:409:8038
    at aee (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:98:101113)
    at n (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:98:101301)
    at HTMLInputElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:99:26769)
    at a.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/polyfills-OXW65WWX.js:1:39327)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-SZGE7EVM.js:98:62335)
    at a.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/polyfills-OXW65WWX.js:1:39248)
```

### Actions Before Error
```
1722500478927: [Task] Add time spent 
1722500478928: [Project] Update Work End 
1722500478928: [Tag] Update Work End for Tag 
1722500478929: [Persistence] Save to DB (3) 
1722500479317: [Global Config] Update Global Config Section 
1722500479342: [Persistence] Save to DB 
1722500479927: [Task] Add time spent 
1722500479928: [Project] Update Work End 
1722500479928: [Tag] Update Work End for Tag 
1722500479928: [Persistence] Save to DB (3) 
1722500480926: [Task] Add time spent 
1722500480928: [Project] Update Work End 
1722500480928: [Tag] Update Work End for Tag 
1722500480929: [Persistence] Save to DB (3) 
1722500481428: [Global Config] Update Global Config Section 
1722500481444: [Persistence] Save to DB 
1722500481927: [Task] Add time spent 
1722500481928: [Project] Update Work End 
1722500481928: [Tag] Update Work End for Tag 
1722500481929: [Persistence] Save to DB (3) 
1722500482553: [Global Config] Update Global Config Section 
1722500482568: [Persistence] Save to DB 
1722500482927: [Task] Add time spent 
1722500482928: [Project] Update Work End 
1722500482928: [Tag] Update Work End for Tag 
1722500482929: [Persistence] Save to DB (3) 
1722500483186: [Global Config] Update Global Config Section 
1722500483201: [Persistence] Save to DB 
1722500483706: [Global Config] Update Global Config Section 
1722500483706: [Persistence] Save to DB
```

**Comment by BadBossy** [comment]
Hi @ArtisVansovics ,

there is already an issue to this topic #3287
