### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isEnabled')

### ISSUE THREAD

**Issue by Selemba1000** [johannesjo/super-productivity#3346]
### Steps to Reproduce
On Android sync to Desktop application via sync thing. Immediately this message will show

### Meta Info
Android 14 via Playstore

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'isEnabled')
    at n5.project (https://app.super-productivity.com/main-VAT5NOZ7.js:256:702)
    at n5._next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:46812)
    at n5.next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:2372)
    at V4._next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:20399)
    at V4.next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:2372)
    at hs.next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:7126)
    at hs.nextInfiniteTimeWindow (https://app.super-productivity.com/main-VAT5NOZ7.js:94:17420)
    at Object.next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:45435)
    at VA.__tryOrUnsub (https://app.super-productivity.com/main-VAT5NOZ7.js:94:4161)
    at VA.next (https://app.super-productivity.com/main-VAT5NOZ7.js:94:3347)
```

### Actions Before Error
```
1723658988325: [SP_ALL] All Data was loaded 
1723658993302: [Layout] Toggle SideBar 
1723658994718: [Layout] Hide SideBar 
1723658997836: [Layout] Show AddTaskBar 
1723658999081: [Layout] Hide AddTaskBar 
1723659000113: [Task][Issue] Add Task 
1723659000122: [Persistence] Save to DB (2) 
1723659000123: [Task] Move tasks to other project 
1723659000130: [Persistence] Save to DB (2) 
1723659003147: [Layout] Toggle SideBar 
1723659007358: [Layout] Hide SideBar (2) 
1723659011586: [Global Config] Update Global Config Section 
1723659011663: [Persistence] Save to DB 
1723659015662: [Global Config] Update Global Config Section 
1723659015664: [Persistence] Save to DB 
1723659017381: [Global Config] Update Global Config Section 
1723659018930: [Persistence] Save to DB (15) 
1723659018962: [SP_ALL] Load(import) all data 
1723659018966: [Persistence] Remove from DB 
1723659022841: [FocusMode] Set focus session elapsed time 
1723659022991: [SP_ALL] Load(import) all data 
1723659022994: [SP_ALL] All Data was loaded 
1723659028477: [Global Config] Update Global Config Section 
1723659028513: [Persistence] Save to DB 
1723659031381: [FocusMode] Set focus session elapsed time 
1723659031439: [SP_ALL] Load(import) all data 
1723659031444: [SP_ALL] All Data was loaded 
1723659046905: [FocusMode] Set focus session elapsed time 
1723659046974: [SP_ALL] Load(import) all data 
1723659046977: [SP_ALL] All Data was loaded
```

**Comment by Selemba1000** [comment]
I am guessing this is already fixed on main. Just need to wait for next release. Until then android app does not seem to work.

**Comment by Selemba1000** [comment]
Issue was indeed fixed with the release.
