### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by javierslopez** [johannesjo/super-productivity#3356]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.7 Electron – es – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.7 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:380:14323)
    at e._onValueChange (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:380:12754)
    at i._onInput (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:409:4951)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:409:8038
    at aee (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:98:101113)
    at n (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:98:101301)
    at HTMLInputElement.<anonymous> (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:99:26769)
    at a.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:39327)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-3NYUOZFK.js:98:62335)
    at a.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_9.0.7.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:39248)
```

### Actions Before Error
```
1724182696595: [Persistence] Save to DB (3) 
1724182697597: [Task] Add time spent 
1724182697598: [Project] Update Work End 
1724182697599: [Tag] Update Work End for Tag 
1724182697599: [Persistence] Save to DB (3) 
1724182697975: [Task] Toggle start 
1724182697976: [Persistence] Save to DB 
1724182697976: [Task] UnsetCurrentTask 
1724182697976: [Pomodoro] Pause Pomodoro 
1724182699668: [Pomodoro] Stop Pomodoro 
1724182699668: [Task] UnsetCurrentTask 
1724182699669: [Pomodoro] Pause Pomodoro 
1724182705080: [Global Config] Update Global Config Section 
1724182705100: [Persistence] Save to DB 
1724182707226: [Global Config] Update Global Config Section 
1724182707242: [Persistence] Save to DB 
1724182708850: [Global Config] Update Global Config Section 
1724182708867: [Persistence] Save to DB 
1724182710269: [Global Config] Update Global Config Section 
1724182710284: [Persistence] Save to DB 
1724182720617: [Task] SetSelectedTask 
1724182720621: [Layout] Hide Notes 
1724182730195: [Task] Move to archive 
1724182730197: [Persistence] Save to DB (3) 
1724182730198: [Task] UnsetCurrentTask 
1724182730198: [Pomodoro] Pause Pomodoro 
1724182730254: [Persistence] Save to DB 
1724229006553: [Layout] Toggle SideBar 
1724229008001: [Layout] Hide SideBar (2)
```

**Comment by javierslopez** [comment]
Hello Johannesjo

It is not an urgent problem, what happens is that in the sound option, when I change the volume I always get the error that I show you here. I can't get the error message, so I have to reload the application, but I can't get the error message.

It allows me to turn the volume down or up, but I have to restart the application because of the error every time I do it. 

Thanks for such a good application and your work.

Translated with www.DeepL.com/Translator (free version)

**Comment by johannesjo** [comment]
Will be fixed with the next release.
