### ISSUE TITLE
Unknown Sync Error: Error: AxiosError: Request failed with status code 400 with dropbox sync

### ISSUE THREAD

**Issue by Anzar-M** [johannesjo/super-productivity#3377]
Console logs
```javascript
VM6:92 preload script loading complete
is-mouse-primary.ts:18 Object
action-logger.reducer.ts:11 @ngrx/store/init Object
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
action-logger.reducer.ts:11 @ngrx/effects/init Objecttype: "@ngrx/effects/init"[[Prototype]]: Object
persistence.service.ts:309 LOAD COMPLETE true
action-logger.reducer.ts:11 [FocusMode] Set focus session elapsed time Object
calendar-integration.effects.ts:90 this._currentlyShownBanners$ Array(0)
calendar-integration.effects.ts:157 SHOW BANNER
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
app.component.ts:342 Persistence already allowed
app.component.ts:371 1 out of 25066 MiB used (0%)
persistence-local.service.ts:40 Object
reminder.service.ts:89 loaded reminders from database Array(2)
cross-model-migrations.ts:14 [M] Starting cross model migrations...
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded Object
sync.effects.ts:137 sync(effect)..... INITIAL_SYNC_TRIGGER
persistence-local.service.ts:40 Object
api.dropboxapi.com/2/files/get_metadata:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
dropbox-sync.service.ts:81 YI
(anonymous) @ dropbox-sync.service.ts:81
sync-provider.service.ts:150 __error during sync__
sync-provider.service.ts:151 Error: AxiosError: Request failed with status code 400
    at e.<anonymous> (dropbox-sync.service.ts:82:15)
    at Generator.throw (<anonymous>)
    at s (main-3NYUOZFK.js:1:1566)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
(anonymous) @ sync-provider.service.ts:151
ipc-event.ts:21 ipcEvent$ trigger IDLE_TIME
ipc-event.ts:21 ipcEvent$ trigger IDLE_TIME
persistence.service.ts:309 LOAD COMPLETE false
persistence-local.service.ts:40 Object
api.dropboxapi.com/2/files/get_metadata:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
dropbox-sync.service.ts:81 YI
(anonymous) @ dropbox-sync.service.ts:81
sync-provider.service.ts:150 __error during sync__
sync-provider.service.ts:151 Error: AxiosError: Request failed with status code 400
    at e.<anonymous> (dropbox-sync.service.ts:82:15)
    at Generator.throw (<anonymous>)
    at s (main-3NYUOZFK.js:1:1566)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:15681:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:15670:25)
(anonymous) @ sync-provider.service.ts:151
persistence.service.ts:309 LOAD COMPLETE false
persistence.service.ts:309 LOAD COMPLETE false
```

**Comment by Anzar-M** [comment]
# Steps to fix this issue
1. Export local data from settings
2. Go to dropbox.com and navigate to "Apps" folder
3. delete "super_productivity" directory
4. remove all the local data or reinstall Super Proudctivity
5. import local data
6. sync with dropbox with new authorization code.

**Comment by StillNewIdeas** [comment]
Thank you, I had the same problem till I realised that 400 means that the error was caused on my side...
Then I realised that I got a 9.x.x-version installed and after I updated the app everything worked fine.
