### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'entities')

### ISSUE THREAD

**Issue by Dantemau** [johannesjo/super-productivity#3405]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.7 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.7 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'entities')
    at fYe (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:163:7949)
    at file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:163:5816
    at Array.forEach (<anonymous>)
    at lYe (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:163:5799)
    at mpe (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:163:5642)
    at e.repairData (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:163:12317)
    at e.<anonymous> (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:170:8520)
    at Generator.next (<anonymous>)
    at o (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-3NYUOZFK.js:1:1522)
    at a.invoke (file:///C:/Users/KDanielADLAP/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:38702)
```

### Actions Before Error
```
1725497754932: [WorkContext] Set Active Work Context 
1725497754975: [Task] SetSelectedTask 
1725497755822: [Layout] Hide SideBar 
1725497756462: [Bookmark] Load Bookmark State 
1725497756468: [Project] Load Project related Data Success 
1725497756537: [Improvement] Clear Hidden Improvements 
1725497756538: [Improvement] Delete multiple Improvements 
1725497763014: [Layout] Toggle SideBar 
1725497781995: [Layout] Hide SideBar (2) 
1725497811126: [Global Config] Update Global Config Section 
1725497811165: [Persistence] Save to DB 
1725497811166: [Dropbox] Trigger Auth Dialog 
1725497876881: [FocusMode] Set focus session elapsed time 
1725497876993: [SP_ALL] Load(import) all data 
1725497876997: [SP_ALL] All Data was loaded 
1725497879945: [Layout] Toggle SideBar 
1725497882819: [Layout] Hide SideBar (2) 
1725497891125: [Global Config] Update Global Config Section 
1725497891170: [Persistence] Save to DB 
1725497894378: [Layout] Toggle SideBar 
1725497895821: [Layout] Hide SideBar (2) 
1725497899264: [Task] UnsetCurrentTask 
1725497899268: [Pomodoro] Pause Pomodoro 
1725497899269: [SimpleCounter] Turn off all simple counters 
1725497904831: [FocusMode] Set focus session elapsed time 
1725497904948: [SP_ALL] Load(import) all data 
1725497904954: [SP_ALL] All Data was loaded 
1725497970563: [Layout] Toggle SideBar 
1725497973030: [Layout] Hide SideBar (2) 
1725498035186: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Can you provide a little more input, please?
