### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'theme')

### ISSUE THREAD

**Issue by zdomokos** [johannesjo/super-productivity#3464]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.4 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.4 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'theme')
    at Object.computation (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:393:2058)
    at Object.producerRecomputeValue (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:91:37518)
    at Cee (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:91:34857)
    at e.r [as tags] (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:91:37123)
    at template (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:393:2712)
    at Une (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:49813)
    at RLe (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:60527)
    at _G (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:61710)
    at rre (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:61539)
    at NLe (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:61505)
```

### Actions Before Error
```
1726347177050: [WorkContext] Set Active Work Context 
1726347177076: [Task] SetSelectedTask 
1726347177093: [Bookmark] Load Bookmark State 
1726347177093: [Project] Load Project related Data Success 
1726347177094: [Improvement] Clear Hidden Improvements 
1726347177094: [Improvement] Delete multiple Improvements 
1726347190983: [Project] Update Project 
1726347190983: [Persistence] Save to DB 
1726347206297: [WorkContext] Set Active Work Context 
1726347206324: [Task] SetSelectedTask 
1726347206377: [Bookmark] Load Bookmark State 
1726347206378: [Project] Load Project related Data Success 
1726347206378: [Improvement] Clear Hidden Improvements 
1726347206379: [Improvement] Delete multiple Improvements 
1726347219477: [Project] Update Project Issue Provider Cfg 
1726347219488: [Persistence] Save to DB 
1726347239968: [WorkContext] Set Active Work Context 
1726347240009: [Task] SetSelectedTask 
1726347240067: [Bookmark] Load Bookmark State 
1726347240067: [Project] Load Project related Data Success 
1726347240067: [Improvement] Clear Hidden Improvements 
1726347240067: [Improvement] Delete multiple Improvements 
1726347260949: [WorkContext] Set Active Work Context 
1726347260998: [Task] SetSelectedTask 
1726347260999: [Project] Delete Project 
1726347261000: [Persistence] Save to DB 
1726347261000: [Persistence] Remove from DB 
1726347261062: [Task] Delete Tasks 
1726347261066: [Persistence] Save to DB (3) 
1726347261066: [Note] Delete Note
```

**Comment by johannesjo** [comment]
Can you maybe provide a bit more information on what happened?

**Comment by zdomokos** [comment]
Deleted the Inbox. Then I had to uninstall an reinstall the product.

**Comment by johannesjo** [comment]
Thank you very much for bringing this crucial error to my attention. This is fixed and the fix will be available with the next release!
