### ISSUE TITLE
Error: Invalid clock string

### ISSUE THREAD

**Issue by gghrgr** [johannesjo/super-productivity#3474]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.4 Electron – zh-CN – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.4 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
Error: Invalid clock string
    at Ll (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:316:1498)
    at e.submit (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:320:4870)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:320:8303
    at Hte (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:102047)
    at n (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:102235)
    at HTMLButtonElement.<anonymous> (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:99:26729)
    at a.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:39327)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/main-JZCSZYK7.js:98:30060)
    at a.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:39248)
    at b.runTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_10.0.4.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/browser/polyfills-EFGSVQYE.js:1:34626)
```

### Actions Before Error
```
1726480656018: [Persistence] Save to DB 
1726480659254: [TaskRepeatCfg] Delete TaskRepeatCfg 
1726480659255: [Persistence] Save to DB 
1726480661982: [TaskRepeatCfg] Delete TaskRepeatCfg 
1726480661983: [Persistence] Save to DB 
1726480664604: [TaskRepeatCfg] Delete TaskRepeatCfg 
1726480664606: [Persistence] Save to DB 
1726480667251: [TaskRepeatCfg] Delete TaskRepeatCfg 
1726480667252: [Persistence] Save to DB 
1726480670759: [TaskRepeatCfg] Delete TaskRepeatCfg 
1726480670760: [Persistence] Save to DB 
1726484250928: [Task] SetSelectedTask 
1726484250929: [Layout] Hide Notes 
1726484285455: [Layout] Toggle AddTaskBar 
1726484298359: [Task][Issue] Add Task 
1726484298361: [Persistence] Save to DB (2) 
1726484299395: [Layout] Hide AddTaskBar 
1726484300928: [Task] SetSelectedTask 
1726484300929: [Layout] Hide Notes 
1726484366798: [Layout] Hide SideBar (2) 
1726484372609: [FocusMode] Set focus session elapsed time 
1726484372735: [SP_ALL] Load(import) all data 
1726484372739: [Idle] Reset 
1726484372739: [SP_ALL] All Data was loaded 
1726484400698: [Global Config] Update Global Config Section 
1726484400753: [Persistence] Save to DB 
1726484400753: [Layout] Hide SideBar 
1726484400755: [Layout] Toggle SideBar 
1726484406856: [Task] SetSelectedTask 
1726484406858: [Layout] Hide Notes
```

**Comment by johannesjo** [comment]
Can you provide a bit more context?

**Comment by gghrgr** [comment]
> Can you provide a bit more context?

It was probably due to haven't set up the calendar, it doesn't matter now, I got a new issue today
