### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by loukaMoroni** [johannesjo/super-productivity#3475]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.6 Browser – fr-FR – Linux aarch64 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at VG.trackById [as _trackByFn] (https://app.super-productivity.com/main-GJDIANPJ.js:180:2297)
    at VG.check (https://app.super-productivity.com/main-GJDIANPJ.js:98:125080)
    at VG.diff (https://app.super-productivity.com/main-GJDIANPJ.js:98:124909)
    at e.ngDoCheck (https://app.super-productivity.com/main-GJDIANPJ.js:98:159511)
    at pte (https://app.super-productivity.com/main-GJDIANPJ.js:98:20595)
    at wNe (https://app.super-productivity.com/main-GJDIANPJ.js:98:20756)
    at Gie (https://app.super-productivity.com/main-GJDIANPJ.js:98:20499)
    at fR (https://app.super-productivity.com/main-GJDIANPJ.js:98:20223)
    at jne (https://app.super-productivity.com/main-GJDIANPJ.js:98:48223)
    at m (https://app.super-productivity.com/main-GJDIANPJ.js:98:48068)
```

### Actions Before Error
```
1726492493721: [SP_ALL] Load(import) all data 
1726492493725: [SP_ALL] All Data was loaded 
1726492495078: [Layout] Show AddTaskBar 
1726492522493: [FocusMode] Set focus session elapsed time 
1726492522716: [SP_ALL] Load(import) all data 
1726492522721: [SP_ALL] All Data was loaded 
1726492526001: [Layout] Show AddTaskBar 
1726492538742: [Task][Issue] Add Task 
1726492538749: [Persistence] Save to DB (2) 
1726492538750: [Task] Move tasks to other project 
1726492538754: [Persistence] Save to DB (2) 
1726492539013: [Layout] Hide AddTaskBar 
1726492550741: [FocusMode] Set focus session elapsed time 
1726492550843: [SP_ALL] Load(import) all data 
1726492550847: [SP_ALL] All Data was loaded 
1726492582590: [FocusMode] Set focus session elapsed time 
1726492582678: [SP_ALL] Load(import) all data 
1726492582683: [SP_ALL] All Data was loaded 
1726492586086: [Layout] Toggle SideBar 
1726492599230: [Layout] Hide SideBar 
1726492599236: [WorkContext] Set Active Work Context 
1726492599294: [Task] SetSelectedTask 
1726492599351: [Layout] Hide SideBar 
1726492600426: [Layout] Show AddTaskBar 
1726492602904: [Layout] Hide AddTaskBar 
1726492603363: [Layout] Toggle SideBar 
1726492604293: [Layout] Hide SideBar 
1726492604298: [WorkContext] Set Active Work Context 
1726492604343: [Task] SetSelectedTask 
1726492604377: [Layout] Hide SideBar
```

**Comment by johannesjo** [comment]
Can you maybe provide a bit more context?

**Comment by loukaMoroni** [comment]
sorry, i just got a big red rectangle with this error message on the app and i just followed what the app told me to do, i did not looked into it yet

**Comment by cwengyan** [comment]
Exact thing is happening for me too. 
![image](https://github.com/user-attachments/assets/4bd94810-3b4e-4745-9f7e-8a45cc75dfbb)

**Comment by johannesjo** [comment]
I was able to fix this. The fix will be out with the next release. Thank you very much!!!

**Comment by loukaMoroni** [comment]
Damn thank YOU, i wasn't much help.

Le lun. 16 sept. 2024, 18:08, Johannes Millan ***@***.***> a
écrit :
