### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by norestraint** [johannesjo/super-productivity#3477]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.6 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.6 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at VG.trackById [as _trackByFn] (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:180:2297)
    at VG.check (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:125080)
    at VG.diff (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:124909)
    at e.ngDoCheck (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:159511)
    at pte (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:20595)
    at wNe (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:20756)
    at Gie (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:20499)
    at hR (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:20174)
    at jne (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:48176)
    at m (file:///snap/superproductivity/2052/resources/app.asar/dist/browser/main-GJDIANPJ.js:98:48068)
```

### Actions Before Error
```
1726507531580: [Task] Update Task 
1726507531582: [Persistence] Save to DB 
1726507537580: [Task] Update Task 
1726507537582: [Persistence] Save to DB 
1726507555596: [Task] SetSelectedTask (2) 
1726507555599: [Layout] Hide Notes 
1726507560781: [TaskRepeatCfg] Update TaskRepeatCfg 
1726507560784: [Persistence] Save to DB 
1726507576073: [Task] SetSelectedTask (2) 
1726507576074: [Layout] Hide Notes 
1726507595766: [Task] SetSelectedTask 
1726507639847: [Planner] Cleanup Old And Undefined Planner Tasks 
1726507639848: [Persistence] Save to DB 
1726507648968: [WorkContext] Set Active Work Context 
1726507649215: [Task] SetSelectedTask 
1726507653101: [Planner] Cleanup Old And Undefined Planner Tasks 
1726507653103: [Persistence] Save to DB 
1726507655839: [WorkContext] Set Active Work Context 
1726507655995: [Task] SetSelectedTask 
1726507656097: [Bookmark] Load Bookmark State 
1726507656098: [Project] Load Project related Data Success 
1726507656098: [Improvement] Clear Hidden Improvements 
1726507656104: [Improvement] Delete multiple Improvements 
1726507659674: [Task] Update Task Tags 
1726507659677: [Persistence] Save to DB (3) 
1726507690225: [Tag] Add Tag 
1726507690225: [Persistence] Save to DB 
1726507690226: [Task] Update Task Tags 
1726507690227: [Persistence] Save to DB (3)
```

**Comment by johannesjo** [comment]
I think this should be already fixed and the fix will be out with the next release.
