### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by huouer** [johannesjo/super-productivity#3481]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.6 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.6 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at VG.trackById [as _trackByFn] (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:180:2297)
    at VG.check (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:125080)
    at VG.diff (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:124909)
    at e.ngDoCheck (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:159511)
    at pte (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:20595)
    at wNe (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:20756)
    at Gie (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:20499)
    at fR (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:20223)
    at jne (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:48223)
    at m (file:///C:/Users/huoue/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-M67BFED4.js:98:48068)
```

### Actions Before Error
```
1726538849958: [Tag] Update Work End for Tag 
1726538849959: [Persistence] Save to DB (3) 
1726538850955: [Task] Add time spent 
1726538850958: [Project] Update Work End 
1726538850958: [Tag] Update Work End for Tag 
1726538850959: [Persistence] Save to DB (3) 
1726538851955: [Task] Add time spent 
1726538851957: [Project] Update Work End 
1726538851958: [Tag] Update Work End for Tag 
1726538851959: [Persistence] Save to DB (3) 
1726538853570: [Task] Add time spent 
1726538853573: [Project] Update Work End 
1726538853573: [Tag] Update Work End for Tag 
1726538853574: [Persistence] Save to DB (3) 
1726538854044: [Task] Add time spent 
1726538854045: [Project] Update Work End 
1726538854046: [Tag] Update Work End for Tag 
1726538854047: [Persistence] Save to DB (3) 
1726538855115: [Task] Add time spent 
1726538855118: [Project] Update Work End 
1726538855118: [Tag] Update Work End for Tag 
1726538855120: [Persistence] Save to DB (3) 
1726538855816: [FocusMode] Set focus session elapsed time 
1726538855918: [SP_ALL] Load(import) all data 
1726538855942: [Idle] Reset 
1726538855943: [SP_ALL] All Data was loaded 
1726538956696: [Layout] Hide SideBar (2) 
1726538963395: [Task] SetSelectedTask 
1726538963397: [Layout] Hide Notes 
1726538967967: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
Possibly a duplicate of https://github.com/johannesjo/super-productivity/issues/3475
