### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isEnableBacklog')

### ISSUE THREAD

**Issue by prakasha** [johannesjo/super-productivity#3488]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.7 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.7 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'isEnableBacklog')
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:107:149038
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:102:13854
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:102:2330
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:102:1801
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:418:75681
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:418:74618
    at file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:102:2210
    at J5.QVe [as accumulator] (file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:102:4348)
    at J5._tryNext (file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:94:44557)
    at J5._next (file:///snap/superproductivity/2057/resources/app.asar/dist/browser/main-WG34NG6Z.js:94:44501)
```

### Actions Before Error
```
1726638928703: [Tag] Update Work End for Tag 
1726638928704: [Persistence] Save to DB (3) 
1726638929463: [Task][Issue] Add Task 
1726638929470: [Persistence] Save to DB (2) 
1726638929703: [Task] Add time spent 
1726638929705: [Project] Update Work End 
1726638929706: [Tag] Update Work End for Tag 
1726638929708: [Persistence] Save to DB (3) 
1726638930700: [Task] Add time spent 
1726638930702: [Project] Update Work End 
1726638930703: [Tag] Update Work End for Tag 
1726638930705: [Persistence] Save to DB (3) 
1726638931635: [Layout] Hide AddTaskBar 
1726638931700: [Task] Add time spent 
1726638931703: [Project] Update Work End 
1726638931704: [Tag] Update Work End for Tag 
1726638931706: [Persistence] Save to DB (3) 
1726638932700: [Task] Add time spent 
1726638932702: [Project] Update Work End 
1726638932703: [Tag] Update Work End for Tag 
1726638932705: [Persistence] Save to DB (3) 
1726638933720: [Task] Add time spent 
1726638933722: [Project] Update Work End 
1726638933723: [Tag] Update Work End for Tag 
1726638933725: [Persistence] Save to DB (3) 
1726638934700: [Task] Add time spent 
1726638934700: [Project] Update Work End 
1726638934700: [Tag] Update Work End for Tag 
1726638934701: [Persistence] Save to DB (3) 
1726638935276: [Project] Move Task from regular to backlog
```

**Comment by johannesjo** [comment]
Thank you! Fix will be out soon.
