### ISSUE TITLE
Error when syncing Calanders - TypeError: Cannot read properties of null (reading 'parent')

### ISSUE THREAD

**Issue by w0rkrb** [johannesjo/super-productivity#3491]
In the last few weeks I've been getting an error when the application tries to read my Outlook and Google calendars.

I believe this could be a data problem rather than the application, to give some background I have been using SuperProductivity since version 8.0.5 with no calendar issues. In August I was in the US for several weeks resulting in me changing timezones from British Summer Time to US Eastern time then back to BST again. I did not have any issues at the time however I'm wondering if something in my Calendar data messed up and is now causing an exception, I'm thinking possibly an entry with no timezone info being read a second time with the same ID for example.

Happy to send my data file or any other troubleshooting steps.

So far I have tried removing and adding back the calendar URLs.
Restoring my data file from a week old backup

### Steps to Reproduce

1. Open application
2. Add Calender URLs from Outlook or Google calender
3. Navigate to Schedule or planner tabs or wait for application to read Outlook and Google Calenders 

### Error Log (Desktop only)
No error log written, today's output to main log:
[2024-09-18 18:30:24.798] [info]  { enabled: null, showDevTools: false, mode: 'bottom' }
[2024-09-18 18:30:25.030] [info]  Saving backups to /home/adrian/.config/superProductivity/backups
[2024-09-18 18:30:26.593] [info]  No custom styles detected at /home/adrian/.config/superProductivity/styles.css
[2024-09-18 18:30:37.658] [warn]  getSettingsCb no callbacks left
[2024-09-18 18:40:45.477] [info]  close, isQuiting: undefined
[2024-09-18 18:40:45.482] [info]  Actions to wait for  [ 'SYNC_BEFORE_CLOSE_ID', 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ]
[2024-09-18 18:40:51.197] [info]  BEFORE_CLOSE_DONE SYNC_BEFORE_CLOSE_ID [ 'FINISH_DAY_BEFORE_CLOSE_EFFECT' ] 

### Console Output

TypeError: Cannot read properties of null (reading 'parent')
    at i.addSubcomponent (ical.min.js:2659:86)
    at Object.updateTimezones (ical.min.js:869:58)
    at S_t (get-relevant-events-from-ical.ts:109:32)
    at gwe (get-relevant-events-from-ical.ts:14:35)
    at z$.project (calendar-integration.service.ts:167:9)
    at z$._next (map.js:29:29)
    at z$.next (Subscriber.js:50:12)
    at z$._next (map.js:34:22)
    at z$.next (Subscriber.js:50:12)
    at Z$._next (filter.js:32:24)

### Meta Info
META: SP10.0.9 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.9 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

**Comment by Intellek-help** [comment]
This looks similar to issue #3055 although I note that was on version 8.0.1 where I did not have the issue. Seems to me this may add to the possibility of it being data related.

**Comment by w0rkrb** [comment]
Quick update, I removed the calendars, updated the secret URLs for the ICS and re-added the calendars after which the application stopped throwing the error. I think that adds to the likelyhood it's data related.

I'm closing the ticket as I don't believe this is an application issue
