### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jadaliha** [johannesjo/super-productivity#3529]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.11 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.11 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
RangeError: Maximum call stack size exceeded
    at i._trySubscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5718)
    at i.subscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5420)
    at q$.call (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:25821)
    at i.subscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5292)
    at O5.call (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:39786)
    at i.subscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5292)
    at w5.call (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:39300)
    at i.subscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5292)
    at hH.call (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:48761)
    at i.subscribe (file:///C:/Users/jadal/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-7WUP32YU.js:94:5292)
```

### Actions Before Error
```
1727584935305: [Project] Update Work End 
1727584935306: [Tag] Update Work End for Tag 
1727584935308: [Persistence] Save to DB (3) 
1727584936302: [Task] Add time spent 
1727584936304: [Project] Update Work End 
1727584936304: [Tag] Update Work End for Tag 
1727584936305: [Persistence] Save to DB (3) 
1727584937303: [Task] Add time spent 
1727584937305: [Project] Update Work End 
1727584937305: [Tag] Update Work End for Tag 
1727584937306: [Persistence] Save to DB (3) 
1727584938304: [Task] Add time spent 
1727584938305: [Project] Update Work End 
1727584938306: [Tag] Update Work End for Tag 
1727584938306: [Persistence] Save to DB (3) 
1727584939303: [Task] Add time spent 
1727584939308: [Project] Update Work End 
1727584939308: [Tag] Update Work End for Tag 
1727584939310: [Persistence] Save to DB (3) 
1727584940304: [Task] Add time spent 
1727584940305: [Project] Update Work End 
1727584940306: [Tag] Update Work End for Tag 
1727584940306: [Persistence] Save to DB (3) 
1727584941305: [Task] Add time spent 
1727584941307: [Project] Update Work End 
1727584941308: [Tag] Update Work End for Tag 
1727584941309: [Persistence] Save to DB (3) 
1727584941356: [Task] Toggle start 
1727584941357: [Persistence] Save to DB 
1727584941357: [Task] UnsetCurrentTask
```

**Comment by johannesjo** [comment]
Can you provide a bit more context?
