### ISSUE TITLE
Error: No tag undefined

### ISSUE THREAD

**Issue by anirudhprakash** [johannesjo/super-productivity#3557]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.11 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.11 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
Error: No tag undefined
    at file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:107:106209
    at file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:7118
    at l (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:6530)
    at dUe (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:6812)
    at file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:7171
    at l (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:6530)
    at z$.project (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:102:5308)
    at z$._next (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:94:21020)
    at z$.next (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:94:2375)
    at e._subscribe (file:///private/var/folders/kj/bk94yg_51rv_xs4xc953mg580000gn/T/AppTranslocation/3890F1F4-8E33-41C1-8A2D-7F0430F35501/d/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-PPXN5QFG.js:94:12255)
```

### Actions Before Error
```
1728404777148: [Tag] Update Work End for Tag 
1728404777149: [Persistence] Save to DB (3) 
1728404778147: [Task] Add time spent 
1728404778151: [Project] Update Work End 
1728404778152: [Tag] Update Work End for Tag 
1728404778152: [Persistence] Save to DB (3) 
1728404779146: [Task] Add time spent 
1728404779147: [Project] Update Work End 
1728404779148: [Tag] Update Work End for Tag 
1728404779148: [Persistence] Save to DB (3) 
1728404780148: [Task] Add time spent 
1728404780152: [Project] Update Work End 
1728404780152: [Tag] Update Work End for Tag 
1728404780153: [Persistence] Save to DB (3) 
1728404781147: [Task] Add time spent 
1728404781148: [Project] Update Work End 
1728404781148: [Tag] Update Work End for Tag 
1728404781149: [Persistence] Save to DB (3) 
1728404782146: [Task] Add time spent 
1728404782149: [Project] Update Work End 
1728404782149: [Tag] Update Work End for Tag 
1728404782150: [Persistence] Save to DB (3) 
1728404783146: [Task] Add time spent 
1728404783148: [Project] Update Work End 
1728404783148: [Tag] Update Work End for Tag 
1728404783148: [Persistence] Save to DB (3) 
1728404783152: [Task] SetCurrentTask 
1728404783153: [Task] Update Task 
1728404783155: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
Can you provide a bit more context?
