### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'subTasks')

### ISSUE THREAD

**Issue by LionGwin** [johannesjo/super-productivity#3564]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.11 Electron – zh-CN – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.11 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of null (reading 'subTasks')
    at file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:107:135902
    at Array.forEach (<anonymous>)
    at $1 (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:107:135878)
    at z$.project (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:109:43296)
    at z$._next (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:21020)
    at z$.next (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:2375)
    at ds.next (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:7136)
    at ds.nextInfiniteTimeWindow (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:17431)
    at Object.next (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:46174)
    at FP.__tryOrUnsub (file:///D:/tmpdir/Temp/2mTBF3pqXBada8wapoDkytj1cjI/resources/app.asar/dist/browser/main-7WUP32YU.js:94:4164)
```

### Actions Before Error
```
1728611266588: [Improvement] Delete multiple Improvements 
1728611274866: [Task] Delete Task 
1728611274867: [Persistence] Save to DB (2) 
1728611274868: [Task] UnsetCurrentTask 
1728611276978: [WorkContextMeta] Move Task in Today 
1728611276979: [Persistence] Save to DB 
1728611281284: [Task] Add SubTask 
1728611281286: [Persistence] Save to DB 
1728611283372: [Task] Toggle Show Sub Tasks 
1728611283373: [Persistence] Save to DB 
1728611285127: [WorkContext] Set Active Work Context 
1728611285200: [Task] SetSelectedTask 
1728611304381: [Task] Delete Task 
1728611324587: [FocusMode] Set focus session elapsed time 
1728611324694: [SP_ALL] Load(import) all data 
1728611324696: [Idle] Reset 
1728611324697: [SP_ALL] All Data was loaded 
1728611332618: [Task] Delete Task 
1728611346742: [FocusMode] Set focus session elapsed time 
1728611346846: [SP_ALL] Load(import) all data 
1728611346849: [Idle] Reset 
1728611346850: [SP_ALL] All Data was loaded 
1728611350401: [Task] Toggle Show Sub Tasks 
1728611350403: [Persistence] Save to DB 
1728611353081: [Task] Delete Task 
1728611353084: [Persistence] Save to DB (2) 
1728611353084: [Task] UnsetCurrentTask 
1728611368026: [Layout] Toggle SideBar (2) 
1728611368028: [Layout] Hide SideBar 
1728611384667: [Task] Delete Task
```

**Comment by fast089609** [comment]
Hello @LionGwin , you forgot to indicate the steps, they come out empty.

**Comment by LionGwin** [comment]
Thank you for your reply. There is no problem with the app after I restarted it
