### ISSUE TITLE
Error: Tag length should not change on re-order

### ISSUE THREAD

**Issue by Nergatar** [johannesjo/super-productivity#3609]
### Steps to Reproduce

1. Created a new tag
2. Tried to move/sort the tag to the top of the tag list
3. (Running on Web version, not PWA)
4. Same error after reload of app

### Meta Info
META: SP10.0.11 Browser – sv – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0

### Stacktrace
```
Error: Tag length should not change on re-order
    at https://app.super-productivity.com/main-DUZ4F2RX.js:107:108982
    at https://app.super-productivity.com/main-DUZ4F2RX.js:102:13854
    at https://app.super-productivity.com/main-DUZ4F2RX.js:102:2330
    at https://app.super-productivity.com/main-DUZ4F2RX.js:102:1801
    at https://app.super-productivity.com/main-DUZ4F2RX.js:418:75681
    at https://app.super-productivity.com/main-DUZ4F2RX.js:418:74618
    at https://app.super-productivity.com/main-DUZ4F2RX.js:102:2210
    at J5.QVe [as accumulator] (https://app.super-productivity.com/main-DUZ4F2RX.js:102:4348)
    at J5._tryNext (https://app.super-productivity.com/main-DUZ4F2RX.js:94:44557)
    at J5._next (https://app.super-productivity.com/main-DUZ4F2RX.js:94:44501)
```

### Actions Before Error
```
1729490433102: [SP_ALL] Load(import) all data 
1729490433107: [Persistence] Remove from DB 
1729490447245: [Task] Update Task Tags 
1729490447247: [Persistence] Save to DB (3) 
1729490447247: [Task] Update Task Tags 
1729490447247: [Persistence] Save to DB (3) 
1729490447247: [Task] Update Task Tags 
1729490447248: [Persistence] Save to DB (3) 
1729490447248: [Task] Update Task Tags 
1729490447249: [Persistence] Save to DB (3) 
1729490447249: [Task] Update Task Tags 
1729490447250: [Persistence] Save to DB (3) 
1729490447250: [Task] Update Task Tags 
1729490447250: [Persistence] Save to DB (3) 
1729490447251: [Task] Update Task Tags 
1729490447251: [Persistence] Save to DB (3) 
1729490447333: [Planner] Update Planner Dialog Last Shown 
1729490447333: [Persistence] Save to DB 
1729490533197: [Layout] Hide SideBar 
1729490541453: [Layout] Toggle SideBar (2) 
1729490541456: [Layout] Hide SideBar 
1729490542558: [Layout] Toggle SideBar 
1729490545627: [Task] SetSelectedTask 
1729490545628: [Layout] Hide Notes 
1729490547961: [Task] SetSelectedTask 
1729490627933: [Tag] Add Tag 
1729490627935: [Persistence] Save to DB 
1729490627935: [Task] Update Task Tags 
1729490627937: [Persistence] Save to DB (3) 
1729490640100: [Tag] Update Tag Order
```

**Comment by johannesjo** [comment]
Hey there! Thank you very much for reporting this!

It might be that for some reason a bit of your data got into an invalid state that I didn't account for and that I can't reproduce. It would be great if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer (and please let me know here, if you send something, as those mails quite often land in the spam folder). You can create an export by navigating to "Settings" and then to "Import/Export" or you can use the "Export data" button from the error Dialog (there is also a button there which will anonymize the data before exporting).

**Comment by Nergatar** [comment]
I have sent the exported data to you. I still had the issue when tested today.

**Comment by johannesjo** [comment]
I think this should be fixed now?

**Comment by Nergatar** [comment]
Yes, I confirm that is is now working!
