### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'shutdownNow')

### ISSUE THREAD

**Issue by MonsterDruide1** [johannesjo/super-productivity#3614]
### Steps to Reproduce

1. Try setting up syncing via WebDAV while having an "incomplete sync" in the cloud
2. When first prompted about a conflict, select "Keep remote"
3. Then the app reports the broken state of remote, select "Shutdown App" here
4. Note that the app does not close, but only shows the (internal) crash screen instead

### Meta Info
META: SP10.0.11 Browser – de-DE – Linux aarch64 – Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.81 Mobile Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'shutdownNow')
    at e.closeApp (https://localhost/main-ANTT3B72.js:237:5967)
    at https://localhost/main-ANTT3B72.js:237:5420
    at Qte (https://localhost/main-ANTT3B72.js:98:103558)
    at n (https://localhost/main-ANTT3B72.js:98:103746)
    at HTMLButtonElement.<anonymous> (https://localhost/main-ANTT3B72.js:99:26910)
    at a.invokeTask (https://localhost/polyfills-KL5Y42F4.js:1:39327)
    at Object.onInvokeTask (https://localhost/main-ANTT3B72.js:98:30477)
    at a.invokeTask (https://localhost/polyfills-KL5Y42F4.js:1:39248)
    at b.runTask (https://localhost/polyfills-KL5Y42F4.js:1:34626)
    at l.invokeTask [as invoke] (https://localhost/polyfills-KL5Y42F4.js:1:40400)
```

### Actions Before Error
```
1729524274520: [FocusMode] Set focus session elapsed time 
1729524274734: [SP_ALL] Load(import) all data 
1729524274749: [SP_ALL] All Data was loaded 
1729524280520: [Layout] Toggle SideBar 
1729524283568: [Layout] Hide SideBar (2) 
1729524338667: [Global Config] Update Global Config Section 
1729524338829: [Persistence] Save to DB 
1729524353063: [Global Config] Update Global Config Section 
1729524353269: [Persistence] Save to DB 
1729524366249: [Global Config] Update Global Config Section 
1729524366660: [Persistence] Save to DB 
1729524382920: [Global Config] Update Global Config Section 
1729524383150: [Persistence] Save to DB 
1729524406439: [Global Config] Update Global Config Section 
1729524406616: [Persistence] Save to DB 
1729524409981: [Global Config] Update Global Config Section 
1729524410186: [Persistence] Save to DB 
1729524467047: [Global Config] Update Global Config Section 
1729524467048: [Persistence] Save to DB 
1729524678769: [Global Config] Update Global Config Section 
1729524678878: [Persistence] Save to DB
```

**Comment by MonsterDruide1** [comment]
Screenshots:
![Conflicting Data](https://github.com/user-attachments/assets/e6571acb-a18a-4425-aba9-3052be8b24b8)

![Incomplete Sync](https://github.com/user-attachments/assets/b08d42c4-0d54-4664-98cd-9825f15d41d9)

![Error Screen](https://github.com/user-attachments/assets/da61e1e7-7f09-4a4c-9312-18f48f30aefd)

**Comment by johannesjo** [comment]
Thank you very much! A fix will be out with the next release.
