### ISSUE TITLE
During interactive tutorial: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Zim-Inn** [johannesjo/super-productivity#3658]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.1.0 Electron – zh-CN – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.1.0 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
RangeError: Maximum call stack size exceeded
    at i._trySubscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5718)
    at i.subscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5420)
    at n5.call (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:25821)
    at i.subscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5292)
    at L5.call (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:39786)
    at i.subscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5292)
    at F5.call (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:39300)
    at i.subscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5292)
    at CH.call (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:48774)
    at i.subscribe (file:///C:/Users/username/AppData/Local/Programs/superProductivity/resources/app.asar/dist/browser/main-IHUXGH3W.js:94:5292)
```

### Actions Before Error
```
1730864256968: [SP_ALL] Load(import) all data 
1730864256969: [SP_ALL] All Data was loaded 
1730864272074: [Layout] Toggle AddTaskBar 
1730864310813: [Task][Issue] Add Task 
1730864310814: [Persistence] Save to DB (2) 
1730864310815: [Task] Move tasks to other project 
1730864310815: [Persistence] Save to DB (2) 
1730864318018: [Layout] Hide AddTaskBar 
1730864345569: [Task] SetSelectedTask 
1730864345570: [Layout] Hide Notes 
1730864348384: [Task] Toggle start 
1730864348384: [Persistence] Save to DB 
1730864348385: [Task] SetCurrentTask 
1730864348909: [Task] Add time spent 
1730864348910: [Project] Update Work Start 
1730864348911: [Project] Update Work End 
1730864348911: [Tag] Update Work Start for Tag 
1730864348912: [Tag] Update Work End for Tag 
1730864348912: [Persistence] Save to DB (5) 
1730864349907: [Task] Add time spent 
1730864349909: [Project] Update Work End 
1730864349910: [Tag] Update Work End for Tag 
1730864349912: [Persistence] Save to DB (3) 
1730864350904: [Task] Add time spent 
1730864350904: [Project] Update Work End 
1730864350905: [Tag] Update Work End for Tag 
1730864350905: [Persistence] Save to DB (3) 
1730864351889: [Task] Toggle start 
1730864351890: [Persistence] Save to DB 
1730864351890: [Task] UnsetCurrentTask
```

**Comment by Zim-Inn** [comment]
> Can you provide a bit more context?
I install the app first time. I start the app, start the tutorials.
The error happened when I try to pause the timer as the tutorials suggesting.
