### ISSUE TITLE
Error: Tag length should not change on re-order

### ISSUE THREAD

**Issue by ELigoP** [johannesjo/super-productivity#3665]
### Steps to Reproduce

1. Create tags some normal tags 'household', 'delegate' etc.
2. create tags '3/3', '1/1', '5/5' (in that order)
3. tag some tasks with those tags
4. try dragging '1/1' tag before '3/3'

### Meta Info
META: SP10.0.11 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.11 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
Error: Tag length should not change on re-order
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:107:108982
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:102:13854
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:102:2330
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:102:1801
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:418:75681
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:418:74618
    at file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:102:2210
    at J5.QVe [as accumulator] (file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:102:4348)
    at J5._tryNext (file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:94:44557)
    at J5._next (file:///tmp/.mount_superP9eM9of/resources/app.asar/dist/browser/main-DUZ4F2RX.js:94:44501)
```

### Actions Before Error
```
1730970942388: [Task] Update Task 
1730970942390: [Task] Update Task Tags 
1730970942392: [Persistence] Save to DB (4) 
1730970945921: [Task] Update Task Tags 
1730970945923: [Persistence] Save to DB (3) 
1730970946816: [Task] Add time spent 
1730970946819: [Project] Update Work End 
1730970946819: [Persistence] Save to DB (2) 
1730970956826: [Task] Add time spent 
1730970956828: [Project] Update Work End 
1730970956829: [Persistence] Save to DB (2) 
1730970958218: [Task] Update Task 
1730970958219: [Persistence] Save to DB 
1730970958220: [Task] Update Task 
1730970958221: [Task] Update Task Tags 
1730970958223: [Persistence] Save to DB (4) 
1730970966825: [Task] Add time spent 
1730970966827: [Project] Update Work End 
1730970966829: [Persistence] Save to DB (2) 
1730970974051: [Task] Update Task 
1730970974052: [Persistence] Save to DB 
1730970974053: [Task] Update Task 
1730970974054: [Task] Update Task Tags 
1730970974056: [Persistence] Save to DB (4) 
1730970976817: [Task] Add time spent 
1730970976819: [Project] Update Work End 
1730970976820: [Persistence] Save to DB (2) 
1730970978261: [WorkContext] Set Active Work Context 
1730970978402: [Task] SetSelectedTask 
1730970980881: [Tag] Update Tag Order
```

**Comment by johannesjo** [comment]
If I am not mistaken, this should be fixed with the newest release.

**Comment by ELigoP** [comment]
Indeed, it is.
