### ISSUE TITLE
Error: Cannot find focus el

### ISSUE THREAD

**Issue by joshajiniran** [johannesjo/super-productivity#3671]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.0.1 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.0.1 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36

### Stacktrace
```
Error: Cannot find focus el
    at e.focusTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:109:56534)
    at e.expandDoneTasks (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:344:1725)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:343:903
    at Lte (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:98:102047)
    at n (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:98:102235)
    at HTMLButtonElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:99:26729)
    at a.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/polyfills-OXW65WWX.js:1:39327)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/main-UZSJVVQF.js:98:30060)
    at a.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/polyfills-OXW65WWX.js:1:39248)
    at b.runTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/browser/polyfills-OXW65WWX.js:1:34626)
```

### Actions Before Error
```
1731122409183: [Task] Update Task 
1731122409185: [Persistence] Save to DB 
1731122425224: [Task] Update Task 
1731122425333: [Persistence] Save to DB 
1731122425333: [Task] Update Task 
1731122425333: [Task] Schedule 
1731122425334: [Persistence] Save to DB (3) 
1731122425334: [Task] Update Task 
1731122425334: [Planner] Remove Task From Days 
1731122425335: [Persistence] Save to DB (2) 
1731122435370: [Planner] Cleanup Old And Undefined Planner Tasks 
1731122435371: [Persistence] Save to DB 
1731122441859: [Task] SetSelectedTask 
1731122441860: [Planner] Cleanup Old And Undefined Planner Tasks 
1731122441860: [Layout] Hide Notes 
1731122441860: [Persistence] Save to DB 
1731122446440: [Task] Update Task 
1731122446443: [Planner] Cleanup Old And Undefined Planner Tasks 
1731122446443: [Persistence] Save to DB (2) 
1731122455666: [Task] SetSelectedTask 
1731122455667: [Planner] Cleanup Old And Undefined Planner Tasks 
1731122455667: [Persistence] Save to DB 
1731122665116: [Task] Toggle Show Sub Tasks 
1731122665117: [Persistence] Save to DB 
1731122672706: [Planner] Cleanup Old And Undefined Planner Tasks 
1731122672706: [Persistence] Save to DB 
1731122684211: [Task] SetSelectedTask 
1731122684213: [Layout] Hide Notes 
1731122687157: [Task] Update Task Ui 
1731122687158: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Can you provide some additional info?
