### ISSUE TITLE
Error: TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by mariovata** [johannesjo/super-productivity#3690]
### Steps to Reproduce
1. Open the App
2. Go to the settings
3. Under Productivity Helper open "Domina mode"
4. Spam click the volume knob (Make sure to drag it first a bit as well)
(The first volume knob in the settings handles this well and I don't get an error)

### Error Log (Desktop only)

[-1731773099039.log](https://github.com/user-attachments/files/17787121/-1731773099039.log)

### Console Output
```
VM803:96 preload script loading complete
is-mouse-primary.ts:18 Object
action-logger.reducer.ts:11 @ngrx/store/init Object
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
action-logger.reducer.ts:11 @ngrx/effects/init Object
persistence.service.ts:313 LOAD COMPLETE true
action-logger.reducer.ts:11 [FocusMode] Set focus session elapsed time Object
calendar-integration.effects.ts:131 SHOW BANNER
action-logger.reducer.ts:11 @ngrx/store/update-reducers Object
app.component.ts:342 Persistence already allowed
app.component.ts:371 1 out of 1099537 MiB used (0%)
persistence-local.service.ts:40 Object
dropbox-api.service.ts:252 LEGACY TOKENS
reminder.service.ts:89 loaded reminders from database Array(0)
cross-model-migrations.ts:14 [M] Starting cross model migrations...
action-logger.reducer.ts:11 [SP_ALL] Load(import) all data Object
action-logger.reducer.ts:11 [SP_ALL] All Data was loaded Object
dropbox-api.service.ts:261 SETTING LEGACY TOKENS Object
dropbox-api.service.ts:284 Update Tokens Object
persistence-local.service.ts:40 Object
planner-initial-dialog.effects.ts:60 Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:410:20)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:410:20)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
global-error-handler.class.ts:24 GLOBAL_ERROR_HANDLER TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._onInput (ngx-formly-material-slider.mjs:328:20)
    at ngx-formly-material-slider.mjs:526:22
    at tie (core.mjs:25806:12)
    at n (core.mjs:25838:18)
    at HTMLInputElement.<anonymous> (platform-browser.mjs:679:112)
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:7018:25)
    at a.invokeTask (zone.js:356:54)
(anonymous) @ global-error-handler.class.ts:24
action-logger.ts:39 Last actions before error: Array(30)
persistence.service.ts:313 LOAD COMPLETE false
action-logger.reducer.ts:11 [Global Config] Update Global Config Section Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
global-error-handler.util.ts:113 Object
global-error-handler.class.ts:24 GLOBAL_ERROR_HANDLER Error: TypeError: Cannot read properties of undefined (reading 'set')
    at e.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at o (main-4LYYPQAI.js:1:1821)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:7029:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:7018:25)
(anonymous) @ global-error-handler.class.ts:24
action-logger.ts:39 Last actions before error: Array(30)
persistence.service.ts:313 LOAD COMPLETE false
console.js:86 17:04:28.979 › Frontend Error: TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._onInput (ngx-formly-material-slider.mjs:328:20)
    at ngx-formly-material-slider.mjs:526:22
    at tie (core.mjs:25806:12)
    at n (core.mjs:25838:18)
    at HTMLInputElement.<anonymous> (platform-browser.mjs:679:112)
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:7018:25)
    at a.invokeTask (zone.js:356:54) TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:339:14525)
    at e._onValueChange (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:339:12956)
    at i._onInput (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:418:4980)
    at file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:418:8077
    at tie (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:98:103558)
    at n (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:98:103746)
    at HTMLInputElement.<anonymous> (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:99:26910)
    at a.invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:39327)
    at Object.onInvokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:98:30477)
    at a.invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:39248)
(anonymous) @ console.js:86
Show 1 more frame
Show less
zone.js:2165 Error: Error: TypeError: Cannot read properties of undefined (reading 'set')
    at e.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at o (main-4LYYPQAI.js:1:1821)
    at a.invoke (zone.js:331:158)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at Z (zone.js:527:23)
    at l.invokeTask [as invoke] (zone.js:436:11)
n.onUnhandledError @ zone.js:2165
Show 1 more frame
Show less
console.js:86 17:04:28.982 › Frontend Error: Error: TypeError: Cannot read properties of undefined (reading 'set')
    at e.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at o (main-4LYYPQAI.js:1:1821)
    at a.invoke (zone.js:331:158)
    at Object.onInvoke (core.mjs:7029:25)
    at a.invoke (zone.js:331:46)
    at b.run (zone.js:111:37)
    at zone.js:2366:30
    at a.invokeTask (zone.js:356:171)
    at Object.onInvokeTask (core.mjs:7018:25) Error: TypeError: Cannot read properties of undefined (reading 'set')
    at e.<anonymous> (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:230:435)
    at Generator.next (<anonymous>)
    at o (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:1:1821)
    at a.invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:38702)
    at Object.onInvoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:98:30663)
    at a.invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:38642)
    at b.run (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:34015)
    at file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:2:554
    at a.invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:39327)
    at Object.onInvokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:98:30477)
(anonymous) @ console.js:86
Show 1 more frame
Show less
zone.js:160 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (slider.mjs:844:52)
    at e._onValueChange (slider.mjs:750:12)
    at i._fixValue (ngx-formly-material-slider.mjs:401:22)
    at ngx-formly-material-slider.mjs:382:14
    at I.<computed> (zone.js:1705:27)
    at a.invokeTask (zone.js:356:171)
    at b.runTask (zone.js:157:39)
    at invokeTask (zone.js:433:26)
    at E.useG.invoke (zone.js:422:38)
    at g.args.<computed> (zone.js:1687:26)
console.js:86 17:04:29.960 › Frontend Error Stack: this._skipUpdate (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/slider.mjs:844:51)
_onValueChange (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/slider.mjs:750:11)
this._onChangeFn (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@ngx-formly/material/fesm2020/ngx-formly-material-slider.mjs:328:19)
MatSliderThumb_input_HostBindingHandler (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@ngx-formly/material/fesm2020/ngx-formly-material-slider.mjs:526:21)
executeListenerWithErrorHandling (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:25806:11)
wrapListenerIn_markDirtyAndPreventDefault (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:25838:17)
decoratePreventDefault (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs:679:111)
invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)
shouldBeIgnoredByZone (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:7018:24)
invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:53)
(anonymous) @ console.js:86
I.<computed> @ zone.js:1705
invokeTask @ zone.js:356
onInvokeTask @ core.mjs:7018
invokeTask @ zone.js:356
runTask @ zone.js:157
invokeTask @ zone.js:433
E.useG.invoke @ zone.js:422
g.args.<computed> @ zone.js:1687
Show 9 more frames
Show less
console.js:86 17:04:29.961 › Frontend Error Stack: isHandledError (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/src/app/core/error-handler/global-error-handler.class.ts:45:12)
T_ (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:1:1821)
invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:157)
onInvoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:7029:24)
invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:45)
run (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:111:36)
zone.scheduleMicroTask(source, (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:2366:29)
invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)
shouldBeIgnoredByZone (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:7018:24)
(anonymous) @ console.js:86
I.<computed> @ zone.js:1705
invokeTask @ zone.js:356
runTask @ zone.js:157
invokeTask @ zone.js:433
E.useG.invoke @ zone.js:422
g.args.<computed> @ zone.js:1687
Show 7 more frames
Show less
action-logger.reducer.ts:11 [Layout] Hide SideBar {type: '[Layout] Hide SideBar'}
```

### Meta Info
META: SP10.1.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.1.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
isHandledError (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/src/app/core/error-handler/global-error-handler.class.ts:45:12)
T_ (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-4LYYPQAI.js:1:1821)
invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:157)
onInvoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:7029:24)
invoke (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:331:45)
run (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:111:36)
zone.scheduleMicroTask(source, (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:2366:29)
invokeTask (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/zone.js/fesm2015/zone.js:356:170)
shouldBeIgnoredByZone (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:7018:24)
```

### Actions Before Error
```
1731772823181: [Tag] Update Work End for Tag 
1731772823184: [Persistence] Save to DB (3) 
1731772824175: [Task] Add time spent 
1731772824177: [Project] Update Work End 
1731772824178: [Tag] Update Work End for Tag 
1731772824180: [Persistence] Save to DB (3) 
1731772825175: [Task] Add time spent 
1731772825177: [Project] Update Work End 
1731772825178: [Tag] Update Work End for Tag 
1731772825181: [Persistence] Save to DB (3) 
1731772825772: [FocusMode] Set focus session elapsed time 
1731772825808: [SP_ALL] Load(import) all data 
1731772825809: [SP_ALL] All Data was loaded 
1731772841938: [Global Config] Update Global Config Section 
1731772841945: [Persistence] Save to DB 
1731772843881: [Global Config] Update Global Config Section 
1731772843885: [Persistence] Save to DB 
1731772844706: [Global Config] Update Global Config Section 
1731772844708: [Persistence] Save to DB 
1731772846250: [Global Config] Update Global Config Section 
1731772846254: [Persistence] Save to DB 
1731772850867: [Global Config] Update Global Config Section 
1731772850886: [Persistence] Save to DB 
1731772859362: [FocusMode] Set focus session elapsed time 
1731772859395: [SP_ALL] Load(import) all data 
1731772859396: [SP_ALL] All Data was loaded 
1731772863023: [Layout] Toggle SideBar (2) 
1731772863031: [Layout] Hide SideBar 
1731772873477: [Global Config] Update Global Config Section 
1731772873497: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
I opened up an issue for ngx formly:
https://github.com/ngx-formly/ngx-formly/issues/4019

**Comment by johannesjo** [comment]
Will be fixed with the next release.
