### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'entities')

### ISSUE THREAD

**Issue by ryanjkemper** [johannesjo/super-productivity#3697]
### Steps to Reproduce

1. Re-installed via snap after upgrading Ubuntu 24.  Previously this crashed and was getting the error as related to #3521
2. After Re-install and attempting to import from backup, hit #1770 and resolved it via the steps in that Issue.
3. Selected the main.json from the latest backup, before the crash.  It asked if I wanted to migrate legacy data and I said yes.
4. Hit this error and am reporting it now.

### Meta Info
META: SP10.1.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.1.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'entities')
    at u7e (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:163:11648)
    at file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:163:9522
    at Array.forEach (<anonymous>)
    at o7e (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:163:9505)
    at mhe (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:163:9348)
    at e.repairData (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:163:16119)
    at e.<anonymous> (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:170:8536)
    at Generator.next (<anonymous>)
    at o (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/main-4LYYPQAI.js:1:1821)
    at a.invoke (file:///snap/superproductivity/2133/resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:38702)
```

### Actions Before Error
```
1731972957818: [FocusMode] Set focus session elapsed time 
1731972957934: [SP_ALL] Load(import) all data 
1731972957936: [SP_ALL] All Data was loaded 
1731973054715: [FocusMode] Set focus session elapsed time 
1731973054830: [SP_ALL] Load(import) all data 
1731973054833: [SP_ALL] All Data was loaded 
1731973142054: [FocusMode] Set focus session elapsed time 
1731973142153: [SP_ALL] Load(import) all data 
1731973142156: [SP_ALL] All Data was loaded 
1731973143966: [Layout] Toggle SideBar 
1731973171130: [FocusMode] Set focus session elapsed time 
1731973171247: [SP_ALL] Load(import) all data 
1731973171249: [SP_ALL] All Data was loaded 
1731973191425: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this! Unfortunately I am unable to reproduce this. :/ Can you by any chance provide me with the contents of the failed backup?
The path will be shown on the settings page under "Sync&Export/Automatic Backups". You can send it to contact@super-productivity.com

**Comment by ryanjkemper** [comment]
Hey there, since I've re-installed I don't seem to have any more issues.  Since I no longer have the corrupted backups, I can go ahead and close this.  Thank you!
