### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by Frankie-B** [johannesjo/super-productivity#3746]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP10.1.1 Electron – en-GB – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.1.1 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'set')
    at e._updateValueIndicatorUI (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:339:14525)
    at e._onValueChange (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:339:12956)
    at i._onInput (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:418:4980)
    at file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:418:8077
    at tie (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:98:103558)
    at n (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:98:103746)
    at HTMLInputElement.<anonymous> (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:99:26910)
    at a.invokeTask (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:39327)
    at Object.onInvokeTask (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-SBEKGIGP.js:98:30477)
    at a.invokeTask (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/polyfills-KL5Y42F4.js:1:39248)
```

### Actions Before Error
```
1733821281544: [Tag] Update Work End for Tag 
1733821281545: [Persistence] Save to DB (3) 
1733821282541: [Task] Add time spent 
1733821282542: [Project] Update Work End 
1733821282542: [Tag] Update Work End for Tag 
1733821282543: [Persistence] Save to DB (3) 
1733821283540: [Task] Add time spent 
1733821283541: [Project] Update Work End 
1733821283542: [Tag] Update Work End for Tag 
1733821283542: [Persistence] Save to DB (3) 
1733821284540: [Task] Add time spent 
1733821284542: [Project] Update Work End 
1733821284543: [Tag] Update Work End for Tag 
1733821284543: [Persistence] Save to DB (3) 
1733821285543: [Task] Add time spent 
1733821285546: [Project] Update Work End 
1733821285546: [Tag] Update Work End for Tag 
1733821285548: [Persistence] Save to DB (3) 
1733821286477: [Global Config] Update Global Config Section 
1733821286497: [Persistence] Save to DB 
1733821287478: [Task] Add time spent 
1733821287481: [Project] Update Work End 
1733821287481: [Tag] Update Work End for Tag 
1733821287482: [Persistence] Save to DB (3) 
1733821288479: [Task] Add time spent 
1733821288482: [Project] Update Work End 
1733821288482: [Tag] Update Work End for Tag 
1733821288483: [Persistence] Save to DB (3) 
1733821288635: [Global Config] Update Global Config Section 
1733821288636: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
This should be fixed with the latest version.
