### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'isEnabled')

### ISSUE THREAD

**Issue by rickleone** [johannesjo/super-productivity#3756]
### Steps to Reproduce

1.
2.
3.
4.

### Meta Info
META: SP9.0.3 Electron – it – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/9.0.3 Chrome/122.0.6261.156 Electron/29.4.5 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'isEnabled')
    at X$.project (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:160:701)
    at X$._next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:46805)
    at X$.next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:2372)
    at P4._next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:20398)
    at P4.next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:2372)
    at Jo.next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:7126)
    at Jo.nextInfiniteTimeWindow (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:17420)
    at Object.next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:45429)
    at LA.__tryOrUnsub (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:4161)
    at LA.next (file:///opt/superProductivity/resources/app.asar/dist/browser/main-JWCHIBT3.js:79:3347)
```

### Actions Before Error
```
1734037655734: [Global Config] Update Global Config Section 
1734037655777: [Persistence] Save to DB 
1734037655882: [Global Config] Update Global Config Section 
1734037655901: [Persistence] Save to DB 
1734037656192: [Global Config] Update Global Config Section 
1734037656213: [Persistence] Save to DB 
1734037656368: [Global Config] Update Global Config Section 
1734037656386: [Persistence] Save to DB 
1734037656544: [Global Config] Update Global Config Section 
1734037656562: [Persistence] Save to DB 
1734037657344: [Global Config] Update Global Config Section 
1734037657361: [Persistence] Save to DB 
1734037657536: [Global Config] Update Global Config Section 
1734037657553: [Persistence] Save to DB 
1734037657752: [Global Config] Update Global Config Section 
1734037657774: [Persistence] Save to DB 
1734037666051: [Task] UnsetCurrentTask 
1734037666058: [SimpleCounter] Set SimpleCounter Counter Off 
1734037666061: [Pomodoro] Pause Pomodoro 
1734037666064: [Persistence] Save to DB 
1734037666065: [SimpleCounter] Turn off all simple counters 
1734193556891: [FocusMode] Set focus session elapsed time 
1734193556972: [SP_ALL] Load(import) all data 
1734193556974: [SP_ALL] All Data was loaded 
1734193557144: [Persistence] Save to DB (14) 
1734193557181: [SP_ALL] Load(import) all data 
1734193557189: [Persistence] Remove from DB 
1734193573506: [FocusMode] Set focus session elapsed time 
1734193573570: [SP_ALL] Load(import) all data 
1734193573573: [SP_ALL] All Data was loaded
```

**Comment by johannesjo** [comment]
Can you provide some more details?
