### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by tesap** [johannesjo/super-productivity#3761]
### Steps to Reproduce
I'm not sure whether it's possible to reproduce this easily, but anyway
1. I've created tag "optional"
2. Assigned some tasks to it
3. Renamed it to "D: optional"
4. Deleted this tag

### Console Output
In logs I repeatedly get something like:
![image](https://github.com/user-attachments/assets/41f6a897-8ec1-461a-931d-c927d3d3ea46)

### Meta Info
META: SP10.2.3 __ Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/10.2.3 Chrome/130.0.6723.118 Electron/33.2.0 Safari/537.36

### Stacktrace
```
TypeError: Cannot read properties of undefined (reading 'id')
    at MDt (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:374:1236)
    at Z$ (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:94320)
    at F3e (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:94466)
    at An (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:98505)
    at PDt (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:374:1417)
    at Gie (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:50721)
    at cje (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:61674)
    at NH (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:62877)
    at ane (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:62686)
    at sne (file:///opt/Super%20Productivity/resources/app.asar/dist/browser/main-BYWTWX2W.js:79:62451)
```

### Actions Before Error
```
1734289345329: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289345332: [Project] Update Work End 
1734289345334: [Tag] Update Work End for Tag 
1734289345338: [Persistence] Save to DB (4) 
1734289346324: [Task] Add time spent 
1734289346330: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289346334: [Project] Update Work End 
1734289346336: [Tag] Update Work End for Tag 
1734289346342: [Persistence] Save to DB (4) 
1734289347361: [Task] Add time spent 
1734289347369: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289347373: [Project] Update Work End 
1734289347375: [Tag] Update Work End for Tag 
1734289347378: [Persistence] Save to DB (4) 
1734289348324: [Task] Add time spent 
1734289348329: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289348332: [Project] Update Work End 
1734289348335: [Tag] Update Work End for Tag 
1734289348340: [Persistence] Save to DB (4) 
1734289349339: [Task] Add time spent 
1734289349343: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289349345: [Project] Update Work End 
1734289349346: [Tag] Update Work End for Tag 
1734289349349: [Persistence] Save to DB (4) 
1734289350089: [Tag] Delete Tag 
1734289350092: [Persistence] Save to DB 
1734289350093: [Task] Remove Tags from all Tasks 
1734289350113: [Planner] Cleanup Old And Undefined Planner Tasks 
1734289350117: [Persistence] Save to DB (2)
```

**Comment by johannesjo** [comment]
Thanks for reporting. I am unable to reproduce this. Are you able to reproduce this relieably? Is the app working again as expected, when you restart? How  did you delete the tag? And what was on the screen before and after you deleted the tag?
