### ISSUE TITLE
Error: No issueProviderId or type given

### ISSUE THREAD

**Issue by ZoranMedojevic** [johannesjo/super-productivity#3771]
### Steps to Reproduce
1. When I try to submit worklog on sub-task complete

Note: task submit updates status as expected.
Until today was working perfectly.

![image](https://github.com/user-attachments/assets/bc8d817d-c0b3-406e-8ce5-15b4cda1bc6a)

### Console Output
![image](https://github.com/user-attachments/assets/4a729fbc-9c3c-454c-91de-9f6abbf8b53e)

### Meta Info
META: SP11.0.0 __ Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/11.0.0 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36

### Stacktrace
```
Error: No issueProviderId or type given
    at e.getCfgOnce$ (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:271:2665)
    at new e (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:303:5036)
    at e.ɵfac [as factory] (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:303:6811)
    at ty (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:79:24564)
    at gBe (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:79:69495)
    at ny.create (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:79:68015)
    at Uie.createComponent (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:79:71299)
    at e.attachComponentPortal (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:88:341483)
    at e.attachComponentPortal (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:90:70187)
    at e.attachComponentPortal (file:///snap/superproductivity/2173/resources/app.asar/dist/browser/main-TEHKTKUW.js:90:82061)
```

### Actions Before Error
```
1734527185700: [Task] SetCurrentTask 
1734527186371: [Task] Add time spent 
1734527186384: [Project] Update Work End 
1734527186384: [Tag] Update Work End for Tag 
1734527186386: [Persistence] Save to DB (3) 
1734527187371: [Task] Add time spent 
1734527187375: [Project] Update Work End 
1734527187376: [Tag] Update Work End for Tag 
1734527187376: [Persistence] Save to DB (3) 
1734527188371: [Task] Add time spent 
1734527188389: [Project] Update Work End 
1734527188390: [Tag] Update Work End for Tag 
1734527188394: [Persistence] Save to DB (3) 
1734527189371: [Task] Add time spent 
1734527189388: [Project] Update Work End 
1734527189389: [Tag] Update Work End for Tag 
1734527189392: [Persistence] Save to DB (3) 
1734527190229: [Task] Update Task 
1734527190249: [Persistence] Save to DB 
1734527190371: [Task] Add time spent 
1734527190375: [Project] Update Work End 
1734527190376: [Tag] Update Work End for Tag 
1734527190377: [Persistence] Save to DB (3) 
1734527191371: [Task] Add time spent 
1734527191390: [Project] Update Work End 
1734527191392: [Tag] Update Work End for Tag 
1734527191394: [Persistence] Save to DB (3) 
1734527191718: [Task] Update Task 
1734527191737: [Persistence] Save to DB 
1734527191737: [Task] UnsetCurrentTask
```

**Comment by Lukas-Pavlusek** [comment]
Hi, I have the same problem. 

Marking a sub-task of a JIRA task as done will throw error. 
If you track your time directly on a JIRA task and "Mark it Done" the dialog for submitting work time works fine.

Thank you

**Comment by ZoranMedojevic** [comment]
@Lukas-Pavlusek thanks, this could do the trick as temp solution.

I hope sub-tasks logging will be fixed soon.
I have some management tickets like `Communication` where i log time as sub-task to create individual worklog records (or tickets that are multiday work so sub-tasks are very useful).

**Comment by johannesjo** [comment]
Thank you very much for reporting! This will be fixed with the next release.

**Comment by ZoranMedojevic** [comment]
@johannesjo thanks 👍

**Comment by ZoranMedojevic** [comment]
@johannesjo works now, thanks a lot :100:
