### ISSUE TITLE
Error: Expected value NOT to be null (crash on marking OpenProject tasks as done)

### ISSUE THREAD

**Issue by heilerich** [johannesjo/super-productivity#3779]
### Steps to Reproduce

1. Have the OpenProject integration and time tracking enabled
2. Spend some time on a task imported from OpenProject
3. Mark the task as done
4. Error (instead of time tracking modal)

This also happens on sub-tasks. It also happens when transition handling is enabled. Basically every time a modal for submitting information to OpenProject is supposed to show up.

### Console Output
```
[Persistence] Save to DB Object
action-logger.reducer.ts:11 [Persistence] Save to DB Object
take-a-break.service.ts:223 _tick$ 999
action-logger.reducer.ts:11 [Task] Update Task Object
play-done-sound.ts:16 ./assets/snd/done2.mp3
action-logger.reducer.ts:11 [Persistence] Save to DB Object
action-logger.reducer.ts:11 [Task] UnsetCurrentTask Object
global-error-handler.class.ts:24 GLOBAL_ERROR_HANDLER Error: Expected value NOT to be null
    at ho (assert-truthy.ts:7:13)
    at new i (dialog-open-project-track-time.component.ts:55:35)
    at i.ɵfac [as factory] (dialog-open-project-track-time.component.ts:195:3)
    at tb (core.mjs:5289:38)
    at aLe (core.mjs:17545:31)
    at rb.create (core.mjs:17401:21)
    at Sie.createComponent (core.mjs:17806:43)
    at t.attachComponentPortal (portal.mjs:527:36)
    at t.attachComponentPortal (dialog.mjs:215:41)
    at t.attachComponentPortal (dialog.mjs:293:25)
(anonymous) @ global-error-handler.class.ts:24
action-logger.ts:39 Last actions before error: Array(30)
global-error-handler.util.ts:113 Object
zone.js:2230 Error: Error: Expected value NOT to be null
    at i.<anonymous> (global-error-handler.class.ts:45:13)
    at Generator.next (<anonymous>)
    at n (chunk-HMYXOI6C.js:1:1816)
    at s.invoke (zone.js:342:158)
    at T.run (zone.js:111:37)
    at zone.js:2431:30
    at s.invokeTask (zone.js:367:171)
    at T.runTask (zone.js:164:39)
    at re (zone.js:538:23)
    at c.invokeTask [as invoke] (zone.js:447:11)
n.onUnhandledError @ zone.js:2230
Show 1 more frame
Show less
console.js:86 11:15:11.241 › Frontend Error: Error: Expected value NOT to be null
    at ho (assert-truthy.ts:7:13)
    at new i (dialog-open-project-track-time.component.ts:55:35)
    at i.ɵfac [as factory] (dialog-open-project-track-time.component.ts:195:3)
    at tb (core.mjs:5289:38)
    at aLe (core.mjs:17545:31)
    at rb.create (core.mjs:17401:21)
    at Sie.createComponent (core.mjs:17806:43)
    at t.attachComponentPortal (portal.mjs:527:36)
    at t.attachComponentPortal (dialog.mjs:215:41)
    at t.attachComponentPortal (dialog.mjs:293:25) Error: Expected value NOT to be null
    at ho (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:273:2618)
    at new i (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:320:3698)
    at i.ɵfac [as factory] (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:320:6268)
    at tb (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:19417)
    at aLe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:70489)
    at rb.create (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:68975)
    at Sie.createComponent (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:72324)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:88:349732)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:90:70114)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:90:82108)
(anonymous) @ console.js:86
Show 1 more frame
Show less
console.js:86 11:15:11.798 › Frontend Error Stack: Error (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/util/assert-truthy.ts:7:12)
assertTruthy (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/features/issue/providers/open-project/open-project-view-components/dialog-open-project-track-time/dialog-open-project-track-time.component.ts:55:34)
this._convertTimestamp(Date.now (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/features/issue/providers/open-project/open-project-view-components/dialog-open-project-track-time/dialog-open-project-track-time.component.ts:195:2)
setIncludeViewProviders (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:5289:37)
initializeDirectives (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17545:30)
setRootNodeAttributes (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17401:20)
_injector.get (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17806:42)
attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/cdk/fesm2022/portal.mjs:527:35)
this._portalOutlet.hasAttached (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/cdk/fesm2022/dialog.mjs:215:40)
attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/dialog.mjs:293:24)
(anonymous) @ console.js:86
O.<computed> @ zone.js:1755
invokeTask @ zone.js:367
runTask @ zone.js:164
invokeTask @ zone.js:444
_.useG.invoke @ zone.js:433
g.args.<computed> @ zone.js:1722
```

### Meta Info
META: SP11.0.2 __ Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/11.0.2 Chrome/130.0.6723.137 Electron/33.2.1 Safari/537.36

### Stacktrace
```
Error: Expected value NOT to be null
    at ho (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:273:2618)
    at new i (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:320:3698)
    at i.ɵfac [as factory] (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:320:6268)
    at tb (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:19417)
    at aLe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:70489)
    at rb.create (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:68975)
    at Sie.createComponent (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:79:72324)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:88:349732)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:90:70114)
    at t.attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-2MTGH7KM.js:90:82108)
```

### Actions Before Error
```
1734689702723: [Task] Add time spent 
1734689702725: [Project] Update Work End 
1734689702726: [Persistence] Save to DB (2) 
1734689703722: [Task] Add time spent 
1734689703724: [Project] Update Work End 
1734689703726: [Persistence] Save to DB (2) 
1734689704723: [Task] Add time spent 
1734689704726: [Project] Update Work End 
1734689704727: [Persistence] Save to DB (2) 
1734689705723: [Task] Add time spent 
1734689705728: [Project] Update Work End 
1734689705729: [Persistence] Save to DB (2) 
1734689706722: [Task] Add time spent 
1734689706725: [Project] Update Work End 
1734689706726: [Persistence] Save to DB (2) 
1734689707723: [Task] Add time spent 
1734689707725: [Project] Update Work End 
1734689707726: [Persistence] Save to DB (2) 
1734689708728: [Task] Add time spent 
1734689708729: [Project] Update Work End 
1734689708730: [Persistence] Save to DB (2) 
1734689709723: [Task] Add time spent 
1734689709725: [Project] Update Work End 
1734689709725: [Persistence] Save to DB (2) 
1734689710723: [Task] Add time spent 
1734689710726: [Project] Update Work End 
1734689710728: [Persistence] Save to DB (2) 
1734689710879: [Task] Update Task 
1734689710889: [Persistence] Save to DB 
1734689710889: [Task] UnsetCurrentTask
```

**Comment by heilerich** [comment]
This has been mentioned as fixed in the 11.0.3 release, but is still an issue. The new stacktrace when closing a sub-task looks like this

```
this._convertTimestamp(Date.now (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/features/issue/providers/open-project/open-project-view-components/dialog-open-project-track-time/dialog-open-project-track-time.component.ts:204:38)
_getCfgOnce$ (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/features/issue/providers/open-project/open-project-view-components/dialog-open-project-track-time/dialog-open-project-track-time.component.ts:56:21)
this._convertTimestamp(Date.now (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/src/app/features/issue/providers/open-project/open-project-view-components/dialog-open-project-track-time/dialog-open-project-track-time.component.ts:209:2)
setIncludeViewProviders (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:5289:37)
initializeDirectives (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17545:30)
setRootNodeAttributes (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17401:20)
_injector.get (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:17806:42)
attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/cdk/fesm2022/portal.mjs:527:35)
this._portalOutlet.hasAttached (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/cdk/fesm2022/dialog.mjs:215:40)
attachComponentPortal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/dialog.mjs:293:24)
```

This is the stacktrace when transition handling is enabled and I start a task

```
TypeError: Cannot read properties of null (reading 'writeValue')
    at XO (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:90:117795)
    at t._setUpStandalone (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:90:125844)
    at t._setUpControl (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:90:125560)
    at t.ngOnChanges (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:90:125108)
    at t.rFe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:8278)
    at SZ (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:14624)
    at wFe (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:14784)
    at Zee (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:14529)
    at uA (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:14253)
    at tie (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/main-KGRCLP6T.js:79:49845)
```

Let me know if I can provide any additional information.

**Comment by heilerich** [comment]
Also this is the error shown when marking an imported issue as done (not a sub-task)

```
TypeError: Cannot read properties of null (reading 'writeValue')

_initUINonRange (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/slider.mjs:700:13)
this._cdr.detectChanges (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/material/fesm2022/slider.mjs:692:63)
callHookInternal (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:4168:9)
callHook (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:4192:6)
assertEqual(isInCheckNoChangesMode (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:4152:8)
assertNotEqual (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:4107:4)
executeCheckHooks (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:14522:10)
isExhaustiveCheckNoChanges (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:14658:4)
viewAttachedToChangeDetector (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:14620:2)
detectChangesInComponent (file:///Applications/Super%20Productivity.app/Contents/Resources/app.asar/dist/browser/node_modules/@angular/core/fesm2022/core.mjs:14609:2)
```

**Comment by heilerich** [comment]
The transition and time tracking features work now, but the settings for the time tracking seem to be gone? I had to use the developer tools debugger to re-enable the feature.
![Screenshot 2025-01-09 at 17 56 28@2x](https://github.com/user-attachments/assets/cf03814e-184a-43f8-b72b-1282d5403637)

**Comment by johannesjo** [comment]
@heilerich you need to expand the "Advanced Config" collabsible.
