### ISSUE TITLE
Global shortcut registration failed: CTRL+Shift+X in Wayland

### ISSUE THREAD

**Issue by ghost** [johannesjo/super-productivity#3789]
### Your Environment

- Version used:  Flatpak (flathub user) 11.0.3
- Operating System and version: Fedora Linux 41 x86_64
- Kernel: Linux 6.12.5-200.fc41.x86_64
- Desktop Environment:   KDE Plasma 6.2.4
- Browser Name and version: 

### Expected Behavior
The shortcut CTRL+Shift+X should work under Wayland when legacy X11 app support is disabled.

### Current Behavior
On start  I get the following message every time.
![image](https://github.com/user-attachments/assets/eacbce22-97f7-4c59-96f6-21d72c3101e7)

It should allow the shortcut to wor under Wayland without relaying on legacy X11 support.

### Steps to Reproduce (for bugs)
1. In the settings on KDE disable the global shortcuts like done in the image.
![image](https://github.com/user-attachments/assets/170186ad-84a6-40b0-9d9a-480a4c1d45ae)

2. Add ELECTRON_OZONE_PLATFORM_HINT = auto as a variable under Flatpak permissions in the settings
![image](https://github.com/user-attachments/assets/0f6cef5a-07d6-45ae-87d6-7e023f753f02)

3. Close all SuperProductivity instances.
4. Start SuperProductivity again and see the error message.

### Can you reproduce this reliably?

Yes, this happens every time I start the program.

### Error Log (Desktop only)
flatpak run com.super_productivity.SuperProductivity 
[3:1223/121905.285229:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Start app...
12:19:05.715 › { enabled: null, showDevTools: false, mode: 'bottom' }
[3:1223/121905.872889:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1223/121905.873004:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Saving backups to /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
12:19:05.991 › Saving backups to /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
[3:1223/121906.004884:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1223/121906.004995:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1223/121906.005059:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
12:19:07.739 › No custom styles detected at /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/styles.css
ERR Global Shortcut registration failed: Ctrl+Shift+X
12:19:07.915 › Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/app/superproductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /app/superproductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:518:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86665)
    at WebContents.emit (node:events:518:28)
12:19:07.916 › Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/app/superproductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /app/superproductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:518:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86665)
    at WebContents.emit (node:events:518:28)
12:19:07.917 › Additional Error info:  Ctrl+Shift+X
^C
[3 preload-host-spawn-strategy] Dropping 0x1f9000038d80 (3) because of connection closed                                                                                                                             
12:28:40.389 › close, isQuiting: null
[3:1223/122840.391080:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting.

**Comment by Adamantt777** [comment]
That notification of error "Global shortcut registration failed" also appeared when using two instances of super productivity on windows: a portable installation on a different folder using the parameter --user-data-dir, and a normal installation on windows 10 folders. But the programs works normally simultaneously.

**Comment by johannesjo** [comment]
The message is correct then as only one of the app instances can register the shortcut. Imho there is nothing to do here. If you have multiple apps binding the same shortcut, it's expected that things don't work properly for both. 

You can change the global shortcut to make the message go away.

**Comment by Adamantt777** [comment]
> The message is correct then as only one of the app instances can register the shortcut. Imho there is nothing to do here. If you have multiple apps binding the same shortcut, it's expected that things don't work properly for both.
> 
> You can change the global shortcut to make the message go away.

I just find out that the web version is simply this link: https://app.super-productivity.com/ I didn't saw it before because the link is not in the "Web Version" description part of the super productivity github page, only the extension is there and that was confusing.

But this solves all my issues, I can use the web version synced with my phone app. and have the windows desktop installed with the older version of super productivity that I like to use. Y use two Dropbox account for this, because the app have the update version and forces me to update the windows old version. So having two dropbox accounts was the solution (one for windows only, and the other for web version and android app sync. and the web version is only used to import the backup file from the windows desktop to the app. This could be a way to solve the import feature to the app in the future.
Thank you for your answer anyway, have a good one.

**Comment by ridicolos** [comment]
I would also be nice if you could run the super-productivity command with a parameter to toggle some of the features that these shortcuts toggle. This would be great for Windows-Managers users but would also allow users to set the keybinds on the Desktop-Environment-Level.

**Comment by cdnia** [comment]
> The message is correct then as only one of the app instances can register the shortcut. Imho there is nothing to do here. If you have multiple apps binding the same shortcut, it's expected that things don't work properly for both.
> 
> You can change the global shortcut to make the message go away.

Hi @johannesjo , I have only one instance running and I changed the global shortcut to no shortcut but the error message still shows up everytime I opened the app. I attached a screenshot of my global shortcut settings. 
<img width="1164" height="359" alt="Image" src="https://github.com/user-attachments/assets/dfa9c20b-9792-46a0-b35f-35bf328bed39" />

**Comment by gozes** [comment]
On fedora by flatpak the short cut dose not work but no error is shown. the flatpak also dose not have a "shortcut" portal

<img width="745" height="355" alt="Image" src="https://github.com/user-attachments/assets/3a71b41c-6e39-4424-a82b-7b73a7102682" />

**Comment by StrNamePete** [comment]
I have the same issue on Fedora Linux 44 (Workstation Edition) with GNOME 50. 
Super Productivity is installed as a flatpak, version 18.19.0FP. 

The global shortcuts don't work and whenever I start Super Productivity, I receive the " Global Shortcut registration failed" message. It also appears each time I change the shortcuts. I have checked my device settings, but there are no other shortcuts registered with the same key combinations.

**Comment by Zoriot** [comment]
The current failure for me is slightly different: registration succeeds on the first launch and only breaks after restarting the app.

### Environment

* Super Productivity: 19.0.1 Flatpak
* Flatpak ID: `com.super_productivity.SuperProductivity`
* OS: Bazzite / Fedora 44
* KDE Plasma: 6.7.5
* `xdg-desktop-portal-kde`: 6.7.5-1.fc44.x86_64
* `xdg-desktop-portal`: 1.22.1-1.fc44.x86_64
* Session: Wayland

### Behavior

If I delete the Super Productivity shortcut from KDE System Settings and then start SP:

1. KDE asks me to configure/confirm the shortcut.
2. The shortcut works correctly in that session.
3. `org.freedesktop.portal.GlobalShortcuts.Activated` is emitted when pressing it.

After quitting SP completely and starting it again:

1. The shortcut is still visible in KDE System Settings.
2. Pressing it does nothing.
3. No `Activated` signal is emitted.

The KDE shortcut entry is stored under the correct Flatpak application ID:

```ini
[com.super_productivity.SuperProductivity]
...-Ctrl+Shift+X=Ctrl+Shift+X,Ctrl+Shift+X,Super Productivity shortcut: Ctrl+Shift+X
_k_friendly_name=Super Productivity
```

### D-Bus / portal finding

On the first launch after deleting/recreating the shortcut, the portal flow includes:

```text
CreateSession
ListShortcuts
BindShortcuts
```

and the shortcut works.

On the next application launch, the persisted shortcut is returned by `ListShortcuts`, but Chromium/Electron does not call `BindShortcuts` for the newly created session.

The result is:

```text
CreateSession
ListShortcuts
(no BindShortcuts)
(no Activated when pressing the shortcut)
```

Deleting the KDE shortcut forces `BindShortcuts` to happen again on the next launch, after which it works until SP is restarted.

This appears to be caused by Chromium's Linux GlobalShortcuts implementation rather than Super Productivity itself.

I reported the Chromium side here:

[https://issues.chromium.org/issues/563913129](https://issues.chromium.org/issues/563913129)

There is also KDE Bug 524138 about the GlobalShortcuts session-startup compatibility change.

### Possible SP workaround

Until this is fixed in Chromium/Electron, SP could potentially work around it on Wayland by using the XDG GlobalShortcuts portal directly and calling `BindShortcuts` for every newly created session, even when the shortcut is already persisted.

### Local Workaround

When the SU Flatpak is changed to X11 again and it's started with ``flatpak run com.super_productivity.SuperProductivity --ozone-platform=x11`` global shortcuts work fine.
