### ISSUE TITLE
Error: Error retrieving icon :repeat! Http failure response for assets/icons/repeat.svg: 0 Unknown Error

### ISSUE THREAD

**Issue by rigelq** [johannesjo/super-productivity#3794]
### Steps to Reproduce

1. Im just trying to start the app.
2.
3.
4.

### Meta Info
META: SP11.0.3_L1A __ Browser – sv-SE – Linux aarch64 – Mozilla/5.0 (Linux Android 5.0 SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

### Stacktrace
```
RM._error (https://app.super-productivity.com/main-7C65B2HP.js:89:20947)
RM.__tryOrUnsub (https://app.super-productivity.com/main-7C65B2HP.js:75:4161)
RM.error (https://app.super-productivity.com/main-7C65B2HP.js:75:3583)
t._error (https://app.super-productivity.com/main-7C65B2HP.js:75:2633)
t.error (https://app.super-productivity.com/main-7C65B2HP.js:75:2430)
A4._error (https://app.super-productivity.com/main-7C65B2HP.js:75:2633)
A4.error (https://app.super-productivity.com/main-7C65B2HP.js:75:2430)
qU._error (https://app.super-productivity.com/main-7C65B2HP.js:75:2633)
qU.error (https://app.super-productivity.com/main-7C65B2HP.js:75:2430)
qU._error (https://app.super-productivity.com/main-7C65B2HP.js:75:2633)
```

### Actions Before Error
```
1734639136732: [Layout] Hide Notes 
1734639138391: [Task] Update Task 
1734654603595: [Persistence] Save to DB (18) 
1734654603699: [SP_ALL] Load(import) all data 
1734654603711: [Persistence] Remove from DB 
1734654608632: [Layout] Show AddTaskBar 
1734654620820: [Task][Issue] Add Task 
1734654620826: [Persistence] Save to DB (2) 
1734654627590: [Layout] Hide AddTaskBar 
1734904467053: [FocusMode] Set focus session elapsed time 
1734904467222: [SP_ALL] Load(import) all data 
1734904467227: [SP_ALL] All Data was loaded 
1734904488483: [FocusMode] Set focus session elapsed time 
1734904488747: [SP_ALL] Load(import) all data 
1734904488752: [SP_ALL] All Data was loaded 
1735015850646: [FocusMode] Set focus session elapsed time 
1735015850878: [SP_ALL] Load(import) all data 
1735015850883: [SP_ALL] All Data was loaded 
1735015868016: [FocusMode] Set focus session elapsed time 
1735015868306: [SP_ALL] Load(import) all data 
1735015868310: [SP_ALL] All Data was loaded 
1735015875206: [FocusMode] Set focus session elapsed time 
1735015875415: [SP_ALL] Load(import) all data 
1735015875422: [SP_ALL] All Data was loaded 
1735079993959: [FocusMode] Set focus session elapsed time 
1735079994214: [SP_ALL] Load(import) all data 
1735079994219: [SP_ALL] All Data was loaded 
1735080080191: [FocusMode] Set focus session elapsed time 
1735080080555: [SP_ALL] Load(import) all data 
1735080080562: [SP_ALL] All Data was loaded
```

**Comment by tevearitli001** [comment]
Hello, I have the same problem, both on chromium Android and on PC (firefox and chromium). What would be the first steps to debug this problem ?

Nevertheless a very good project that's worth intention, very helpful !!

**Comment by johannesjo** [comment]
@tevearitli001 is just opening the webpage bringing up this error?

**Comment by tevearitli001** [comment]
Yes just opening the webpage just like one day after setting the project up and re-checking the page on chromium or Firefox, or Bing (all on arch linux) or via chromium on Android.

The project is available via via docker, nginx reverse proxy + authentik and on arch linux server also.

I could not find logs in the container, but I checked the console on the client navigator and I see multiple errors (see image below). Here it seems like elements in assets folder cannot be retrieved (which is coherent with absence of icons and UI elements on the webpage. Here below is also an error log in the navigator:

`polyfills-VRABRW6Y.js:1 
 Error: [object Object]
    at n.<anonymous> (main-4PAZ2Q4F.js:136:27312)
    at Generator.next (<anonymous>)
    at n (chunk-HMYXOI6C.js:1:1816)
    at s.invoke (polyfills-VRABRW6Y.js:1:42522)
    at T.run (polyfills-VRABRW6Y.js:1:37775)
    at polyfills-VRABRW6Y.js:2:554
    at s.invokeTask (polyfills-VRABRW6Y.js:1:43147)
    at T.runTask (polyfills-VRABRW6Y.js:1:38417)
    at re (polyfills-VRABRW6Y.js:1:45190)
    at c.invokeTask [as invoke] (polyfills-VRABRW6Y.js:1:44250)
n.onUnhandledError	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
n.microtaskDrainDone	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
IndexedDB		
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	chunk-HMYXOI6C.js:1
j	@	polyfills-VRABRW6Y.js:2
u	@	chunk-HMYXOI6C.js:1
o	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
n	@	chunk-HMYXOI6C.js:1
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
IndexedDB		
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	chunk-HMYXOI6C.js:1
j	@	polyfills-VRABRW6Y.js:2
u	@	chunk-HMYXOI6C.js:1
o	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
n	@	chunk-HMYXOI6C.js:1
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
IndexedDB		
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	chunk-HMYXOI6C.js:1
j	@	polyfills-VRABRW6Y.js:2
u	@	chunk-HMYXOI6C.js:1
o	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
n	@	chunk-HMYXOI6C.js:1
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
IndexedDB		
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	chunk-HMYXOI6C.js:1
j	@	polyfills-VRABRW6Y.js:2
u	@	chunk-HMYXOI6C.js:1
o	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
n	@	chunk-HMYXOI6C.js:1
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
IndexedDB		
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
(anonymous)	@	chunk-HMYXOI6C.js:1
j	@	polyfills-VRABRW6Y.js:2
u	@	chunk-HMYXOI6C.js:1
o	@	main-4PAZ2Q4F.js:125
(anonymous)	@	main-4PAZ2Q4F.js:125
n	@	chunk-HMYXOI6C.js:1
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
_.useG.invoke	@	polyfills-VRABRW6Y.js:1
g.args.<computed>	@	polyfills-VRABRW6Y.js:1
setTimeout		
l	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
onScheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleMacroTask	@	polyfills-VRABRW6Y.js:1
oi	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:1
n.<computed>	@	polyfills-VRABRW6Y.js:1
kf	@	main-4PAZ2Q4F.js:73
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
__tryOrUnsub	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
notifyError	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
notifyError	@	main-4PAZ2Q4F.js:75
_error	@	main-4PAZ2Q4F.js:75
error	@	main-4PAZ2Q4F.js:75
u	@	main-4PAZ2Q4F.js:130
invokeTask	@	polyfills-VRABRW6Y.js:1
onInvokeTask	@	main-4PAZ2Q4F.js:79
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
invokeTask	@	polyfills-VRABRW6Y.js:1
P	@	polyfills-VRABRW6Y.js:1
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
error		
T	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
onScheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleEventTask	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	main-4PAZ2Q4F.js:130
_trySubscribe	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
ol	@	main-4PAZ2Q4F.js:75
_innerSub	@	main-4PAZ2Q4F.js:75
_next	@	main-4PAZ2Q4F.js:75
next	@	main-4PAZ2Q4F.js:75
(anonymous)	@	main-4PAZ2Q4F.js:75
_trySubscribe	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
ol	@	main-4PAZ2Q4F.js:75
_innerSub	@	main-4PAZ2Q4F.js:75
_tryNext	@	main-4PAZ2Q4F.js:75
_next	@	main-4PAZ2Q4F.js:75
next	@	main-4PAZ2Q4F.js:75
(anonymous)	@	main-4PAZ2Q4F.js:75
_trySubscribe	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
(anonymous)	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
(anonymous)	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
call	@	main-4PAZ2Q4F.js:75
subscribe	@	main-4PAZ2Q4F.js:75
loadAndCompileTranslations	@	main-4PAZ2Q4F.js:125
retrieveTranslations	@	main-4PAZ2Q4F.js:125
setDefaultLang	@	main-4PAZ2Q4F.js:125
setDefault	@	main-4PAZ2Q4F.js:187
n	@	main-4PAZ2Q4F.js:412
n.ɵfac	@	main-4PAZ2Q4F.js:412
Uy	@	main-4PAZ2Q4F.js:79
RPe	@	main-4PAZ2Q4F.js:79
create	@	main-4PAZ2Q4F.js:79
bootstrap	@	main-4PAZ2Q4F.js:79
(anonymous)	@	main-4PAZ2Q4F.js:79
invoke	@	polyfills-VRABRW6Y.js:1
onInvoke	@	main-4PAZ2Q4F.js:79
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
(anonymous)	@	polyfills-VRABRW6Y.js:2
invokeTask	@	polyfills-VRABRW6Y.js:1
onInvokeTask	@	main-4PAZ2Q4F.js:79
invokeTask	@	polyfills-VRABRW6Y.js:1
runTask	@	polyfills-VRABRW6Y.js:1
re	@	polyfills-VRABRW6Y.js:1
Promise.then		
k	@	polyfills-VRABRW6Y.js:1
G	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
onScheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleTask	@	polyfills-VRABRW6Y.js:1
scheduleMicroTask	@	polyfills-VRABRW6Y.js:1
o	@	polyfills-VRABRW6Y.js:2
then	@	polyfills-VRABRW6Y.js:2
postMessage	@	main-4PAZ2Q4F.js:299
postMessageWithOperation	@	main-4PAZ2Q4F.js:299
checkForUpdate	@	main-4PAZ2Q4F.js:299
n	@	main-4PAZ2Q4F.js:299
n.ɵfac	@	main-4PAZ2Q4F.js:299
hydrate	@	main-4PAZ2Q4F.js:79
get	@	main-4PAZ2Q4F.js:79
dMe	@	main-4PAZ2Q4F.js:76
et	@	main-4PAZ2Q4F.js:76
h	@	main-4PAZ2Q4F.js:76
n	@	main-4PAZ2Q4F.js:299
n.ɵfac	@	main-4PAZ2Q4F.js:299
hydrate	@	main-4PAZ2Q4F.js:79
get	@	main-4PAZ2Q4F.js:79
dMe	@	main-4PAZ2Q4F.js:76
et	@	main-4PAZ2Q4F.js:76
h	@	main-4PAZ2Q4F.js:76
(anonymous)	@	main-4PAZ2Q4F.js:131
jne	@	main-4PAZ2Q4F.js:131
t	@	main-4PAZ2Q4F.js:79
hydrate	@	main-4PAZ2Q4F.js:79
get	@	main-4PAZ2Q4F.js:79
dMe	@	main-4PAZ2Q4F.js:76
et	@	main-4PAZ2Q4F.js:76
fj	@	main-4PAZ2Q4F.js:76
r.factory	@	main-4PAZ2Q4F.js:79
hydrate	@	main-4PAZ2Q4F.js:79
get	@	main-4PAZ2Q4F.js:79
dMe	@	main-4PAZ2Q4F.js:76
et	@	main-4PAZ2Q4F.js:76
n.ɵfac	@	main-4PAZ2Q4F.js:131
t	@	main-4PAZ2Q4F.js:79
hydrate	@	main-4PAZ2Q4F.js:79
get	@	main-4PAZ2Q4F.js:79
dMe	@	main-4PAZ2Q4F.js:76
et	@	main-4PAZ2Q4F.js:76
useValue	@	main-4PAZ2Q4F.js:79
resolveInjectorInitializers	@	main-4PAZ2Q4F.js:79
(anonymous)	@	main-4PAZ2Q4F.js:79
invoke	@	polyfills-VRABRW6Y.js:1
onInvoke	@	main-4PAZ2Q4F.js:79
invoke	@	polyfills-VRABRW6Y.js:1
run	@	polyfills-VRABRW6Y.js:1
run	@	main-4PAZ2Q4F.js:79
bFe	@	main-4PAZ2Q4F.js:79
WZ	@	main-4PAZ2Q4F.js:79
kne	@	main-4PAZ2Q4F.js:130
(anonymous)	@	main-4PAZ2Q4F.js:413`

Moreover, I see CORS errors (second picture) but maybe it's totally orthogonal to this icons problem.

I can help debug this on my own, I would maybe need some help installing the environment and a few tips on how to debug the code. Thank you and thank you again for this wonderful project !

![Image](https://github.com/user-attachments/assets/c325c376-7d5a-40a8-a7e6-a17d9e531634)

![Image](https://github.com/user-attachments/assets/1a645b8e-df51-49d4-ab52-15260fcea040)

**Comment by tevearitli001** [comment]
I resolved the error and I think I know the reason.

Basically from my understanding the docker was sending HTTPS request to itself (for fetching media and assets files mainly) and this caused my reverse proxy nginx to redirect the requests to my authentification system (like any external requests), namely authentik, but here the request came internally thus authentification does not make sense.

Authentik does not support CORS at that time for reverse proxy (forward auth). Therefore I added this code below above the line `location \ {` in order to pre-empt it:

```
location ~ ^/(assets|media|manifest\.json|ngsw.*) {
        proxy_pass http://127.0.0.1:<internal_port>;  # ✅ No path in proxy_pass
        proxy_set_header Host $host;

        add_header "Access-Control-Allow-Origin" "*" always;
        add_header "Access-Control-Allow-Credentials" "true" always;
        add_header "Access-Control-Allow-Methods" "GET, OPTIONS" always;
        add_header "Access-Control-Allow-Headers" "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range" always;
        add_header "Access-Control-Expose-Headers" "Content-Length,Content-Range" always;
    }

```
I might try one day to change the * of allowed CORS to only my domain name (which should be sufficient), but for now it seems I do not have any problem now in the console and I got back the icons, both on all my browsers and on android ! a few page refresh made it.
