### ISSUE TITLE
Error: Project not found

### ISSUE THREAD

**Issue by pedrohcan** [johannesjo/super-productivity#454]
### Steps to Reproduce

1. Shutdown the computer the nigth before
2. Open the project the next day
3. Receive a bunch of alerts saying that some tasks have been associated with the wrong project and should be deleted
4. Start receiving errors as soon as you create a new task
5. Close and reopen, reload the app or restart everything and still receive the error :(
6. Ignore the warning, click on every project and confirm the deletion of the task with wrong project ID
7. The app works! :)
8. Close and open the app again and the error is back :(

### Error Log (Desktop only)

[2020-07-24 11:17:44.667] [error] Frontend Error: Error: Project not found
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2232561
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587471
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at dt (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587025)
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587525
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at e.project (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586180)
    at e._next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:159226)
    at e.next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:573610)
    at e._subscribe (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:75355) Error: Project not found
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2232561
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587471
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at dt (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587025)
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587525
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at e.project (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586180)
    at e._next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:159226)
    at e.next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:573610)
    at e._subscribe (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:75355)
[2020-07-24 11:17:48.943] [error] Frontend Error Stack: Error (webpack:///src/app/features/project/store/project.reducer.ts:75:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)
[2020-07-24 11:17:57.800] [error] Frontend Error: Error: Project not found
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2232561
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587471
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at dt (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587025)
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587525
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at e.project (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586180)
    at e._next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:159226)
    at e.next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:573610)
    at e._subscribe (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:75355) Error: Project not found
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2232561
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587471
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at dt (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587025)
    at file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2587525
    at memoized (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586558)
    at e.project (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:2586180)
    at e._next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:159226)
    at e.next (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:573610)
    at e._subscribe (file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js:1:75355)
[2020-07-24 11:18:01.564] [error] Frontend Error Stack: Error (webpack:///src/app/features/project/store/project.reducer.ts:75:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)

### Console Output

electron/js2c/renderer_init.js:82 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ electron/js2c/renderer_init.js:82
t.invoke @ polyfills.aebe8ecc43d658291381.js:1
e.run @ polyfills.aebe8ecc43d658291381.js:1
(anonymous) @ polyfills.aebe8ecc43d658291381.js:1
t.invokeTask @ polyfills.aebe8ecc43d658291381.js:1
e.runTask @ polyfills.aebe8ecc43d658291381.js:1
b @ polyfills.aebe8ecc43d658291381.js:1
main.fd58362f53e9a5e6b70d.js:1 Persistent store granted
main.fd58362f53e9a5e6b70d.js:1 1 out of 13010 MiB used (0%)
main.fd58362f53e9a5e6b70d.js:1 Migrating model "task" to version from 3.1313 to 3.3333 Object
main.fd58362f53e9a5e6b70d.js:1 Migrating model "task" to version from 3.1313 to 3.3333 Object
main.fd58362f53e9a5e6b70d.js:1 24-07-2020 --- 11:16:27
main.fd58362f53e9a5e6b70d.js:1 24-07-2020 --- 11:16:27
main.fd58362f53e9a5e6b70d.js:1 false "2020-07-24T14:16:27.798Z" 1595600187798
main.fd58362f53e9a5e6b70d.js:1 GLOBAL_ERROR_HANDLER Error: Project not found
    at main.fd58362f53e9a5e6b70d.js:1
    at main.fd58362f53e9a5e6b70d.js:1
    at memoized (main.fd58362f53e9a5e6b70d.js:1)
    at dt (main.fd58362f53e9a5e6b70d.js:1)
    at main.fd58362f53e9a5e6b70d.js:1
    at memoized (main.fd58362f53e9a5e6b70d.js:1)
    at e.project (main.fd58362f53e9a5e6b70d.js:1)
    at e._next (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e._subscribe (main.fd58362f53e9a5e6b70d.js:1)
t.handleError @ main.fd58362f53e9a5e6b70d.js:1
main.fd58362f53e9a5e6b70d.js:1 META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36
polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: Project not found
    at t.handleError (main.fd58362f53e9a5e6b70d.js:1)
    at Object.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.o [as _next] (main.fd58362f53e9a5e6b70d.js:1)
    at e.__tryOrUnsub (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e._next (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.next (main.fd58362f53e9a5e6b70d.js:1)
    at e.emit (main.fd58362f53e9a5e6b70d.js:1)
    at main.fd58362f53e9a5e6b70d.js:1
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/reminder.fc53a8950e2e9cd6c010.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/lz.758d42083f84b546d14c.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/runtime.c51bd5b1c616d9ffddc1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/main.fd58362f53e9a5e6b70d.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///snap/superproductivity/716/resources/app.asar/dist/styles.7019285b763bf4d29f54.css.map: 
main.fd58362f53e9a5e6b70d.js:1 Error (webpack:///src/app/features/project/store/project.reducer.ts:75:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)
main.fd58362f53e9a5e6b70d.js:1 <a href=​"https:​/​/​github.com/​johannesjo/​super-productivity/​issues/​new?body=%23…3.122+Electron%2F9.1.0+Safari%2F537.36%0A&title=Error%3A+Project+not+found" id=​"github-issue-url" target=​"_blank">​! Please copy & report !​</a>​

### Stacktrace
```
Error (webpack:///src/app/features/project/store/project.reducer.ts:75:12)
memoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:627:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
selectors.map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:601:38)
defaultMemoize(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:630:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/fesm5/store.js:576:37)
source$.pipe(map(function (webpack:///node_modules/@ngrx/store/fesm5/store.js:513:66)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_super.prototype._subscribe.call (webpack:///node_modules/rxjs/_esm5/internal/BehaviorSubject.js:22:23)
```

### Meta Info
META: SP5.5.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment]
Thank you very much for reporting!  Would you by any chance be willing to provide me with a copy of your personal data so I can try to reproduce the issue on my computer? You can send it to contact@super-productivity.com.

**Comment by pedrohcan** [comment]
Everything was sorted out! Thanks!
