### ISSUE TITLE
Error: Error: Value is null

### ISSUE THREAD

**Issue by bpcliff** [johannesjo/super-productivity#460]
### Steps to Reproduce

1.  Had an existing task that I had completed.  I decided to make it repeating so I opened that dialogue box.   Note that it had two additional tags (along with the **Today** tag).
2.  I added in Saturday & Sunday (clicked on selection box)
3.  Hit _Save_ button
4.

### Error Log (Desktop only)

_There was no log.log file.  However, there was a main.log file.  (Note - the first line is probably a carryover from where I was trying to configure a project to hook into a personal JIRA account.)_

[2020-07-25 11:06:11.828] [error] Frontend Error: { HANDLED_ERROR_PROP: 'Jira: Unauthorized' } undefined
[2020-07-25 11:06:11.835] [error] Frontend Error Stack: 
[2020-07-25 11:12:36.402] [error] Frontend Error: Error: Value is null
    at r (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:152517)
    at t.save (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:3433701)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:3435184
    at _a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:428912)
    at i (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:429114)
    at HTMLFormElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:1668546)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:476423)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9912)
    at e.runTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:5070) Error: Value is null
    at r (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:152517)
    at t.save (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:3433701)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:3435184
    at _a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:428912)
    at i (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:429114)
    at HTMLFormElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:1668546)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:476423)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9912)
    at e.runTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:5070)
[2020-07-25 11:12:36.405] [error] Frontend Error: Error: Error: Value is null
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:4104177)
    at Yi (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:405704)
    at _a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:428933)
    at i (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:429114)
    at HTMLFormElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:1668546)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:476423)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9912)
    at e.runTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:5070)
    at e.invokeTask [as invoke] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:11123) Error: Error: Value is null
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:4104177)
    at Yi (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:405704)
    at _a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:428933)
    at i (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:429114)
    at HTMLFormElement.<anonymous> (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:1668546)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.783738af98800c234484.js:1:476423)
    at t.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9912)
    at e.runTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:5070)
    at e.invokeTask [as invoke] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:11123)
[2020-07-25 11:12:38.455] [error] Frontend Error Stack: T> (webpack:///src/app/util/exists.ts:3:10)
save (webpack:///src/app/features/task-repeat-cfg/dialog-edit-task-repeat-cfg/dialog-edit-task-repeat-cfg.component.ts:71:77)
save (webpack:///src/app/features/task-repeat-cfg/dialog-edit-task-repeat-cfg/dialog-edit-task-repeat-cfg.component.html:1:16)
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14935:15)
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14976:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
[2020-07-25 11:12:38.457] [error] Frontend Error Stack: isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14976:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:503:37)

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:53:12)
handleError (webpack:///node_modules/@angular/core/fesm5/core.js:9066:33)
listenerFn (webpack:///node_modules/@angular/core/fesm5/core.js:14938:8)
executeListenerWithErrorHandling (webpack:///node_modules/@angular/core/fesm5/core.js:14976:21)
function (webpack:///node_modules/@angular/platform-browser/fesm5/platform-browser.js:615:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:39)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:50)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:503:37)
```

### Meta Info
META: SP5.5.1 Electron – en-US – MacIntel – Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.5.1 Chrome/83.0.4103.122 Electron/9.1.0 Safari/537.36

**Comment by johannesjo** [comment]
Thanks for opening this up. Currently repeating tasks is only allowed for tasks that belong to a project. But this definitely should be handled better. I'll have a look!

About the Jira Error: Normally repeating tasks can't be issues, so I am unsure what the connection is here. `Jira: Unauthorized'` usually means that there is something wrong with the Jira config provided. Sometimes Jira doesn't allow any access from the outside in this case one needs to resort to the new "wonky cookie mode".

**Comment by johannesjo** [comment]
This should (hopefully) be fixed with the next release. Please let me know if it isn't.
