### ISSUE TITLE
McAfee moved to quarantine superProductivity.exe after crash

### ISSUE THREAD

**Issue by JustAPhrog** [johannesjo/super-productivity#532]
### Your Environment

* Version used: 5.6.5.0
* Operating System and version: Windows 10 1909

### Expected Behavior
Possibility to read full description of error without closing an app.

### Current Behavior
Exe file was moved to quarantine by McAfee.

### Steps to Reproduce (for bugs)

1. Open app.
2. Click to project called 'Pozostale' (it is set as *default project to use for tasks if none is specified*)
3. Popup appeard with *TypeError: Cannot read property 'isDone' of null*.
4. After couple of seconds windows closed.
5. In McAfee in quarantine section I can restore file.

### Day before
21.09.2020 I've installed app (again) and before start i've added to shortcut --user-data-dir= parameter. Everything was good with app (creating tasks, done them, comment them, etc.) but in *Pozostale* project there was strange error like *Wrong project id*. I ignore that error end continue using app. I thaught that mayby deleteing default project *superProductivity* (one when I start app) was a bad idea.

### Error Log (Desktop only)

I've cut user profile name in log.

[2020-09-22 07:56:23.370] [error] Frontend Error: TypeError: Cannot read property 'isDone' of null
    at file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:6876
    at Array.filter (<anonymous>)
    at e.I [as project] (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:6847)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:159280)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:717296)
    at e.nextInfiniteTimeWindow (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:1398437)
    at Object.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:2116649)
    at e.__tryOrUnsub (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:575970)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:575115) TypeError: Cannot read property 'isDone' of null
    at file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:6876
    at Array.filter (<anonymous>)
    at e.I [as project] (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:6847)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:159280)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:717296)
    at e.nextInfiniteTimeWindow (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:1398437)
    at Object.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:2116649)
    at e.__tryOrUnsub (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:575970)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:575115)
[2020-09-22 07:56:23.422] [error] Frontend Error: TypeError: Cannot read property 'projectId' of null
    at file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:4179833
    at Array.filter (<anonymous>)
    at e.project (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:4179804)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:159280)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:2336310)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e._subscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:1398918)
    at e.t._trySubscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:171789)
    at e._trySubscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:717886) TypeError: Cannot read property 'projectId' of null
    at file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:4179833
    at Array.filter (<anonymous>)
    at e.project (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:4179804)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:159280)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e._next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:2336310)
    at e.next (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:573862)
    at e._subscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:1398918)
    at e.t._trySubscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:171789)
    at e._trySubscribe (file:///C:/Users/<user>/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.0252e44b9a2d8cc992e4.js:1:717886)
[2020-09-22 07:56:25.025] [error] Frontend Error Stack: hasTasksToWorkOn (webpack:///src/app/features/work-context/work-context.util.ts:21:14)
hasTasksToWorkOn (webpack:///src/app/features/work-context/work-context.util.ts:20:31)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
observers.slice (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:47:24)
_events.push (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js:39:30)
next (webpack:///node_modules/rxjs/_esm5/internal/operators/shareReplay.js:33:49)
__tryOrUnsub (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:192:15)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:130:21)
[2020-09-22 07:56:25.026] [error] Frontend Error Stack: projectId (webpack:///src/app/features/project/store/project.effects.ts:326:55)
filter (webpack:///src/app/features/project/store/project.effects.ts:326:35)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/take.js:40:29)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
subscriber.add (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js:67:27)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:43:24)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:89:50)

**Comment by JustAPhrog** [comment]
Another error when I go to *Pozostale* project but McAfee didnt move it:
### Stacktrace
```
projectId (webpack:///src/app/features/project/store/project.effects.ts:326:55)
filter (webpack:///src/app/features/project/store/project.effects.ts:326:35)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/take.js:40:29)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
subscriber.add (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js:67:27)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:43:24)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:89:50)
```

### Meta Info
META: SP5.6.5 Electron – pl – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.6.5 Chrome/83.0.4103.122 Electron/9.1.1 Safari/537.36

### Actions Before Error
```
1600756518477: [Improvement] Load Improvement State 
1600756518478: [Obstruction] Load Obstruction State 
1600756518478: [Project] Load Project related Data Success 
1600756518479: [Improvement] Clear Hidden Improvements 
1600756518480: [Improvement] Delete multiple Improvements 
1600756519605: [WorkContext] Set Active Work Context 
1600756519615: [Task] SetSelectedTask 
1600756519626: [Note] Load Note State 
1600756519626: [Bookmark] Load Bookmark State 
1600756519627: [Metric] Load Metric State 
1600756519628: [Improvement] Load Improvement State 
1600756519631: [Obstruction] Load Obstruction State 
1600756519631: [Project] Load Project related Data Success 
1600756519631: [Improvement] Clear Hidden Improvements 
1600756519632: [Improvement] Delete multiple Improvements 
1600756520621: [WorkContext] Set Active Work Context 
1600756520633: [Task] SetSelectedTask 
1600756520685: [Note] Load Note State 
1600756520687: [Bookmark] Load Bookmark State 
1600756520690: [Metric] Load Metric State 
1600756520691: [Improvement] Load Improvement State 
1600756520693: [Obstruction] Load Obstruction State 
1600756520695: [Project] Load Project related Data Success 
1600756520695: [Improvement] Clear Hidden Improvements 
1600756520695: [Improvement] Delete multiple Improvements
```

**Comment by johannesjo** [comment]
Hey there! I contacted McAffee about this. I hope they will whitelist the app soon.

Could you maybe provide me with a copy of your data for the other issue and send it to contact@super-productivity.com. I can fix your data and send it back to you.

I am also working on a mechanism to automatically fix corrupted data, but this will take a little bit more time.

**Comment by johannesjo** [comment]
I got on email back from McAffeee:

Could you maybe provide me with information about these three:
McAfee Product Name (Consumer/Enterprise):
Detection Name:
Quarantine log:



> Dear Sir/Madam, 

> Thank you for contacting McAfee. 

> We regret the inconvenience caused. 

> Please provide us the following information to proceed further:
 

> Company Name:
> Company Website:
> McAfee Product Name (Consumer/Enterprise):
> Detection Name:
> Quarantine log:
> Link to download the detected software:
> Functionality of the software: 

> Please revert back to us as early as possible for quick resolution.

> Regards,

> McAfee Data Submission Team

**Comment by JustAPhrog** [comment]
@johannesjo About other issue I realy dont find any problems with tasks.

McAfee Product Name (Consumer/Enterprise): McAfee Endpoint Security (Enterprise) 10.7.0
Feature name: Real Protect Cloud
Detection Name: Trojan horse
Threat timestamp: 22.9.2020 7:56 AM

PS: That app is realy helpfull and this is what I need to be more productive :) Thanks a lot!

**Comment by johannesjo** [comment]
Thank you very much! I submitted the info to McAffee. Let's see what happens next. :)

**Comment by JustAPhrog** [comment]
@johannesjo I've sended (yesterday) to you my currupt data - can you fix it?

**Comment by johannesjo** [comment]
I check it this evening. Meanwhile you can also try the brand new autofixer that is available starting with version 5.9.0.

**Comment by JustAPhrog** [comment]
@johannesjo Ok, I can try but how to update app? simply replace exe file? Im on Win10 and install manually not from MS Store.

**Comment by johannesjo** [comment]
> Ok, I can try but how to update app? simply replace exe file? Im on Win10 and install manually not from MS Store.
If you are using the pen drive version (the exe without the Setup suffix). This should work.

**Comment by johannesjo** [comment]
Also: I just checked, but I got no mail in my mailbox... Did you send it to the right address?

**Comment by JustAPhrog** [comment]
> Also: I just checked, but I got no mail in my mailbox... Did you send it to the right address?

I used this: contact@super-productivity.com

**Comment by JustAPhrog** [comment]
> > Ok, I can try but how to update app? simply replace exe file? Im on Win10 and install manually not from MS Store.
> 
> If you are using the pen drive version (the exe without the Setup suffix). This should work.

No, I used with setup.

**Comment by johannesjo** [comment]
Then you should just execute the newer setup exe and execute it from your download folder. This will install the app over the old version.

**Comment by johannesjo** [comment]
I got another mail...

> Dear Sir/Madam,

 

> Please provide us the detection logs along with the exact detection name which starts with Real Protect -----

 

> Regards,

> McAfee Data Submission Team

**Comment by johannesjo** [comment]
ping @JustAPhrog

**Comment by JustAPhrog** [comment]
Oh, I thaut that I've replied 😋 
Detection name: Real Protect-EC!603D1E1DB4A2
What exatly means:  detection logs? I had 24 files so which one?

**Comment by johannesjo** [comment]
> What exatly means: detection logs? I had 24 files so which one?

Not sure. Maybe the one with the creation date of the issue? If they're not too big maybe all of them :D

**Comment by JustAPhrog** [comment]
@johannesjo  I've send you log by mail to your gmail and contact[AT]superproductivity.com. Check spam 😏

**Comment by johannesjo** [comment]
Thank you very much!

**Comment by johannesjo** [comment]
> Dear Sir/Madam,
> We appreciate your patience.
> We have reviewed the logs and the detection has been suppressed.
> Regards,
> McAfee Data Submission Team

**Comment by johannesjo** [comment]
@JustAPhrog Thank you very much for your help!

**Comment by JustAPhrog** [comment]
@johannesjo I have bad news... I used setup version with separate user-dir and after each update i need to add to shortcut `--user-dir` so I've dowloded `.exe` version. After coulpe seconds after start Mc Afee done it again... Can you contact with them again?

Detection name: Real Protect-EC!463417871E72

I've sent logs to you by mail. Check spam 😉

**Comment by johannesjo** [comment]
Thank you! I'll report this.

**Comment by JustAPhrog** [comment]
Any news? McAfee do this again:

Threat name: Real Protect-EC!463417871E72
Threat timestamp: 4.12.2020 8:44 AM

**Comment by johannesjo** [comment]
> Any news?

No. No reaction yet :(
