### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot assign to read only property '0' of object '[object Array]' 

### ISSUE THREAD

**Issue by venkateshyaali** [johannesjo/super-productivity#538]
### Steps to Reproduce

1.
2.
3.
4.

### Console Output
```
<!-- Is there any output if you press Ctrl+Shift+i (Cmd+Alt+i for mac) in the console tab? If so please post it here. -->
TypeError: Cannot assign to read only property '0' of object '[object Array]'    
    at Array.sort ()   
    at isEntityStateConsistent (http://localhost:4200/main.js:61914:123)
    at http://localhost:4200/main.js:51081:170
    at Array.find ()
    at _isEntityStatesConsistent (http://localhost:4200/main.js:51081:36)
    at isValidAppData (http://localhost:4200/main.js:51025:16)
    at DataInitService. (http://localhost:4200/main.js:4859:128)
    at step (http://localhost:4200/main.js:4804:23)
    at Object.next (http://localhost:4200/main.js:4785:53)
    at fulfilled (http://localhost:4200/main.js:4776:58)
```

### Stacktrace

```
arrayEquals(Object.keys(data.entities).sort (webpack:///src/app/util/check-fix-entity-state-consistency.ts:28:64)
webpack:///src/app/imex/sync/is-valid-app-data.util.ts:102:55
_isEntityStatesConsistent (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:102:18)
isValidAppData (webpack:///src/app/imex/sync/is-valid-app-data.util.ts:33:7)
DataInitService.<anonymous> (webpack:///src/app/core/data-init/data-init.service.ts:53:37)
_.ops.pop (http://localhost:4200/main.js:4804:23)
verb (http://localhost:4200/main.js:4785:53)
fulfilled (http://localhost:4200/main.js:4776:58)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:)
value.hasOwnProperty (webpack:///node_modules/zone.js/dist/zone.js:784:)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:894:)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28132:)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:420:)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone.js:188:)
drainMicroTaskQueue (webpack:///node_modules/zone.js/dist/zone.js:601:)
```

### Meta Info
META: SP5.8.2 Browser – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

### Actions Before Error
```

```

**Comment by johannesjo** [comment]
Thank you very much for reporting. Could you by any chance provide send a copy of your data to contact@super-productivity.com? This would be very helpful.

**Comment by venkateshyaali** [comment]
Thanks for your Response.. I will mail you the details needed..

**Comment by johannesjo** [comment]
Thank you!

**Comment by johannesjo** [comment]
This should be fixed with the next release.
