### ISSUE TITLE
Frontend Error: Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.

### ISSUE THREAD

**Issue by bloodpet** [johannesjo/super-productivity#542]
### Your Environment

* Version used: 5.9.0 (from snap)
* Operating System and version: kde neon 5.19 (based on ubuntu 20.04) uname -a: Linux HOSTNAME 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Desktop Environment: KDE Plasma
* Browser Name and version: N/A

### Expected Behavior
Should have preserved my data after crashing.

### Current Behavior
It crashed & lost my data (preferences, projects & tasks)

### Steps to Reproduce (for bugs)
I had pomodoro, break timer (set to 25mins), & standing desk timer
1. add a new project
2. add a new task
3. disable break timer
4. start task
5. enable break timer (did 3-5 to sync pomodoro & break timer since i don't have speakers/headphones)
it just crashed in the middle of work

### Console Output
This is what the app asked me to copy:
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:2812
```

Warning:
`Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.`

Error:
```
IDLE_TIME 210000 Tue Sep 29 2020 13:39:19 GMT+0800 (Philippine Standard Time)
main.85c5718eafb26d401081.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at S (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at s (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvoke (main.85c5718eafb26d401081.js:1)
    at t.invoke (polyfills.aebe8ecc43d658291381.js:1)
    at e.run (polyfills.aebe8ecc43d658291381.js:1)
    at polyfills.aebe8ecc43d658291381.js:1
    at t.invokeTask (polyfills.aebe8ecc43d658291381.js:1)
    at Object.onInvokeTask (main.85c5718eafb26d401081.js:1)
t.handleError @ main.85c5718eafb26d401081.js:1
main.85c5718eafb26d401081.js:1 Last actions before error: Array(25)
main.85c5718eafb26d401081.js:1 IDLE_TIME 221000 Tue Sep 29 2020 13:39:27 GMT+0800 (Philippine Standard Time)
polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at t.handleError (main.85c5718eafb26d401081.js:1)
    at Object.next (main.85c5718eafb26d401081.js:1)
    at e.o [as _next] (main.85c5718eafb26d401081.js:1)
    at e.__tryOrUnsub (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e._next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.next (main.85c5718eafb26d401081.js:1)
    at e.emit (main.85c5718eafb26d401081.js:1)
    at main.85c5718eafb26d401081.js:1
```

### Error Log (Desktop only)
I only have these files:
```
$ find ~/snap/superproductivity/current/.config/superProductivity/ | grep log
/home/eman/snap/superproductivity/current/.config/superProductivity/Session Storage/000003.log
/home/eman/snap/superproductivity/current/.config/superProductivity/IndexedDB/file__0.indexeddb.leveldb/000158.log
/home/eman/snap/superproductivity/current/.config/superProductivity/Local Storage/leveldb/000028.log
/home/eman/snap/superproductivity/current/.config/superProductivity/superProductivity/logs
```
the .log files are all binary files

from ~/.config/superProductivity/logs/main.log i got:
```
[2020-09-29 13:39:27.747] [error] Frontend Error: Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at S (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:15562)
    at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:14646
    at s (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476668)
    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)
    at e.run (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)
    at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
    at t.invokeTask (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476551) Error: Uncaught (in promise): AbortError: The transaction was aborted, so the request cannot be fulfilled.
    at S (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:15562)
    at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:14646
    at s (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9307)
    at Object.onInvoke (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476668)
    at t.invoke (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9247)
    at e.run (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:4407)
    at file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:16325
    at t.invokeTask (file:///snap/superproductivity/755/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js:1:9991)
    at Object.onInvokeTask (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:476551)
[2020-09-29 13:39:51.459] [error] Frontend Error Stack: scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone.js:832:38)
function (webpack:///node_modules/zone.js/dist/zone.js:739:20)
Ur (file:///snap/superproductivity/755/resources/app.asar/dist/main.85c5718eafb26d401081.js:1:1794622)
invoke (webpack:///node_modules/zone.js/dist/zone.js:386:29)
onInvoke (webpack:///node_modules/@angular/core/fesm5/core.js:28134:32)
invoke (webpack:///node_modules/zone.js/dist/zone.js:385:35)
run (webpack:///node_modules/zone.js/dist/zone.js:143:46)
zone.scheduleMicroTask (webpack:///node_modules/zone.js/dist/zone.js:891:37)
invokeTask (webpack:///node_modules/zone.js/dist/zone.js:421:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm5/core.js:28122:32
```

**Comment by johannesjo** [comment]
Thank you very much for opening this up. I am closing this in favor of #401

**Comment by johannesjo** [comment]
Btw. you will be probably able to restore your data by using one of the automatic backups.
