### ISSUE TITLE
Error: Not in project context

### ISSUE THREAD

**Issue by Linux4win** [johannesjo/super-productivity#545]
### Steps to Reproduce
1. Copy some text, e.g. a URL into the system clipboard.
1. Open a work view other than a project view (Today or a certain tag view).
1. Press Ctrl+V (or the system shortcut for pasting), this will open the "Add bookmark" dialogue.
1. When you submit the dialogue, the app will crash.

### Error Log (Desktop only)

```
[2020-09-29 18:44:15.998] [error] Frontend Error: Error: Not in project context
    at e.project (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:9730)
    at e._next (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:159459)
    at e.next (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574041)
    at e._subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:1399415)
    at e.t._trySubscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171968)
    at e._trySubscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:718065)
    at e.t.subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171754)
    at e.<anonymous> (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2117541)
    at e.t.subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171632)
    at t.call (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:159231) Error: Not in project context
    at e.project (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:9730)
    at e._next (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:159459)
    at e.next (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574041)
    at e._subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:1399415)
    at e.t._trySubscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171968)
    at e._trySubscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:718065)
    at e.t.subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171754)
    at e.<anonymous> (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2117541)
    at e.t.subscribe (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:171632)
    at t.call (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:159231)
[2020-09-29 18:44:16.090] [error] Frontend Error: Error: Error: Not in project context
    at t.handleError (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:4122109)
    at e.selector (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2085544)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:284471)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2563956)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121)
    at e.notifyError (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:818293)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2266901)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574427)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121) Error: Error: Not in project context
    at t.handleError (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:4122109)
    at e.selector (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2085544)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:284471)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2563956)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121)
    at e.notifyError (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:818293)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:2266901)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121)
    at e._error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574427)
    at e.error (file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js:1:574121)
[2020-09-29 18:44:18.681] [error] Frontend Error Stack: map( (webpack:///src/app/features/work-context/work-context.service.ts:98:14)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:35:34)
next (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:53:17)
subscriber.add (webpack:///node_modules/rxjs/_esm5/internal/ReplaySubject.js:67:27)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:43:24)
_trySubscribe (webpack:///node_modules/rxjs/_esm5/internal/Subject.js:89:50)
toSubscriber (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:29:21)
complete (webpack:///node_modules/rxjs/_esm5/internal/operators/shareReplay.js:46:31)
toSubscriber (webpack:///node_modules/rxjs/_esm5/internal/Observable.js:24:30)
call (webpack:///node_modules/rxjs/_esm5/internal/operators/map.js:18:22)
[2020-09-29 18:44:18.682] [error] Frontend Error Stack: isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:54:12)
observable$.pipe(catchError(function (webpack:///node_modules/@ngrx/effects/fesm5/effects.js:161:25)
error (webpack:///node_modules/rxjs/_esm5/internal/operators/catchError.js:34:30)
this._tapError.call (webpack:///node_modules/rxjs/_esm5/internal/operators/tap.js:61:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
_error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:79:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
```

### Console Output

```
Persistent store granted
main.e5747aa1d467d597947c.js:1 0 out of 349594 MiB used (0%)
main.e5747aa1d467d597947c.js:1 Migrating model "TaskRepeat" to version from undefined to 1 Object
index.html#/tag/l0FtwLsOn/tasks:1 Autofocus processing was blocked because a document already has a focused element.
main.e5747aa1d467d597947c.js:1 GLOBAL_ERROR_HANDLER Error: Not in project context
    at e.project (main.e5747aa1d467d597947c.js:1)
    at e._next (main.e5747aa1d467d597947c.js:1)
    at e.next (main.e5747aa1d467d597947c.js:1)
    at e._subscribe (main.e5747aa1d467d597947c.js:1)
    at e.t._trySubscribe (main.e5747aa1d467d597947c.js:1)
    at e._trySubscribe (main.e5747aa1d467d597947c.js:1)
    at e.t.subscribe (main.e5747aa1d467d597947c.js:1)
    at e.<anonymous> (main.e5747aa1d467d597947c.js:1)
    at e.t.subscribe (main.e5747aa1d467d597947c.js:1)
    at t.call (main.e5747aa1d467d597947c.js:1)
t.handleError @ main.e5747aa1d467d597947c.js:1
main.e5747aa1d467d597947c.js:1 Last actions before error: Array(25)
main.e5747aa1d467d597947c.js:1 GLOBAL_ERROR_HANDLER Error: Error: Not in project context
    at t.handleError (main.e5747aa1d467d597947c.js:1)
    at e.selector (main.e5747aa1d467d597947c.js:1)
    at e.error (main.e5747aa1d467d597947c.js:1)
    at e._error (main.e5747aa1d467d597947c.js:1)
    at e.error (main.e5747aa1d467d597947c.js:1)
    at e.notifyError (main.e5747aa1d467d597947c.js:1)
    at e._error (main.e5747aa1d467d597947c.js:1)
    at e.error (main.e5747aa1d467d597947c.js:1)
    at e._error (main.e5747aa1d467d597947c.js:1)
    at e.error (main.e5747aa1d467d597947c.js:1)
t.handleError @ main.e5747aa1d467d597947c.js:1
main.e5747aa1d467d597947c.js:1 Last actions before error: Array(25)
polyfills.aebe8ecc43d658291381.js:1 Uncaught Error: Error: Error: Not in project context
    at t.handleError (main.e5747aa1d467d597947c.js:1)
    at Object.next (main.e5747aa1d467d597947c.js:1)
    at e.o [as _next] (main.e5747aa1d467d597947c.js:1)
    at e.__tryOrUnsub (main.e5747aa1d467d597947c.js:1)
    at e.next (main.e5747aa1d467d597947c.js:1)
    at e._next (main.e5747aa1d467d597947c.js:1)
    at e.next (main.e5747aa1d467d597947c.js:1)
    at e.next (main.e5747aa1d467d597947c.js:1)
    at e.emit (main.e5747aa1d467d597947c.js:1)
    at main.e5747aa1d467d597947c.js:1
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/reminder.792c29922fd96ecda281.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/lz.e95a1750fff9165699fd.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/runtime.c51bd5b1c616d9ffddc1.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/polyfills.aebe8ecc43d658291381.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/main.e5747aa1d467d597947c.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///tmp/.mount_superP6x4Vbr/resources/app.asar/dist/styles.b39aa09e24212b0544f7.css.map: 
```

### Stacktrace
```
isHandledError (webpack:///src/app/core/error-handler/global-error-handler.class.ts:54:12)
observable$.pipe(catchError(function (webpack:///node_modules/@ngrx/effects/fesm5/effects.js:161:25)
error (webpack:///node_modules/rxjs/_esm5/internal/operators/catchError.js:34:30)
this._tapError.call (webpack:///node_modules/rxjs/_esm5/internal/operators/tap.js:61:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
_error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:79:25)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
```

### Meta Info
META: SP5.7.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.7.0 Chrome/85.0.4183.87 Electron/10.1.0 Safari/537.36

### Actions Before Error
```
1601397506963: [Task] SetSelectedTask 
1601397507762: [WorkContext] Set Active Work Context 
1601397507789: [Task] SetSelectedTask 
1601397514250: [Task] SetSelectedTask 
1601397528155: [Task] Update Task 
1601397529920: [Task] Update Task Tags 
1601397532530: [WorkContextMeta] Move Task in Today 
1601397534694: [WorkContextMeta] Move Task in Today 
1601397538252: [WorkContextMeta] Move Task in Today 
1601397541375: [WorkContextMeta] Move Task in Today 
1601397544312: [Task] Delete Task 
1601397544363: [Task] UnsetCurrentTask 
1601397544366: [Pomodoro] Pause Pomodoro 
1601397549374: [Task] Update Task 
1601397550810: [Task] Update Task Tags 
1601397552769: [WorkContextMeta] Move Task in Today 
1601397573023: [Task] Update Task 
1601397579045: [Task] Update Task 
1601397580722: [Task] SetSelectedTask 
1601397586731: [WorkContextMeta] Move Task in Today 
1601397596374: [WorkContext] Set Active Work Context 
1601397596418: [Task] SetSelectedTask 
1601397845280: [WorkContext] Set Active Work Context 
1601397845355: [Task] SetSelectedTask 
1601397855967: [Bookmark] Add Bookmark
```

**Comment by johannesjo** [comment]
Thanks for opening this up! I also encountered this recently. Will try to provide a fix tomorrow.

**Comment by johannesjo** [comment]
Finally found the time to fix this. It should be available with the next release. Thanks again.
