### ISSUE TITLE
Superproductivity fails to start

### ISSUE THREAD

**Issue by Morganamilo** [johannesjo/super-productivity#57]
## Your Environment

* Version used: 1.8.1.r3.g8959fde-1 based on deb
* Also occurs on: 1.8.1
* Was working fine on: 1.7.5.r0.g20d6d67-1

* Operating System and version: 4.15.5-1-ARCH
* Desktop Environment: i3

## Expected Behavior

The program starts.

## Current Behavior

Program does not start.

```
morganamilo@Octavia ~/aur/superproductivity-git % superproductivity 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'jira-client'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/opt/superProductivity/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/superProductivity/resources/app.asar/electron/jira.js:1:172)
    at Object.<anonymous> (/opt/superProductivity/resources/app.asar/electron/jira.js:58:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

## Steps to Reproduce (for bugs)

1. start the program

I doubt something this big would slip through so it's probably something on my end. Missing dependencies or something maybe?

**Comment by johannesjo** [comment]
Thanks for reporting! Seems like I messed up the dependencies and it somehow slipped through :( 
Sorry about that! I'll publish a patch today.

**Comment by johannesjo** [comment]
Should be fixed with 1.8.3. Could you please check?

**Comment by Morganamilo** [comment]
1.8.3.r2.ga36f011-1 works fine for me. I actually did update my build scripts as soon as 1.8.3 came out but I got distracted and never actually built it. Sorry about that.

**Comment by johannesjo** [comment]
Np :)
