### ISSUE TITLE
Hangs on Startup and Can't Quit

### ISSUE THREAD

**Issue by PrurientJellyfish** [johannesjo/super-productivity#580]
### Your Environment
Super productivity version 5.4.2-1 from the Arch User Repository
Arch Linux with the hardened kernel version 5.8.14.a-1.
Sway (for Wayland) but have X11 support enabled.

### Expected Behavior
The app should open/close

### Current Behavior
When I launch super productivity, it hangs on startup. It shows the normal startup animation and seems fine, but never makes it past that. Then, when I try to close super productivity I have to force quit it because it isn't able to close

### Steps to Reproduce (for bugs)
1. Open it

### Console Output
```
Saving backups to /home/larva/.config/superProductivity/backups
{ enabled: null, showDevTools: false, mode: 'bottom' }
(node:9880) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.send (electron/js2c/renderer_init.js:103:332)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:99:328)
(node:9880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Then, when I hit CTRL+C or try to close the window it shows:
`close, isQuiting: undefined`

I'm guessing this has to do with some update somewhere breaking a dependency or something similar, I've  just got no clue about how node works. Thanks in advance.

**Comment by johannesjo** [comment]
Thanks for reporting. v5.4.2 is quite old. Could you try a more recent version?

**Comment by johannesjo** [comment]
@jvalecillos could you please trigger another update?

**Comment by johannesjo** [comment]
We could maybe also try to automate this:
https://github.com/KSXGitHub/github-actions-deploy-aur

**Comment by PrurientJellyfish** [comment]
@johannesjo I'll wait until the AUR package gets updated as I'm sure that's the problem and I don't want to install snap just for this one package. Is there an ETA for when it'll get updated? Thanks for the quick reply

**Comment by johannesjo** [comment]
@PrurientJellyfish Alright, but this could take a while. I don't maintain it myself.

**Comment by jvalecillos** [comment]
I'm working 

> @jvalecillos could you please trigger another update?

I'm working on an update but I had issues with building Angular in the version that Arch is using. I'll send an update once I fix the problem and I push a new version.

**Comment by jvalecillos** [comment]
I've updated the main package [superproductivity](https://aur.archlinux.org/packages/superproductivity/) :tada: 

The git package (using the latest commit) compiles/builds but it shows an error on startup :man_shrugging:

**Comment by johannesjo** [comment]
@jvalecillos what error does it show?

I'd recommend checking out the latest published version instead (v5.9.13). The master branch, while normally it shouldn't be completely broken, is more of a bleeding-edge thing.

**Comment by PrurientJellyfish** [comment]
@jvalecillos @johannesjo The update solved my problem! Thanks so much for the help and responsiveness (and for a great tool). I'll let you guys close this issue when you've resolved the git version

**Comment by jvalecillos** [comment]
The error details I was getting with the the git version (5.9.15.r145.gaf6a32419) is as follows:

### Error Log
```
[2020-10-26 10:55:38.057] [error] Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'isEnabled' of undefined
TypeError: Cannot read property 'isEnabled' of undefined
    at u (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:709099)
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:707939)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816)
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7178)
    at Z (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:15998)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:15077
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:1643957)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816) Error: Uncaught (in promise): TypeError: Cannot read property 'isEnabled' of undefined
TypeError: Cannot read property 'isEnabled' of undefined
    at u (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:709099)
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:707939)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816)
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7178)
    at Z (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:15998)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:15077
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:1643957)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816)
[2020-10-26 10:55:38.200] [error] Frontend Error: TypeError: Cannot read property 'isEnabled' of undefined
    at u (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:709099)
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:707939)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816)
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7178) TypeError: Cannot read property 'isEnabled' of undefined
    at u (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:709099)
    at o (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:707939)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6639)
    at Object.onInvoke (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344927)
    at l.invoke (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:6579)
    at i.run (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:2051)
    at file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:16770
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7257)
    at Object.onInvokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:344816)
    at l.invokeTask (file:///usr/lib/superproductivity/resources/app.asar/dist/polyfills.20026ac6e172abe81e44.js:1:7178)
[2020-10-26 10:55:40.441] [error] Frontend Error Stack: Object.keys(keyboardCopy).forEach( (webpack:///src/app/features/config/migrate-global-config.util.ts:116:34)
isMigrateModel (webpack:///src/app/features/config/migrate-global-config.util.ts:20:22)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
[2020-10-26 10:55:40.444] [error] Frontend Error Stack: Object.keys(keyboardCopy).forEach( (webpack:///src/app/features/config/migrate-global-config.util.ts:116:34)
isMigrateModel (webpack:///src/app/features/config/migrate-global-config.util.ts:20:22)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:1643957)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
```


### Stacktrace
```
Object.keys(keyboardCopy).forEach( (webpack:///src/app/features/config/migrate-global-config.util.ts:116:34)
isMigrateModel (webpack:///src/app/features/config/migrate-global-config.util.ts:20:22)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:406:63)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///usr/lib/superproductivity/resources/app.asar/dist/main.c0253f62ffcefdde8547.js:1:1643957)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
```

### Meta Info
META: SP5.9.15 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/5.9.15 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36

### Actions Before Error
```
1602695555418: [SP_ALL] Load(import) all data 
1602695555421: [SP_ALL] All Data was loaded 
1602695555431: [WorkContext] Set Active Work Context 
1602695555450: [Task] SetSelectedTask
```

**Comment by johannesjo** [comment]
@jvalecillos could you please try again with v6.0.1? The error should be fixed there.

**Comment by jvalecillos** [comment]
I just checked, the latest version `6.0.1.r2.g15c734304`(https://github.com/johannesjo/super-productivity/commit/15c734304b25e1dae68f9e57528485e279caae70) , builds and works correctly.

I'm uploading pushing the new updated packages.

We can close this issue now @johannesjo.

**Comment by johannesjo** [comment]
Thank you very much for checking and reporting back!
