### ISSUE TITLE
Javascript error at launch

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#589]
### Your Environment
* Version used: 6.0.0
* Operating System and version: MacOS Catalina 10.15.6

### Current Behavior
When I launch the desktop app I get this error message:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Applications/superProductivity.app/Contents/Resources/app.asar/electron/assets/icons/tray-icoTemplate.png
    at Object.exports.initIndicator (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/indicator.js:45:16)
    at App.createIndicator (/Applications/superProductivity.app/Contents/Resources/app.asar/electron/main.js:206:17)
    at App.emit (events.js:322:22)
```

### Steps to Reproduce (for bugs)
1. Install latest version on MacOS
2. launch the app

### Console Output
```
Persistence already allowed
main.ab6a34781ead8f16fecb.js:1 0 out of 80349 MiB used (0%)
main.ab6a34781ead8f16fecb.js:1 Migrating model "GlobalConfig" to version from 1.3 to 2 Object
main.ab6a34781ead8f16fecb.js:1 Migrating model "GlobalConfig" to version from 1.3 to 2 Object
main.ab6a34781ead8f16fecb.js:1 Migrating model "SimpleCounter" to version from undefined to 2 Object
main.ab6a34781ead8f16fecb.js:1 Object
main.ab6a34781ead8f16fecb.js:1 true Object
main.ab6a34781ead8f16fecb.js:1 Dropbox
main.ab6a34781ead8f16fecb.js:1 sync(effect)..... INITIAL_SYNC_TRIGGER
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND
main.ab6a34781ead8f16fecb.js:1 Dropbox PRE1: ↔ Same Rev 015b1da34f40cdb00000001dfaf8530
main.ab6a34781ead8f16fecb.js:1 Dropbox PRE1: No local changes to sync
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/runtime.076604685350bc36956d.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.250ebd3af63450554a58.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.ab6a34781ead8f16fecb.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/reminder.5b0fa13d8ca10813efca.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/lz.5d2c2359e92f65d00e61.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/styles.e1c786d55963a75bdeca.css.map: 
```
### Error Log (Desktop only)

on macOS: ~/Library/Logs/superProductivity/log.log
```
[2020-07-17 16:56:15.362] [error] Frontend Error: TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103) TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103)
[2020-07-17 16:56:16.248] [error] Frontend Error Stack: taskIds (webpack:///src/app/features/tag/store/tag.reducer.ts:307:54)
map (webpack:///src/app/features/tag/store/tag.reducer.ts:304:43)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:269:19)
combination (webpack:///node_modules/@ngrx/store/fesm5/store.js:219:42)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:111:11)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:258:19)
reduceState (webpack:///node_modules/@ngrx/store/fesm5/store.js:439:16)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:54:24)
[2020-07-20 14:19:20.011] [error] Frontend Error: TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103) TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103)
[2020-07-20 14:19:20.959] [error] Frontend Error Stack: taskIds (webpack:///src/app/features/tag/store/tag.reducer.ts:307:54)
map (webpack:///src/app/features/tag/store/tag.reducer.ts:304:43)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:269:19)
combination (webpack:///node_modules/@ngrx/store/fesm5/store.js:219:42)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:111:11)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:258:19)
reduceState (webpack:///node_modules/@ngrx/store/fesm5/store.js:439:16)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:54:24)
[2020-08-31 16:02:07.763] [error] Frontend Error: Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
    at Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:4119448)
    at e.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2084698)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:284292)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:573926)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965) Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
    at Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:4119448)
    at e.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2084698)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:284292)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:573926)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
[2020-08-31 16:02:08.618] [error] Frontend Error Stack: EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
createErrorAlert (webpack:///src/app/core/error-handler/global-error-handler.class.ts:43:27)
observable$.pipe(catchError(function (webpack:///node_modules/@ngrx/effects/fesm5/effects.js:161:25)
error (webpack:///node_modules/rxjs/_esm5/internal/operators/catchError.js:34:30)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
```

**Comment by johannesjo** [comment]
Thanks for reporting!! Should be fixed with rc4.
