### ISSUE TITLE
Error: Uncaught (in promise): DataError: Failed to read large IndexedDB value 

### ISSUE THREAD

**Issue by mazenadel19** [johannesjo/super-productivity#607]
### Steps to Reproduce

- Hey man, I'm a big fan of super-productivity, been using it for almost a year now, unfortunately I have this error when the app start and I can't find a way around it .

- the only unusual thing that I did today was opening Zoom  but I don't know if it's related to the bug since then whenever I try to open the app I get this error

![Screenshot from 2020-10-25 16-19-55](https://user-images.githubusercontent.com/26392390/97109853-4ae4ee00-16de-11eb-94bc-27bde9f0b323.png)

- tried to provide as much information as I could below, tell me if there's anything else I can do to help

### Error Log (Desktop only)
```
[2020-05-03 06:11:44.370] [error] Frontend Error: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at h.<computed>.readAsText (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1433:64)
    at t.handleFileInput (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.ts:86:12)
    at listenerFn (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.html:81:24)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14820:16)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51) TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at h.<computed>.readAsText (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1433:64)
    at t.handleFileInput (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.ts:86:12)
    at listenerFn (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.html:81:24)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14820:16)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
[2020-05-03 06:11:44.392] [error] Frontend Error: Error: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at t.handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:139:13)
    at handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8836:34)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14823:9)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
    at e.invokeTask [as invoke] (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38) Error: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at t.handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:139:13)
    at handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8836:34)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14823:9)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
    at e.invokeTask [as invoke] (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38)
[2020-05-03 06:11:44.460] [error] Frontend Error Stack: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at h.<computed>.readAsText (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1433:64)
    at t.handleFileInput (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.ts:86:12)
    at listenerFn (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.html:81:24)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14820:16)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51) h.<computed>.readAsText (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:1433:64)
t.handleFileInput (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.ts:86:12)
listenerFn (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/pages/project-overview-page/project-overview-page.component.html:81:24)
executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14820:16)
eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
[2020-05-03 06:11:44.487] [error] Frontend Error Stack: Error: TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at t.handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:139:13)
    at handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8836:34)
    at executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14823:9)
    at eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
    at HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
    at Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
    at t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
    at e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
    at e.invokeTask [as invoke] (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38) t.handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/src/app/core/error-handler/global-error-handler.class.ts:139:13)
handleError (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:8836:34)
executeListenerWithErrorHandling (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14823:9)
eventHandler (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:14855:22)
HTMLInputElement.apply (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js:575:36)
t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:421:35)
Object.onInvokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js:27859:33)
t.invokeTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:420:40)
e.runTask (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:188:51)
e.invokeTask [as invoke] (file:///snap/superproductivity/601/resources/app.asar/dist/webpack:/node_modules/zone.js/dist/zone.js:503:38)
```
### Console Output
```
//main.200c36d211df28ad70a3.js:1 

GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): DataError: Failed to read large IndexedDB value
    at Z (polyfills.250ebd3af63450554a58.js:1)
    at polyfills.250ebd3af63450554a58.js:1
    at o (main.200c36d211df28ad70a3.js:1)
    at l.invoke (polyfills.250ebd3af63450554a58.js:1)
    at Object.onInvoke (main.200c36d211df28ad70a3.js:1)
    at l.invoke (polyfills.250ebd3af63450554a58.js:1)
    at i.run (polyfills.250ebd3af63450554a58.js:1)
    at polyfills.250ebd3af63450554a58.js:1
    at l.invokeTask (polyfills.250ebd3af63450554a58.js:1)
    at Object.onInvokeTask (main.200c36d211df28ad70a3.js:1)
```

```
//polyfills.250ebd3af63450554a58.js:1 

Uncaught Error: Error: Uncaught (in promise): DataError: Failed to read large IndexedDB value
    at t.handleError (main.200c36d211df28ad70a3.js:1)
    at Object.next (main.200c36d211df28ad70a3.js:1)
    at d.i [as _next] (main.200c36d211df28ad70a3.js:1)
    at d.__tryOrUnsub (main.200c36d211df28ad70a3.js:1)
    at d.next (main.200c36d211df28ad70a3.js:1)
    at l._next (main.200c36d211df28ad70a3.js:1)
    at l.next (main.200c36d211df28ad70a3.js:1)
    at Ac.next (main.200c36d211df28ad70a3.js:1)
    at Ac.emit (main.200c36d211df28ad70a3.js:1)
    at main.200c36d211df28ad70a3.js:1
```

```
//main.200c36d211df28ad70a3.js:1 

GLOBAL_ERROR_HANDLER DOMException: Failed to read large IndexedDB value
```

```
//main.200c36d211df28ad70a3.js:1 
Initial Dialog Error
(anonymous) @ main.200c36d211df28ad70a3.js:1

//main.200c36d211df28ad70a3.js:1 
DOMException: Failed to read large IndexedDB value
(anonymous) @ main.200c36d211df28ad70a3.js:1

//main.200c36d211df28ad70a3.js:1 
Service worker registration failed with: TypeError: Failed to register a ServiceWorker for scope ('file:///snap/superproductivity/911/resources/app.asar/dist/') with script ('file:///snap/superproductivity/911/resources/app.asar/dist/ngsw-worker.js'): An unknown error occurred when fetching the script.
```

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1390011)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27474:32)
```

### Meta Info
META: SP6.0.1 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.0.1 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36

### Actions Before Error
```
1603633671726: [Task] Add time spent 
1603633671727: [Project] Update Work End 
1603633671728: [Tag] Update Work End for Tag 
1603633671736: [Persistence] Save to DB 
1603633671737: [Persistence] Save to DB 
1603633671737: [Persistence] Save to DB 
1603633672726: [Task] Add time spent 
1603633672728: [Project] Update Work End 
1603633672729: [Tag] Update Work End for Tag 
1603633672736: [Persistence] Save to DB 
1603633672736: [Persistence] Save to DB 
1603633672737: [Persistence] Save to DB 
1603633673726: [Task] Add time spent 
1603633673729: [Project] Update Work End 
1603633673729: [Tag] Update Work End for Tag 
1603633673736: [Persistence] Save to DB 
1603633673736: [Persistence] Save to DB 
1603633673736: [Persistence] Save to DB 
1603633674726: [Task] Add time spent 
1603633674731: [Project] Update Work End 
1603633674733: [Tag] Update Work End for Tag 
1603633674740: [Persistence] Save to DB 
1603633674741: [Persistence] Save to DB 
1603633674741: [Persistence] Save to DB 
1603633675726: [Task] Add time spent 
1603633675729: [Project] Update Work End 
1603633675730: [Tag] Update Work End for Tag 
1603633675740: [Persistence] Save to DB 
1603633675740: [Persistence] Save to DB 
1603633675741: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for taking the time to open this up!

It would help me a lot if you could share a copy of your data to contact@super-productivity.com, so I can debug this on my computer. You can create an export by navigating to "Settings" and then to "Import/Export". 

If the error occurs on startup, you might still be able to go there, though it might be a bit tricky to navigate around the modal. If not you might be able to find the latest data in the folder for automatic backups.

If you don't want to share your data (which I can totally understand), maybe you could try to make an export nevertheless and tell me its file size?

**Comment by mazenadel19** [comment]
Just sent you json file, good luck

**Comment by johannesjo** [comment]
Hey @mazenadel19 the data seems to be fine and it's not too big or something neither (your export is just 240kb, my own data export is about 3mb and I didn't encounter any issues with that so far). What you might want to try is to delete all data for your app and re-import the export you send me. You can check your data for completeness with the web app first: https://app.super-productivity.com/

Hopefully, this resolves the issue. I am not sure at all what might be causing this. As I was unable to reproduce this I spent [some time googeling](https://www.google.com/search?q=Uncaught+(in+promise)%3A+DataError%3A+Failed+to+read+large+IndexedDB+value&oq=Uncaught+(in+promise)%3A+DataError%3A+Failed+to+read+large+IndexedDB+value&aqs=chrome.0.69i59j69i61l2&sourceid=chrome&ie=UTF-8), but found nothing I could work with although it seems others have encountered this as well.

**Comment by mazenadel19** [comment]
just tried that and looks like everything is back to normal, hopefully that solved it for now, will let you know If I encountered any future problems

**Comment by johannesjo** [comment]
Thank you. Glad that it works for now at least.
