### ISSUE TITLE
Insufficient Settings provided for Jira

### ISSUE THREAD

**Issue by mjgwood** [johannesjo/super-productivity#649]
### Your Environment

* Version used: 6.0.1 snap
* Operating System and version: Ubuntu 20.04.1
* Desktop Environment: GNOME

### Expected Behavior
No notification popup

### Current Behavior
Whenever clicking on a Project after viewing one with Jira set up I get an error notification popup that says 'Insufficient Settings provided for Jira'

### Steps to Reproduce (for bugs)
1. Configure Jira for a Project
2. Go to the Project's work view
3. Click on a different Project to see its work view
4. Error notification popup appears

### Console Output
`main.200c36d211df28ad70a3.js:1 GLOBAL_ERROR_HANDLER ObjectHANDLED_ERROR_PROP: "Insufficient Settings for Jira myself__GET__XEhh8OPLC"__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
handleError @ main.200c36d211df28ad70a3.js:1
undefined:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`

### Error Log (Desktop only)
`[2020-11-05 19:46:07.578] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__IqnbmtoxW'
} undefined
[2020-11-05 19:46:07.591] [error] Frontend Error Stack: 
[2020-11-05 19:48:49.703] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__zE3w_NAqN'
} undefined
[2020-11-05 19:48:49.715] [error] Frontend Error Stack: 
[2020-11-05 19:51:54.225] [error] Frontend Error: { HANDLED_ERROR_PROP: 'Jira: Unsupported Media Type' } undefined
[2020-11-05 19:51:54.228] [error] Frontend Error Stack: 
[2020-11-05 19:52:01.327] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928)
[2020-11-05 19:52:01.329] [error] Frontend Error Stack: 
[2020-11-05 19:52:12.837] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__SOclRuQlM'
} undefined
[2020-11-05 19:52:12.847] [error] Frontend Error Stack: 
[2020-11-05 19:53:10.912] [error] Frontend Error: { HANDLED_ERROR_PROP: 'Jira: Unsupported Media Type' } undefined
[2020-11-05 19:53:10.914] [error] Frontend Error Stack: 
[2020-11-05 19:53:10.928] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928)
[2020-11-05 19:53:10.930] [error] Frontend Error Stack: 
[2020-11-05 19:53:54.764] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__yAmCSpiXQ'
} undefined
[2020-11-05 19:53:54.848] [error] Frontend Error Stack: 
[2020-11-05 19:55:02.921] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__Y58Xy5H9_'
} undefined
[2020-11-05 19:55:02.996] [error] Frontend Error Stack: 
[2020-11-05 19:57:12.342] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__4FdayC-0Z'
} undefined
[2020-11-05 19:57:12.359] [error] Frontend Error Stack: 
[2020-11-05 20:02:27.396] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Jira: Not Found"}
    at Z (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:3067637)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1544039)
    at l.invoke (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///snap/superproductivity/911/resources/app.asar/dist/main.200c36d211df28ad70a3.js:1:1543928)
[2020-11-05 20:02:27.398] [error] Frontend Error Stack: 
[2020-11-05 20:02:35.298] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__CncuBetxW'
} undefined
[2020-11-05 20:02:35.308] [error] Frontend Error Stack: 
[2020-11-05 20:03:29.563] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__K8spEGJ66'
} undefined
[2020-11-05 20:03:29.647] [error] Frontend Error Stack: 
[2020-11-05 20:05:30.260] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__0kD120nzj'
} undefined
[2020-11-05 20:05:30.271] [error] Frontend Error Stack: 
[2020-11-05 20:05:52.273] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira search__POST__z-u18dKmV'
} undefined
[2020-11-05 20:05:52.275] [error] Frontend Error Stack: 
[2020-11-05 20:07:49.422] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__XEhh8OPLC'
} undefined
[2020-11-05 20:07:49.550] [error] Frontend Error Stack: 
[2020-11-05 20:08:19.338] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__PT8cu9WRn'
} undefined
[2020-11-05 20:08:19.352] [error] Frontend Error Stack: 
[2020-11-05 20:08:25.384] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__cK5ByD8e6'
} undefined
[2020-11-05 20:08:25.396] [error] Frontend Error Stack: 
[2020-11-05 20:08:30.687] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__ISlIQp-Lr'
} undefined
[2020-11-05 20:08:30.697] [error] Frontend Error Stack: 
[2020-11-05 20:08:33.466] [error] Frontend Error: {
  HANDLED_ERROR_PROP: 'Insufficient Settings for Jira myself__GET__IX-rpjffq5'
} undefined
[2020-11-05 20:08:33.477] [error] Frontend Error Stack: `

**Comment by johannesjo** [comment]
Thank you very much for reporting! I look into it!

**Comment by johannesjo** [comment]
So far I have not been able to reproduce this. Are you by any chance switching from a Jira project to another Jira project with an invalid configuration for Jira?

**Comment by mjgwood** [comment]
Thanks for the quick reply Johannes. I'm not really sure how to check if I'm doing that. I just entered the Host, Email, API token, and added `assignee in (currentUser()) AND project = MM order by created DESC` in the 'JQL Query for limiting searching tasks' field. The rest of the settings I've left as default. I assume the fact that I included `project = MM` in the query should mean that I'm only fetching issues from a single project?

I'm able to see and edit the tasks in SP, which updates them in Jira, so it appears to be working aside from the error messge that keeps popping up.

**Comment by mjgwood** [comment]
Here are my settings. I forgot to mention that I disabled 'Transition Handling' because I don't really understand what it does.

![image](https://user-images.githubusercontent.com/12268867/98321147-4c3be200-201f-11eb-9bf2-962ad8e3fa6e.png)

**Comment by johannesjo** [comment]
Thanks for getting back to me!

> I'm not really sure how to check if I'm doing that.

The question is if the project you're switching to also has Jira enabled (you can check this by going to the project settings from the project context menu (the three little dots when you hover over the project name in the project list in the left-hand menu).

**Comment by mjgwood** [comment]
I replied via email and only just realised that didn't work for some reason. I didn't think I did have any other projects with Jira enabled but it looks like I must have accidentally enabled it on one without adding any additional settings.. Oops! Sorry for wasting your time with this!

**Comment by johannesjo** [comment]
No worries! I am glad that it works now! :)
