### ISSUE TITLE
Jira-Integration: Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefinedTypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by elendis** [johannesjo/super-productivity#652]
My colleage and I are both getting this error when the Jira integration for a project is enabled. 
Our Jira installation is quite old (v7.2.6), that might be a factor.

### Steps to Reproduce
1. Enable Jira-Integration for project
2. Wait some time (I would guess until an auto-refresh is triggered)
3. Error is displayed

I can also trigger the error via "Update issue data" on a imported Jira-Task.

### Error Log (Desktop only)
```
[2020-11-08 13:37:23.102] [error] Frontend Error: { HANDLED_ERROR_PROP: 'Jira: Bad Request' } undefined
[2020-11-08 13:37:23.104] [error] Frontend Error Stack: 
[2020-11-08 13:37:23.127] [error] Frontend Error: Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.s (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054376)
    at s.next (<anonymous>)
    at n (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054491)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344927)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344816)
    at Z (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3067647)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344927)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344816) Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.s (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054376)
    at s.next (<anonymous>)
    at n (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054491)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344927)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344816)
    at Z (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15998)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:15077
    at o (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3067647)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6639)
    at Object.onInvoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344927)
    at l.invoke (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:6579)
    at i.run (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:2051)
    at file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:16770
    at l.invokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/polyfills.250ebd3af63450554a58.js:1:7257)
    at Object.onInvokeTask (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:344816)
[2020-11-08 13:37:24.048] [error] Frontend Error Stack: length (webpack:///src/app/features/issue/providers/jira/jira-common-interfaces.service.ts:89:47)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054491)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3067647)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
```
### Console Output
```
Uncaught Error: Error: Uncaught (in promise): TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at t.s (main.60c059cd76aa04d8353f.js:1)
    at s.next (<anonymous>)
    at n (main.60c059cd76aa04d8353f.js:1)
    at l.invoke (polyfills.250ebd3af63450554a58.js:1)
    at Object.onInvoke (main.60c059cd76aa04d8353f.js:1)
    at l.invoke (polyfills.250ebd3af63450554a58.js:1)
    at i.run (polyfills.250ebd3af63450554a58.js:1)
    at polyfills.250ebd3af63450554a58.js:1
    at l.invokeTask (polyfills.250ebd3af63450554a58.js:1)
    at Object.onInvokeTask (main.60c059cd76aa04d8353f.js:1)
    at t.handleError (main.60c059cd76aa04d8353f.js:1)
    at Object.next (main.60c059cd76aa04d8353f.js:1)
    at d.i [as _next] (main.60c059cd76aa04d8353f.js:1)
    at d.__tryOrUnsub (main.60c059cd76aa04d8353f.js:1)
    at d.next (main.60c059cd76aa04d8353f.js:1)
    at l._next (main.60c059cd76aa04d8353f.js:1)
    at l.next (main.60c059cd76aa04d8353f.js:1)
    at Ac.next (main.60c059cd76aa04d8353f.js:1)
    at Ac.emit (main.60c059cd76aa04d8353f.js:1)
    at main.60c059cd76aa04d8353f.js:1
```

### Stacktrace
```
length (webpack:///src/app/features/issue/providers/jira/jira-common-interfaces.service.ts:89:47)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3054491)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
scheduleResolveOrReject (webpack:///node_modules/zone.js/fesm2015/zone.js:1215:38)
makeResolver (webpack:///node_modules/zone.js/fesm2015/zone.js:1118:20)
Ur (file:///C:/Program%20Files/WindowsApps/53707johannesjo.SuperProductivity_6.0.1.0_x64__ch45amy23cdv6/app/resources/app.asar/dist/main.60c059cd76aa04d8353f.js:1:3067647)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:373:29)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:27486:32)
invoke (webpack:///node_modules/zone.js/fesm2015/zone.js:372:55)
run (webpack:///node_modules/zone.js/fesm2015/zone.js:135:46)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/fesm2015/zone.js:1274:39)
invokeTask (webpack:///node_modules/zone.js/fesm2015/zone.js:407:34)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:27474:32)
```

### Meta Info
META: SP6.0.1 Electron – de – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.0.1 Chrome/85.0.4183.121 Electron/10.1.3 Safari/537.36

### Actions Before Error
```
1604838945080: [Bookmark] Load Bookmark State 
1604838945081: [Metric] Load Metric State 
1604838945082: [Improvement] Load Improvement State 
1604838945082: [Obstruction] Load Obstruction State 
1604838945083: [Project] Load Project related Data Success 
1604838945083: [Improvement] Clear Hidden Improvements 
1604838945083: [Improvement] Delete multiple Improvements 
1604838955966: [Project] Update Project Issue Provider Cfg 
1604838955980: [Persistence] Save to DB 
1604838974987: [Project] Update Project Issue Provider Cfg 
1604838974994: [Persistence] Save to DB 
1604838998089: [Layout] Hide SideBar 
1604839002290: [SP_ALL] Load(import) all data 
1604839002327: [SP_ALL] All Data was loaded 
1604839002333: [WorkContext] Set Active Work Context 
1604839002350: [Task] SetSelectedTask 
1604839002618: [Note] Load Note State 
1604839002619: [Bookmark] Load Bookmark State 
1604839002619: [Metric] Load Metric State 
1604839002620: [Improvement] Load Improvement State 
1604839002622: [Obstruction] Load Obstruction State 
1604839002622: [Project] Load Project related Data Success 
1604839002623: [Improvement] Clear Hidden Improvements 
1604839002623: [Improvement] Delete multiple Improvements 
1604839009439: [Project] Update Project Issue Provider Cfg 
1604839009452: [Persistence] Save to DB 
1604839017966: [Project] Update Project Issue Provider Cfg 
1604839018004: [Persistence] Save to DB 
1604839021026: [Project] Update Project Issue Provider Cfg 
1604839021034: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. I provided a workaround for this, which should be available with the next release.

**Comment by elendis** [comment]
Awesome, thank you!
