### ISSUE TITLE
Error: QeuxxwDDR not found

### ISSUE THREAD

**Issue by papernoise** [johannesjo/super-productivity#797]
### Your Environment
* Version used: 6.3.0.0
* Operating System and version: MacOS 10.15.7 

### Expected Behavior
Open the app and start working

### Current Behavior
The app crashes at launch, giving me the error reported below.

when I then reload the app it says:

| Your data seems to be damaged. Do you want to try to automatically fix it? This might result in partial data loss.

I click OK and SP works again, but all my projects are scrambled in the sidebar. I.e. they are not where I put them, but in a different order. No tasks seem to have gotten lost though.

### Steps to Reproduce (for bugs)
1. open app
2. watch it crash

### Error window
![Screenshot 2021-01-15 at 09 31 58](https://user-images.githubusercontent.com/1595523/104700896-244eb600-5715-11eb-8e3c-ccca37415807.png)

### Console Output
![Screenshot 2021-01-15 at 09 35 57](https://user-images.githubusercontent.com/1595523/104700857-17ca5d80-5715-11eb-90aa-bb4a224ea3ce.png)

### Error Log (Desktop only)
[2020-07-17 16:56:15.362] [error] Frontend Error: TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103) TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103)
[2020-07-17 16:56:16.248] [error] Frontend Error Stack: taskIds (webpack:///src/app/features/tag/store/tag.reducer.ts:307:54)
map (webpack:///src/app/features/tag/store/tag.reducer.ts:304:43)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:269:19)
combination (webpack:///node_modules/@ngrx/store/fesm5/store.js:219:42)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:111:11)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:258:19)
reduceState (webpack:///node_modules/@ngrx/store/fesm5/store.js:439:16)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:54:24)
[2020-07-20 14:19:20.011] [error] Frontend Error: TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103) TypeError: Cannot read property 'taskIds' of undefined
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090425
    at Array.map (<anonymous>)
    at E (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2090363)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417936
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2416737
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:4349782
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2417122
    at e.nt [as accumulator] (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:2420152)
    at e._tryNext (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732218)
    at e._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.b71e192d96ee69a8df29.js:1:1732103)
[2020-07-20 14:19:20.959] [error] Frontend Error Stack: taskIds (webpack:///src/app/features/tag/store/tag.reducer.ts:307:54)
map (webpack:///src/app/features/tag/store/tag.reducer.ts:304:43)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:269:19)
combination (webpack:///node_modules/@ngrx/store/fesm5/store.js:219:42)
reducer (webpack:///src/app/root-store/meta/undo-task-delete.meta-reducer.ts:111:11)
function (webpack:///node_modules/@ngrx/store/fesm5/store.js:258:19)
reduceState (webpack:///node_modules/@ngrx/store/fesm5/store.js:439:16)
_tryNext (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:61:26)
_next (webpack:///node_modules/rxjs/_esm5/internal/operators/scan.js:54:24)
[2020-08-31 16:02:07.763] [error] Frontend Error: Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
    at Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:4119448)
    at e.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2084698)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:284292)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:573926)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965) Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
    at Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
    at t.handleError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:4119448)
    at e.selector (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2084698)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:284292)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
    at e.error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:573926)
    at e.notifyError (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:817898)
    at e._error (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.a0999bf0de13775cbc47.js:1:2265965)
[2020-08-31 16:02:08.618] [error] Frontend Error Stack: EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.sendSync (electron/js2c/renderer_init.js:126:403)
Object.remoteMemberFunction (electron/js2c/renderer_init.js:82:2000)
createErrorAlert (webpack:///src/app/core/error-handler/global-error-handler.class.ts:43:27)
observable$.pipe(catchError(function (webpack:///node_modules/@ngrx/effects/fesm5/effects.js:161:25)
error (webpack:///node_modules/rxjs/_esm5/internal/operators/catchError.js:34:30)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
error (webpack:///node_modules/rxjs/_esm5/internal/Subscriber.js:59:17)
notifyError (webpack:///node_modules/rxjs/_esm5/internal/OuterSubscriber.js:13:25)
_error (webpack:///node_modules/rxjs/_esm5/internal/InnerSubscriber.js:18:20)
[2021-01-13 07:29:55.697] [error] Frontend Error: Error: Project QeuxxwDDR not found
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1809139
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686886
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at le (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1687287)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686940
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at a.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686110)
    at a._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1697897)
    at a.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:169837)
    at e._subscribe (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:80313) Error: Project QeuxxwDDR not found
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1809139
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686886
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at le (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1687287)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686940
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at a.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686110)
    at a._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1697897)
    at a.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:169837)
    at e._subscribe (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:80313)
[2021-01-13 07:29:56.511] [error] Frontend Error Stack: Error (webpack:///src/app/features/project/store/project.reducer.ts:76:12)
function (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1124:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1047:39)
args (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1087:38)
function (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1133:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1047:39)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:896:24)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)
[2021-01-15 09:30:49.414] [error] Frontend Error: Error: Project QeuxxwDDR not found
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1809139
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686886
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at le (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1687287)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686940
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at a.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686110)
    at a._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1697897)
    at a.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:169837)
    at e._subscribe (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:80313) Error: Project QeuxxwDDR not found
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1809139
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686886
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at le (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1687287)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686940
    at memoized (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686457)
    at a.project (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1686110)
    at a._next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:1697897)
    at a.next (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:169837)
    at e._subscribe (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.8f9400abc07e6653ef0a.js:1:80313)
[2021-01-15 09:30:50.286] [error] Frontend Error Stack: Error (webpack:///src/app/features/project/store/project.reducer.ts:76:12)
function (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1124:29)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1047:39)
args (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1087:38)
function (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1133:35)
isArgumentsChanged (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:1047:39)
source$.pipe(pluck (webpack:///node_modules/@ngrx/store/__ivy_ngcc__/fesm2015/ngrx-store.js:896:24)
_next (webpack:///node_modules/rxjs/_esm2015/internal/operators/map.js:29:34)
next (webpack:///node_modules/rxjs/_esm2015/internal/Subscriber.js:49:17)
super._subscribe (webpack:///node_modules/rxjs/_esm2015/internal/BehaviorSubject.js:14:23)

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting this. Likely just a rare hickup, but I look into. I am glad that the data repair script seems to work! The thing with the project ordering is to be expected when it runs unfortunately.

**Comment by papernoise** [comment]
Thanks a lot! Maybe worth adding that the issue appears at every launch so far.

**Comment by johannesjo** [comment]
Oh! It definitely shouldn't appear on every startup for sure! Could you by any chance sent me a copy of your data?
