### ISSUE TITLE
Error: Uncaught (in promise): TimeoutError: Transaction timed out due to inactivity.

### ISSUE THREAD

**Issue by etherblitzdev** [johannesjo/super-productivity#840]
### Steps to Reproduce

0. Super Productivity installed by Microsoft Store (which I am not a big fan of, nevertheless I took the install recommendation
because of Certificates.)

**Please mention other locations where logs could exist?**

No logs under:
on Windows 10.0.19042.746 : %USERPROFILE%\AppData\Roaming\superProductivity\log.log
on Windows: %USERPROFILE%\AppData\Local\superProductivity\log.log
on Windows: %USERPROFILE%\AppData\LocalLow\superProductivity\log.log

No Install info under:
C:\Program Files (x86)
C:\Program Files

1. Created Project Break with a Task Lunch.
2. Put windows 10 in sleep Mode
3. Returned after lunch Awoke Laptop from Sleep and signed in.
4.Received Alert below(*) in Super Productivity, strangely without my action an Inspect code page was open at this line.

Received Alert below(*) in Super Productivity:
=============================
![2021_01_28_14_14_31_](https://user-images.githubusercontent.com/32279175/106143630-58919000-6173-11eb-92df-3ab098411f51.png)

```
Error: Uncaught (in promise): TimeoutError: Transaction timed out due to inactivity.
! Please copy & report !

Error: Uncaught (in promise): TimeoutError: Transaction timed out due to inactivity.
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28269:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:16)
META: SP6.3.3 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36
```
=================================================================================

### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/fesm2015/core.js:28269:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:16)
```

### Meta Info
META: SP6.3.3 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

### Actions Before Error
```
1611832538466: [Tag] Update Work End for Tag 
1611832538467: [Persistence] Save to DB 
1611832538468: [Persistence] Save to DB 
1611832538468: [Persistence] Save to DB 
1611832539457: [Task] Add time spent 
1611832539458: [Project] Update Work End 
1611832539478: [Tag] Update Work End for Tag 
1611832539478: [Persistence] Save to DB 
1611832539479: [Persistence] Save to DB 
1611832539479: [Persistence] Save to DB 
1611832540476: [Task] Add time spent 
1611832540479: [Project] Update Work End 
1611832540495: [Tag] Update Work End for Tag 
1611832540503: [Persistence] Save to DB 
1611832540503: [Persistence] Save to DB 
1611832540504: [Persistence] Save to DB 
1611832541457: [Task] Add time spent 
1611832541458: [Project] Update Work End 
1611832541462: [Tag] Update Work End for Tag 
1611832541462: [Persistence] Save to DB 
1611832541462: [Persistence] Save to DB 
1611832541462: [Persistence] Save to DB 
1611832542457: [Task] Add time spent 
1611832542459: [Project] Update Work End 
1611832542463: [Tag] Update Work End for Tag 
1611832542463: [Persistence] Save to DB 
1611832542463: [Persistence] Save to DB 
1611832542463: [Persistence] Save to DB 
1611838499192: [Task] Remove time spent 
1611838499194: [Task] UnsetCurrentTask
```

**Comment by etherblitzdev** [comment]
Great Product. Feel free to get in touch. If there are other suggestions where to find missing logs, please mention. Default locations were not useful. Thanks and keep up the good work Johannes. :-)

**Comment by johannesjo** [comment]
Thank you very much for reporting this and the kind feedback! Did this just happen once or a couple of times?

**Comment by crtxcr** [comment]
Hi,

first of all: nice app. 

Since you said #1116 is a duplicate of this one, I'll post it here. -

I started logging a task, went away, came back and saw this error:

```

> Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:2326700) at Generator.throw () at o (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:2325912) at l.invoke (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:1631243) at l.invoke (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:1631059)
> ! Please copy & report !
> 
> Error: Uncaught (in promise): Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. Error: InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing. at t. (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:2326700) at Generator.throw () at o (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:2325912) at l.invoke (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6594) at Object.onInvoke (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:1631243) at l.invoke (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:6534) at i.run (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:2006) at file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:16792 at l.invokeTask (file:///snap/superproductivity/1209/resources/app.asar/dist/polyfills.d9d3c25e259fe76fbf1e.js:1:7212) at Object.onInvokeTask (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:1631059)
> await (webpack:///src/app/core/persistence/database.service.ts:58:12)
> Ur (file:///snap/superproductivity/1209/resources/app.asar/dist/main.9f5d7bf6bce32563528c.js:1:2325912)
> invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:372:25)
> onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28553:32)
> invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:371:51)
> run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:134:42)
> zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1276:35)
> invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:406:30)
> onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28540:32)
> META: SP7.0.0-rc13 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/7.0.0-rc13 Chrome/89.0.4389.128 Electron/12.0.7 Safari/537.36

```
4 Minutes of that task got logged, if that helps. 


### Your Environment



- Version used: 7.0.0-rc13 (snap)
- Operating System and version: Ubuntu 21.04
- Desktop Environment: KDE 
- Browser Name and version: n/a

### Expected Behavior

The error should not happen and the tracked time of the task not lost

### Current Behavior


That error occured and most time spent on the tracked task was lost. 

### Steps to Reproduce (for bugs)





I think it cannot be reproduced, but what I did:

1. Started logging a task
2. Went away to take a walk
3. Came back and saw this error

The desktop was locked, but the system did not go to some hibernation mode or something. 

### Error Log (Desktop only)

I did not find anything relevant.

**Comment by johannesjo** [comment]
@crtxcr could you maybe check if your disk is full, when this happens? There seems to be a bug in the rc13 (which is at least appropriately named ;)).

**Comment by crtxcr** [comment]
The disk has more than enough free space (as in several hundred gigabytes), I don't think this is the issue in my case.

**Comment by johannesjo** [comment]
There was a bug in the logging library that was causing a huge memory leak. So it's still possible :)
