### ISSUE TITLE
Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.    

### ISSUE THREAD

**Issue by iamtburger** [johannesjo/super-productivity#884]
### Steps to Reproduce

1. Switched to SuperProductivity Window

### Error Log (Desktop only)

There was no log file in the folder.

### Console Output

main.839fd4a6fbc40d5fd73d.js:1 GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:2346445)
    at Proxy.s (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:2347527)
    at e.<anonymous> (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:2355867)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:2355205)
    at l.invoke (file:///snap/superproductivity/1004/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:1555412)
    at l.invoke (file:///snap/superproductivity/1004/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.run (file:///snap/superproductivity/1004/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)
    at file:///snap/superproductivity/1004/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758

Uncaught Error: Error: Uncaught (in promise): InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (main.839fd4a6fbc40d5fd73d.js:1)
    at Proxy.s (main.839fd4a6fbc40d5fd73d.js:1)
    at e.<anonymous> (main.839fd4a6fbc40d5fd73d.js:1)
    at Generator.next (<anonymous>)
    at a (main.839fd4a6fbc40d5fd73d.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvoke (main.839fd4a6fbc40d5fd73d.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.run (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at e.handleError (main.839fd4a6fbc40d5fd73d.js:1)
    at Object.next (main.839fd4a6fbc40d5fd73d.js:1)
    at d.i [as _next] (main.839fd4a6fbc40d5fd73d.js:1)
    at d.__tryOrUnsub (main.839fd4a6fbc40d5fd73d.js:1)
    at d.next (main.839fd4a6fbc40d5fd73d.js:1)
    at l._next (main.839fd4a6fbc40d5fd73d.js:1)
    at l.next (main.839fd4a6fbc40d5fd73d.js:1)
    at Uc.next (main.839fd4a6fbc40d5fd73d.js:1)
    at Uc.emit (main.839fd4a6fbc40d5fd73d.js:1)
    at main.839fd4a6fbc40d5fd73d.js:1

### Stacktrace
```
function (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:150:25)
function (webpack:///node_modules/idb/build/esm/index.js:65:24)
constructor (webpack:///src/app/core/persistence/database.service.ts:49:49)
Ur (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:2355205)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28281:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
Ur (file:///snap/superproductivity/1004/resources/app.asar/dist/main.839fd4a6fbc40d5fd73d.js:1:1400545)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28281:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
run (webpack:///node_modules/zone.js/dist/zone-evergreen.js:130:42)
zone.scheduleMicroTask(source, (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1272:35)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28269:32)
```

### Meta Info
META: SP6.3.3 Electron – en-US – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.3.3 Chrome/85.0.4183.121 Electron/10.2.0 Safari/537.36

### Actions Before Error
```
1612792835676: [Task] Add time spent 
1612792835677: [Project] Update Work End 
1612792835686: [Tag] Update Work End for Tag 
1612792835686: [Persistence] Save to DB 
1612792835686: [Persistence] Save to DB 
1612792835686: [Persistence] Save to DB 
1612792836676: [Task] Add time spent 
1612792836678: [Project] Update Work End 
1612792836688: [Tag] Update Work End for Tag 
1612792836689: [Persistence] Save to DB 
1612792836689: [Persistence] Save to DB 
1612792836689: [Persistence] Save to DB 
1612792837676: [Task] Add time spent 
1612792837677: [Project] Update Work End 
1612792837686: [Tag] Update Work End for Tag 
1612792837686: [Persistence] Save to DB 
1612792837687: [Persistence] Save to DB 
1612792837687: [Persistence] Save to DB 
1612792838676: [Task] Add time spent 
1612792838678: [Project] Update Work End 
1612792838686: [Tag] Update Work End for Tag 
1612792838686: [Persistence] Save to DB 
1612792838686: [Persistence] Save to DB 
1612792838686: [Persistence] Save to DB 
1612792841797: [Task] Add time spent 
1612792841798: [Project] Update Work End 
1612792841804: [Tag] Update Work End for Tag 
1612792841805: [Persistence] Save to DB 
1612792841806: [Persistence] Save to DB 
1612792841806: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for reporting this (and sorry for the lat reply). Theoretically this should be fixed with one of the next electron/chromium releases) so there might not be much we can do now unfortunately.

This might also be caused by the disk being full.
