### ISSUE TITLE
Error "unknown bus address" when starting the app on Windows

### ISSUE THREAD

**Issue by pbouda** [johannesjo/super-productivity#9]
I get an error when I try to start the app on Windows. I tried the binary that is available for download first, and then also the source with the build instructions in the README. The error I get is:

```
Error: unknown bus address
    at createStream (C:\Users\pbouda\Projects\git-github\super-productivity\node_modules\dbus-native\index.js:25:26)
    at createConnection (C:\Users\pbouda\Projects\git-github\super-productivity\node_modules\dbus-native\index.js:84:30)
    at Function.module.exports.createClient (C:\Users\pbouda\Projects\git-github\super-productivity\node_modules\dbus-native\index.js:144:20)
    at Function.module.exports.sessionBus (C:\Users\pbouda\Projects\git-github\super-productivity\node_modules\dbus-native\index.js:155:25)
    at Object.<anonymous> (C:\Users\pbouda\Projects\git-github\super-productivity\electron\dbus.js:9:25)
    at Object.<anonymous> (C:\Users\pbouda\Projects\git-github\super-productivity\electron\dbus.js:120:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

I am on Windows 10 Professional, Node version 6.11.1. Any idea?

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting! I think I know the problem. I'll get back to you in a bit.

**Comment by johannesjo** [comment]
Could check again if it works for you with the latest version? I'm also uploading a new binary just now, but it takes some time.

**Comment by pbouda** [comment]
I got the new code. Now the main window opens without the error (cool!). The window is empty, though, no app.

**Comment by johannesjo** [comment]
Does a console open if you press `CTRL-SHIFT+J` and if not: Could you try starting the app with line 40 uncommented in `main-window.js` (`mainWin.webContents.openDevTools()`) to see if there are any errors showing up in the console.

**Comment by pbouda** [comment]
I could open the console with ctrl+shift+i. I get two errors:

```
Uncaught TypeError: angular.module(...).info is not a function
    at angular-messages.js:275
    at angular-messages.js:740
```
and
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at InitGlobalModels (init-global-models-s.js:60)
    at initGlobalModels (_app.js:96)
    at Object.invoke (angular.js:4862)
    at angular.js:4665
    at forEach (angular.js:357)
    at createInjector (angular.js:4665)
    at doBootstrap (angular.js:1842)
    at bootstrap (angular.js:1863)
    at angularInit (angular.js:1748)
    at angular.js:33129
```

**Comment by johannesjo** [comment]
I updated the angular version and added a quick fix for the theme issue. Could you check again?

**Comment by pbouda** [comment]
Yes, it works now. 🥇  Thanks a lot, awesome!

**Comment by johannesjo** [comment]
Very happy to hear that! Haven't actually tested the app on windows myself. If you encounter any other issues, please let me know!
