### ISSUE TITLE
Empty string gitlabBaseUrl causes api requests to fail

### ISSUE THREAD

**Issue by Koleok** [johannesjo/super-productivity#926]
### Your Environment

* Version used: homebrew 6.4.0 
* Operating System and version: macOs 11.1
* Browser Name and version: N/A _(using desktop app)_ 

### Expected Behavior
If I enter a value for 
> **project > settings > gitlab integration > `Custom Gitlab Base URL`**
<img src="https://user-images.githubusercontent.com/10928312/108953422-2885c180-7639-11eb-912f-10d783202cec.png" width="450" />

and save the project, then edit the project and remove that value, the effect should be the same as not having entered a value at all.

### Current Behavior
The empty string that sticks around as value for `gitlabBaseUrl`, ends up being used to construct the final gitlab api url, which is then interpreted as `file://` host by the electron shell, and I am guessing the browser version would do something similar and use it's current host  address. Either way this blocks any api communication with gitlab for the project.

### Steps to Reproduce (for bugs)

1. Create a new project
1. Navigate to it's settings
1. Add a working gitlab integration setup with auto polling checked _(this means including an access token)_
1. Add a bogus `Custom Gitlab Base URL`
1. Save the configuration
1. Edit the project settings again
1. Clear the field for `Custom Gitlab Base URL`
1. Save the conifguration
1. When a autocomplete search is attempted or the project starts to poll, the requests will fail

### Console Output
- N/A _(basically the same as log output listed below in `details` block)_

### Error Log (Desktop only)
<details>
  <pre>
  [2021-02-24 00:21:10.877] [error] Frontend Error: Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Gitlab: Http failure response for /api/v4/projects/21224335/issues?state=opened&order_by=updated_at&per_page=100&page=1: 0 Unknown Error"}
    at Z (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15047
    at a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:3978873)
    at l.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:1603753)
    at l.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758
    at l.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:1603569) Error: Uncaught (in promise): Object: {"HANDLED_ERROR_PROP":"Gitlab: Http failure response for /api/v4/projects/21224335/issues?state=opened&order_by=updated_at&per_page=100&page=1: 0 Unknown Error"}
    at Z (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15047
    at a (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:3978873)
    at l.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:1603753)
    at l.invoke (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.run (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)
    at file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758
    at l.invokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:7190)
    at Object.onInvokeTask (file:///Applications/superProductivity.app/Contents/Resources/app.asar/dist/main.2a178195260c881581ac.js:1:1603569)
  </pre>
</details>

### Notes
- This looks to be a result of checks in a few places that `cfg.gitlabBaseUrl` is `!= null`, which misses the case of saving an empty text input which results in an empty string. If a simple `falsey` condition was used in these spots it should solve the issue.
  - [`src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts#L217-L219`](https://github.com/johannesjo/super-productivity/blob/9a50f522a19bcf70dde977e4e7a3d7923dc483ca/src/app/features/issue/providers/gitlab/gitlab-api/gitlab-api.service.ts#L217-L219)
  - [`src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts#L30-L32`](https://github.com/johannesjo/super-productivity/blob/f472e825e0ef62938dbf4350d6904eecad04c9a7/src/app/features/issue/providers/gitlab/gitlab-common-interfaces.service.ts#L30-L32)

**Comment by Koleok** [comment]
As a workaround for this, I did the following which got me back up and running:
1. Closed the desktop app
1. Edited my most recent backup, which in this case on a mac was `~/Library/Application Support/superProductivity/backups/2021-02-24.json` so that all `"gitlabBaseUrl"` properties were removed entirely.
1. Opened the desktop app
1. Settings > Import/Export > `Import From File`
1. Select the edited backup file

**Comment by johannesjo** [comment]
Thank you very much for opening and digging into this! Could I interest you by any chance to provide a PR for this? (:

**Comment by Koleok** [comment]
> Thank you very much for opening and digging into this! Could I interest you by any chance to provide a PR for this? (:

Yep I think it'll be a two-liner also, just need to grab some time on a non-work computer in between all the kids zoom calls haha.

**Comment by johannesjo** [comment]
Hehe. Oh yeah, I can picture this... :D Hang tough! 

Thank you!
