### ISSUE TITLE
First time sync error. (No correct localLastSync given nullError)

### ISSUE THREAD

**Issue by dembeck** [johannesjo/super-productivity#942]
### Steps to Reproduce

1. I downloaded the latest release from the releases page (superProductivity-Setup-6.4.0.exe)
2. I installed it
3. I opened it and went to look at the settings
4. I saw that it has sync capabilities and proceeded to enable sync and select Google Drive
5. Google came back with an auth code which I pasted into the app.
6. The code was accepted, then the app gave me the error.
7.  Whenever I click on the window it gives me a prompt "No remote data found. Upload local to Remote?" I clicked OK and then it didn't seem to be doing anything, so I clicked the window again, and it gave me the same prompt again. Did that a couple more times over the next few minutes, but it didn't seem to improve or even change the situation.
8. I exited the app and reopened it.
9. After reloading the app it seems to be working correctly, with no additional input or changes from me. I have not tried to load the sync from a different device, but Google Drive is showing that the file has been changed three times over the last half hour, so it now seems to be connecting fine.

#### Other Notes
* This is the first time I have used this app and so did not have a sync file already. 
* Even with this error it still saved the json file. It has the same time stamp as when the error occurred, though I do not see a way for Google to show the time with seconds, and as such I am unsure if the json was created before or after the error happened, but it was within that 60 second window. 
* The json that it saved to my Google Drive is not in English, but when I export my settings it is? Not sure if that means anything...

#### Attachments
* The original sync file (Github wouldn't let me attach a json, so added txt to the end) [SUPER_PRODUCTIVITY_SYNC.json.txt](https://github.com/johannesjo/super-productivity/files/6081095/SUPER_PRODUCTIVITY_SYNC.json.txt)
* The manually created export file [super-productivity-backup.json.txt](https://github.com/johannesjo/super-productivity/files/6081105/super-productivity-backup.json.txt)
*  Log file [%USERNAME%\AppData\Roaming\superProductivity\logs\main.log](https://github.com/johannesjo/super-productivity/files/6080904/main.log)
* Copy of the console [Console_Log.txt](https://github.com/johannesjo/super-productivity/files/6080905/MSEdge_Console_Log.txt)
* Copy of the stacktrace [Stacktrace.txt](https://github.com/johannesjo/super-productivity/files/6080906/Stacktrace.txt)
* And some screenshots

![Google Auth Code](https://user-images.githubusercontent.com/9568447/109913875-9fd3da80-7c63-11eb-9ea1-9df93f028913.png)

 ![Screenshot of Prompt](https://user-images.githubusercontent.com/9568447/109912802-a3fef880-7c61-11eb-9c11-43c817a5877c.png)

 ![Screenshot of the Error](https://user-images.githubusercontent.com/9568447/109912257-8715f580-7c60-11eb-8faf-260b8019d915.png)

#### Link: [main.log](https://github.com/johannesjo/super-productivity/files/6080904/main.log)
```
[2021-03-03 20:26:56.352] [error] Frontend Error: Error: Uncaught (in promise): Error: No correct localLastSync given null
Error: No correct localLastSync given null
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588249)
    at Generator.next (<anonymous>)
    at file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581556
    at new C (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at ED (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
    at e._setLocalRevAndLastSync (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3587268)
    at Generator.next (<anonymous>)
    at a (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Z (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at ED (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
    at e._setLocalRevAndLastSync (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3587268)
    at Generator.next (<anonymous>)
    at a (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:384454)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512) Error: Uncaught (in promise): Error: No correct localLastSync given null
Error: No correct localLastSync given null
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588249)
    at Generator.next (<anonymous>)
    at file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581556
    at new C (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17831)
    at ED (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
    at e._setLocalRevAndLastSync (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3587268)
    at Generator.next (<anonymous>)
    at a (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Z (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:15962)
    at new C (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:17857)
    at ED (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
    at e._setLocalRevAndLastSync (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
    at e.<anonymous> (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3587268)
    at Generator.next (<anonymous>)
    at a (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:384454)
    at l.invoke (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
[2021-03-03 20:26:59.287] [error] Frontend Error Stack: typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:292:12)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581556)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

#### Link: [MSEdge_Console_Log.txt](https://github.com/johannesjo/super-productivity/files/6080905/MSEdge_Console_Log.txt)
```
main.df3595a993fca4741013.js:1 Array(0)
main.df3595a993fca4741013.js:1 @ngrx/store/update-reducers Object Object
main.df3595a993fca4741013.js:1 @ngrx/effects/init Object Object
main.df3595a993fca4741013.js:1 @ngrx/store/update-reducers Object Object
main.df3595a993fca4741013.js:1 Persistence already allowed
main.df3595a993fca4741013.js:1 0 out of 269015 MiB used (0%)
main.df3595a993fca4741013.js:1 IDB UPGRADE 0 2
main.df3595a993fca4741013.js:1 Migrating model "GlobalConfig" to version from undefined to 2.2001 Object
main.df3595a993fca4741013.js:1 Migrating model "Tag" to version from undefined to 1 Object
main.df3595a993fca4741013.js:1 Array(1)
main.df3595a993fca4741013.js:1 Migrating model "SimpleCounter" to version from undefined to 2 Object
main.df3595a993fca4741013.js:1 Migrating model "TaskRepeat" to version from undefined to 1 Object
main.df3595a993fca4741013.js:1 [SP_ALL] Load(import) all data Object Object
main.df3595a993fca4741013.js:1 Migrating model "Task" to version from undefined to 3.3334 Object
main.df3595a993fca4741013.js:1 [SP_ALL] All Data was loaded Object Object
main.df3595a993fca4741013.js:1 Activated SyncProvider: null
main.df3595a993fca4741013.js:1 [WorkContext] Set Active Work Context Object Object
main.df3595a993fca4741013.js:1 [Task] SetSelectedTask Object Object
main.df3595a993fca4741013.js:1 [Layout] Toggle SideBar Object Object
main.df3595a993fca4741013.js:1 [Layout] Hide SideBar Object Object
main.df3595a993fca4741013.js:1 [Layout] Hide SideBar Object Object
main.df3595a993fca4741013.js:1 [Global Config] Update Global Config Section Object Object
main.df3595a993fca4741013.js:1 Activated SyncProvider: GoogleDrive
main.df3595a993fca4741013.js:1 [Persistence] Save to DB Object Object
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832008611
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832012955
main.df3595a993fca4741013.js:1 [Global Config] Update Global Config Section Object Object
main.df3595a993fca4741013.js:1 sync(effect)..... SYNC_DBX_AFTER_ENABLE
main.df3595a993fca4741013.js:1 [Persistence] Save to DB Object Object
main.df3595a993fca4741013.js:1 __trigger_sync__ globalConfig Object
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832014379
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832014608
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832014826
main.df3595a993fca4741013.js:1 GoogleDrive ↑ PRE4: Update Remote
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832018936
main.df3595a993fca4741013.js:1 GoogleDrive ↑ Uploaded Data ↑ ✓
main.df3595a993fca4741013.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): Error: No correct localLastSync given null
Error: No correct localLastSync given null
    at e.<anonymous> (main.df3595a993fca4741013.js:1)
    at Generator.next (<anonymous>)
    at main.df3595a993fca4741013.js:1
    at new C (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at ED (main.df3595a993fca4741013.js:1)
    at e._setLocalRevAndLastSync (main.df3595a993fca4741013.js:1)
    at e.<anonymous> (main.df3595a993fca4741013.js:1)
    at Generator.next (<anonymous>)
    at a (main.df3595a993fca4741013.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Z (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at new C (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at ED (main.df3595a993fca4741013.js:1)
    at e._setLocalRevAndLastSync (main.df3595a993fca4741013.js:1)
    at e.<anonymous> (main.df3595a993fca4741013.js:1)
    at Generator.next (<anonymous>)
    at a (main.df3595a993fca4741013.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvoke (main.df3595a993fca4741013.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
handleError @ main.df3595a993fca4741013.js:1
main.df3595a993fca4741013.js:1 Last actions before error: Array(11)
polyfills.bbc1c0564b6a5d42ba73.js:1 Uncaught Error: Error: Uncaught (in promise): Error: No correct localLastSync given null
Error: No correct localLastSync given null
    at e.<anonymous> (main.df3595a993fca4741013.js:1)
    at Generator.next (<anonymous>)
    at main.df3595a993fca4741013.js:1
    at new C (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at ED (main.df3595a993fca4741013.js:1)
    at e._setLocalRevAndLastSync (main.df3595a993fca4741013.js:1)
    at e.<anonymous> (main.df3595a993fca4741013.js:1)
    at Generator.next (<anonymous>)
    at a (main.df3595a993fca4741013.js:1)
    at l.invoke (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at e.handleError (main.df3595a993fca4741013.js:1)
    at Object.next (main.df3595a993fca4741013.js:1)
    at d.i [as _next] (main.df3595a993fca4741013.js:1)
    at d.__tryOrUnsub (main.df3595a993fca4741013.js:1)
    at d.next (main.df3595a993fca4741013.js:1)
    at l._next (main.df3595a993fca4741013.js:1)
    at l.next (main.df3595a993fca4741013.js:1)
    at Fh.next (main.df3595a993fca4741013.js:1)
    at Fh.emit (main.df3595a993fca4741013.js:1)
    at main.df3595a993fca4741013.js:1
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/runtime.f8acce36d38b4573bc3e.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/reminder.ce132bbfd6c00fa9679e.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/lz.4032bbfae8ed49675219.worker.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/styles.368de9a5b2ff92174cdb.css.map: 
main.df3595a993fca4741013.js:1 __trigger_sync after auditTime__ globalConfig {appDataKey: "globalConfig", data: {…}, isDataImport: false, projectId: undefined, isSyncModelChange: true}
main.df3595a993fca4741013.js:1 sync(effect)..... {appDataKey: "globalConfig", data: {…}, isDataImport: false, projectId: undefined, isSyncModelChange: true}
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832074541
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832074832
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832075077
main.df3595a993fca4741013.js:1 GoogleDrive ↑ PRE4: Update Remote
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832109769
main.df3595a993fca4741013.js:1 GoogleDrive ↑ Uploaded Data ↑ ✓
main.df3595a993fca4741013.js:1 sync(effect)..... I_FOCUS_THROTTLED
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832115059
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832115425
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832115651
main.df3595a993fca4741013.js:1 GoogleDrive ↑ PRE4: Update Remote
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832118806
main.df3595a993fca4741013.js:1 GoogleDrive ↑ Uploaded Data ↑ ✓
main.df3595a993fca4741013.js:1 sync(effect)..... I_FOCUS_THROTTLED
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832205637
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832205951
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832206267
main.df3595a993fca4741013.js:1 GoogleDrive ↑ PRE4: Update Remote
main.df3595a993fca4741013.js:1 GOOGLE API: SESSION EXPIRED, expiresAt 1614832210984
main.df3595a993fca4741013.js:1 GoogleDrive ↑ Uploaded Data ↑ ✓
```

#### Link: [Stacktrace.txt](https://github.com/johannesjo/super-productivity/files/6080906/Stacktrace.txt)
```
typeof (webpack:///src/app/imex/sync/sync-provider.service.ts:292:12)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581556)
constructor (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1383:28)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
executor(makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1386:16)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581301)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3588131)
isValidAppData (webpack:///src/app/imex/sync/sync-provider.service.ts:244:11)
Ur (file:///C:/Users/dustin/AppData/Local/Programs/superProductivity/resources/app.asar/dist/main.df3595a993fca4741013.js:1:3581358)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:368:25)
onInvoke (webpack:///node_modules/@angular/core/fesm2015/core.js:28512:32)
invoke (webpack:///node_modules/zone.js/dist/zone-evergreen.js:367:51)
```

### Meta Info
META: SP6.4.0 Electron – en-US – Win32 – Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1614831901097: [SP_ALL] Load(import) all data 
1614831901107: [SP_ALL] All Data was loaded 
1614831901145: [WorkContext] Set Active Work Context 
1614831901204: [Task] SetSelectedTask 
1614831945321: [Layout] Toggle SideBar 
1614831946885: [Layout] Hide SideBar 
1614831947828: [Layout] Hide SideBar 
1614831973275: [Global Config] Update Global Config Section 
1614831973334: [Persistence] Save to DB 
1614832010682: [Global Config] Update Global Config Section 
1614832010693: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thank you very much for the detailed error report! I'll try to investigate this as soon as I can.

**Comment by johannesjo** [comment]
Despite the excellent debugging information you provided (thanks again!), I am unable to reproduce this with v6.5.0. Might be tat de5a47d fixed the problem.
