### ISSUE TITLE
Error: Uncaught (in promise): UnknownError: Connection is closing.

### ISSUE THREAD

**Issue by kYem** [johannesjo/super-productivity#950]
### Steps to Reproduce

1. It was just tracking time for existing tasks
2. Was not interacting with the app

### Error Log (Desktop only)

**Seems old logs only**
[2021-02-20 15:59:38.155] [error] Frontend Error: { HANDLED_ERROR_PROP: 'GD File creation: No token' } undefined
[2021-02-20 15:59:38.181] [error] Frontend Error Stack: 

### Console Output

```
[Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 GLOBAL_ERROR_HANDLER Error: Uncaught (in promise): UnknownError: Connection is closing.
    at Z (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at polyfills.bbc1c0564b6a5d42ba73.js:1
    at IDBTransaction.s (main.a276ef2d735aa2fdb6d1.js:1)
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at Object.onInvokeTask (main.a276ef2d735aa2fdb6d1.js:1)
    at l.invokeTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at i.runTask (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at u.invokeTask [as invoke] (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at _ (polyfills.bbc1c0564b6a5d42ba73.js:1)
    at IDBTransaction.k (polyfills.bbc1c0564b6a5d42ba73.js:1)
handleError @ main.a276ef2d735aa2fdb6d1.js:1
main.a276ef2d735aa2fdb6d1.js:1 Last actions before error: Array(30)
polyfills.bbc1c0564b6a5d42ba73.js:1 Uncaught Error: Error: Uncaught (in promise): UnknownError: Connection is closing.
    at e.handleError (main.a276ef2d735aa2fdb6d1.js:1)
    at Object.next (main.a276ef2d735aa2fdb6d1.js:1)
    at d.i [as _next] (main.a276ef2d735aa2fdb6d1.js:1)
    at d.__tryOrUnsub (main.a276ef2d735aa2fdb6d1.js:1)
    at d.next (main.a276ef2d735aa2fdb6d1.js:1)
    at l._next (main.a276ef2d735aa2fdb6d1.js:1)
    at l.next (main.a276ef2d735aa2fdb6d1.js:1)
    at Fh.next (main.a276ef2d735aa2fdb6d1.js:1)
    at Fh.emit (main.a276ef2d735aa2fdb6d1.js:1)
    at main.a276ef2d735aa2fdb6d1.js:1
main.a276ef2d735aa2fdb6d1.js:1 [Task] Add time spent Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Project] Update Work End Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Tag] Update Work End for Tag Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 [Persistence] Save to DB Object Object
main.a276ef2d735aa2fdb6d1.js:1 GLOBAL_ERROR_HANDLER DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Proxy.n (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2396084)
    at Proxy.s (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2397166)
    at e.<anonymous> (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2405512)
    at Generator.next (<anonymous>)
    at a (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:2404850)
    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6572)
    at Object.onInvoke (file:///snap/superproductivity/1030/resources/app.asar/dist/main.a276ef2d735aa2fdb6d1.js:1:1603753)
    at l.invoke (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:6512)
    at i.run (file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:1984)
    at file:///snap/superproductivity/1030/resources/app.asar/dist/polyfills.bbc1c0564b6a5d42ba73.js:1:16758
```
### Stacktrace
```
scheduleResolveOrReject (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1209:30)
makeResolver (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1116:16)
error (webpack:///node_modules/idb/build/esm/wrap-idb-value.js:77:12)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:402:30)
onInvokeTask (webpack:///node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:28499:32)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:401:59)
task._transitionTo (webpack:///node_modules/zone.js/dist/zone-evergreen.js:174:46)
invokeTask (webpack:///node_modules/zone.js/dist/zone-evergreen.js:483:33)
callback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1596:13)
globalZoneAwareCallback (webpack:///node_modules/zone.js/dist/zone-evergreen.js:1622:16)
```

### Meta Info
META: SP6.4.0 Electron – en-GB – Linux x86_64 – Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) superProductivity/6.4.0 Chrome/85.0.4183.121 Electron/10.3.1 Safari/537.36

### Actions Before Error
```
1615042999895: [Task] Add time spent 
1615042999897: [Project] Update Work End 
1615042999898: [Tag] Update Work End for Tag 
1615042999912: [Persistence] Save to DB 
1615042999913: [Persistence] Save to DB 
1615042999913: [Persistence] Save to DB 
1615043000894: [Task] Add time spent 
1615043000897: [Project] Update Work End 
1615043000898: [Tag] Update Work End for Tag 
1615043000902: [Persistence] Save to DB 
1615043000902: [Persistence] Save to DB 
1615043000902: [Persistence] Save to DB 
1615043001895: [Task] Add time spent 
1615043001897: [Project] Update Work End 
1615043001898: [Tag] Update Work End for Tag 
1615043001910: [Persistence] Save to DB 
1615043001910: [Persistence] Save to DB 
1615043001911: [Persistence] Save to DB 
1615043002895: [Task] Add time spent 
1615043002897: [Project] Update Work End 
1615043002898: [Tag] Update Work End for Tag 
1615043002912: [Persistence] Save to DB 
1615043002913: [Persistence] Save to DB 
1615043002913: [Persistence] Save to DB 
1615043016046: [Task] Add time spent 
1615043016047: [Project] Update Work End 
1615043016047: [Tag] Update Work End for Tag 
1615043016049: [Persistence] Save to DB 
1615043016050: [Persistence] Save to DB 
1615043016050: [Persistence] Save to DB
```

**Comment by johannesjo** [comment]
Thanks for opening this up. I hope this will be solved for good with one of the future chromium/electron versions.
